[core][Issue #10109] replaced split function to allow for escaped periods in dot notation
aws/aws-cdk pull request #10158
Opened 2020-09-03 15:54 UTC by enjaygee

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-09-03 15:59 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: f96000a566527e6bd979e6d21f831811067f2e27
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e917977c-d0b7-48a5-b579-1c82a2ce57fa%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-03 16:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: bb0e68ead06a2895185a3693ed13015853e251ef
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5356f654-3f44-46b2-983a-af0ad1409c50%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-07 07:43 UTC, rix0rrr requested changes

2021-04-12 03:09 UTC, Chriscbr commented
I think this can be closed per #10441 which addressed the same issue

2022-03-10 16:20 UTC, cgarvis commented
Fixed in #10441

2022-03-10 16:20 UTC, closed without merging