build(appsync): fix jsii bug to prevent toString() override w/ dotnet
aws/aws-cdk pull request #10167
Opened 2020-09-03 21:07 UTC by BryanPan342

jsii bug that's preventing packaging

<details>
<summary> bug output </summary>

```shell
#STDOUT> Amazon/CDK/AWS/AppSync/Directive.cs(88,32): error CS0115: 'Directive.ToString(AuthorizationType[]?)': no suitable method found to override [/tmp/npm-packqZC1CO/Amazon.CDK.MonoCDK.Experiment/Amazon.CDK.MonoCDK.Experiment.csproj]
#STDOUT> Amazon/CDK/AWS/AppSync/InputType.cs(66,32): error CS0115: 'InputType.ToString(AuthorizationType[]?)': no suitable method found to override [/tmp/npm-packqZC1CO/Amazon.CDK.MonoCDK.Experiment/Amazon.CDK.MonoCDK.Experiment.csproj]
#STDOUT> Amazon/CDK/AWS/AppSync/InterfaceType.cs(64,32): error CS0115: 'InterfaceType.ToString(AuthorizationType[]?)': no suitable method found to override [/tmp/npm-packqZC1CO/Amazon.CDK.MonoCDK.Experiment/Amazon.CDK.MonoCDK.Experiment.csproj]
#STDOUT> Amazon/CDK/AWS/AppSync/InputType.cs(66,32): error CS0115: 'InputType.ToString(AuthorizationType[]?)': no suitable method found to override [/tmp/npm-packqZC1CO/Amazon.CDK.AWS.AppSync/Amazon.CDK.AWS.AppSync.csproj]
#STDOUT> Amazon/CDK/AWS/AppSync/Directive.cs(88,32): error CS0115: 'Directive.ToString(AuthorizationType[]?)': no suitable method found to override [/tmp/npm-packqZC1CO/Amazon.CDK.AWS.AppSync/Amazon.CDK.AWS.AppSync.csproj]
#STDOUT> Amazon/CDK/AWS/AppSync/InterfaceType.cs(64,32): error CS0115: 'InterfaceType.ToString(AuthorizationType[]?)': no suitable method found to override [/tmp/npm-packqZC1CO/Amazon.CDK.AWS.AppSync/Amazon.CDK.AWS.AppSync.csproj]
```

</details>

Fix was to add a method called `bindModes` to give IntermediateTypes a method set `modes` and make `toString()` without arguments.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-09-03 21:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: c92ab44c0fa2a9854df2ddccf439157ce7ba1afc
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9dacda9f-177e-4940-b18f-daa8634a9ebc%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-03 22:27 UTC, shivlaks requested changes
the symptoms are useful, can you also include the root cause as part of the commit body.
The commit body also needs to be updated to reflect the implementation.

2020-09-03 22:27 UTC, shivlaks commented on packages/@aws-cdk/aws-appsync/lib/schema-base.ts
> +  bindToGraphqlApi(api: GraphqlApi): IIntermediateType;
our `bind` methods typically take in a scope (even if it's not used), and a struct of `Options` (even if it's empty) as well. It's more future friendly. 

They also return a `xyzConfig` object with the properties that are to be bound. This is a slightly different approach.

2020-09-03 22:27 UTC, shivlaks commented on packages/@aws-cdk/aws-appsync/lib/schema-base.ts
> +   * @param modes the authorization modes
nit: needed? not sure this is adding much more than the signature itself

2020-09-03 22:27 UTC, shivlaks commented on packages/@aws-cdk/aws-appsync/lib/schema-intermediate.ts
> +   * Bind this Interface Type to a GraphQL Api
update this comment to include when it's called (see bindToCluster, bindToInstance for examples)

2020-09-03 22:27 UTC, shivlaks commented on packages/@aws-cdk/aws-appsync/lib/schema-base.ts
> +  public bindToGraphqlApi(modes?: AuthorizationType[]): Directive {
is the return type of `Directive` here intentional?

2020-09-03 22:30 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 77aafa268fe86ae42e09548cdf66331db2beb5bf
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=cd54ec9d-2182-4e74-b8f0-05b735c8b984%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-03 22:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 5c6a24cd56270c01b99849a54dce0e71e0a9b94b
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6b0a6aef-9da2-4e27-955f-439ae2a927aa%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-04 00:27 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 4884b37067f940e916eb6586c214b705c0f97cc8
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d888c3ac-8d10-4e09-afe3-c7e17ef12173%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-04 05:11 UTC, MrArnoldPalmer approved these changes

2020-09-04 05:17 UTC, merged

2020-09-04 18:04 UTC, shivlaks commented on packages/@aws-cdk/aws-appsync/lib/schema-base.ts
> +  public bindToGraphqlApi(modes?: AuthorizationType[]): Directive {
that's worth a comment