feat(eks): connect all custom resources to the cluster VPC
aws/aws-cdk pull request #10200
Opened 2020-09-05 16:20 UTC by iliapolo

Just a PoC yet.

Closes https://github.com/aws/aws-cdk/issues/9509 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-09-05 16:33 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 298c414e9dcf419fd69fbcb3a7656433ca07b896
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8a28d4eb-df3b-4bdf-b2af-375ab0bd4b01%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-07 06:01 UTC, alexey-boyko commented
is it possible to add ability to define proxy for lambda functions as aws doesn't have vpc endpoints for api's, for example  to reach eks api from private network?

2020-09-07 19:55 UTC, iliapolo commented
@alexey-boyko Yes it will be possible

2020-09-09 08:00 UTC, alexey-boyko commented
> @alexey-boyko Yes it will be possible

cool thanks, ping me if you need me to test

2020-10-27 10:00 UTC, alexey-boyko commented
@iliapolo hello, any plans to merge it this year?

2020-10-27 12:22 UTC, iliapolo commented
@alexey-boyko Yes it is on our roadmap for this quarter.

2020-12-13 11:47 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 84a0b92c2c2f9cfae9bb92ad820d28b33e2f0b6b
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1f153c94-99ed-4cb8-8657-e5e167f30077%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-13 20:33 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 18716b0141769f6870f69d382e2e3141c633528a
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=10cd29e1-4183-44d8-b676-01e6d1e4be94%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-14 11:40 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: e118ff021f939dcd6eb64dde9539509bacb1474d
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9aa81f69-df04-424b-b4ec-edccdc73a8f8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-15 17:50 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 90bcfecbca64a8c9fbcefa6de50117e0bc220ffe
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2b8ef523-0aa0-40f0-a89a-5b44c9912691%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-15 20:51 UTC, iliapolo commented on packages/@aws-cdk/aws-eks/lib/kubectl-provider.ts
> +      vpc: cluster.kubectlPrivateSubnets ? cluster.vpc : undefined,
This isn't related to the `placeClusterHandlerInVpc` property. But seems like we should have done this when we introduced private endpoints, consolidating all the related functions into the same network configuration.

2020-12-15 20:51 UTC, iliapolo commented on packages/@aws-cdk/aws-eks/test/integ.eks-cluster-handlers-vpc.ts
> +class EksAllHandlersInVpcStack extends TestStack {
Reluctantly, adding another integ test because this property affects the cluster deployment and operation.

2020-12-15 21:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: fed2509532e2e4749d7c301dff6208a18a02f677
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e55129e6-6f2e-4a51-b305-a02373c5d7ff%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-21 01:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: cd3dc87e7c297671dd07c8d173dfbb2d88660dea
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=61545e70-bab9-4994-93be-cd4c278b4cf3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-21 11:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: d40f7182c6e17023f24c706b8d3bace98392475d
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7a99fe3c-7327-42fa-bd7c-69479bd2ba2d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-21 12:06 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 68a625dce41835264ac0a728a8faa814a8979b3f
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0ba93610-49f6-408e-9f59-74051923dd94%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-21 12:32 UTC, eladb requested changes

2020-12-21 12:32 UTC, eladb commented on packages/@aws-cdk/aws-eks/lib/cluster.ts
> +  readonly placeClusterHandlerInVpc?: boolean;
It would make sense to use a similar prefix:

```suggestion
  readonly clusterHandlerVpc?: boolean;
```

2020-12-21 12:32 UTC, eladb commented on packages/@aws-cdk/aws-eks/README.md
> +The `ClusterHandler` is a Lambda function responsible to interact with the EKS API in order to control the cluster lifecycle. To provision this function inside the VPC, set the `placeClusterHandlerIn
What about the kubectl handler?

2020-12-21 12:33 UTC, eladb commented
Okay now just saw the PR description

2020-12-21 12:33 UTC, eladb approved these changes

2020-12-21 19:00 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 9407f5e48e065e2b927411b82c023f1e2a74ab6f
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=33807678-1c33-41d2-a2e3-175513228133%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-21 19:04 UTC, merged