feat(codepipeline-actions): support region attribute on CodeBuildAction
aws/aws-cdk pull request #10281
Opened 2020-09-10 04:22 UTC by amhammett

fixes #10279

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-09-10 04:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: b6944bb74a8ccb379054358abd7cab44ba81fe62
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e72335fc-948d-4bba-af66-594fe5475d41%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-10 05:30 UTC, amhammett commented on packages/@aws-cdk/aws-codepipeline-actions/README.md
> +#### Cross-Region CodeBuild Actions
I have tried to make this section as concise as possible to show what is required to implement cross-region build actions. I'm happy to expand this.

2020-09-10 05:54 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 3006892cb6e737be4cee8f7dfed18edcaac51105
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0e883bb6-d9d6-4c1d-b05a-bf9c7ba77632%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-10 17:58 UTC, skinny85 requested changes
Thanks for the PR @amhammett , but this is a non-starter. Actions that are backed by a resource take its region from the resource's region, you cannot provide one separately (it doesn't make much sense).

In your case, you probably want to the correct logic in `fromProjectArn(): IProject` method in the `Project` class to take the region out of the ARN, very similarly like it [works for Bucket today](https://github.com/aws/aws-cdk/blob/287f808cf34870295e4032995fc083ac204b64c3/packages/@aws-cdk/aws-codepipeline-actions/README.md#aws-s3).

2020-09-16 06:55 UTC, amhammett commented
Thanks for the feedback @skinny85 I've taken a look at the code you referenced and just need to get my head around and finish some testing before I update this PR.

2020-09-16 19:17 UTC, skinny85 commented
> Thanks for the feedback @skinny85 I've taken a look at the code you referenced and just need to get my head around and finish some testing before I update this PR.

Sounds good, let me know if you need any additional information, I'll be happy to assist 🙂.

2021-06-22 16:09 UTC, skinny85 commented
I'm closing this one due to inactivity. Please comment if you want it re-opened.

2021-06-22 16:09 UTC, closed without merging