Fix for [rds] Support for RDS SQL Version 15.00.4043.16.v1 #10273
aws/aws-cdk pull request #10289
Opened 2020-09-10 15:59 UTC by abjoshi2785

Fix for [rds] Support for RDS SQL Version 15.00.4043.16.v1 #10273

Please review the changes.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-09-10 16:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 79bc4369c3c371caf1b6524b8a579d030c15f499
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ae27a64b-0135-4f4f-8618-139d5c5e10e1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-10 16:32 UTC, shivlaks submitted a review, later dismissed

2020-09-10 16:33 UTC, njlynch commented on packages/@aws-cdk/aws-rds/lib/instance-engine.ts
> +
```suggestion

```

2020-09-10 16:38 UTC, shivlaks commented on packages/@aws-cdk/aws-rds/lib/instance-engine.ts
> +
thanks @njlynch !

2020-09-10 16:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 3b8c77ab2a6a995ca05522e7658d575ae573b28b
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7fc70227-06a8-458d-ad13-9ed629261dc5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-10 17:05 UTC, skinny85 submitted a review, later dismissed
Thanks for the PR @abjoshi2785 !

2020-09-10 17:05 UTC, skinny85 commented on packages/@aws-cdk/aws-rds/lib/instance-engine.ts
> +  /** Version "15.00" (only a major version, without a specific minor version). */
Please add a newline before this line. Just without any trailing whitespace :).

2020-09-10 17:30 UTC, njlynch commented on packages/@aws-cdk/aws-rds/lib/instance-engine.ts
> +  /** Version "15.00" (only a major version, without a specific minor version). */
```suggestion

  /** Version "15.00" (only a major version, without a specific minor version). */
```

2020-09-10 17:46 UTC, skinny85 submitted a review, later dismissed

2020-09-10 17:55 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 66d2965e1ab8deccc3bd16f2beaacb4dfbf4671d
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=edcfe88a-b98e-4548-aab9-deba4047ec10%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-10 19:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 7a83b68816d3e07d1c7ac35580673acfc31bf663
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=58c40f0c-e0a8-4f02-9fb9-491ca567ab13%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-11 13:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 94ee1d82fdbb19e6e03e9308c57fb34411b03c21
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1555fcd9-135b-455a-b27a-3bd1279d68d1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-15 11:16 UTC, njlynch submitted a review, later dismissed

2020-09-15 11:40 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 460d0b397843c5a4253c2d33bd60675ca9211766
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=73f725a8-b920-4c3e-955c-2d740ea79386%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-15 11:42 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: bb2ff6d626bdf521ad21ca86502a7698ec08757a
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=52ca13ae-5cbd-491c-96f6-2cc38b0d7b08%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-15 23:40 UTC, skinny85 commented
@abjoshi2785 did you ["Allow changes to be pushed to your fork"](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)? I think we can't merge your PR until you do...

2020-09-16 01:32 UTC, skinny85 requested changes
Putting in "Request changes" to try and unblock the Mergify queue.

2020-09-16 02:53 UTC, skinny85 approved these changes
Seems the queue is unclogged, approving again 🙂

2020-09-16 03:06 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 36a64330fb643d97866743245bb2a33bab39df5a
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=87011541-1bd6-4c67-89a1-4bc5bf52af04%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-16 03:33 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 7c12e46fd5899b2a0a4b8936e2ab07f161ed27c5
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e413838b-1b1e-4fd6-8193-cbd43f065b1a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-16 03:33 UTC, merged

2020-09-17 15:21 UTC, abjoshi2785 commented
Thank you! :)

2020-09-17 18:42 UTC, skinny85 commented
> Thank you! :)

No, thank _you_ for the contribution 🙂