feat(apigateway): Add grant* methods to ApiKey
aws/aws-cdk pull request #10633
Opened 2020-10-01 16:52 UTC by ayush987goyal

feat(apigateway): Add grant* methods to ApiKey

[Ref](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-iam-policy-examples.html)

close #8060

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-10-01 17:17 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 09b4d10740f1b5a7296322f380427627951a245e
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=21355e26-1ab4-443e-9767-0d0b663b3d40%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-07 04:53 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 75a9dfe81c957571d67748392b83a7861463e178
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=aea58546-0e59-46bb-81fa-f565ef6bf8b4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-07 13:30 UTC, nija-at requested changes
Suggestion:

If you could implement these APIs on a class called `ApiKeyBase` and then have both `ApiKey` and the `Import` class extend this base class, then this functionality is also available to imported keys.

Something like this -

```ts
class ApiKeyBase extends Resource implements IApiKey {
   public grantRead(...)  { ... }
   public grantWrite(...) { ... } 
   ...
}

export class ApiKey extends ApiKeyBase {
  public static fromApiKeyId(scope: Construct, id: string, apiKeyId: string): IApiKey {
    class Import extends ApiKeyBase {
      public keyId = apiKeyId;
    }
    return new Import(scope, id);
  }
}
```

Note that, `ApiKeyBase` is not exported.

2020-10-07 13:30 UTC, nija-at commented on packages/@aws-cdk/aws-apigateway/lib/api-key.ts
> +    this.keyArn = `arn:aws:apigateway:${Stack.of(this).region}::/apikeys/${this.keyId}`;
Use [`Stack.formatArn()`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stack.html#format-wbr-arncomponents) instead.

2020-10-07 13:30 UTC, nija-at commented on packages/@aws-cdk/aws-apigateway/lib/api-key.ts
> +   * Permits the IAM principle all read operations through this key
```suggestion
   * Permits the IAM principal all read operations through this key
```

2020-10-07 13:30 UTC, nija-at commented on packages/@aws-cdk/aws-apigateway/lib/api-key.ts
> +   * Permits the IAM principle all write operations through this key
```suggestion
   * Permits the IAM principal all write operations through this key
```

2020-10-07 15:03 UTC, ayush987goyal commented
Hi @nija-at , you might have to add the pr-readme-exempt label to this one.

2020-10-07 15:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 437582bc24f7fa571e9b93b6824712d7e36e88be
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=83d56b6e-9e6b-4e33-9042-cc52779712d5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-07 16:39 UTC, nija-at commented
> Hi @nija-at , you might have to add the pr-readme-exempt label to this one.

Instead, how about creating a new section called 'Api Key' at line 154 (and in the table of contents)? It feels like lines154-239 are talking about API keys. Then, add a couple of sentences around the grant APIs to that section

2020-10-07 17:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: fa8be7b7242a4feceb4ffe9b92a036d64cac308a
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e3958401-811a-4b8e-8256-98963e0d3d42%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-09 13:17 UTC, nija-at commented
I would prefer not to export `ApiKeyBase` and I think we don't need an `ApiKeyBaseProps`. 

I've pushed a commit that changes this and restructures the code so the export is not needed. Take a look and let me know what you think.

2020-10-09 13:18 UTC, nija-at requested changes

2020-10-09 13:42 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: e312965cebc4d6b156eb44b7302694f8287cce9b
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c276f562-a4ee-4602-a275-44cb0e0e1f31%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-09 14:15 UTC, ayush987goyal commented
> I would prefer not to export ApiKeyBase and I think we don't need an ApiKeyBaseProps.

I've pushed a commit that changes this and restructures the code so the export is not needed. Take a look and let me know what you think.

These changes look good to me. Thanks!

2020-10-09 14:19 UTC, nija-at submitted a review, later dismissed

2020-10-09 14:41 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 9b5d40da16bb86ea063eac8915e0d1b9ceac3a97
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9523704d-ebe2-4bff-b274-96b10118cd96%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-09 15:11 UTC, nija-at approved these changes

2020-10-09 15:35 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 9cab7023381a477449ddfc44e83c7d4db96371aa
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=699bdd28-a37c-4176-ab38-0bdbdc4bd929%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-09 15:35 UTC, merged