fix(s3): correct write permission with key decrypt
aws/aws-cdk pull request #10679
Opened 2020-10-04 05:43 UTC by ayush987goyal

fix(s3): correct write permission with key decrypt

[Ref](https://aws.amazon.com/premiumsupport/knowledge-center/s3-multipart-kms-decrypt/)

closes #8947

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-10-04 05:59 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: a0c55cd046cb62e2ced15529342895147af85d7f
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=065c9418-d3f8-45d6-9bc6-07a93dab612c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-04 07:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: cab10114aa84951c186fe946664e0cc142005a72
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=86c0187b-0e13-4c9a-91cf-bcff0b5b354f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-07 04:52 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: d8b3d55d9230ffba337239cd983a480e1d10741e
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=155f3e64-c0fd-41cd-8e21-89ce6f6c3850%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-08 11:25 UTC, iliapolo requested changes

2020-10-08 11:25 UTC, iliapolo commented on packages/@aws-cdk/aws-s3/lib/perms.ts
> +  'kms:Decrypt', // required for multipart uploads. Refer https://aws.amazon.com/premiumsupport/knowledge-center/s3-multipart-kms-decrypt/
Why not add this to the `KEY_WRITE_ACTIONS` array? Would make it apply across the board for all write operations.

2020-10-08 11:25 UTC, iliapolo commented on packages/@aws-cdk/aws-s3/lib/bucket.ts
> +    const keyActions = perms.KEY_WRITE_ACTIONS.concat(perms.KEY_WRITE_ACTIONS_FOR_MULTIPART);
Should also be added to `grantReadWrite`

2020-10-08 11:26 UTC, iliapolo commented
@skinny85 Mind taking a look at this as well?

2020-10-08 13:14 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 761e6c0ce0352b7729a76e45e5331351005174a2
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7a8ef589-bc96-43cf-b689-51999799784f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-08 23:06 UTC, skinny85 approved these changes
LGTM! I feel like we're making a mistake by keeping the required KMS permissions in the S3 module, instead of in KMS, where they IMO belong, but that's a different issue (https://github.com/aws/aws-cdk/issues/4381), and so I'm fine with this fix.

2020-10-08 23:08 UTC, skinny85 commented
@iliapolo looks good to me, feel free to merge whenever you're ready 🙂

2020-10-08 23:34 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: c8bb031d242be1ee2bde41328ae56dbeefe2c1c5
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4517f7f3-2bae-4e10-bc94-b577da22f096%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-09 14:26 UTC, ayush987goyal commented
@iliapolo Let's merge this?

2020-10-09 16:44 UTC, iliapolo approved these changes

2020-10-09 17:12 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 1b317b82a3ec36bd1226e2799fd6ae0fcf37c34f
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6e160710-8637-450e-ada5-190d5c37d69e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-09 17:13 UTC, merged