Add ServiceCatalog L2 Construct
aws/aws-cdk pull request #11086
Opened 2020-10-24 21:31 UTC by JordanDeBeer

This PR adds support for some AWS ServiceCatalog L2 constructs.

One piece of this PR that I think is particularly interesting and warrants a solid review is the `CDKProduct` resource. Particularly because it allows the user to pass in a `core.Stack` struct and the CDKProduct handles synthesizing it so it can use the generated template in an asset.

I don't fully understand how the `cdk-assets` package works enough to support assets, but I am willing to work this part further with some guidance.
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-10-24 21:38 UTC, JordanDeBeer commented on packages/@aws-cdk/aws-servicecatalog/lib/constraints.ts
> +  readonly rules: string;
I wasn't able to find much information on how this works. The CfnResource `CfnLaunchTemplateConstraint` expects a string here.

2020-10-24 21:59 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 288785406299f8d31c8ebc162f1e1ffc29a4f70a
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=02778a4f-9e8c-4d33-93f7-e6a99f26c284%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-10-24 23:10 UTC, JordanDeBeer commented on packages/@aws-cdk/aws-servicecatalog/lib/constraints.ts
> +      // This is likely a bug and these lines can be swapped once this issue is resolved.
This line is definitely worth paying attention to.

2020-11-02 17:21 UTC, MrArnoldPalmer requested changes
Just some preliminary feedback, specifics to come as I dig in.

Can you write a section in the module's README with some example usage of the new constructs. Specifically docs about `CdkProduct` vs `Product` I think would be helpful. They definitely would be for me 😄 .

We need to update the `maturity` and `stability` fields in the package.json to reflect that the `L2s` are experimental.

Very excited for this, TY!!

2020-11-02 19:06 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: a77f055d22ec5692ed03fab6ea5bbf158a5ae553
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a75d6956-dc06-4441-bbb1-6a72b46ce55f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-02 19:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 78a85f974655cca0af7f126e69bfabfe7e227cec
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0f6ca02b-bd81-4538-a026-bc96a2b60270%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-02 20:08 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 6ab761f37946c306bd0de42aaf29f22b66e9d55c
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f12ce471-b346-4155-8240-6cce5b462fff%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-02 20:23 UTC, JordanDeBeer commented
Not sure why the build is failing due to missing "Experimental" banner.

2021-02-25 00:52 UTC, closed without merging