Publish cdk-integ-tools as separate package
aws/aws-cdk pull request #11155
Opened 2020-10-27 19:54 UTC by workeitel

Very helpful for testing construct libraries.

There was couple of times discussed in https://github.com/aws/aws-cdk/issues/993, https://github.com/aws/aws-cdk-rfcs/issues/89, https://github.com/aws/aws-cdk/issues/2898, https://github.com/aws/aws-cdk/issues/6429 and I think it's time to make it public :)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-10-27 20:21 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: e6657bc2ed0c44fbc6d2ad041f455080d156e007
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1444e7e1-e5bd-4c8d-bfa6-f5bc7f0261b8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-09 14:20 UTC, rix0rrr requested changes
Hi,

I appreciate the enthusiasm but we're not comfortable publishing the package as-is.

I suggest you use jest's `expect(...).toMatchSnapshot()` instead.

2020-11-09 22:04 UTC, workeitel commented
I agree, using jest's functionality is a good start. But the `cdk-integ-tools` package takes care of canonicalizing the template and makes it significantly easier to create the snapshot by creating and deleting the CloudFormation stack. `@aws-cdk/assert` makes it easy to compare parts of the stack but `cdk-integ-tools` is important for integration tests.

2020-11-11 08:32 UTC, rix0rrr commented
I know. We have plans to do work in this area, though I can't promise any dates. We will revisit at that time. For now, this tool isn't production ready yet and we'd be distracted supporting it if we released it.

2020-11-11 08:32 UTC, closed without merging