Allow access to lambdaFunction property of SingletonFunction
aws/aws-cdk pull request #11272
Opened 2020-11-03 15:22 UTC by mpvosseller

Provide an API to access the underlying Function of a SingletonFunction.

This allows the user, for example, to set the removal policy of the underlying Function. 
Fixes https://github.com/aws/aws-cdk/issues/11270

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-11-03 15:35 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 6b219118f818199b0367d75263977431d0c19af1
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fe8db6a7-48c3-4432-bd0c-ce5f97a6b808%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-03 16:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 9f1fb9d6783c0fa44b970c65b2abe6ef15d70517
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f2ffa552-6a98-43c6-8344-00acc8844c26%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-03 16:04 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 04a179c408020bb7a5d3711e7871b4939f2949b2
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=04ee1ffa-73c0-4d02-be59-cf6d5a1b14bf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-03 16:40 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 12800adef976123a43d86dfb6bf621c1d84e3187
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=32aff628-f5e5-4024-bddd-1d909ed93924%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-03 17:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: f9e1189129efcee70f3ded885d2791239b616833
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6d3c37f9-dbf0-4f72-b2ad-4122ad6709fa%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-09 14:25 UTC, nija-at submitted a review, later dismissed

2020-11-09 14:31 UTC, nija-at reviewed
Hey. Thanks for this PR. I'm not terribly opposed to it but I'm curious about 2 things -

(1) why do you use a singleton function along with Lambda@Edge?

(2) once the underlying Function construct, how do you plan to use it? 
I'm wondering if a `applyRemovalPolicy()` API on `SingletonFunction` be more appropriate and targeted to your use case.

2020-11-09 15:19 UTC, mpvosseller commented
Thanks for the response @nija-at 

(1) I'm building a reusable construct (call it `MyConstruct`) that creates a Lambda@Edge function. A given stack might create multiple instances of `MyConstruct`. The function logic is identical for each `MyConstruct` so a singleton can be used. Lamba@Edge functions can't be automatically deleted so an added benefit of a singleton is that later I only need to manually delete 1 function instead of N. 

(2) Yes all I'm doing is calling `applyRemovalPolicy()` so adding that to `SingletonFunction` would work just as well for my case. FWIW my current workaround was just to extend `SingletonFunction` and access the protected method `_functionNode` to set the removal policy.

```typescript
import * as lambda from '@aws-cdk/aws-lambda'
import { CfnResource, Construct, RemovalPolicy } from '@aws-cdk/core'

export class RetainedSingletonFunction extends lambda.SingletonFunction {
  constructor(scope: Construct, id: string, props: lambda.SingletonFunctionProps) {
    super(scope, id, props)
    const resource = super._functionNode().defaultChild as CfnResource // XXX protected api
    resource.applyRemovalPolicy(RemovalPolicy.RETAIN)
  }
}
```

2020-11-10 10:02 UTC, nija-at requested changes
Thanks for the explanation. 

I think changing this to add an API `applyRemovalPolicy()` would be a better change than exposing the underlying implementation.

2020-11-10 15:19 UTC, mpvosseller commented
Thanks @nija-at  

I looked quickly at implementing `applyRemovalPolicy()` on `SingletonFunction` and now tend to think it would muddy the API generally.

`applyRemovalPolicy()` appears to be an L1 API (e.g. `s3.CfnBucket`). L2 constructs (e.g. `s3.Bucket`) usually accept a `removalPolicy` property in their constructor instead.

If I extended `SingletonFunction` / `SingletonFunctionProps` to support a `removalPolicy` property it may also make sense (or require?) similar support in `Function` / `FunctionProps`. A `Function` creates multiple child constructs so it is unclear to me if the policy should also be applied to them as well.

My particular use case is just to work around the fact that lambda@edge functions don't delete cleanly and not sure it warrants the above complications.

There may be other use cases for accessing the underlying function (I saw at least [one request on SO](https://stackoverflow.com/questions/62674559/how-to-get-cfnfunction-from-singletonfunction-with-aws-cdk) but I for the time being I'm fine sticking with my class inheritance / protected API hack.

I'll close this PR.

2020-11-10 15:19 UTC, closed without merging