fix(stepfunctions-tasks): don't require encryption
aws/aws-cdk pull request #11355
Opened 2020-11-08 10:02 UTC by adamelmore

AthenaStartQueryExecution fails to deploy if
resultConfiguration.encryptionConfiguration isn't
specified. This configuration should be optional.

2020-11-08 10:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 5f94720d3a6e09aa3c867034e93d3268530b32d2
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7b39d4df-f43e-4c08-be61-0f95b6f69b2e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-09 18:12 UTC, shivlaks requested changes
@adamelmore thanks for submitting this fix - had a couple of small suggestions.
let me know if you have any questions or thoughts!!

2020-11-09 18:12 UTC, shivlaks commented on packages/@aws-cdk/aws-stepfunctions-tasks/lib/athena/start-query-execution.ts
> +
can you extract this to a helper function? (something like `parseEncryption`, `renderEncryption`, other)

2020-11-09 18:12 UTC, shivlaks commented on packages/@aws-cdk/aws-stepfunctions-tasks/lib/athena/start-query-execution.ts
> +        KmsKey: this.props.resultConfiguration?.encryptionConfiguration?.encryptionKey,
are we able to drop the `?` since we've already performed checks to verify that it's defined

2020-11-09 19:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: e2d97b45ab76b66120c890aa45db166d5a0ad864
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1f0327a1-7483-4cc5-b265-1736978c8e52%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-09 19:07 UTC, adamelmore commented
@shivlaks let me know what you think about these changes!

2020-11-09 19:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 22240f75c04388aca007693c9e98b581d779b4cb
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5731a70c-60b3-4909-b566-cbbb56a6067f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-10 07:15 UTC, shivlaks submitted a review, later dismissed

2020-11-10 07:16 UTC, shivlaks commented
@adamelmore looks great!!

2020-11-10 08:56 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: bf0754f4f44665fb339ec6bcdd0994c397ac6a81
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=11f5c766-7dad-423e-b21b-242826a43c25%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-10 08:57 UTC, adamelmore commented
@shivlaks I noticed that CodeBuild wasn't finishing, so I merged in latest and all looks green now! Sorry for the dismissal!

2020-11-12 08:02 UTC, shivlaks approved these changes

2020-11-12 08:02 UTC, shivlaks commented
@adamelmore - all good, sorry i missed your message. re-approved!!

2020-11-12 08:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 570ec11178cd47f299c9d42b5b7b32673faaed1e
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=87e65625-9b32-496d-8e5f-d4b9962b1341%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-12 08:32 UTC, merged