chore(ubergen): exclude cx-api and cloud-assembly-schema
aws/aws-cdk pull request #11422
Opened 2020-11-11 15:27 UTC by nija-at

The cx-api and cloud-assembly-schema packages define protocol between
the CDK framework and the CDK CLI.

With v2, they need to be published as public packages instead of being
bundled in with monolithic framework.

They are also required for CLI installation, since they're declared as a
dependency.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-11-11 15:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: b69deedfdabea1810b564b8a308208f34c7cdcfe
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=210cf4c5-c2ec-48f9-b6e8-181b5f757571%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-11 16:09 UTC, eladb requested changes
I think the correct way is to do both: bundle them in aws-cdk-lib _and_ publish them as independent modules so they can be consumed by the CLI (and anyone else).

I also think cx-api is a mess and we should look into deprecating it for v2.

@iliapolo thoughts?

2020-11-11 16:32 UTC, nija-at commented
> bundle them in aws-cdk-lib and publish them as independent modules

Curious why it also needs to be bundled in aws-cdk-lib.

2020-11-11 16:55 UTC, eladb commented
> Curious why it also needs to be bundled in aws-cdk-lib.

I think it might be okay if this was a regular dependency but I have a gut feeling that we need to only have a single non-bundled dependency in aws-cdk-lib (`constructs`). I think this deserves a face-to-face discussion though.

2020-11-12 13:01 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 4436f28fe88efd60d818034e4cfc43f6b2d6cfa9
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0eaaf58a-bb2c-4ed4-90d9-321385f09cb5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-12 13:10 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 816cb5259ee3540345c2ddf7d115b61e84be17d5
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=768602ce-d604-4dac-b45a-2731c1881711%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-12 14:12 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 1eb2910fa810cdfb0f7a23bebc5af9224b075a98
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=34239edd-4960-4631-977d-7c1d562b4efd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-12 14:27 UTC, eladb commented on package.json
>        "aws-cdk-lib/semver/**",
remove `semver` and `jsonSchema` from here as well, right?

2020-11-12 14:50 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 0fe6d325e1841e6e27ae830bf9a448275d320a66
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7b2244cb-7ba9-404b-81b5-1c7110ecf600%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-12 14:52 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 00497d33cb316466754f411f5f610f6d8018689f
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=280db9f6-cbe1-4348-8562-ecf571669ce5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-12 15:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 0fe6d325e1841e6e27ae830bf9a448275d320a66
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5fd1dccb-8932-480c-b445-39a2a0ad1e7a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-13 10:45 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 470c9714f5ba422cd8b6c9128309252c5a9e319a
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f485aeb2-1501-4c6d-9442-29986628d3f9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-13 10:55 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 8658cf74be18a2ff09ccd8a1afbcab1a4c861fc5
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=336b6f08-4867-41e1-b80b-3959802ef9d3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-13 11:27 UTC, eladb approved these changes

2020-11-13 11:36 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 1883ea30a7c675dfc97e764f627becf7573e840f
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0133096d-a4de-4f8f-ba69-594cd6ed457a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-13 14:30 UTC, nija-at commented
The build is failing with the error - 

```
[2020-11-13T13:15:49.324] [ERROR] jsii/compiler - Type model errors prevented the JSII assembly from being created
error JSII3002: Type "@aws-cdk/cx-api.AssemblyBuildOptions" cannot be used as a base interface because it is not exported from @aws-cdk/cx-api
error JSII9002: Unable to resolve type "@aws-cdk/cx-api.AssemblyBuildOptions". It may be @internal or not exported from the module's entry point (as configured in "package.json" as "main").
error JSII9002: Unable to resolve type "@aws-cdk/cx-api.MetadataEntry". It may be @internal or not exported from the module's entry point (as configured in "package.json" as "main").
error JSII9002: Unable to resolve type "@aws-cdk/cx-api.MissingContext". It may be @internal or not exported from the module's entry point (as configured in "package.json" as "main").
```

The fix is likely to re-export the types from within the bundled dependencies as part of `monocdk` and `aws-cdk-lib`. 

@RomainMuller had some further thoughts on why he thinks bundling is a bad idea here. I'll let him chime here.

@eladb - given that the scope of this change is slowly expanding, would you be ok with changing directions for our alpha release, and making `cx-api` and `cloud-assembly-schema` regular dependencies of `monocdk`, `aws-cdk-lib` and `aws-cdk`? 
This will help clear out the v2 pipeline and get our first alpha release out. I can take a note to re-visit this before RC.

2020-11-13 14:33 UTC, RomainMuller commented
So I basically disagree *bundling* literally ANYTHING is a long-term viable solution to any problem... 🤷🏻‍♂️
- If you bundle it AND vend another separate library... Then you might end up with both in the closure & a lot of confusion down the path.
- Yarn 2 does not support bundled dependencies, because they're gross and a source of problems. Yarn PnP is pretty darn awesome, but implies Yarn 2, meaning no bundled dependencies. If you use bundled dependencies, nobody can use Yarn PnP if they use your library.
- This means we get copies of libraries that people simply *cannot* control (it's the version shipped in and no other). This is also a longer term maintenance nightmare if you need to security patch, etc... Because there is no changing the contents of the bundled libraries out there...

If some contract must be shared between aws-cdk-lib and aws-cdk, then it must be done as:
- `aws-cdk` depends on `aws-cdk-lib` and consumes that
- `aws-cdk` and `aws-cdk-lib` share a reference to `@aws-cdk/toolkit-api` or something (which is published separately)
- `aws-cdk` and `aws-cdk-lib` both include the same submodule (i.e: they both have a copy of it which is "created" by our build tools, NOT by `npm` bundled dependencies)

2020-11-15 06:44 UTC, eladb commented
@RomainMuller I agree that eventually cx-schema should just be a copy that we bundle in both modules, not npm bundled from.

But... what would you propose for non-jsii modules? How do you propose that we use them?

2020-11-16 13:52 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: e5ac1182b7e60e108963344179a0958bb84f219c
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9b4ea12a-3859-4f4d-bbc0-9d5a336e812a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-16 17:11 UTC, closed without merging