feat(stepfunctions-tasks): add EKS run job to SFN-tasks
aws/aws-cdk pull request #11721
Opened 2020-11-25 22:36 UTC by Sumeet-Badyal

feat(stepfunctions-tasks): support for EKS Run Job Profile

Implementation

Update package @aws-cdk/aws-stepfunctions-tasks to include support for EKS Run Job
API as per documentation here:
https://docs.aws.amazon.com/step-functions/latest/dg/connect-eks.html

Includes support for the following Amazon EKS API calls:
RunJob
RunJob.sync

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-11-25 22:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: fbbdf17c8668912d1927701c9d80ea9e77382688
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=90d09671-9005-46c5-88bd-cf7b29aaa037%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-11-27 22:10 UTC, russmackenzie commented on packages/@aws-cdk/aws-stepfunctions-tasks/lib/eks/run-job.ts
> +    if (this.props.logOptions) {
LogOptions only applies if using the Run a Job pattern. Would it be useful to validate that here?

2020-11-27 22:10 UTC, russmackenzie commented on packages/@aws-cdk/aws-stepfunctions-tasks/lib/eks/run-job.ts
> +   * Non grouped logs
"Skip attempting to parse logs as JSON"

2020-12-01 08:01 UTC, shivlaks requested changes
similar feedback to the other open PRs, let's align on one first before tackling the rest

2021-01-28 04:34 UTC, daisuke-yoshimoto commented
@Sumeet-Badyal @rushimusmaximus @shivlaks 
Will this PR not be merged for a while yet? I would like to use this function.

2021-02-04 06:30 UTC, NovakGu commented
Taking over the ownership of this PR, will post a new PR soon.

2021-02-24 00:24 UTC, daisuke-yoshimoto commented
@NovakGu 

Thank you for PR of #12779. I'm sorry, but could you make a PR for this takeover?

2021-02-24 03:05 UTC, NovakGu commented
> @NovakGu
> 
> Thank you for PR of #12779. I'm sorry, but could you make a PR for this takeover?

I’m currently working on a separate PR for adding codeBuild support https://github.com/aws/aws-cdk/pull/13208. The refactoring for eks runjob has been done locally which I haven’t pushed in yet, I’ll have a PR out for this one once the codeBuild support is merged in.

2021-02-24 04:05 UTC, daisuke-yoshimoto commented
@NovakGu 

OK. Thanks you.

2021-07-22 17:33 UTC, shivlaks commented
this PR is not actively being worked on - resolving for now.

2021-07-22 17:33 UTC, closed without merging