Adding prefix in DefaultStackSynthesizer for s3 assets
aws/aws-cdk pull request #11855
Opened 2020-12-03 10:07 UTC by naveenkoppula

#https://github.com/aws/aws-cdk/issues/10710----

#11327 @rix0rrr 

Adding bucketPrefix to "stackTemplateAssetObjectUrl"

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-12-03 10:36 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 273ed122edae306181a7f2dbc0fd1fa52a7bc917
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ed034116-cfa8-4d71-84da-c323dbacf765%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-14 10:51 UTC, rix0rrr requested changes
There's no test update here.

2020-12-15 06:30 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: fd8d7f31d2945a96dd5e9369398d2dc3be449acd
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bcf8c2f0-7591-4aaf-9a96-02ebf45fa6c3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-23 13:24 UTC, naveenkoppula commented
> There's no test update here.

Did add testcase for using bucketPrefix for "stackTemplateAssetObjectUrl".

2021-01-04 19:18 UTC, Brian969 commented
@rix0rrr - How do we get this unblocked and merged?

2021-01-06 14:41 UTC, rix0rrr approved these changes

2021-01-06 15:42 UTC, merged