feat(aws-lamdba): support kmsKeyArn in lambda Function props
aws/aws-cdk pull request #11893
Opened 2020-12-06 07:31 UTC by alvyn279

- ARN for KMS key used to encrypt lambda env vars can now be specified in L2 `Function` construct
- fixes #10837

Notes:
Could we please decorate this PR with the `pr-linter/exempt-readme` label? I don't think this is a big enough feature to add README content.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-12-06 08:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 6bb8aa8a323f18bdb8c2ec1dd1707bd09a18c82d
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8a0bd978-c43f-4306-b582-87088b630390%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-08 13:16 UTC, nija-at submitted a review, later dismissed
Thanks for submitting the PR. I have one comment below.

2020-12-08 13:16 UTC, nija-at commented on packages/@aws-cdk/aws-lambda/lib/function.ts
> +  readonly kmsKeyArn?: string;
This needs to be of type [IKey](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-kms.IKey.html).

Several times, I've assumed this to be the kms key for encrypting code and realize it's not until I read the description. We should name this property `environmentEncryption` so as to make it clear.

2020-12-08 22:08 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 2841d412fe7ea56da7d0f1f1e166f59a1cf0dbec
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=577567be-51cf-4a22-b99d-52ec9609680c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-09 17:16 UTC, nija-at requested changes

2020-12-09 17:16 UTC, nija-at commented on packages/@aws-cdk/aws-lambda/package.json
> +    "@aws-cdk/aws-kms": "0.0.0"
We usually sort this alphabetically. Can you move this to line 120?

2020-12-09 17:16 UTC, nija-at commented on packages/@aws-cdk/aws-lambda/lib/function.ts
> +   * @default - AWS Lambda uses a default service key.
```suggestion
   * @default - AWS Lambda creates and uses an AWS managed customer master key (CMK).
```

2020-12-09 17:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: a55cbe8e4c0ca0518ecf47fa6a516a6ead449e61
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c76657b5-73e3-45d3-acb9-c6649cdd2071%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-10 14:08 UTC, nija-at approved these changes
Thanks for contributing to the CDK! 😊

2020-12-12 02:11 UTC, alvyn279 commented
@nija-at Do I need to fix anything (i.e.: the readme linter issue) for the Mergify bot to merge to `master` ?

2020-12-14 12:41 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 874c59787f5b5f4318d0c8312d2ee0c4943630d1
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=327f9a3f-b5af-4ea3-a785-04def99250a3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-14 12:42 UTC, merged