[ECR] configure immutable tags for ecr repo
aws/aws-cdk pull request #11954
Opened 2020-12-09 08:16 UTC by captainrandom

When creating an ecr repo allow tags to be immutable by setting the ImageTagMutability field found here:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-imagetagmutability

Trying to get the minor version bump script to work.
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-12-09 08:28 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: dc4a6a7d788e97efab410926f341a717008fb1b4
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f3e9a5cd-ecec-4661-8415-af8b429a15ed%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-09 08:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 0567ff219968acebeae467029b1af2cfb44d51e4
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2cabbd80-31c2-4915-a6a8-8d3480b0389a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-09 19:24 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 4ad87f2e4063775a5abe5a7ca51f51dad2d10e7e
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0c2455f3-6a7e-4205-bae3-c343afcc0c13%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-09 21:17 UTC, captainrandom commented
Broader question: should the `imageTagImmutable` property be a boolean or should it be a string?

2021-01-13 19:15 UTC, MrArnoldPalmer requested changes
The following files have unnecessary changes. Would appreciate if you could clean these up.

You can do `yarn install --frozen-lockfile` to install without upgrading versions in yarn.lock.

.github/actions/prlinter/package.json
packages/cdk/package.json
packages/decdk/test/fixture/package.json
tools/yarn-cling/test/test-fixture/package1/package.json
tools/yarn-cling/test/test-fixture/package2/package.json
yarn.lock

2021-01-13 19:15 UTC, MrArnoldPalmer commented on packages/@aws-cdk/aws-ecr/lib/repository.ts
> +   *  @default true
The default for this is actually `false` right? When you pass `undefined` to the L1, then the default value is `MUTABLE` as documented [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-imagetagmutability)

2021-01-13 19:37 UTC, MrArnoldPalmer requested changes
Actually I believe that the name of this property should be `imageTagMutability` to match the underlying L1 and the type should be an Enum. Even though there are only two options this feels like the best balance between safety and verbosity. The users of the L2 don't need to know to put 'MUTABLE' or 'IMMUTABLE' they just select an option on the Enum and this ensures that in the future if new options are added (idk what those would be but whatever) we can handle those.

2021-02-11 22:38 UTC, ap00rv commented
this is duplicate of : https://github.com/aws/aws-cdk/pull/10557/files

2021-05-06 02:53 UTC, MrArnoldPalmer commented
Closing this since #10557 got merged.

2021-05-06 02:53 UTC, closed without merging