feat(apigateway): add integrationOptions to LambdaRestApiProps
aws/aws-cdk pull request #12004
Opened 2020-12-11 00:35 UTC by yamatatsu

close #3269

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-12-11 01:04 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 45767fdab9bb2465a5a9ad391e31580d4921605f
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1ded1dd1-d233-4905-bfbd-0ba67a0387d5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-11 01:17 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: bcea8759542098e32cb96221497291a3159ae920
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=18c10329-f97f-46d2-99a3-4826668ca13b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-01-06 15:41 UTC, nija-at requested changes
Thanks for submitting this PR. Please see some of my comments below.

2021-01-06 15:41 UTC, nija-at commented on packages/@aws-cdk/aws-apigateway/lib/lambda-api.ts
> +   * Integration options, such as request/resopnse mapping, content handling
```suggestion
   * Integration options, such as request/response mapping, content handling
```

2021-01-06 15:41 UTC, nija-at commented on packages/@aws-cdk/aws-apigateway/lib/lambda-api.ts
> +   * @default - no options.
```suggestion
   * @default - see defaults defined in `LambdaIntegrationOptions`.
```

2021-01-07 12:51 UTC, yamatatsu commented on packages/@aws-cdk/aws-apigateway/README.md
> -- [Defining APIs](#defining-apis)
Oh. OK. I did not intend.

2021-01-07 12:53 UTC, yamatatsu commented on packages/@aws-cdk/aws-apigateway/lib/lambda-api.ts
> +   * Integration options, such as request/resopnse mapping, content handling
lol🤣

2021-01-07 13:04 UTC, yamatatsu commented
Thanks for your comments, nija-at.
I believe I've addressed all comments.

2021-01-07 13:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: fea9a5accaedbc399e0183a2195aa22293548776
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c8799ccf-e9f4-4b77-b99f-e4e1c54bbdc1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-01-07 15:07 UTC, nija-at approved these changes

2021-01-07 15:27 UTC, nija-at requested changes
Looks like there's a failing test. Can you look at the build output. A link to the build logs are in the automated comment above.

2021-02-09 00:24 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: f8d22b04cb87eed80984bcb16fd91a2733f7633f
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=637309bd-e08f-4e26-bd2b-d17d5ef858c6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-02-09 15:50 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: af50a1708a3ef5d0d2bd839b8e90ff5eec25144c
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ad9953d9-c633-4f9a-9c5b-bf420f2679fa%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-02-15 14:43 UTC, nija-at requested changes
Could you address the failing build?

2021-07-19 12:22 UTC, nija-at commented
Closing this old pull request. Please open a new pull request when you have updates.

2021-07-19 12:22 UTC, closed without merging