chore(codebuild): update default build image to STANDARD_4_0
aws/aws-cdk pull request #12002
Opened 2020-12-10 20:25 UTC by blimmer

By default, CodeBuild projects were defaulting to `aws/codebuild/standard:1.0`, which is quite old. According to [these docs](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html):

> The latest version of each image is cached. If you specify a more specific version, then CodeBuild provisions that version instead of the cached version. This can result in longer build times. 

Before I specified a newer build image, my CodeBuild project was taking 4+ minutes to provision and I was confused about why it was so slow. When I dug deeper and found the docs linked above, provisioning took less than 30 seconds.

Therefore, to provide users the best out-of-the-box experience, I believe the default should be the newer, cached image. This PR updates that default.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-12-10 20:39 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 5b0e68edb52e5a9650bf78d710292a795042568e
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=799cf84b-bc4d-437d-9c5f-23b5315d7cc7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-10 20:43 UTC, blimmer commented
I'll fix these tests up in a bit.

2020-12-10 20:53 UTC, skinny85 requested changes
Sorry, not before v2 😉

2020-12-10 21:54 UTC, blimmer commented
Hey @skinny85 - I don't actually know about v2 - is there a code freeze or something?

2020-12-10 22:36 UTC, skinny85 commented
No, this would just be a breaking change in version 1.x of CDK. See https://github.com/aws/aws-cdk/issues/11960 .

2020-12-10 23:53 UTC, blimmer commented
Ah, OK, I understand now. I didn't see that other issue. Are breaking changes only acceptable for certain (experimental) packages?

2020-12-11 00:05 UTC, skinny85 commented
> Are breaking changes only acceptable for certain (experimental) packages?

Yep. When we declare a give package "Stable", like CodeBuild is now, we no longer allow breaking changes to it in minor releases (like `1.76.0` to `1.77.0`).

Any breaking changes to these have to be reserved for a major version release (like `1.77.0` to `2.0.0`).

2021-06-22 16:06 UTC, skinny85 commented
Closing in favor of https://github.com/aws/aws-cdk/pull/14472.

2021-06-22 16:06 UTC, closed without merging