fix(cloudwatch-actions): alarm not sent to KMS encrypted SNS topic
aws/aws-cdk pull request #12117
Opened 2020-12-16 20:57 UTC by jumi-dev

Grant KMS permission to cloudwatch service principal if a cloudwatch alarm is sent to a KMS encrypted SNS topic.

fixes #11121

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-12-16 21:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: c6a71638c07fee90069297f6d81fcddf65c53b04
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=64ded5ca-93fb-49c4-bc92-5f7decdbeef5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-16 21:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 361d8750c99c696b78e7664b6016c2e122e08dd9
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=17fa9247-edba-4573-bf31-3bf2060be446%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-12-17 11:44 UTC, jumi-dev commented
@rix0rrr The build process for this pull request is still in process. Is this caused by the changes in the commit? Or is there an issue in the build process?
The build logs are empty, so I can't figure out what's wrong.
Thanks.

2020-12-22 05:48 UTC, NetaNir commented
@jumi-dev the build is running now

2020-12-22 06:25 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 0c69af91ebc5b3e4344d42b0c418b24abb28cc68
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e522ce94-652d-4f54-b0be-304e3684d931%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-01-06 14:01 UTC, rix0rrr requested changes
I'm not entirely a fan of this, as it is very individual-case based. This fixes it for CloudWatch Actions but what about Events or StepFunctions or ...? Are we going to have to copy/paste this logic around?

I'd rather do one of two things which I'm like 90% sure should also work:

# 1. Add this to the `grant` methods of the topic.

The topic will know if it's encrypted, and so can add the requires permissions on the key. This will capture all cases where we're using topic grants.

# 2. Make the key policy trust itself being used *via* SNS

We use this mechanism for S3: https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml#L113-L119

It makes it so you have access to the key as long as the encryption call is done by SNS on behalf of you (which implies you have access to the SNS topic, which is the most pertinent issue).

This option depends a bit on the actual call pattern: are the messages transparently encrypted (as happens in S3) or is the client expected to encrypt the messages itself and then push encrypted messages into the topic?

2021-09-28 20:22 UTC, jaresuth approved these changes

2022-03-22 00:15 UTC, closed without merging