append construct name and unique id to event policy statement id
aws/aws-cdk pull request #12538
Opened 2021-01-15 16:18 UTC by mazayan

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

Note: this pull request is in reference to git issue: https://github.com/aws/aws-cdk/issues/12479

2021-01-15 16:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 6c80bab0bbfa29bc9e292bc132947567346dfb41
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d13c5f0a-3059-4564-8c5d-90acad3eff09%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-01-15 19:34 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 38578de90ececab5a32ef5d3b0f5fe5ea11150f5
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=06d96c69-9a41-48ae-8752-85f743691da5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-01-15 19:58 UTC, skinny85 commented
Assigned @rix0rrr , who now owns the `@aws-cdk/aws-events` module.

2021-01-26 15:11 UTC, rix0rrr requested changes

2021-01-26 15:11 UTC, rix0rrr commented on packages/@aws-cdk/aws-events/lib/rule.ts
> +            statementId: `Allow-account-${sourceAccount}-${Names.uniqueId(this)}`,
What is the maximum length of a Sid? Can you ensure this length never grows too large?

2021-01-26 15:27 UTC, rix0rrr commented on packages/@aws-cdk/aws-events/lib/rule.ts
> +            statementId: `Allow-account-${sourceAccount}-${Names.uniqueId(this)}`,
`this.node.addr` may be better.

2022-03-17 17:24 UTC, closed without merging