feat(aws-codepipeline-actions): Add Full Clone support for CodeCommit
aws/aws-cdk pull request #12558
Opened 2021-01-17 22:08 UTC by DaWyz

Add `codeBuildCloneOutput` property to the CodeCommit source action.

This property can only be used by CodeBuild downstream actions.

If you choose this option, you need to add the `codecommit:GitPull` permission to your CodeBuild service role for CodeCommit source actions.

Closes #12236

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-01-17 22:45 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: f8bc186a5a9d96bddbafdc4f4e7625e1620e4723
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b4ffc7e4-3b68-4498-8999-67bd917d4d94%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-01-17 23:25 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: e11e1ac2b93e1de13c4970918f72feac6de1f857
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1b42c7b2-032e-44e4-97b9-b30ddadac53c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-01-17 23:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 1fa5fe8eb347f0e244e15c6fcc7d147df09c30e0
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c3a9f30e-c930-4064-b5a0-5369e5266c86%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-01-19 23:35 UTC, skinny85 requested changes
Looks great @DaWyz , thanks so much for the contribution! Couple of minor comments below 😊.

2021-01-19 23:35 UTC, skinny85 commented on packages/@aws-cdk/aws-codepipeline-actions/lib/codebuild/build-action.ts
> +import { CodeCommitSourceAction } from '../codecommit/source-action';
This should be moved up, just below the `import { BitBucketSourceAction } from '..';` line.

2021-01-19 23:35 UTC, skinny85 commented on packages/@aws-cdk/aws-codepipeline-actions/lib/codecommit/source-action.ts
> +    if (this.props.codeBuildCloneOutput === true) {
Can you actually fold this statement into the above one, considering their Resource is the same? Something like this:

```ts
      actions: [
        'codecommit:GetBranch',
        'codecommit:GetCommit',
        'codecommit:UploadArchive',
        'codecommit:GetUploadArchiveStatus',
        'codecommit:CancelUploadArchive',
        ...this.props.codeBuildCloneOutput ? ['codecommit:GetRepository'] : [],
      ],
```

2021-01-19 23:35 UTC, skinny85 commented on packages/@aws-cdk/aws-codepipeline-actions/test/codecommit/test.codecommit-source-action.ts
> +            {},
If you use the helpers we have like `objectLike()` and `arrayWith()`, you can avoid these empty objects. Here's an example of using them: https://github.com/aws/aws-cdk/blob/12868a2ac9c7016e47633045fb0c00be7eeb5092/packages/%40aws-cdk/pipelines/test/cross-environment-infra.test.ts#L33-L48

2021-01-19 23:35 UTC, skinny85 commented on packages/@aws-cdk/aws-codepipeline-actions/test/codecommit/test.codecommit-source-action.ts
> +            {},
Same comment here as above.

2021-01-19 23:37 UTC, skinny85 commented
Also, please update the [ReadMe file of the package](https://github.com/aws/aws-cdk/blob/12868a2ac9c7016e47633045fb0c00be7eeb5092/packages/@aws-cdk/aws-codepipeline-actions/README.md#aws-codecommit)!

2021-01-20 01:36 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: b34aa9e007048e47954cbaa5fb9913d8b7a88210
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9d5cd65e-fe52-4621-bb8b-237df93480a5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-01-20 02:06 UTC, DaWyz commented
@skinny85 PR updated. Please, double check the section added in the `README.md` to make sure it's good enough.

Thanks!

2021-01-21 21:48 UTC, skinny85 approved these changes
This is absolutely fantastic work @DaWyz . Thanks so much for the contribution!

2021-01-21 22:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 657a869fa95cf530f054492d74706d3074f37db5
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=41788fdf-a896-49c3-9900-bf33739fb690%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-01-21 22:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 6c2756023d4ffca1136bf449cc57812165f3c951
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0a55ec32-8761-4f33-b3fb-20c7f4601bf9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-01-21 22:58 UTC, merged