feat(lambda): add nodejs14.x runtime
aws/aws-cdk pull request #12861
Opened 2021-02-04 02:14 UTC by trivikr

Blog post: [Node.js 14.x runtime now available in AWS Lambda](https://aws.amazon.com/blogs/compute/node-js-14-x-runtime-now-available-in-aws-lambda/)
Developer Guide: [Node.js lambda runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-02-04 02:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 7227d6ef2a57ac884df3c0355ab19d00e40ad7d6
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6ad6ec3c-de4b-4adc-bef1-0c0f6aab3f76%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-02-04 08:40 UTC, coderbyheart requested changes

2021-02-04 08:40 UTC, coderbyheart commented on packages/@aws-cdk/aws-lambda/lib/runtime.ts
> +  public static readonly NODEJS_14_X = new Runtime('nodejs14.x', RuntimeFamily.NODEJS, { supportsInlineCode: true });
```suggestion
  public static readonly NODEJS_14_X = new Runtime('nodejs14.x', RuntimeFamily.NODEJS, { supportsInlineCode: false });
```

I have tested this, and as of now the runtime does not support inline code in `eu-central-1`

> 8/17 | 8:24:49 AM | CREATE_FAILED        | AWS::Lambda::Function       | Lambda (LambdaD247545B) ZipFile can only be used when Runtime is set to either of nodejs8.10, nodejs10.x, nodejs12.x, python2.7, python3.6, python3.7, python3.8.

2021-02-04 10:04 UTC, nija-at submitted a review, later dismissed
Thanks for the PR.

Please address the comment above

2021-02-04 16:07 UTC, trivikr commented
> Please address the comment above

Addressed :+1:

2021-02-04 16:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 6b8344c36c87244655487641ef78d25520a3eb09
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5787d2ab-1b7b-45de-82db-e2fe29670ecf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-02-04 17:36 UTC, nija-at approved these changes

2021-02-04 18:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 1359ee248b1b156923811744e598d5503d71e1e2
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=94aba4a8-b627-479a-b349-7eed9f73d078%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-02-04 18:49 UTC, merged

2021-02-10 08:37 UTC, lielran commented
Thanks for the quick PR and merge. happy to see cdk stay up to date with upgrades of aws services.