Change Python app template to import core module as cdk
aws/aws-cdk pull request #12970
Opened 2021-02-10 16:55 UTC by Jerry-AWS

For consistency and to make it easier to translate TypeScript examples into Python, import the `aws_cdk.core` module as `cdk`.

There are snippets in the CDK Developer Guide that assume the `core` module is imported as `core`. It is difficult to synchronize changes to the CDK with changes in the Guide, so this PR causes the `core` module to be imported under _both_ names. Once this change is released, the Guide snippets can be updated to use `cdk` rather than `core` to refer to the `core` module. At some point in the future, this template can be updated again to remove the now-redundant `core` import.

This is to support this Guide issue: https://github.com/awsdocs/aws-cdk-guide/issues/268 which intends to make all code snippets in the Guide follow the guidance in the "Working with the CDK in Python" topic.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-02-10 17:14 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: d644e0b00d9af9ce50b89f9b1f1eeab30b9f3e3c
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0f9c5f3e-e689-4302-ab31-3301ea202587%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-02-10 18:21 UTC, shivlaks requested changes

2021-02-10 18:21 UTC, shivlaks commented on packages/aws-cdk/lib/init-templates/v1/app/python/app.template.py
> +from aws_cdk import core, core as cdk
```suggestion
import core from aws_cdk as cdk
```

2021-02-11 20:57 UTC, Jerry-AWS commented on packages/aws-cdk/lib/init-templates/v1/app/python/%name.PythonModule%/%name.PythonModule%_stack.template.py
> +from aws_cdk import core, core as cdk
This isn't valid Python syntax and doesn't have the intended effect (having `core` imported a both `cdk` and `core` to give me a window to update the code snippets to use `cdk`, where the examples can use either without breaking).

2021-02-11 20:57 UTC, Jerry-AWS commented on packages/aws-cdk/lib/init-templates/v1/app/python/app.template.py
> +from aws_cdk import core, core as cdk
Same as above.

2021-02-22 23:09 UTC, Jerry-AWS commented
I changed this to do the two imports of `core` separately and added a comment to explain why it was being imported twice.

2021-02-22 23:24 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 195b4bce31921410432d5531eacd0c607ac8aee9
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3340ab0c-ed09-4add-aff4-a598b9999dd1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-02-22 23:38 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 15662ed3cccd28e02c7f10518af4cb8cabfcc3e3
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=69564eea-d0f7-4d30-9234-6061360a9385%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-02-25 13:41 UTC, rix0rrr approved these changes

2021-02-25 16:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: d6b0838cfefa86df322de9fc39aafc0f34968f3e
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0c7c6f2e-af43-4603-b9f2-887ea280b320%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-02-25 17:02 UTC, Jerry-AWS commented
@rix0rrr How do I fix the PR Linter error? I don't think there are any tests that involve the template. I can report that the template does synth fine.

2021-02-25 18:01 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 81832edb0e8caddfc6c159511297013d9b1beadd
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=12e45ca5-81ab-452c-8232-6954fc4d34a1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-02-25 22:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 6ff2e17474717d78f3dca957ccc1ee45e84e9747
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f2d2e4fd-4443-472b-aac6-0815ad74f7f7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-02-25 22:37 UTC, merged