feat(cloudwatch): add contributor insights widget
aws/aws-cdk pull request #13008
Opened 2021-02-12 09:49 UTC by muelleme

This adds a ContributorInsightsWidget to show data from Contributor
Insights rules. This was a feature supported by the console but not the
CDK so far. This closes #13005

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-02-12 10:23 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 70a9d68dffd805fd1ae042356363b2531080c731
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a9b150e4-a813-4722-9bf3-84fcc644066f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-02-25 13:39 UTC, rix0rrr requested changes

2021-02-25 13:39 UTC, rix0rrr commented on packages/@aws-cdk/aws-cloudwatch/lib/contributor-insights-widget.ts
> +  readonly ruleName: string;
Is an "insights rule" a resource that is created independently?

In that case, referencing it should follow the same rules as referencing other AWS resources: we don't accept buckets as `bucketName: string`, we accept bucket as `bucket: IBucket`.

By that same token, we're probably going to need an `IInsightRule` and an `InsightRule.fromInsightRuleName()` to produce one.

You could go as far as completely fill out the L2 for [`AWS::CloudWatch::InsightRule`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-insightrule.html) but I will accept an `abstract` class that only allows importing existing insight rules as a minimal delta from what we have, to move this PR forward.

2022-03-30 20:50 UTC, TheRealAmazonKendra commented
This PR has been deemed to be abandoned, and will be closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-03-30 20:50 UTC, closed without merging