feat(cloudwatch): period in GraphWidget
aws/aws-cdk pull request #13555
Opened 2021-03-11 20:16 UTC by bentonkribbs

This PR adds support for the period property in CloudWatch GraphWidgets.

The property in question can be seen here, under "period": https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/CloudWatch-Dashboard-Body-Structure.html#CloudWatch-Dashboard-Properties-Metric-Widget-Object

This fixes https://github.com/aws/aws-cdk/issues/6367

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-03-11 20:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 79f34c3ba36a1eed15fbd46ea242522193fa3f7f
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6415be9a-edf2-4796-b54d-f2cd52e43c26%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-11 20:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: b7b4d78fda70b81b6647ebac12053fee75ce7751
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5cf2d336-6c46-4572-aae2-57e71edcc1d9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-11 21:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 0b2c40387bbc49de651041567c41866f0c1bd0be
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a48eb8ab-09ef-49a5-b04a-cb95435e7897%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-11 21:42 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: df7c20c4df935ddb185e7865894fe4424d6fe73d
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=08e568c8-889d-4c8e-bbb7-c997adf90b7f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-18 08:49 UTC, rix0rrr commented
I think doing this will break how metrics are rendered. Right now, when metrics render themselves they will render their own `period` if it is `!= 300`, assuming that the graph period is going to be 5 minutes (and so no need to render duplicate numbers).

Right now, if you set the graph period to `1 minute` and add a `5 minute` metric, the metric will NOT RENDER its period and hence appear at a `1 minute` rate.

Can you describe the problem you are solving?

2021-03-22 16:53 UTC, NetaNir requested changes
see Rico's comment

2021-03-22 23:34 UTC, bentonkribbs commented
My primary use case was creating a `GraphWidget` with a `MathExpression`, and trying to set all `MathExpression`s and `Metric`s in this `GraphWidget` to use a period of 60 seconds. At the time, the `MathExpression`'s period wasn't working as expected in our local version of CDK, but this: ( https://github.com/aws/aws-cdk/pull/13078) now solves my use case. 

I am not sure if there is an other use case where the `GraphWidget`'s period property would need set which can't be satisfied by setting the individual `MathExpression`s and `Metric`s periods. Based on the fact that `IMetric` is [only implemented](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudwatch.IMetric.html) by these two classes, I think this PR is no longer needed.

2021-03-22 23:34 UTC, closed without merging