feat(aws-logs): allow optional role to write log events in destination
aws/aws-cdk pull request #13553
Opened 2021-03-11 19:12 UTC by gmeligio

* [x ] Testing
  - Unit test added.
* [x ] Docs
  - __jsdocs__: All public APIs documented
  - __README__: README and/or documentation topic updated

Add an optional `role` to the log group that will be used to write logs in the destination.
 
Closes #7661.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-03-11 19:17 UTC, gmeligio commented
I was able to unit test `aws-logs` but no `aws-logs-destinations` because the latter has peer-dependencies that are not available with `yarn install` like `@aws-cdk/aws-iam` and `@aws-cdk/aws-lambda`.

2021-03-11 19:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 8ae7542939d06e9487064f99883d350eb252c3a6
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4e57ad0f-8146-4be1-b800-3b2e367204b5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-11 19:33 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 630e73da76876b23c50f1466feed87eda83c6b4e
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=53c20673-4ee3-41ea-bf2c-8b5f461fc0ef%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-15 11:29 UTC, rix0rrr requested changes
It looks like what you're trying to do is preventing the Kinesis destination from creating a Role for you. I'm assuming because your organization does not allow the creation of new Roles by developers.

Right now it's the case that the `ILogSubscriptionDestination` is responsible for creating the Roles. If you want it to stop doing that, the easiest way is to make a pre-existing Role configurable on all the individual subclasses of `ILogSubscriptionDestination`, starting with the Kinesis one. Create a new (optional) Props object with a single `role?: Role` field, and use that one if given instead of creating a new one. This is the pattern used all across the CDK.

----

The next question might be--does this make sense? Should the Role not be configured by the subscription filter itself instead of its destination?

A case could definitely be made for that. That requires a bigger refactor, where we add the `role?: Role` argument to `SubscriptionFilterOptions`, and we need to add some protocol between the SubscriptionFilter and the Destination to indicate whether or not the filter already HAS a role or needs one configured (and even if one already exists, permissions may still need to be added to them!).

You could also take on that, I'm not opposed to it.

-----

In neither case is a change to `LogGroup` necessary, or does `LogGroup` implicitly get a Role or something. You are using the LogGroup object to transport a single variable somewhere else -- that doesn't seem necessargy.

2021-03-15 11:29 UTC, rix0rrr commented on packages/@aws-cdk/aws-logs/README.md
> +    roleArn: role.roleArn
It's not roleArn though, right?

2021-03-15 11:29 UTC, rix0rrr commented on packages/@aws-cdk/aws-logs/lib/log-group.ts
> +  readonly role?: iam.IRole;
No need to expose this here.

2022-01-11 20:14 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 0c79237530a71548632f9325f6b84620da95c250
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ec41564a-05b3-427c-ac06-66b9e61e4135%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-01-15 17:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 179d5a1657f81810cab5981bd1c09d6c8d56b3da
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bc591a64-92ce-4a05-bf2d-77db6c3250a0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-15 13:04 UTC, rix0rrr approved these changes

2022-02-15 13:26 UTC, rix0rrr approved these changes

2022-02-15 13:27 UTC, rix0rrr submitted a review, later dismissed

2022-02-15 13:35 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 561c0f66de92b95dd79c2f8934983701f1f19393
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5cc30251-b127-4a8d-9f66-6b9897c382a4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-15 14:09 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: e6497099d2246163a5e98daa6065e00cb7482ad4
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=af0188f4-9b4c-4c26-b30c-e1a755dab22b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-15 15:04 UTC, rix0rrr submitted a review, later dismissed

2022-02-15 15:45 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 773c85b87f8601ae970b4ca55e62b5de4c7c67b9
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=628e04ba-815c-413b-bb2e-26ccba51e5c7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-16 10:47 UTC, rix0rrr approved these changes

2022-02-16 11:28 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 0e38f67fc36facb0ed8218eb2b275373a6dd1f35
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c2bff6e6-d7e8-455e-87c1-ab1ce217d0dc%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-16 11:28 UTC, merged