feat(aws-batch): fargate support for batch jobs
aws/aws-cdk pull request #13591
Opened 2021-03-15 03:52 UTC by kokachev

Added Fargate support for Batch jobs.

closes: #13590

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-03-15 04:26 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 5bfc53192bde0d19134ae0661564cfb3e5f1a966
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d230fe8b-4af3-4eca-818e-ccac9c449400%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-15 04:34 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 1d6f5d54b49e697885884f49818e429697d34939
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=cefaf100-db08-4385-ba92-72b86c0b4d5d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-16 01:04 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 84119ba04854ce8f11cc1593ba72bae352a89f92
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=22df7da3-0115-4d39-98a4-cf7413adbbe2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-16 01:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 166c998ee8d62bfdcd298ad3b8690fae64077518
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=70b658d8-4f10-4e28-8b32-ec4c9dba128f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-16 02:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 3c4fd44a8a5ec1f9bf7ef3618bdf8d4ee55f6220
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6eeda759-33b7-4efa-91b6-27ceb2580581%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-16 02:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: a77942caa17c2cec928a36e0aa28efcc8f9e7428
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fd09ad91-497e-49c3-92fa-9ac5f1d05ce3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-16 02:43 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: bef6f4662a631f765344229d0cbf3fef511f8f32
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=24917a9d-73d6-4c36-8015-ce8c12089257%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-16 03:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: f3eadba10d54892e79a9f2864c6d59dec559bb7d
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0471108c-51b2-4724-b79e-beb3d96618ef%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-02 02:00 UTC, kokachev commented
@iliapolo review?

2021-04-02 09:49 UTC, iliapolo commented
> @iliapolo review?

Apologies for the delay. Thanks for creating this PR! 

I should be able to get a first round in soon 👍

2021-04-21 00:19 UTC, kokachev commented
> > @iliapolo review?
> 
> @kokachev Apologies for the delay. Thanks for creating this PR!
> 
> I should be able to get a first round in soon 👍

@iliapolo can someone else review it?

2021-05-06 11:22 UTC, kokachev commented
@iliapolo should I close this PR?

2021-05-06 11:33 UTC, iliapolo commented
@kokachev No - I still have this on my radar. Would be good if you resolved the conflicts that arose in the meantime though :)

2021-05-17 20:53 UTC, iliapolo requested changes
Nice. Very clean and straight forward 👍

2021-05-17 20:53 UTC, iliapolo commented on packages/@aws-cdk/aws-batch/README.md
> +const spotEnvironment = new batch.ComputeEnvironment(stack, 'MyFargateEnvironment', {
```suggestion
const fargateSpotEnvironment = new batch.ComputeEnvironment(stack, 'MyFargateEnvironment', {
```

2021-05-17 20:53 UTC, iliapolo commented on packages/@aws-cdk/aws-batch/lib/compute-environment.ts
> +  FARGATE_SPOT = 'FARGATE_SPOT',
What does *spot* mean in the context of *fargate*? would be nice to have a sentence or two about it.

2021-05-17 20:53 UTC, iliapolo commented on packages/@aws-cdk/aws-batch/test/compute-environment.test.ts
> +  describe('using fargate resources', () => {
We also need an integ test. Add a compute environment to https://github.com/aws/aws-cdk/blob/master/packages/@aws-cdk/aws-batch/test/integ.batch.ts#L30

2021-05-18 06:08 UTC, kokachev commented
will update the PR.

2021-05-19 11:47 UTC, brendonparker commented
Looking forward to being able to play with this :)

2021-05-19 11:59 UTC, brendonparker commented on packages/@aws-cdk/aws-batch/lib/job-definition.ts
> +      fargatePlatformConfiguration: container.fargatePlatformConfiguration ? {
Sorry, my github-fu is weak. Not sure how to put a comment on code that isn't a part of the PR.

But above, when setting the `resourceRequirements`, don't we need a way to pass those in for fargate?
```
resourceRequirements: container.gpuCount
  ? [{ type: 'GPU', value: String(container.gpuCount) }]
  : undefined
```

Also, pretty sure that `vcpus` needs to be not set

2021-07-14 14:08 UTC, robertd commented
Looking forward to this PR being merged in 👍 ... just in time for what I'm working on. 😄

2021-08-02 03:36 UTC, DDynamic commented
@iliapolo @brendonparker since it has been a little while since the author has responded, I've opened PR #15848 that responds to all of the feedback left of this MR in hopes that this will be brought to completion soon. A review as soon as you get a chance would be greatly appreciated.

2021-08-02 03:39 UTC, robertd commented
@DDynamic sweet 👍😊

2021-08-02 14:59 UTC, iliapolo commented
Closing in favor of https://github.com/aws/aws-cdk/pull/15848

2021-08-02 14:59 UTC, closed without merging