feat(init-templates): app template comes with hint comments for 'env'
aws/aws-cdk pull request #13696
Opened 2021-03-19 15:10 UTC by rix0rrr

How the `env` parameter is supposed to be used is still confusing to
a lot of users.

Add uncommentable lines to the init templates showing and describing
the 3 alternatives.

Fixes #12321.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-03-19 15:10 UTC, rix0rrr commented
Not merging yet -- would like to get some agreement on verbiage before I apply the same to all templates.

2021-03-19 15:20 UTC, nija-at requested changes

2021-03-19 15:20 UTC, nija-at commented on packages/aws-cdk/lib/init-templates/v1/app/typescript/bin/%name%.template.ts
> +  /* If you don't specify 'env', this stack will be environment-agnostic.
Other languages? v2 templates?

2021-03-19 15:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 04de13cd3e8b82941cd5d59b8ed7498f184924da
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=98c1c5cc-3df4-41d1-8e15-333349e4a118%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-19 16:17 UTC, rix0rrr commented on packages/aws-cdk/lib/init-templates/v1/app/typescript/bin/%name%.template.ts
> +  /* If you don't specify 'env', this stack will be environment-agnostic.
> Not merging yet -- would like to get some agreement on verbiage before I apply the same to all templates.

2021-03-19 16:23 UTC, nija-at reviewed
I'm ok using this and the verbiage.

Just one comment.

2021-03-19 16:23 UTC, nija-at commented on packages/aws-cdk/lib/init-templates/v1/app/typescript/bin/%name%.template.ts
> +   * but a single synthesized template can be deployed anywhere. */
```suggestion
   * but a single synthesized template can be deployed anywhere.
   * See https://docs.aws.amazon.com/cdk/latest/guide/stacks.html to
   * learn more about environment agnostic stacks.
   * See https://docs.aws.amazon.com/cdk/latest/guide/context.html to
   * learn more about runtime contexts. */
```

2021-03-19 17:34 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 3bb5c65406fbf86b8391a6a1ed99d69a90d3a381
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=41126856-0155-45a3-add7-83547aa42c3a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-22 10:13 UTC, nija-at approved these changes

2021-03-22 10:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: e3cc22ff7d368445584d9edefc9caf0166e94ff1
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=725160d1-c92f-4cf8-940e-77d3c9c50456%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-22 11:24 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 53a925b6c34122d418c44a2206ce8e969d939840
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2d34c965-9866-4b5e-a00c-da2b4457bfbc%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-22 11:24 UTC, merged