chore(core): remove deprecated construct dependency APIs
aws/aws-cdk pull request #13871
Opened 2021-03-30 08:26 UTC by eladb

Delete bunch of remaining APIs that are deprecated and available in constructs 10.x

Follow up of https://github.com/aws/aws-cdk/pull/12054

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-03-30 08:40 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: ae2d0e7f5a97f52939719e5476d95fc677d1e8df
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ed6d3b95-08ad-42cd-bb26-dbe594f174c3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-30 08:55 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 2d6c56d6a0f02aaa9ebe301de14127d7da99e0f4
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=aa8ce165-495f-4be4-8364-3302b11d6296%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-30 11:04 UTC, nija-at requested changes

2021-03-30 11:04 UTC, nija-at commented on packages/@aws-cdk/aws-ec2/lib/vpc.ts
At a glance, it looks like many of these can be applied to master instead of `v2-main`.

2021-03-30 11:04 UTC, nija-at commented on packages/@aws-cdk/aws-iam/lib/grant.ts
> +export class Grant implements IDependable {
could we do `export class Grant implements cdk.IDependable, IDependable {` on master, and mark the former as deprecated?

2021-03-30 11:04 UTC, nija-at commented on packages/@aws-cdk/aws-ec2/lib/vpc.ts
> +  public readonly internetConnectivityEstablished: IDependable = new DependencyGroup();
similar. can we mark `internetConnectivityEstablished` as deprecated and introduce new equivalent props?

2021-03-30 13:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: d1ec54c1502ca7bb50108b99234639ee0ad1f6d4
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ee9351c7-8c79-4301-85d4-1ff80d4555f7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-30 13:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 0f29d223fcd9453c1085ca24a4d58d7b5cf682d4
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=096e4aa9-52ef-4ed7-b341-9479fe91be18%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-03-30 14:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: b7ebfd7b7985a916f668a345164ba6cbe9719749
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=692656bb-3283-4b82-8fea-b1074f7207d8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-06 13:16 UTC, eladb commented
@nija-at following on our chat, let me know if you approve this.

2021-04-06 13:23 UTC, nija-at approved these changes

2021-04-06 13:53 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 24ce80ee86abd202388a1ae49a47df0ec2328b5b
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6d43b126-a687-4162-8318-3f954ed2b92a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-06 13:53 UTC, merged