feat(lambda-python): support build args (#12949)
aws/aws-cdk pull request #13938
Opened 2021-04-01 15:43 UTC by rirze

Add support for passing build arguments when building the bundling
image.

Closes #12949

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-04-01 15:47 UTC, rirze commented
If possible, I'd like some help in adding support for passing in Docker environment variables for both `PythonFunction` and `PythonLayerVersion`. I tried taking a look at how it was implemented in `lambda-nodejs` but my Typescript comprehension wasn't strong enough to port over that functionality to this module.

2021-04-01 16:12 UTC, eladb requested changes
Did you consider exposing a `bundling` option (like in `NodeJsFunction`) which already allows specifying `buildArgs`.

2021-04-01 16:12 UTC, eladb commented on packages/@aws-cdk/aws-lambda-python/README.md
> +Use the `build_args` parameter to pass build arguments when building the bundling image:
```suggestion
Use the `buildArgs` parameter to pass build arguments when building the bundling image:
```

2021-04-01 16:12 UTC, eladb commented on packages/@aws-cdk/aws-lambda-python/lib/bundling.ts
> +  readonly buildArgs?: { [key:string] : string };
Stylistic:

```suggestion
  readonly buildArgs?: { [key:string]: string };
```

2021-04-01 16:14 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 16f43d108d213f0e8cbaa33028e623b07334894d
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d3921440-158f-4c74-bf41-6f9c0078e730%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-01 16:17 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 768867b7be97fb07cd5ad62178532fec618756ef
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8e355ff7-6405-4ff6-9c59-330b910fcd8e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-01 16:24 UTC, rirze commented
I did consider creating a bundling options class, but after looking at its implementation in `aws-lambda-nodejs/bundling.ts`, I couldn't separate what was essential to Docker and what was specific to Typescript bundling (esbuild). 

If desired, I could try my hand at exposing a `Bundling` class for this module and we could iteratively refine it. I'd imagine this would require a few rounds of feedback.

2021-04-01 16:58 UTC, eladb commented
@rirze there is already a `BundlingOptions` struct, why not reuse that? (like `NodeJsFunction` does)

@jogold any chance you can work with @rirze to align those APIs?

2021-04-01 16:59 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: adf007b29537d722bc2e78e2eb73c1cdf99e08f2
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=228a218e-ed44-42e7-900f-abd57a1eedef%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-01 17:06 UTC, rirze commented
Hmm, I think I was confused because I assumed `PythonFunction` would need its own `Bundling` class like it does in `NodeJsFunction` (`Bundling implements cdk.BundlingOptions`). But looking it more, it seems like most of the logic there is related to esbuild. So making sure I understand correctly, passing in a `cdk.BundlingOptions` should be sufficient for `PythonFunction`/`PythonLayerVersion`, correct?

2021-04-01 17:28 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: e19580fdda1535de1ab3677dea969b8adb2ad554
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7e73c236-7eb7-42dc-815f-2a52cc57741e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-20 06:53 UTC, jogold commented
We currently have the following API for the `NodejsFunction`:
* a `bundling` prop in `NodejsFunctionProps` of type `BundlingOptions`: https://github.com/aws/aws-cdk/blob/26919865f3f9079cbfa3103a4df14051f45fb734/packages/%40aws-cdk/aws-lambda-nodejs/lib/function.ts#L69-L75
* in there we have `buildArgs`: https://github.com/aws/aws-cdk/blob/26919865f3f9079cbfa3103a4df14051f45fb734/packages/%40aws-cdk/aws-lambda-nodejs/lib/types.ts#L175-L180

I think we can do the same here.

2021-05-02 06:54 UTC, eladb commented
@rirze I am closing this PR for now. Feel free to re-open when ready to continue :-)

2021-05-02 06:54 UTC, closed without merging