fix(cli): wrong account used when containers are pushed, a followup from #7022
aws/aws-cdk pull request #14151
Opened 2021-04-13 18:08 UTC by bigkraig

Continuation on fix from #7022, the container push was missed.

Duplicates account lookup used on files, for containers: https://github.com/aws/aws-cdk/commit/afd70453de70e8e54bfd941404efda74d594e0e6#diff-ae0c51f3723b61d922c2c1db93891e22ab0b78b95a24b9794044d4c140bfd649L28-R30

Resolves #14008

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-04-13 18:41 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 4535e421ed4580b4e89c0210d955a16e97eaf24a
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e7e07c31-0a7c-44c1-ac06-98fae845d6bc%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-21 14:23 UTC, rix0rrr requested changes
I believe you, but I have a hard time understanding the PR message and the code confuses me.

It's turning a VALUE into a FUNCTION? And this is correct?

Can you please explain the PR body what the issue is, what the root cause is and why the code change fixes it?

And this probably needs a test as well...

2021-04-21 14:24 UTC, rix0rrr commented
Ah I see, we're purposely turning a value into a thunk.

That's fine I suppose, but we need the thunk evaluated properly in the places where we used to use the value. That code you linked had more changes than just this one, as you'll see.

2021-06-17 23:20 UTC, jmortlock commented
@rix0rrr I believe this ticket can be closed as I fixed this in https://github.com/aws/aws-cdk/pull/14816

Didn't realize there was already open tickets for it!

2021-07-05 12:38 UTC, closed without merging