feat(apigateway): Allow specifying integration timeout.
aws/aws-cdk pull request #14154
Opened 2021-04-13 21:35 UTC by Samrose-Ahmed

Add an option to set a custom timeout when adding a RestApi integration.

fixes #14123

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-04-13 22:08 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 28093a03ff7bd357a3973fa149a8243000d4b77a
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=276a4562-d862-485a-ad1a-3ac0d91ee0ba%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-13 23:07 UTC, Samrose-Ahmed commented
It seems to be complaining about a readme update. Should I change this to a fix, or should I add something to the readme?

2021-04-15 13:23 UTC, nija-at requested changes
Hi @Samrose-Ahmed -

Thanks for submitting this PR! The code looks good. A few minor comments below.

> It seems to be complaining about a readme update. Should I change this to a fix, or should I add something to the readme?

Usually we expect feature requests to have a corresponding entry in the readme, but since this is trivial, I've added a label that will prevent the linter from complaining.

2021-04-15 13:23 UTC, nija-at commented on packages/@aws-cdk/aws-apigateway/lib/integration.ts
> +   * @default 29,000 milliseconds or 29 seconds.
```suggestion
   * @default Duration.seconds(29)
```

2021-04-15 13:23 UTC, nija-at commented on packages/@aws-cdk/aws-apigateway/lib/integration.ts
> +      throw new Error('Integration timeout must be between 50 and 29000 milliseconds.');
```suggestion
      throw new Error('Integration timeout must be between 50 milliseconds and 29 seconds.');
```

2021-04-15 13:23 UTC, nija-at commented on packages/@aws-cdk/aws-apigateway/lib/integration.ts
> +   * Must be between 50 and 29,000 milliseconds.
```suggestion
   * Must be between 50 milliseconds and 29 seconds.
```

2021-04-15 13:23 UTC, nija-at commented on packages/@aws-cdk/aws-apigateway/lib/integration.ts
> +    if (options.timeout && (options.timeout.toMilliseconds() < 50 || options.timeout.toMilliseconds() > 29000)) {
You also need to sure that timeout is not a token before applying this validation

```suggestion
    if (options.timeout && !options.timeout.isUnresolved() && (options.timeout.toMilliseconds() < 50 || options.timeout.toMilliseconds() > 29000)) {
```

2021-04-15 19:10 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 41ceb934a53216f5a849fd254e1c896ea392549c
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6b4c93cb-34b9-4ace-8b39-f9da9b834f2d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-16 15:27 UTC, nija-at approved these changes

2021-04-16 15:53 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 7a5882037140d2c6502e062749b00a907f605a5e
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a516dc43-d686-47de-a6bd-c910f48f001d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-16 16:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 14f00367ba44e4e778bbed502066c17bdb400387
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4216ddea-6c59-4d7c-b445-180ff83087e7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-16 16:19 UTC, merged