feat(cognito-userpool): Add mfaMessage option
aws/aws-cdk pull request #14241
Opened 2021-04-18 13:58 UTC by cjihrig

This commit adds a new, optional `mfaMessage` to Cognito UserPools.

Fixes: https://github.com/aws/aws-cdk/issues/14084

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-04-18 14:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 523f27e84faa44c04820200a8798891781242253
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6b10afcc-f7dc-436b-a0ac-aee119064032%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-18 14:27 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 2b46380c1c148e043e2d8ae526e0405c18105ece
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=861de3a0-8cda-4a0e-9f7f-e82542790ad5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-04 23:44 UTC, cjihrig commented
Ping @nija-at based on the assignment of https://github.com/aws/aws-cdk/issues/14084.

2021-06-01 09:24 UTC, nija-at requested changes
Thanks for submitting this PR @cjihrig. Apologies for the delayed response.

Could you address some of my comments below.

2021-06-01 09:24 UTC, nija-at commented on packages/@aws-cdk/aws-cognito/lib/user-pool.ts
> +   * A string representing the MFA message.
```suggestion
   * The SMS message template sent during MFA verification.
   * Use '{####}' in the template where Cognito should insert the verification code.
```

2021-06-01 09:24 UTC, nija-at commented on packages/@aws-cdk/aws-cognito/lib/user-pool.ts
> +   * @default - Omitted by default.
Is this the correct default?

I assume that turning on SMS based MFA but not specifying a message would mean that users in the user pool will receive some default SMS message, no?

If so, that should be the documented default.

2021-06-01 09:24 UTC, nija-at commented on packages/@aws-cdk/aws-cognito/lib/user-pool.ts
> +  private mfaMessage(props: UserPoolProps): string | undefined {
Looks great!

2021-06-02 01:21 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: d2f9785b2312d129309ed287d1bac2f33d529e61
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d8f3ba3d-479e-4df0-aa4b-dc64e3ab3d40%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-02 01:45 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: d0b4936128bf702f83469a4cbbf855593a18a25e
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=139e1dab-5ac3-41a0-84e5-4c03b2967958%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-02 01:46 UTC, cjihrig commented
Thanks for the review @nija-at. I have updated the PR based on your feedback.

2021-06-03 11:53 UTC, nija-at commented on packages/@aws-cdk/aws-cognito/lib/user-pool.ts
> +   * @default - 'Your authentication code is {####}.'
```suggestion
   * @default 'Your authentication code is {####}.'
```

2021-06-03 11:54 UTC, nija-at approved these changes
Thanks for the contribution @cjihrig. Looks good!

2021-06-03 12:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 40f5f2fca8150472b0dc4d0e9a1b4b7da443750d
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=54d7ed2c-c1b6-4a3e-aa50-482c8409c1f7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-04 09:55 UTC, nija-at approved these changes

2021-06-04 10:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: cfa990eedd7f6f013fa34514721ac4ddd425c192
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2ea59168-de92-424f-a5c3-9df8baeb0358%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-04 10:49 UTC, merged

2021-06-04 10:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 12d4f49a38e51a7726f16c29308c89aa6a9e0536
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=46afe554-da44-4230-89ee-091a8a7e3c30%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->