feat(ec2): create NAT Gateways with fixed IPs
aws/aws-cdk pull request #14250
Opened 2021-04-19 09:41 UTC by rix0rrr

Select static IPs for NAT gateways by pre-creating EIP allocations and
passing them into the NAT gateway provider.

Fixes #11884, fixes #4067.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-04-19 10:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 1db070d47fb8b70307f13ad298f8261463e72486
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=78c3647e-32ba-4b2e-8c93-4298169b2a98%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-19 12:01 UTC, nija-at requested changes

2021-04-19 15:46 UTC, rix0rrr commented on packages/@aws-cdk/aws-ec2/lib/nat.ts
> + * @experimental
The APIs above and below also had `@experimental` still there, so seeing as no code change has been made here yet, I'd like to keep this in line with the rest.

2021-04-19 15:47 UTC, rix0rrr commented on packages/@aws-cdk/aws-ec2/lib/nat.ts
> +   * EIP allocation IDs for the NAT gateways
People who need to know this will know what it is.

2021-04-19 16:54 UTC, nija-at commented on packages/@aws-cdk/aws-ec2/lib/nat.ts
> + * @experimental
coordinate with @NetaNir on this. See https://github.com/aws/aws-cdk/pull/14071.

2021-04-19 16:54 UTC, nija-at approved these changes
added label for second approver. Check with Neta on the experimental annotation.

Rest of the code LGTM.

2021-04-21 00:46 UTC, NetaNir commented on packages/@aws-cdk/aws-ec2/lib/nat.ts
> + * @experimental
@nija-at is right, we removed all @expiremental annotations and add a lint rule to disallow the use of this annotation. The PR for the removal was merged today, I was keeping it open to allow owners to make any adjustments before the API are marked as stable. I have pushed the change to removed the @experimetnal flag to your branch and merged in the latest changes from master. If you want to keep this API not final you can add the preview suffix to both the method and the props. The preview API spec is not yet written but we had some discussion on this [PR](https://github.com/aws/aws-cdk/pull/13780#pullrequestreview-629595262), which added an api with the suffix `beta1`.

2021-04-21 00:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: fbdf64374134591e21c59221131e2a249732cb5b
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=945f6541-d988-4ba1-a16d-01edf0d68a3e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-21 01:00 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: c07015104bd191383dd78980b933f20283728f2c
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6809fee5-466d-4d93-954f-9a7e808011be%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-21 14:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 423deafaec7702b810768e548f4f0b01043736aa
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=88c70490-5b93-4525-b506-3b5c1c4b6731%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-21 14:44 UTC, merged