feat(ec2): Implement UserData methods in MultipartUserData
aws/aws-cdk pull request #14347
Opened 2021-04-23 16:42 UTC by ddneilson

Implements: https://github.com/aws/aws-cdk/issues/14346

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-04-23 17:10 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: a59bce780cb6662b53b60b0edc8da812ec58f4d0
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4a48f719-c672-4d3e-85e2-50a2b90d6073%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-10 11:28 UTC, rix0rrr requested changes

2021-05-10 11:28 UTC, rix0rrr commented on packages/@aws-cdk/aws-ec2/lib/user-data.ts
> +  public addUserDataPartForCommands(userData: UserData) {
I think I would prefer the first invocation of `adduserDataPart()` to trigger this behavior, optionally gated by a `makeDefault?: boolean` parameter (which defaults to `true` if no default has been set yet and defaults to `false` if a default has already been set).

This additional method also feels awkward.

2021-05-10 11:28 UTC, rix0rrr commented on packages/@aws-cdk/aws-ec2/lib/user-data.ts
> +  private static readonly USE_PART_ERROR = 'MultipartUserData does not support this operation. Please use addUserDataPartForCommands().';
The error message could be more helpful about the behavior. How about:

```
MultipartUserData only supports this operation if it has a default UserData. Call addUserDataPart with makeDefault=true
```

2021-05-10 15:11 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 1f153ec652b8ef85a2ca9b32d567859448865c4c
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4592941b-7a4e-408e-a446-8d5d5285cefc%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-11 14:23 UTC, ddneilson commented
Just fyi, @rix0rrr , the changes have been made & this is ready for you to take another pass at it.

2021-05-17 14:54 UTC, ddneilson commented
@rix0rrr Just a reminder poke that this is waiting on you.

2021-06-04 14:55 UTC, rix0rrr approved these changes

2021-06-04 15:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 67846311b427edf872f8fefc49490975a5c88300
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6f877b5a-7103-450b-bab8-43be3cd3ca55%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-04 15:44 UTC, merged