feat(cloudtrail): custom log delivery role and sendToCloudWatchLogs on intent-based
aws/aws-cdk pull request #14366
Opened 2021-04-25 06:58 UTC by 14kw

- Enable custom log delivery role
- Enable sendToCloudWatchLogs on intent-based
  - https://github.com/aws/aws-cdk/pull/11104#discussion_r522425586

Even if sendToCloudWatchLogs is undefined, it will be evaluated if the properties associated with CloudWatchLogs are set.

closes #9583

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-04-25 07:26 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: e707ec048ae93e51171f6c00f7736454e302e186
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=147363ac-a80c-4a2e-bf27-78b0948c457a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-04-30 00:30 UTC, NetaNir commented
We have reviewed this pull request and marking it as p2, which means that we are unable to work on it immediately. We especially value community contributed code, so this is not a final decision.
We use +1s to help prioritize our work, and are happy to revaluate this pull request based on community feedback. You can reach out to the cdk.dev community on Slack to solicit support for reprioritization.

2022-04-28 00:08 UTC, TheRealAmazonKendra requested changes
Thank you for your contribution. Overall this PR is great! I think this is a valuable change, just a couple comments below, but I'd love to see this get merged.

2022-04-28 00:08 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/aws-cloudtrail/test/cloudtrail.test.ts
> -          sendToCloudWatchLogs: true,
While we should have at least one test case where this is removed and the other relevant fields are set, making this true, we should also still have a test case where this is set explicitly. Overall, I'd like to see a bit more test coverage for the various cases with this new behavior (including throwing an error as suggested above).

2022-07-06 22:21 UTC, TheRealAmazonKendra commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-07-06 22:21 UTC, closed without merging