chore(lambda-layer-awscli): update awscli to v2.2.1
aws/aws-cdk pull request #14487
Opened 2021-05-02 09:56 UTC by kirintwn

Update awscli to version 2.2.1, fix #13993.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-05-02 10:10 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 37b09a835b5ceb1b53a90660f6d3451f0c119936
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5069b570-160e-4c08-8b96-5b74f545e82e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-02 15:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 7ba53a58c605412d226a8435a1a735edbd095412
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ffdcb641-3237-4f9b-9824-6ba2aec7a635%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-02 16:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 9e51b2e8d05e87eb899281a791921b42921b090f
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c16ca11f-b68d-4ded-b3b7-4193fe59d14d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-05 03:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 0d66df7c0d75d2c44365c752d45df03a31e79394
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2f153728-3222-4814-9dca-3bb854aa5584%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-13 11:25 UTC, eladb commented
Okay I reviewed the migration guide and it looks like the upgrade should not break any usages within the CDK.

2021-05-13 11:27 UTC, eladb commented
@nija-at @njlynch curious what you think about this. Should we pick this change up or perhaps take a different strategy for this update such as vending a new module such as `lambda-layer-awscli-v2`.

2021-05-13 13:06 UTC, njlynch commented
> Should we pick this change up or perhaps take a different strategy for this update such as vending a new module such as `lambda-layer-awscli-v2`.

Would we need to vend an entirely new module? If there are legitimate reasons for wanting to supply AWS CLI v1 -- and I'm not sure if there are or not -- could we just offer it as an option with the existing construct? Something like this:

```ts
new AwsCliLayer(stack, 'AwsCliLayer', { cliMajorVersion: 2 ));
// OR
new AwsCliV2Layer(stack, 'AwsCliLayer');
```

I presume if we did the above, we'd want to adjust all of our own internal usage to the v2 variant, so we'd be just vending the v1 variant for backwards-compatibility reasons.

2021-05-13 16:03 UTC, eladb commented
> Would we need to vend an entirely new module?

Of course you are right :-) we can just export another layer for v2. Let's do that :-)

@kirintwn sorry for the hassle, but we are really trying to avoid any type of breaking changes in public APIs and technically (and practically), CLI v2 is a major version of the CLI. Would you be willing to put the extra effort and instead of replacing the current implementation, add another layer for v2.

Bonus points for moving the AWS CDK codebase to use this v2 layer, but totally understand if this is too much, and I can pick this as a follow up PR after we merge this.

2021-05-13 16:04 UTC, eladb requested changes
See comments

2021-05-16 12:20 UTC, eladb commented
@kirintwn let me know if you are interested to continue to work on thi

2021-05-16 12:21 UTC, kirintwn commented
Sorry for the late reply, I will continue to work on this tomorrow.

2021-05-17 08:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 2a0804c97038cb11815f0a12306a212e6b6d14b4
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7e7cecf9-8fc9-4eaa-806b-9ebfdd2b5c06%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-17 09:25 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 8fb06c7e7a736e50ddc3a357cf090a664a73f52a
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7d896de4-ec73-4ec7-ab6c-daa5c2eef866%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-17 16:42 UTC, eladb submitted a review, later dismissed

2021-05-17 16:42 UTC, eladb commented on packages/@aws-cdk/lambda-layer-awscli/layer/Dockerfile
> -
I expected to see a new dockerfile Instead of a modification.

2021-05-17 16:42 UTC, eladb commented on packages/@aws-cdk/lambda-layer-awscli/layer/Dockerfile
> +COPY --from=v1 /layer_v1.zip /layer_v1.zip
Let's just split to two dockerfiles

2021-05-18 05:13 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 3901bd0fbe29d012e808e85aa67da70f4b7bb8e2
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=116bc5b3-2036-4e97-9a61-4fe39343f022%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-18 05:47 UTC, eladb requested changes
Minor

2021-05-18 05:47 UTC, eladb commented on packages/@aws-cdk/lambda-layer-awscli/layer/v1.Dockerfile
> +FROM public.ecr.aws/lambda/provided:latest AS base
Let's keep this file unchanged please

2021-05-18 06:41 UTC, kirintwn commented on packages/@aws-cdk/lambda-layer-awscli/layer/v1.Dockerfile
> +FROM public.ecr.aws/lambda/provided:latest AS base
noted, please review again, thank you!

2021-05-18 07:05 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 5df4d46bd24a720478dcbe19a87812fc9fe5a526
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a1410770-8565-4851-848e-2f1b4441fd8f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-18 07:08 UTC, eladb approved these changes
🙏🙏🙏

2021-05-18 07:36 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: bf8d98c7077f58127d9d6842de9b0b9652a69f8b
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=694f85c8-0d97-4fb5-9c3b-ef5e8d7afde5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-18 07:36 UTC, merged