fix: init templates use node jest environment
aws/aws-cdk pull request #14632
Opened 2021-05-11 03:52 UTC by MrArnoldPalmer

Remove usage of the `jsdom` test environment in init templates to speed
up unit testing by default.

fix: #14630

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-05-12 09:27 UTC, nija-at requested changes
Dang! Should we be setting this to all of the CDK repo jest set up too? 

What kind of improvements do you see/expect from this?

2021-05-12 09:27 UTC, nija-at commented on packages/aws-cdk/lib/init-templates/v1/app/javascript/jest.config.js
> +module.exports = {
Can you add a comment to this PR titled 'Testing' on how you tested this change? At a minimum, that the experience doesn't regress.

context: we don't have very good automated test coverage for our init templates, and have got it wrong many times.

2021-05-12 16:28 UTC, MrArnoldPalmer commented
> Dang! Should we be setting this to all of the CDK repo jest set up too?
> 
> What kind of improvements do you see/expect from this?

This is already correctly configured in the cdk jest environment via our [root jest config](https://github.com/aws/aws-cdk/blob/master/tools/cdk-build-tools/config/jest.config.js#L8), so no gains for us 😢

2021-05-12 16:38 UTC, MrArnoldPalmer commented
Testing: ran `cdk init --language=(typescript|javascript)` against local build of CLI then ran `yarn test` to verify that the testing config was valid and jest correctly used the `node` environment.

2021-05-13 08:33 UTC, nija-at approved these changes

2021-05-13 09:00 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 383021622d4cc592c1128d920b3ad47f1771ceea
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3fb088bd-cea6-445b-a618-ac31d4be8b2f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-13 09:01 UTC, merged