feat(aws-stepfunctions-tasks): Add support for SageMaker CreateProcesingJob API (#9537)
aws/aws-cdk pull request #14633
Opened 2021-05-11 04:43 UTC by heatsink

**Implementation**

Update module `@aws-cdk/aws-stepfunctions-tasks` to include for SageMaker **CreateProcessingJob** API.
See: https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateProcessingJob.html

Includes support for the following Amazon SageMaker API calls:
* `CreateProcessingJob`

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-05-11 05:09 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 82612b4eed88094939ca167e2cc5d09e8bdb8004
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=22fe3d5b-4657-48e1-af13-24b59c2da24c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-17 05:04 UTC, BenChaimberg requested changes
Thank you so much for your work on this feature! I didn't review the whole PR since there are some high level changes that I think need to be made.

It seems like you have modeled the various interfaces directly from the Sagemaker API. While I see the benefits of keeping naming and structure similar between the service API and the CDK definition, I think one of the best parts of the CDK is the ability to add a little bit more abstraction and make it as easy as possible for users to interact with AWS. I would like to see some more thought put into the "happy path" of how a user can spin up a processing job without having to configure every value provided in the API. This means that we can bundle several related items into one that determines all of the individual values. Remember, if someone wants to configure every value, they can do so already without this feature existing. Further, if we could reduce the amount of nesting, that will help users discover the essential features.

I also see that you have taken a lot of the documentation directly from the API reference. While I would like to say that any material published by AWS is pristine, the documentation here could use a bit more love in terms of describing what the interfaces are actually for, from a user experience perspective. This manifests itself particularly in the "default" values, this gives us a great opportunity to showcase what a "typical" user would want to do, so let's make it clear that we will end up doing.

2022-02-17 21:23 UTC, kaizen3031593 commented
@heatsink have you had time to think on this? i'm actually interested in taking over if you're unable to carve out the time.

2022-03-18 18:28 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: f5519d2bfc2ebe17438c4dd987a975bad5105a96
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b2c879a8-0d33-4cab-9ffe-861a247e7a8c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-18 18:32 UTC, closed without merging

2022-03-18 18:35 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 1142d635f01d3f35d1b88d98b6893e4677d89ada
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f5d26c5c-88cb-4156-bf09-52204a17fe08%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-18 18:36 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 3d9321e816b2e2d1aa381f0b40cd1ff57b0958fb
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a1ccf07e-e0f8-459d-9977-a4a0aa034eef%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-18 18:40 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: d03f6a2d14f23ab228b3cd49913b66bdec0e91b7
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a372357e-a7cb-4239-a970-c3005f4b1d6f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-18 18:40 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 8fef47068d54159264d8d0cb68b97c0be0b2fbe5
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f15bc669-3f2f-4a88-b1f4-49c51d2996cd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-18 18:40 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: f5519d2bfc2ebe17438c4dd987a975bad5105a96
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=496ab483-afd2-4dac-adef-8a425bf76365%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-18 18:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 3fa92df73a9b2b15eb23a705ac4bb669a35aaece
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a7e24ef7-5807-4886-8aec-44eefb6e96fe%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-19 00:20 UTC, heatsink commented
I'm planning to start fresh in a new pull request in https://github.com/aws/aws-cdk/pull/19468/, but although it is a new request I've taken into account many of the comments above from BenChaimberg. 

Note: (as of writing this comment I've yet to publish the draft. Still adding some finishing touches and making the implementation cleaner)