docs(aws-synthetics): Added info about cron-expresssions
aws/aws-cdk pull request #14737
Opened 2021-05-18 08:18 UTC by marius-jakobi

`Schedule.expression` can also take a `cron()` expression string to utilize schedules > 59 minutes

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-05-18 08:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 464192c0ba8eea7517bbb92a1c96fca6c4035902
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9146ba32-2471-4fde-8590-af77c07c36ed%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-18 11:09 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 79c7fc8170a214ea9097c1003c76d15b8dcac37a
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=52e16d7d-26cb-43a6-8497-5daf733d3a85%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-18 11:40 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: f380ddc9441c3cbf275196a8dc1db1a5c198dd86
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2fc11d4a-0fe4-4406-a445-c64306da119f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-18 15:55 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: ce0e5b1854f7d2e43b1f29f5a31e853b2000c23a
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4f641b77-0998-4499-b959-48362ae1ec21%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-18 17:24 UTC, NetaNir reviewed
Seems like it will be more valuable to add a check that verifies that if `rate` was used it's < 60?

2021-05-18 17:53 UTC, marius-jakobi commented
> Seems like it will be more valuable to add a check that verifies that if `rate` was used it's < 60?

There ist actually a Check in Schedule.expression. I Just wanted to add a hint to the comment to let Users know thar they can use 'cron()' as a Expression.

2021-05-19 06:39 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: f014138fae3d237cc58955d70777d3569e5a0a09
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4ead6324-5430-449b-9429-19302f3f876a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-19 06:41 UTC, marius-jakobi commented
@NetaNir 
https://github.com/aws/aws-cdk/blob/773ca8c5d2a845f392f530d7710020075b884c72/packages/%40aws-cdk/aws-synthetics/lib/schedule.ts#L33
I think the limitation to 60 minutes is not valuable since in the console a longer interval can be set. I just wanted to add the hint about `cron()` expressions in the comments to view it to users when they are setting up a canary schedule.

2021-05-19 11:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 58fb5082e41a56e975a4d8bc20fff599e7b9dc70
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=522ee1db-c3c3-4078-bf40-42749f493e6d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-19 16:13 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 5ca49e28fdb413c41b78857217d7f3b47b5ebc9d
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b23edd7e-7237-4c93-a98e-28733dd7538f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-01 06:47 UTC, marius-jakobi commented
What's the status about this PR?

2021-06-01 07:13 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: b1ec23cac048e4ed3902efb457466d57528bc7ff
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9115ee6b-8dc7-4c6b-be6b-57dd71837bb7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-02 19:11 UTC, BenChaimberg requested changes

2021-06-02 19:11 UTC, BenChaimberg commented on packages/@aws-cdk/aws-synthetics/lib/schedule.ts
> +   * Construct a schedule from a literal schedule expression. The expression must be in a `rate(number units)` or `cron(0 12 * * * *)` format.
cron has a complicated syntax that we shouldn't try to reproduce it here. Please also add a link to https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_cron.html
```suggestion
   * Construct a schedule from a literal schedule expression. The expression must be in a `rate(number units)` or cron format.
```

2021-06-02 19:11 UTC, BenChaimberg commented on packages/@aws-cdk/aws-synthetics/lib/schedule.ts
> +   * With a `rate()` expression only intervals of < 60 minutes can be used.
```suggestion
   * With a `rate()` expression only intervals of <= 60 minutes can be used.
```

2021-06-02 19:11 UTC, BenChaimberg commented on packages/@aws-cdk/aws-synthetics/lib/schedule.ts
>     *
As @NetaNir mentioned, I'd like to see a simple validation on this statement for the rate expression. Just a string parsing for "rate" at the beginning of the expression and ensuring the minute equivalent is at most 60. Do you think you can add this change here?

2021-06-04 07:50 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 738af820f0c998d10f210c7a74f45145b3e3f31b
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b8a3e4b7-4e39-436a-980a-39a2c2abef73%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-04 07:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 12de3936f9af8c9d68d3dc8bebbed05992fd118a
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=91a585c1-099d-4a77-94e1-fa37d99888cd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-04 07:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: caa8ec076963cd8b9cfafdac5ff4d4b0c7f4c309
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=db5fb2f4-22d4-4e65-83ab-416ea29b19cc%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-09 13:48 UTC, BenChaimberg commented on packages/@aws-cdk/aws-synthetics/lib/schedule.ts
>     *
Not addressed

2021-06-09 17:40 UTC, closed without merging