fix(aws-stepfunctions-tasks) typo in EmrClusterScaleDownBehvaior description
aws/aws-cdk pull request #14839
Opened 2021-05-23 01:16 UTC by SaxyPandaBear

It ain't much, but it's honest work -- I only noticed it cause I've been going down a rabbit hole of defining EMR cluster steps in CDK this week.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-05-23 01:42 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: b018b0d2a09b9f55f6f20839db7a4a5544ad6df2
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5265bc01-af69-4ba0-bc67-f96008ed3836%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-03 22:39 UTC, BenChaimberg requested changes
Well, if we're changing this anyway...can we make this description more informative? Maybe take a look at [the corresponding API docs](https://docs.aws.amazon.com/emr/latest/APIReference/API_RunJobFlow.html#EMR-RunJobFlow-request-ScaleDownBehavior) and see if you can pull something that gives a better description of what these values actually *do*.

2021-06-03 22:41 UTC, SaxyPandaBear commented
@BenChaimberg Sounds good to me. I'll take a look

2021-06-05 19:55 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: bcc20f64058082e0ae32efe6a3f7e3f0ff2b62ef
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fae4b2b6-2e3c-4402-bc6c-2d8a767dd4c1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-05 20:01 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 790939b90e9834d000d22eb1b2faf59037229e48
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c2824dc0-0b5c-44ea-aaf8-ed013db4ff1d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-05 20:57 UTC, BenChaimberg approved these changes

2021-06-06 01:32 UTC, SaxyPandaBear commented
@BenChaimberg looks like it said the CodeBuild failed but I can't see why (but the github bot posted CodeBuild success?)

2021-06-06 13:34 UTC, BenChaimberg requested changes

2021-06-06 13:34 UTC, BenChaimberg commented on packages/@aws-cdk/aws-stepfunctions-tasks/lib/emr/emr-create-cluster.ts
> +   * The Cluster ScaleDownBehavior specifies the way that individual Amazon EC2 instances terminate when an automatic scale-in activity
```suggestion
   * The Cluster ScaleDownBehavior specifies the way that individual Amazon EC2 instances terminate when an automatic scale-in activity
```

2021-06-06 13:35 UTC, BenChaimberg approved these changes

2021-06-06 14:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 7a616ef0bd9a59c9a85a8145a950bf2f30714a28
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fc1e2e42-4821-4bd0-9c75-3ffe53d0fb33%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-06 14:02 UTC, merged