(aws backup): Support for advancedBackupSettings
aws/aws-cdk pull request #14891
Opened 2021-05-27 13:25 UTC by Patil2099

Fixes #14803

2021-05-27 13:26 UTC, Patil2099 commented
Can you please review this @MrArnoldPalmer ?

2021-05-27 13:42 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 22f5631ec7cb8b837f9e8aaf817b979a9a83a210
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=63c1f61c-8606-425e-bb0f-29579415d875%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-28 16:17 UTC, BenChaimberg requested changes
Please consult [the contributing guide](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) for the requirements for pull requests in this repository.

In particular, please address the following issues:
- PRs should be named following [the conventional commit specification](https://www.conventionalcommits.org/en/v1.0.0/) (I fixed this for you already)
- public interfaces must have associated documentation
- new features must add to the README
- changes should modify or create tests
- build must pass

Besides these (somewhat) administrative issues, I'm not sure if this is the correct solution to implement #14803. Given that the only supported key for BackupOptions is "WindowsVSS", adding a property like "windowsVssBackup?: boolean" and generating the correct options will be more literate to the user.

2021-05-28 16:17 UTC, BenChaimberg commented on packages/@aws-cdk/aws-backup/lib/plan.ts
> +        backupOptions: props.backupOptions || {},
This is not the correct location for this value, please consult [the documentation for this resource](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-backup.CfnBackupPlan.html).

2022-03-30 21:25 UTC, TheRealAmazonKendra commented
This PR has been deemed to be abandoned, and will be closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-03-30 21:25 UTC, closed without merging