fix(ec2): typo at member name clientVpnEndoint to clientVpnEndpoint
aws/aws-cdk pull request #14902
Opened 2021-05-27 22:48 UTC by cokia

It is a solution to the issue #13810

Corrected the typo "clientVpnEndpoint" in the ec2 module to "clientVpnEnpoint".

The maintainer (@rix0rrr) talked about @deprecated tags on existing incorrect members in the issue thread, but I didn't work on it because I thought it was an internal reference member. (if @deprecated tag is the rule of this repository in this case, please comment).

This is my first commitment to this report. If there's anything wrong, please let me know in the comments. thanks

---- edit -----
Originally, this PR was #14835 , but I deleted my fork report by mistake, so I couldn't correct the error, so I uploaded it again.

2021-05-27 23:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 8303e7fb4c6c2c196be5188661c9eb85eab5aee3
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a68b2880-4237-49bb-a3ff-4763c29903b7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-05-28 00:18 UTC, cokia commented
When I tested locally, it was built normally and even tested, but I don't know why the server got such an error.

2021-06-04 12:58 UTC, rix0rrr commented
> When I tested local, it was built normally and even tested, but I don't know why the server got such an error.

This is the error:

```
API elements with incompatible changes:
err  - PROP @aws-cdk/aws-ec2.ClientVpnAuthorizationRuleProps.clientVpnEndoint: has been removed [removed:@aws-cdk/aws-ec2.ClientVpnAuthorizationRuleProps.clientVpnEndoint]
err  - IFACE @aws-cdk/aws-ec2.ClientVpnAuthorizationRuleProps: newly required property 'clientVpnEndpoint' added: input to @aws-cdk/aws-ec2.ClientVpnAuthorizationRule.<initializer> [strengthened:@aws-cdk/aws-ec2.ClientVpnAuthorizationRuleProps]
err  - PROP @aws-cdk/aws-ec2.ClientVpnRouteProps.clientVpnEndoint: has been removed [removed:@aws-cdk/aws-ec2.ClientVpnRouteProps.clientVpnEndoint]
err  - IFACE @aws-cdk/aws-ec2.ClientVpnRouteProps: newly required property 'clientVpnEndpoint' added: input to @aws-cdk/aws-ec2.ClientVpnRoute.<initializer> [strengthened:@aws-cdk/aws-ec2.ClientVpnRouteProps]
```

I think you saw this coming when you said: 

> The maintainer (@rix0rrr) talked about @deprecated tags on existing incorrect members in the issue thread, but I didn't work on it because I thought it was an internal reference member.

😀

2021-06-04 13:53 UTC, rix0rrr commented
(Bottom line, we are not allowed to break existing code -- so we're going to have to go the deprecated+alternative route)

2021-06-07 08:37 UTC, rix0rrr requested changes
We need to go the non-breaking route

2021-06-12 16:31 UTC, cokia reviewed
I added deprecated tag to typo route

2021-06-12 16:35 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 7d3378f323fc7c2d2ea80b9e6d688869c26f4944
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4ef7843e-e870-4b9b-abdb-24bc42eb91e9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-12 18:05 UTC, cokia commented
Linter did not allow me to delete the typo type, and I made it an option type and added a new one to solve this problem. Is this the right solution? I don't know if it's the right choice to manage this optionally defined type.

2021-06-12 18:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: ee809464f901cbac169a957b55e72d840fbd014b
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=254bd5a4-f40f-4c8f-8924-fdf171567ec2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-13 02:56 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 7458a05a6aee0b101f5a686f9495eb1011f89d2d
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d782dc7d-dc29-48af-afb9-601e46733199%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-14 13:16 UTC, rix0rrr commented
> I made it an optional type and added a new one to solve this problem

This is exactly the right way. Plus adding validation (in code) to make sure exactly one of the parameters is supplied (either the typoed or non-typoed one).

2021-06-14 13:18 UTC, rix0rrr requested changes

2021-06-14 13:18 UTC, rix0rrr commented on packages/@aws-cdk/aws-ec2/lib/client-vpn-authorization-rule.ts
> +  readonly clientVpnEndpoint: IClientVpnEndpoint;
Aha, here is the confusion. Both need to be declared optional (type-wise), and runtime code needs to validate exactly one of them is supplied anyway.

Don't forget that both need a `@default` annotation as well. I'd recommend something like:

```
@default clientVpnEndpoint is required
```

2021-06-21 09:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: cb024e0f384655a7e2e83a8655c7dce9bbfc12a2
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bd4d61ed-3fd2-497b-b8ed-863b64c51dd3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-21 09:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: ae8d03f3e6169cc4b5e478296019b2109e06a7e4
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=19e98d5a-d256-4847-97ac-83dbb60eddf9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-29 13:34 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: b46f1cf15959c0a151aa5a901ca22de4069c3fa6
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=21012efe-82ca-4d90-a234-9bd1a20ca157%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-30 04:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 3e63d2840fdd9862e3fff5466646001b2713721b
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c5eb5d87-30dc-47b9-87e7-2b20dd7bf8cb%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-30 06:25 UTC, cokia commented
@rix0rrr build succeeded!
please recheck this PR 🚀

2021-07-03 23:10 UTC, cokia commented
I'm sorry to tag you again.
If you don't mind, could you recheck this PR? @rix0rrr

2021-07-04 15:15 UTC, douglasnaphas commented
@cokia You still have a [linter failure](https://github.com/aws/aws-cdk/pull/14902/checks?check_run_id=2948626370), with the message:

> Error: Fixes must contain a change to a test file

@rix0rrr recommended [above](https://github.com/aws/aws-cdk/pull/14902#issuecomment-860676290):

> ...adding validation (in code) to make sure exactly one of the parameters is supplied (either the typoed or non-typoed one).

I suggest adding the following tests:

1. Instantiate a `ClientVpnAuthorizationRule`, supplying `clientVpnEndpoint` and `clientVpnEndoint`. Expect an error explaining that one or the other is required, but both are not allowed.
2. Instantiate a `ClientVpnAuthorizationRule`, supplying neither `clientVpnEndpoint` nor `clientVpnEndoint`. Expect an error explaining that one or the other is required.
3. Instantiate a `ClientVpnRoute`, supplying `clientVpnEndpoint` and `clientVpnEndoint`. Expect an error explaining that one or the other is required, but both are not allowed.
4. Instantiate a `ClientVpnRoute`, supplying neither `clientVpnEndpoint` nor `clientVpnEndoint`. Expect an error explaining that one or the other is required.

Commit the tests, get builds that fail because the logic isn't in place in the code yet, then implement checks that will make the tests pass in [ClientVpnAuthorizationRule](https://github.com/aws/aws-cdk/blob/3e63d2840fdd9862e3fff5466646001b2713721b/packages/%40aws-cdk/aws-ec2/lib/client-vpn-authorization-rule.ts#L53) and [ClientVpnRoute](https://github.com/aws/aws-cdk/blob/3e63d2840fdd9862e3fff5466646001b2713721b/packages/%40aws-cdk/aws-ec2/lib/client-vpn-route.ts#L83).

Also I don't think the `!` on [this line](https://github.com/aws/aws-cdk/blob/3e63d2840fdd9862e3fff5466646001b2713721b/packages/%40aws-cdk/aws-ec2/lib/client-vpn-authorization-rule.ts#L58)

```ts
      clientVpnEndpointId: props.clientVpnEndpoint!.endpointId,
```

and [this identical line](https://github.com/aws/aws-cdk/blob/3e63d2840fdd9862e3fff5466646001b2713721b/packages/%40aws-cdk/aws-ec2/lib/client-vpn-route.ts#L87):

```ts
      clientVpnEndpointId: props.clientVpnEndpoint!.endpointId,
```

can stay, because we want to allow for existing usages of `ClientVpnAuthorizationRuleProps` and `ClientVpnRouteProps` that  use `clientVpnEndoint` to still work.

2021-07-18 02:40 UTC, douglasnaphas commented
@cokia As noted in [my earlier comment](https://github.com/aws/aws-cdk/pull/14902#issuecomment-873609825), this PR needs updates to tests, and some changes to the logic to enforce the requirement that one or the other or `clientVpnEndoint` (typo) or `clientVpnEndpoint` is provided.

I pulled down your branch, and made commits that I believe will get this PR passing the linter and able to pass review.

I have my changes on my branch [douglasnaphas:fix-clientVpnEndpoint-doug](https://github.com/aws/aws-cdk/compare/master...douglasnaphas:fix-clientVpnEndpoint-doug?expand=1). Take a look at that, and if you agree with those changes, you could:
  1. Merge `aws/aws-cdk:master` into your PR's branch.
  2. Merge [douglasnaphas/aws-cdk:fix-clientVpnEndpoint-doug](https://github.com/douglasnaphas/aws-cdk/tree/fix-clientVpnEndpoint-doug) into your your PR's branch.

Then I think we will be in good shape for the maintainers to take a look and get this change merged.

2021-08-07 16:48 UTC, cokia commented
@douglasnaphas  I am not familiar with the structure of this project and the basics for the contribution. You've helped me a lot, and I'm very grateful for this.

2021-08-07 16:53 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 38a1abb84d437b4129cb7efde9b580b35a7f738a
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7ed38857-0463-4af0-aab9-0ba3a3e5460b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-07 17:10 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: c89359a43bb5a479b75a60a51d52c44c04c35e0f
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fb70c6ff-3fbc-4255-93fd-e04aa1b6e2b6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-07 17:27 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: b7fb4784416242aacb29d46fa950a4249ed91b73
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4c461a48-e8b3-4109-a748-33244a78abd1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-10 10:21 UTC, douglasnaphas commented
@rix0rrr, the build that was previously failing on this PR is passing, so it is ready for another review when you have a chance.

2021-08-10 11:31 UTC, rix0rrr approved these changes

2021-08-10 12:12 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: a9bf41e8a8ffd7a1a4c25fd502ab5c2b456ada13
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4e024417-418d-453b-bc6a-5b12ee700ffe%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-10 12:12 UTC, merged