feat(aws-efs): Add arn attribute and grant method to FileSystem construct
aws/aws-cdk pull request #14999
Opened 2021-06-06 04:49 UTC by DaWyz

Closes #14998.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-06-06 05:17 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 070c266276b8393dd5f839f63657f36dc2a1a8cd
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=32825e80-b595-4b52-9bb7-5786c11f061a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-13 15:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 1d573dac0760943febf281582f912ca641a5c3ea
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2ad8ac06-df7a-437d-a097-c415bfe2e36b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-21 10:03 UTC, nija-at submitted a review, later dismissed
Thanks for the PR @DaWyz. Looks mostly good. A few comments below.

2021-06-21 10:03 UTC, nija-at commented on packages/@aws-cdk/aws-efs/README.md
> +importedFileSystem.grant(role, 'elasticfilesystem:ClientWrite');
Document the grant API in a separate section.

2021-06-21 23:11 UTC, DaWyz commented on packages/@aws-cdk/aws-efs/lib/efs-file-system.ts
> +    });
Good catch. Just updated the code.

2021-06-21 23:11 UTC, DaWyz commented on packages/@aws-cdk/aws-efs/lib/efs-file-system.ts
> +    if (!attrs.fileSystemId && !attrs.fileSystemArn) {
I'm going to throw an error if both are provided (similar to how it's done for DynamoDB tables).

2021-06-21 23:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 429d94348cd60adcff332c8ad21fc8f550488c4c
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a7a16f09-0f75-41df-a2b6-a5308613f5fb%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-21 23:41 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 2436ad3acf81260b2ab76de44093724b7efacec3
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=27fa45cc-7ea8-47d7-96a1-3d53ad46a848%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-22 05:02 UTC, nija-at requested changes
Thanks for making the changes. A few more comments below.

2021-06-22 05:02 UTC, nija-at commented on packages/@aws-cdk/aws-efs/lib/efs-file-system.ts
> +    }
Add unit tests for these

2021-06-22 13:47 UTC, DaWyz commented
Updates the code following last recommendations. Also updated the pull request description.

2021-06-22 14:08 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 13c32c189f4409d588df2570500ac78f8a21da38
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7877ad96-6f17-4293-a831-dfdb2e8cd116%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-22 16:08 UTC, nija-at approved these changes
Awesome! Looks great.

2021-06-22 17:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: f5b0da9c359e5907ee8b034c34ba1ef7dfcc0d8f
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c2abc96a-aefd-46c0-b94d-a56fc64a4b79%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-23 08:55 UTC, nija-at requested changes
@DaWyz - can you take a look at the failing build with the latest changes.

It's likely because you need to update the tests to use the new assertion framework - https://github.com/aws/aws-cdk/commit/367fe7e1e05be31b77fbf7c6e2e60e126e854a59

2021-06-24 00:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 1c731451e4781dd5ea0c80c3ab4868bdc564e247
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f26df1e4-5b03-43a0-892c-a044ff7b6a82%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-07-15 14:38 UTC, nija-at approved these changes

2021-07-15 15:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 936c7690ec1c7a4f0e5bdda94c5667ac73cedc4c
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=98575e0b-e302-4f33-8e85-61d06f0291a5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-07-15 15:17 UTC, merged