feat(codepipeline): allow granting manual approval permissions
aws/aws-cdk pull request #15102
Opened 2021-06-11 22:21 UTC by hoegertn

This feature allows granting permissions to click on the manual approval button in a CodePipeline to a supplied IGrantable. This can be used to allow IAM users and roles to approve pipeline actions.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-06-11 22:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: d1d441388238ca76e302f3aca702f4061e67dd94
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ef18dc71-2153-41f4-9214-6c1f745f4e58%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-14 20:12 UTC, skinny85 requested changes
Looks great @hoegertn, thanks a lot for the contribution!

I wouldn't be the picky asshole I'm known for being if I didn't find a few places to nitpick on 😉.

2021-06-14 20:12 UTC, skinny85 commented on packages/@aws-cdk/aws-codepipeline-actions/README.md
> +
Some example code here would be nice 🙂.

2021-06-14 20:12 UTC, skinny85 commented on packages/@aws-cdk/aws-codepipeline-actions/lib/manual-approval-action.ts
> +  private stage?: codepipeline.IStage;
Let's move this below `props`.

2021-06-14 20:12 UTC, skinny85 commented on packages/@aws-cdk/aws-codepipeline-actions/lib/manual-approval-action.ts
> +   * grantManualApproval
Some docs here would be nice 🙂.

2021-06-14 20:12 UTC, skinny85 commented on packages/@aws-cdk/aws-codepipeline-actions/lib/manual-approval-action.ts
> +  public grantManualApproval(grantable: iam.IGrantable) {
Please specify the return type explicitly.

2021-06-14 20:12 UTC, skinny85 commented on packages/@aws-cdk/aws-codepipeline-actions/lib/manual-approval-action.ts
> +    if (!this.stage || !this.stage.pipeline) {
`stage.pipeline` is never `undefined`, so this condition can be simplified to:

```suggestion
    if (!this.stage) {
```

2021-06-14 20:12 UTC, skinny85 commented on packages/@aws-cdk/aws-codepipeline-actions/test/manual-approval.test.ts
> +      });
Can you move these local variables closer to where they are first used?

2021-06-14 20:12 UTC, skinny85 commented on packages/@aws-cdk/aws-codepipeline-actions/test/manual-approval.test.ts
> +                ],
Let's conserve the lines here a little bit more:

```suggestion
                'Fn::Join': ['', [
                  'arn:',
                  {'Ref': 'AWS::Partition' },
                  ':codepipeline:',
                  {'Ref': 'AWS::Region' },
                  ':',
                  {'Ref': 'AWS::AccountId' },
                  ':',
                  {'Ref': 'pipelineDBECAE49'},
                ]],
```

Same comment below.

2021-06-17 14:42 UTC, hoegertn commented
@skinny85 I addressed your comments. Something went sideways with the push but the changes seem to be correct. Squashing should make it go away.

2021-06-17 15:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 98fdbe653b739dc04c632a0d597a944b109bba47
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3ba61624-a69f-4e83-89bd-d4372b20eb0a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-17 15:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: cf4373d8f8f9b2a8fc55690e98a9b1e785006368
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b4978c38-8b6c-4456-bea3-12f477ef5a27%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-17 15:17 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: ac2746f98fa12c17415b78082f7e0fc5157862b3
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4ae4c3d7-638a-46e1-a7b1-74f5ec821abe%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-17 18:35 UTC, skinny85 approved these changes
👍

2021-06-17 19:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: a62fea5fa54eab357c158d6b4addb1678ce2843e
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=36f50094-5e62-4e4f-badb-f9425fb74ad4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-17 19:23 UTC, merged