feat(codepipeline): add ability to specify encryption key for imported S3 source bucket
aws/aws-cdk pull request #15310
Opened 2021-06-25 08:27 UTC by berenddeboer

If you import an S3 bucket encrypted with a custom key, it's impossible to give the CodeBuild role permission to use that key for decryption as far as I could see. I.e. I was not able to access this CodeBuild role.

By adding `encryptionKey` you can specify it at in the S3 source props, and permissions can then be granted inside this private heavy object. 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-06-25 09:05 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 7421b6f3d5eff38fe9326aea4eef5f30a1852c08
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=57d51314-550c-4de2-932b-5bb4aed8caca%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-25 22:41 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 8191f3fe95714bd7d150ec5cb52501db88164fe3
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0a1401c2-209e-4efc-8edf-7d817c677f13%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-25 22:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: e4850e124bf070beef829546a1229f2760ba1b8b
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2aa215a5-388e-4a3f-81fb-4b2c0211792d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-27 16:21 UTC, skinny85 requested changes
Thanks for the PR @berenddeboer, but the way to do that in the CDK is to specify the Key when importing a Bucket:

```ts
const bucket = s3.Bucket.fromBucketAttributes(this, 'Bucket', {
  arn: 'arn:aws:s3:...',
  encryptionKey: kms.Key.fromKeyArn(stack, 'MyKey', 'arn:aws:kms:...'),
});
```

Now, passing `bucket` to `S3SourceAction` will grant the action's Role permissions to use that Key.

(BTW, if you want to customize the permissions a Role for a given Action has, you can always pass in a Role when creating the Action by using the  `role` property of the Action class)

Hope this clears this up!

2021-06-27 19:28 UTC, berenddeboer commented
Ah that's great, I completely missed that. Shall I just change my pull request to a documentation update? I.e. giving an example?

And would it be better to submit a new pull request for that?

2021-06-27 19:33 UTC, skinny85 commented
> Ah that's great, I completely missed that. Shall I just change my pull request to a documentation update? I.e. giving an example?
> 
> And would it be better to submit a new pull request for that?

Feel free to either repurpose this one to only have a documentation update, or close this one, and open a new one - I'm fine with either, whatever is easier for you 🙂.

2021-06-28 23:28 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 37b9e276ee125f20d87a62044eda3dd37c432524
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=73cffce8-bfa7-4a38-b849-940bb3f7ee25%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-30 20:56 UTC, dnz-bdeboer commented
Linter now fails as I removed the test file change. Is it possible to change the title to a docs update? It seems I can't change the title myself.

2021-06-30 21:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 39dc3f7b76d8d6853c940eae9416a0c3512876ae
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=447151a8-83e9-48ea-b73d-4615c404ed0e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-30 22:17 UTC, skinny85 requested changes
> Linter now fails as I removed the test file change. Is it possible to change the title to a docs update? It seems I can't change the title myself.

Done!

2021-06-30 22:17 UTC, skinny85 commented on packages/@aws-cdk/aws-codepipeline-actions/README.md
> +```
All of this should be removed.

2021-06-30 22:17 UTC, skinny85 commented on packages/@aws-cdk/aws-codepipeline-actions/lib/s3/source-action.ts
> +   * });
Let's not put code in the docs (remember that CDK is a multi-language environment).

Just mention the `Bucket.fromBucketAttributes()` method here, and that you should provide the Key there.

Or move these docs to the ReadMe file (those are automatically translated to other languages).

2021-07-02 07:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 655471a80e560c2dcc5bd795402182854ec2a9f1
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=26b0432e-849f-404a-b3aa-80ceac1eefda%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-07-02 21:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: c9f296e73c378f428340dcdb9698401ab1e55eb6
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bff2747c-f898-491d-a3eb-6a8a2fcefebb%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-07-08 16:26 UTC, skinny85 approved these changes
Thanks for the contribution @berenddeboer!

2021-07-08 17:05 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 90051cbf27cad07ce8b286f9a1d11373ee3bd9f4
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7aa58b21-2010-4be2-9093-2d6ddec2baef%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-07-08 17:06 UTC, merged