fix(elasticsearch): advancedOptions in domain has no effect
aws/aws-cdk pull request #15330
Opened 2021-06-28 20:24 UTC by jumic

Property `advancedOptions` in ElasticSearch domain did have no effect because the assignment was missing.
* add assignment for advancedOptions to fix issue
* test cases
* describe function in readme

Fixes #14067

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-06-28 21:01 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 9e730114d003e52210a5b6152fa974206c7dce08
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4850a862-b0e9-44e4-85b9-db56e2736ae5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-07-06 23:53 UTC, peterwoodworth submitted a review, later dismissed
This PR looks great! Thank you for fixing this oversight

2021-07-23 00:42 UTC, BenChaimberg requested changes
Can you please also add one or more of these to the integ.elasticsearch.ts integration test?

2021-07-23 00:42 UTC, BenChaimberg commented on packages/@aws-cdk/aws-elasticsearch/test/domain.test.ts
> +describe('advanded options', () => {
```suggestion
describe('advanced options', () => {
```

2021-07-23 00:42 UTC, BenChaimberg commented on packages/@aws-cdk/aws-elasticsearch/README.md
> +        'rest.action.multi.allow_explicit_index': 'false',
let's put all three documented options here

2021-07-23 21:25 UTC, jumic commented on packages/@aws-cdk/aws-elasticsearch/README.md
> +        'rest.action.multi.allow_explicit_index': 'false',
done

2021-07-23 21:44 UTC, jumic commented
I added the integration test as requested and changed the readme.

I also hat to change the policy in the integration test. I received the message 'Apply a restrictive access policy to your domain' when I deployed the stack. My changes where not active at this time. I replaced `iam.AnyPrincipal()`by `iam.AccountRootPrincipal()` to use a valid policy.

2021-07-23 21:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 56bd14528ffb4c2161682e060aa416f54bf0f013
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2d48dcfa-7d14-4164-abb7-1f09e29cb670%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-07-23 21:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 248087dd91db4399cf3bbe5eaa89c1a2cb6a42ec
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e4f7c268-ee94-4298-8048-03f39f82cfa7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-07-23 22:09 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 9179d959de6c12d579f7b9e1a43d8c2e8eb71cd7
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5637454c-0de7-437f-aa78-255c11d30689%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-07-23 22:20 UTC, BenChaimberg approved these changes

2021-07-23 22:22 UTC, merged