docs(synthetics): Updated CloudWatch Synthetics README with canary scheduling details.
aws/aws-cdk pull request #15352
Opened 2021-06-29 18:11 UTC by jonrhall

This PR adds more extensive documentation for how to schedule CloudWatch Synthetics canary cron jobs via CDK, because today the service documentation for how to schedule cron jobs is lacking and takes developers a lot of investigation to figure out how to make it work successfully.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-06-29 18:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 6b623241acbfa190be0db6daf05448659978d9b5
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1d44e50c-5f79-4e14-817d-5f39c84fbaf0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-06-29 18:26 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: f67158f0b9ea6af0676ef1360df8cafe12174c9c
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=424c6ed8-4f9f-46fa-840b-5acbd893950b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-07-07 18:14 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 64c5d8f0955398703a177558bc772c9e4061fb7e
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=09427658-6af9-4cd3-ab78-36124aacdd0f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-07-21 05:55 UTC, BenChaimberg requested changes
thank you for improving our documentation! these are the most important contributions in my book, so sorry for the massive comment-to-changed-line ratio

2021-07-21 05:55 UTC, BenChaimberg commented on packages/@aws-cdk/aws-synthetics/README.md
> +```js
```suggestion
```ts
```

2021-07-21 05:55 UTC, BenChaimberg commented on packages/@aws-cdk/aws-synthetics/README.md
> +```js
```suggestion
```ts
```

2021-07-21 05:55 UTC, BenChaimberg commented on packages/@aws-cdk/aws-synthetics/README.md
> +You can set the canary `schedule` property by assigning it a value with the `synthetics.Schedule` [class](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-synthetics.Schedule.html).
"set the canary schedule property" is not really a helpful statement, how about something like "Specify the schedule on which a canary runs by providing a `Schedule` value to the `schedule` property."?

2021-07-21 05:55 UTC, BenChaimberg commented on packages/@aws-cdk/aws-synthetics/README.md
> +If expanded access to scheduling the canary is needed, use `synthetics.Schedule.expression` with [cron expressions, as defined here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Clo
```suggestion
If expanded access to scheduling the canary is needed, use `Schedule.expression` with [cron expressions](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_cron.html):
```

2021-07-21 05:55 UTC, BenChaimberg commented on packages/@aws-cdk/aws-synthetics/README.md
> +
please also add a small section about `once`

2021-07-21 05:55 UTC, BenChaimberg commented on packages/@aws-cdk/aws-synthetics/README.md
> +synthetics.Schedule.rate(Duration.minutes(5)), // Run every 5 minutes.
```suggestion
Schedule.rate(Duration.minutes(5)), // Run every 5 minutes.
```

2021-07-21 05:55 UTC, BenChaimberg commented on packages/@aws-cdk/aws-synthetics/README.md
> +Configure a run rate of up to 60 minutes with `synthetics.Schedule.rate`:
```suggestion
Configure a run rate of up to 60 minutes with `Schedule.rate`:
```

2021-07-21 05:55 UTC, BenChaimberg commented on packages/@aws-cdk/aws-synthetics/README.md
> +synthetics.Schedule.expression('cron(0 0,8,16 * * ? *)'), // Run at 12am, 8am, 4pm UTC every day
```suggestion
Schedule.expression('cron(0 0,8,16 * * ? *)'), // Run at 12am, 8am, 4pm UTC every day
```

2021-09-22 21:58 UTC, kaizen3031593 approved these changes

2021-09-22 22:00 UTC, kaizen3031593 approved these changes

2021-09-22 22:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: bd1b4b714eb72a9b9e7df3e0c98ad33b576a003c
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=67182291-5cfe-46af-b8e0-ac1e2bca100b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-09-22 22:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: ef63e22a5f0bbcbba8cf5cbc8f557b3fd6a9ff9f
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ec4cf2be-af59-4853-accb-31b5ab9b5e6f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-09-22 22:48 UTC, merged