feat(cli): print diff, change set on deploy and add --confirm-change-set flag
aws/aws-cdk pull request #15494
Opened 2021-07-11 09:32 UTC by stevehodgkiss

A work in progress towards addressing #3780.

Changes:

- Prints template diff and change set details by default.
- Adds a `--confirm-change-set` flag, which can also be configured in `cdk.json` as `"confirmChangeSet": true`.

<img width="989" alt="Screen Shot 2021-07-11 at 1 13 03 pm" src="https://user-images.githubusercontent.com/62331/125190003-0ee1c100-e24c-11eb-93e2-6e2deeafd718.png">

Thoughts:

- deploy-stack.ts was the easiest place to add this functionality, but I'm wondering if it would be better to break this function up into `proposeChange` and `deployChange` methods, and have the interactivity / flag handling in CdkToolkit?
- Is it ok to print the template diff and change set by default, or should that be behind an additional flag/config option? I would want this always on, but I'm not sure if that should be the default.
- The change set display logic is based on how [StackMaster](https://github.com/envato/stack_master/blob/master/lib/stack_master/change_set.rb#L70) (the tool we are migrating to CDK from) presents change sets. Change set review and confirmation is must have feature for us. There's room for improvement in how the change set detail is presented though.
- TODO: add tests for this new functionality.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-07-11 10:11 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: f4447211a63b320f315d79fd4876fc7ccad17e48
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=65b74741-7107-415b-ac61-1776b251880b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-05 09:34 UTC, nija-at commented
Wonder if we start with an RFC for this as mentioned in https://github.com/aws/aws-cdk/issues/3780#issuecomment-893312471.

Leaving this assigned to @rix0rrr to determine next steps.

2021-08-10 12:04 UTC, rix0rrr commented
I agree with @nija-at and @eladb: this ties into `--require-approval` (which is misnamed and should have been called `--require-confirmation` or something), and having both `--require-approval` and `--confirm-change-set` feels weird to me.

Maybe some sort of unified `--require-confirm=changeset`, or something? 

And I feel this should also integrate with the current `cdk diff` analysis in some way -- the change set view doesn't give a lot of information. We could add `--require-confirm=diff`. Another problem is that we might not find all changes, but we could combine the results of the changeset analysis as well as the template analysis. Do you have any thoughts in that direction?

I like your idea of separating out the "proposeChange" and "executeChange" into separate functions and hoisting the confirmation to the top level. I think it'll make for better factored code.

2021-08-10 12:18 UTC, stevehodgkiss commented
> Maybe some sort of unified --require-confirm=changeset, or something?

That sounds reasonable to me. I would want this turned on automatically in settings if that would be possible.

> the change set view doesn't give a lot of information

The change set provides a definitive view of what will happen when deploying a given change. I don't think there's an effective way to reproduce that with calculations (cdk template diff etc). Being able to view that is essential to deploying changes safely. It indicates if (for example) an RDS DB will be "recreated" and all data would be lost by doing that. It's a format we're used to with out current CFN tool StackMaster, which always creates a change set and presents it for review before applying.

> I like your idea of separating out the "proposeChange" and "executeChange" into separate functions and hoisting the confirmation to the top level. I think it'll make for better factored code.

Yeah I think that's a reasonable refactoring to make, and aligns with the actions that the user would take (propose change, then press y to apply them once reviewed).

2021-08-10 12:29 UTC, rix0rrr commented
> I would want this turned on automatically in settings if that would be possible.

It should be. Fairly sure we're reading `requireApproval` from `cdk.json` already.

> I don't think there's an effective way to reproduce that with calculations (cdk template diff etc)

I'm not saying use one or the other exclusively; I'm saying combine the sources of information into one view. Each of them can do things the other one can't. But I appreciate this might be too much for you to get into right now.

2021-08-22 11:20 UTC, stevehodgkiss commented
> I'm not saying use one or the other exclusively; I'm saying combine the sources of information into one view. Each of them can do things the other one can't. But I appreciate this might be too much for you to get into right now.

Gotcha. Some changes don't have an associated template difference (i.e. CFN parameter changes). It would be interesting to explore how the 2 could be combined into a unified view though (diff with change set details), but it would need to account for changes that don't have an associated template diff.

Here's a screenshot of our internal tooling (an opinionated copilot-like tool that wraps CDK CLI with some additional features) deploying an ECS service with CFN parameter triggered updates to the task definition and fargate service (a typical deploy):

<img width="1294" alt="Screen Shot 2021-08-22 at 3 08 11 pm" src="https://user-images.githubusercontent.com/62331/130352957-af6cbe9f-e247-4d4d-858b-00354e79aed3.png">

> But I appreciate this might be too much for you to get into right now.

Yeah this isn't something I have time to get into right now. I think it's worth exploring though.

2021-10-04 11:53 UTC, rix0rrr requested changes
I would like to pivot this into a `--confirm=` flag, out of which changeset confirmation is one of the possible options. This new flag would deprecate and subsume `--require-approval=`.

2022-02-15 16:01 UTC, closed without merging