feat(aws-cloudwatch): add verticalAnnotations property to GraphWidget
aws/aws-cdk pull request #15809
Opened 2021-07-29 02:38 UTC by brendo-m

Adds a `verticalAnnotation` property to `GraphWidget`. See https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/CloudWatch-Dashboard-Body-Structure.html#CloudWatch-Dashboard-Properties-Annotation-Format.

Also see https://github.com/aws/aws-cdk/issues/7622

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-07-29 03:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: bc433b3e2b1f4febdf6b1bf0a7ecfb982ccbd76e
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d6733e60-2301-465e-a99b-f9600fa1b7d3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-07-29 03:57 UTC, brendo-m commented
Just realized there are breaking changes here - interface `Shading` has been renamed to `HorizontalShading` and there's a new `VerticalShading`.

Should I revert `HorizontalShading` to `Shading` and keep `VerticalShading`? It's a little unclear but not the end of the world

2021-07-29 04:10 UTC, brendo-m commented
I just went ahead and made that change

2021-07-29 04:50 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: c8d9eee70c278395556e7ebdcf18fb65cee85ef3
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d27e8a25-840a-4ed0-8161-35e281500001%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-06 02:09 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: c56443ae2e6d3b4d3f8e2a875398321f14a0f0b6
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9d086af2-2612-4d68-bd12-132fce080ed1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-01-28 15:53 UTC, gshpychka commented
@RomainMuller any change of this to get merged?

2022-01-28 17:08 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 391a19206fab7e239b287c70511859978256c379
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c0ad063f-f50c-41dc-90c6-0a593038c0d4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-01 00:29 UTC, madeline-k requested changes
Thank you for your contribution, @brendo-m! We just need a description and an example added to the README before this can be merged.

2022-02-01 00:29 UTC, madeline-k commented on packages/@aws-cdk/aws-cloudwatch/lib/graph.ts
> +    }) : undefined;
Should we check for `verticalAnnotations.length > 0` ?

2022-02-01 01:17 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: c346945c47f9d669865038aa7cb5866469bedbe5
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a1e292ad-c157-49fe-8ff6-b2ec02d1a104%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-01 18:30 UTC, madeline-k requested changes
We need an update to the README with a description and example for this feature.

2022-03-25 03:14 UTC, TheRealAmazonKendra commented
This PR has been deemed to be abandoned, and will be closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-03-25 03:14 UTC, closed without merging

2022-10-19 22:25 UTC, brendo-m commented
Reviving this PR in https://github.com/aws/aws-cdk/pull/22568