feat(ecr): add option to auto delete images upon ECR repo removal
aws/aws-cdk pull request #15932
Opened 2021-08-07 08:34 UTC by kirintwn

Closes #2765 #12618.

### Use Case
ECR repositories currently do not get delete if they contain images even the `removalPolicy` is set to `DESTROY`.

It was reported in #2765, and was thought to be a responsibility of CloudFormation team [aws-cloudformation/cloudformation-coverage-roadmap#515](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/515).

### Proposed Solution
I do think we should add a option to force delete the images using custom resource provider, which is just like #12090 that uses a custom resource provider to delete objects in s3.

The code might looks like this:

```ts
const bucket = new ecr.Repository(this, 'Repo', {
  repositoryName: 'delete-even-if-contains-images',
  removalPolicy: cdk.RemovalPolicy.DESTROY,
  autoDeleteImages: true,
});
```

The props `autoDeleteImages` can only to be true if `removalPolicy` is set to `DESTROY`.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-08-07 09:17 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 4b7ff58e58805af90dbe5a63b14294e737273c36
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0bf6d5fb-ed06-4081-9773-c25287afb3bc%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-09-03 06:48 UTC, heiba commented
Hello @peterwoodworth, hope you're well. Any chance we can have this PR reviewed please ? We are in dire need for this feature (ability to delete non-empty ECR). @kirintwn has thankfully developed it but it is waiting to be merged.

2021-09-17 14:16 UTC, heiba commented
Hello @madeline-k would greatly appreciate if we can have this PR reviewed and possibly merged please ?

2021-09-21 02:28 UTC, rittneje commented
@kirintwn I have a question about your implementation. Suppose someone deploys their stack with an ECR repo with `autoDeleteImages: true`. That will in turn create this custom resource. But then they change their mind and deploy again with `autoDeleteImages: false`. Would that not cause the custom resource to be deleted, and consequently all the images in the repo would be destroyed at that time?

2021-09-22 12:57 UTC, rittneje commented
@kirintwn We have confirmed that the bug I described exists, so unfortunately your current implementation is not safe. The same bug affects the S3 `auto_delete_objects` feature, for which I will be filing a bug.

2021-09-23 01:30 UTC, rittneje commented on packages/@aws-cdk/aws-ecr/lib/auto-delete-images-handler/index.ts
> +  const listedImages = await ecr.listImages(params).promise();
@kirintwn If the ECR repo was already deleted out-of-band, this will cause the custom resource deletion to fail with an error.

2021-10-01 17:18 UTC, ryparker commented
> @kirintwn We have confirmed that the bug I described exists, so unfortunately your current implementation is not safe. The same bug affects the S3 `auto_delete_objects` feature, for which I will be filing a bug. #16603

Great find! See here for how we're patching that in the S3 package: https://github.com/aws/aws-cdk/pull/16756

2022-02-09 23:25 UTC, madeline-k requested changes
Thanks for implementing this @kirintwn! 

We need to include the same approach in this PR as the fix for the emptying s3 buckets issue that @rittneje and @ryparker have called out.

2022-03-30 21:46 UTC, TheRealAmazonKendra commented
This PR has been deemed to be abandoned, and will be closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-03-30 21:46 UTC, closed without merging