Ecs deploy region
aws/aws-cdk pull request #15944
Opened 2021-08-09 14:21 UTC by robert-lilleker

This is a fix for the region issue raised by https://github.com/aws/aws-cdk/issues/11199 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-08-09 15:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 5e2a888614209cb4f1bd772ac11e5ab4d894c0bc
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b03a1d49-d141-4065-bfb0-20aad1e7b74c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-12 10:09 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: d40572c4266a7b33bb6d5e755283e0941745def5
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5aa943ee-f738-48ca-b9fd-6b5d848a1c76%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-17 15:28 UTC, robert-lilleker commented
Is there anything I can do that might further this along?

2021-09-02 22:22 UTC, skinny85 requested changes
Awesome work @robert-lilleker, but we also need a unit test 🙂. Take some inspiration from [these](https://github.com/aws/aws-cdk/blob/dbfebb47a8ae61b2bb0557b6ba79a7b073f9d0df/packages/%40aws-cdk/aws-codecommit/test/test.codecommit.ts#L107-L108).

2022-03-30 21:50 UTC, TheRealAmazonKendra commented
This issue was fixed by #16997.

2022-03-30 21:50 UTC, closed without merging