feat(pipelines): add property to specify a namespace so exported variables can be used
aws/aws-cdk pull request #15964
Opened 2021-08-10 00:09 UTC by berenddeboer

The pipelines interface currently does not allow setting the namespace of an action. And no "automatic" namespaces are created.

This addition allows specifying `variableNamespace` on a `CodeBuildStep`.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-08-10 00:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 871ba5b9a533fac8c0ab41fbc1409f7344decb4f
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4f7423ac-9b71-4e0c-b586-b9022b1626dc%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-10 01:12 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 90f3e1109b42fd7aa10a084df7a850fd57cba824
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=14cf338f-1feb-48d8-963f-090f087c30d7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-12 08:37 UTC, rix0rrr requested changes
Why all the unrelated changes?

I'd feel more for a `codeBuildStep.variable('asdf')` method which creates a unique namespace and returns the corresponding `'#{MyStep1481.asfd}'` expression.

2021-08-12 21:44 UTC, berenddeboer commented
Unrelated changes: must have come in when I tried rebase against latest, sorry about that. I will try the update branch button here in the future.

I like your proposal: should that also insert things into the exported section of `buildspec.yml`? I think I've seen this approach in the code-pipelines, they seem to generate a unique namespace, at least saw that in the comments there I think. So basically the idea is to make that available in pipelines?

2021-09-17 11:48 UTC, rix0rrr commented
> should that also insert things into the exported section of buildspec.yml? 

Weeelll... it *could*, but I'm not sure we can make that SUPER easy and obvious. Better to leave the underlying CodeBuild mechanism there I think.

2021-12-16 13:11 UTC, igilham commented
@rix0rrr Is there still an interest in pursuing this feature? I have to ask, since you closed my related PR for absolutely no reason.

2022-02-16 12:04 UTC, rix0rrr commented
#17189 is closer to what I want, so I will be finishing that one.

2022-02-16 12:04 UTC, closed without merging