fix(lambda-python): python function index/handler logic broken if handler in subdirectory
aws/aws-cdk pull request #15981
Opened 2021-08-11 02:21 UTC by vincent-turato

If a handler function is located in a subdirectory of the lambda code package, the aws_lambda.Function handler property would be set to an incorrect value.

Copied from: https://github.com/aws/aws-cdk/issues/15391

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-08-11 03:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: f11200f6ac70e0c1592b320e33750444b95137e1
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=745e3075-4576-4aca-9f60-f11aba88bc6d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-12 14:31 UTC, nija-at reviewed
Thanks for submitting this PR. I just have one main comment.

I can't find any docs on how the handler name should be specified when it is in the inner directory - https://docs.aws.amazon.com/lambda/latest/dg/python-handler.html

Can you supply how you tested and confirmed that this is the correct solution, or point me to some docs?

2021-08-24 09:54 UTC, nija-at requested changes
Setting the status to 'request changes' to address the comment above.

2021-08-25 03:48 UTC, vincent-turato commented
@nija-at 
Please see: https://github.com/aws/aws-cdk/issues/15391#issuecomment-905157965

His explanation aligns with my understanding for why this is needed.

2021-09-27 08:15 UTC, nija-at requested changes
Hi @vincent-turato -

Looks good generally. Just one comment.

2021-09-27 08:15 UTC, nija-at commented on packages/@aws-cdk/aws-lambda-python/lib/function.ts
> +      handler: `${index.replace(/\.py$/i, '').replace('/', '.')}.${handler}`,
Can you add a little comment with a small example explaining this string replace?

2021-11-25 14:51 UTC, nija-at commented
Closing this PR since there has been no traction in a while.

2021-11-25 14:51 UTC, closed without merging