feat(aws-s3-deployment): enable exclude and include filters
aws/aws-cdk pull request #16054
Opened 2021-08-14 14:33 UTC by davidtucker

Closes #14362 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-08-14 14:52 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 7abfc8fefba4a366580eb329c32a30e28e8cc678
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=def3b1e4-2dd6-4e67-a0e2-65cd7023104e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-14 15:25 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 9898937a9d4b0e8784e0de8c07567c45b1fa05c0
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c9bb6426-8eb1-4155-8642-0b191ceb0da7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-14 22:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: fcaac07f9e72322b374c32db66bb119afc940f84
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b48053ae-9ce5-493e-ba4c-6b74df39c1c8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-17 06:38 UTC, eladb requested changes
Looks good. Please change API to support more than a single exclude/include pattern

2021-08-17 06:38 UTC, eladb commented on packages/@aws-cdk/aws-s3-deployment/lib/bucket-deployment.ts
> +  readonly exclude?: string
The CLI allows specifying `--exclude` and `--include` multiple times, so I believe these options should be arrays:

```suggestion
  readonly exclude?: string[]
```

2021-08-17 10:04 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 592ea6624d307e13074cb9ddf54b00e3c5d43365
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fc6293f9-e59b-4182-86f8-6c20c51cd682%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-17 11:16 UTC, eladb commented on packages/@aws-cdk/aws-s3-deployment/README.md
> +  exclude: '*.txt'
```suggestion
  exclude: ['*.txt']
```

2021-08-17 11:16 UTC, eladb commented on packages/@aws-cdk/aws-s3-deployment/README.md
> +  include: 'build/config.json'
```suggestion
  exclude: ['build/*'],
  include: ['build/config.json']
```

2021-08-17 11:16 UTC, eladb approved these changes

2021-08-17 11:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 90acb7e2b9a80119e49c3ad942d89758d7d18900
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b98c869e-1df4-4800-99ee-0d75726a784c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-17 11:47 UTC, davidtucker commented
@eladb I just realized I missed the README update, but I see that you already tackled that.  Apologies for not catching that in the update.

2021-08-17 11:51 UTC, eladb submitted a review, later dismissed
Just realized something - `AssetOptions` also have support for exclusions, which are also taken into account when calculating the asset hash (and therefore invalidate the asset appropriately). @davidtucker I am wondering if using exclusions at the asset level is sufficient and addresses your use case. What do we gain from adding this at the deployment time?

2021-08-17 11:55 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 05c4482244c0f3d76937e32ab42bce5d891b01e9
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1dfded5c-d6f2-4164-ab75-13b8c85d452a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-17 11:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: dbd3e0ecb00354f8ef33c4f73d3d19dcad358c13
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c4d4e2b5-e01d-4acb-9687-6996ebcd0c2b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-17 12:06 UTC, davidtucker commented
@eladb The main issue here (that led to me creating this PR) is that I want to exclude files from being pruned in the destination bucket.  In my original use case, I have two things in a bucket: 

- A web application (uploaded using `aws-s3-deployment`)
- A config file (creating using a CloudFormation custom resource)

Using the S3 CLI, this is east to manage.  You can set it to prune with `--delete` but exclude the config file.  You can see further discussion on this in #14362 .  If there is another way to address this, I am fine with it, but I think just using `AssetOptions` solves one issue (including and excluding at the asset level) but not the other (excluding files in the destination bucket from the sync process).

2021-08-19 09:50 UTC, eladb commented
> Using the S3 CLI, this is east to manage. You can set it to prune with --delete but exclude the config file. You can see further discussion on this in #14362 . If there is another way to address this, I am fine with it, but I think just using AssetOptions solves one issue (including and excluding at the asset level) but not the other (excluding files in the destination bucket from the sync process).

OK, makes sense. Can you please add a note in the docs for `include` and `exclude` that points users to the asset `exclude` option if they want to exclude files from being evaluated when invalidating the asset?

2021-08-19 13:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 77d9c446c3f71bf08cf8b90847950ceb8fbb3ff3
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=69b2baf3-df7c-47ee-92ba-230ccdead18c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-19 14:28 UTC, eladb approved these changes

2021-08-19 14:47 UTC, eladb commented
Thanks for the awesome contribution @davidtucker

2021-08-19 15:06 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: f558345c404d7857fa7bfce8cb3a5ee082277603
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9c33fc9c-a70d-44dc-a41b-abf65f9da52b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-19 15:06 UTC, merged