fix(cloudformation-diff): cdk diff not picking up differences if old/new value is in format x.y.z
aws/aws-cdk pull request #16050
Opened 2021-08-13 21:55 UTC by vincent-turato

"cdk diff" in the current version doesn't pick up differences if the old/new value has a number-like format but actually isn't a number (e.g. 0.31.1)

Example: two version strings like "0.31.1-prod" and "0.31.2-prod" are both parsed into "0.31" (and hence incorrectly considered equal).

Copied from: https://github.com/aws/aws-cdk/issues/15898

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-08-13 22:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 3f10ab9ca56342b75755773f87687e3fbfd165bb
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=50df4d0e-c4c5-473b-bf30-6807f99ac0a4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-24 14:36 UTC, aleksil commented
We just hit this bug, but with IP-addresses when working with WAF IP Sets. Changes to the two last octets are not picked up (e.g. changing IP from 1.1.1.1 to 1.1.2.2). I don't think your patch fixes this edge case either, the regex could probably be changed to only allow one dot in a float?

2021-08-30 21:28 UTC, BenChaimberg requested changes

2021-08-30 21:28 UTC, BenChaimberg commented on packages/@aws-cdk/cloudformation-diff/lib/diff/util.ts
> +  const nonNumericRegex = /[^\d\-\.]/;
I think this is too restrictive. Let's try `/\d*\.\d+\./`?

2021-08-30 22:01 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 329905ba4e415967b305f866d179f0df50e4aec0
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0f02e199-6f82-402c-bf62-6e6874dda709%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-09-02 22:02 UTC, BenChaimberg commented on packages/@aws-cdk/cloudformation-diff/test/diff-template.test.ts
> +  const newTags = ['0.31.2-prod'];
please add some more test cases from the comments on this PR and from the issue

2021-09-02 22:41 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 5df80079e03ae0d57bac553494e2de3a57daa7d3
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b0012472-693a-4e73-9eb1-e6565559bdd3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-09-03 06:23 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 28dedd0e4beba075e4c153e7f78ebb3a64c2fda6
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d32b22be-f369-4a16-af10-d5a9b1b9993a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-09-09 22:24 UTC, BenChaimberg approved these changes

2021-09-09 23:14 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 0faf36248d19f7c79ec3e02420af7a607f0d0c1f
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5981097f-2f80-4793-87a4-c4936dd32e8e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-09-09 23:15 UTC, merged