Update RDS engine versions
aws/aws-cdk pull request #16115
Opened 2021-08-18 09:06 UTC by wuhkuh

Added every change as a separate commit, feel free to rebase as you see fit.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-08-18 09:41 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 0a47ca595b79e67d0589ebebaeee426a39417fee
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=33457b83-b288-463a-bfcc-c3c765f903a8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-18 09:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 9e59ac0db54dc19243e5a5121869ca3a1aa971de
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=72a05c82-c5e1-4f84-afe6-d5a2d2ad54de%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-08-18 10:45 UTC, wuhkuh commented
> err  - PROP @aws-cdk/aws-rds.SqlServerEngineVersion.VER_15_00_4043_23_V1: has been removed [removed:@aws-cdk/aws-rds.SqlServerEngineVersion.VER_15_00_4043_23_V1]
> (...)
> Some packages seem to have undergone breaking API changes. Please avoid.

At best this version could point towards the correct version to preserve API compatibility, but keep in mind there's nothing to preserve—[this version simply doesn't exist](https://support.microsoft.com/en-us/topic/kb4518398-sql-server-2019-build-versions-782ed548-1cd8-b5c3-a566-8b4f9e20293a). Preserving compatibility would also nullify the point of type-safe versioning.

Strongly in favor of using the escape hatch (overriding this warning) and patching this up.

2021-08-23 23:02 UTC, skinny85 requested changes
Thanks for the contribution @wuhkuh!

2021-08-23 23:02 UTC, skinny85 commented on packages/@aws-cdk/aws-rds/lib/instance-engine.ts
> +  public static readonly VER_15_00_4073_23_V1 = SqlServerEngineVersion.of('15.00.4073.23.v1', '15.00');
Please, leave the `VER_15_00_4043_23_V1` unchanged, and instead add the new `VER_15_00_4073_23_V1` constant instead.

2021-08-23 23:04 UTC, skinny85 commented
> > err  - PROP @aws-cdk/aws-rds.SqlServerEngineVersion.VER_15_00_4043_23_V1: has been removed [removed:@aws-cdk/aws-rds.SqlServerEngineVersion.VER_15_00_4043_23_V1]
> > (...)
> > Some packages seem to have undergone breaking API changes. Please avoid.
> 
> At best this version could point towards the correct version to preserve API compatibility, but keep in mind there's nothing to preserve—[this version simply doesn't exist](https://support.microsoft.com/en-us/topic/kb4518398-sql-server-2019-build-versions-782ed548-1cd8-b5c3-a566-8b4f9e20293a). Preserving compatibility would also nullify the point of type-safe versioning.
> 
> Strongly in favor of using the escape hatch (overriding this warning) and patching this up.

Instead of removing the `VER_15_00_4043_23_V1` constant, deprecate it.

2021-08-26 17:30 UTC, merged