fix(aws-ecs): Defines ContainerDefinition PseudoTerminal (#16263)
aws/aws-cdk pull request #16694
Opened 2021-09-28 16:46 UTC by AWS-MattB

fixes aws#16263

The CfnContainerDefinition has a parameter `pseudoTerminal` that
is currently missing from the ContainerDefinition construct.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-09-28 17:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: a8efde4f8fd6dc122d4e728985329745c012bb6d
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=dade1506-f973-45e0-97b8-b34aa0344dcf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-09-28 17:52 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 19d1356effc3bee2f5fd0493504e81c77241d044
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2c36964b-55b7-4420-b74f-fe6c8b8b90e4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-09-28 17:54 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: c0324c392de3512c7a02cf915f2891d60b1cc1df
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9bd6eaa5-f4be-4c74-9fa9-eecda61196fe%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-09-28 17:59 UTC, AWS-MattB commented
This change built OK for me locally, but I only ran `yarn build`, `yarn test`, and `./scripts/check-api-compatibility.sh`. Looking at the failure, I can't fathom how the change I made could be related.

```
monocdk: $ yarn --silent jsii-rosetta extract
aws-cdk-lib: (node:15031) UnhandledPromiseRejectionWarning: Error [ERR_WORKER_OUT_OF_MEMORY]: Worker terminated due to reaching memory limit: JS heap out of memory
...
monocdk: FATAL ERROR: NewSpace::Rebalance Allocation failed - JavaScript heap out of memory
```

2021-10-01 07:57 UTC, rix0rrr requested changes
I know it's super trivial, but we need a test for the feature as well.

2022-04-10 14:24 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in CHANGES REQUESTED for 21 days, and looks abandoned. It will be closed in 10 days if no further commits are pushed to it.

2022-04-20 07:32 UTC, closed without merging