fix(apigatewayv2-authorizers): cannot add multiple user pool authorizers without specifying name
aws/aws-cdk pull request #16791
Opened 2021-10-04 23:29 UTC by peterwoodworth

fixes: #13711

BREAKING CHANGE: Users now have to specify `HttpUserPoolAuthorizer` prop `authorizerName`
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-10-04 23:32 UTC, peterwoodworth commented
[HttpLambdaAuthorizer](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2-authorizers.HttpLambdaAuthorizerProps.html) already requires the `authorizerName` prop and doesn't check for tokens like the other Authorizers do. Should we update this construct to check for tokens as well?

2021-10-05 00:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 74b1e0d7e92d01c9bf999f0fa712827af45f221d
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=92267a34-8671-4142-aa9d-b60bea858ff7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-05 16:13 UTC, nija-at requested changes
Hey @peterwoodworth - can you summarize the bug and your fix in the PR description? 
It would be helpful to review this. The issue linked has a few things going on that is hard to follow.

Once done, dismiss my review so it comes back to my plate.

2021-11-29 14:04 UTC, nija-at commented
Closing this since there's no response. Please reopen when ready.

2021-11-29 14:04 UTC, closed without merging