feat(apigatewayv2-authorizers): http api - allow multiple user pool clients per HttpUserPoolAuthorizer
aws/aws-cdk pull request #16903
Opened 2021-10-11 08:47 UTC by tmokmss

closes #15431

BREAKING CHANGE: `userPoolClient` property in `UserPoolAuthorizerProps`
is now renamed to `userPoolClients`.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-10-11 09:06 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 81f9fda8f23cbcc3dd99b3a409eaba63bcd24990
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bc771820-c83b-4650-943d-4bbcb61c9b9b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-05 16:27 UTC, nija-at requested changes
Looks good!

Can you add a new test case that adds multiple user pools and that verify that they show up in the `Audience` field?

2021-11-06 01:02 UTC, tmokmss commented
Hi @nija-at, thanks for the review! I added a test for that. 
Also please be aware that this PR does NOT support multiple user pools, but multiple user pool **clients**. CFn only allows one user pool per Jwt authorizer. So I think this PR title is a bit misleading.

2021-11-06 01:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 9068e9d45d4fe87587b11353c9fc2510fc3fd385
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ded8b1ce-af28-4478-b6c0-51533b3f6ec3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-06 17:35 UTC, nija-at commented
> Hi @nija-at, thanks for the review! I added a test for that. Also please be aware that this PR does NOT add support for multiple user pools, but multiple user pool **clients**. CFn only allows one user pool per Jwt authorizer. So I think this PR title is a bit misleading.

Ah, thanks for the clarification! I've updated the title.

2021-11-06 17:35 UTC, nija-at approved these changes

2021-11-06 18:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 55fb0d9e3119fa8cde0b083c9df5ffb913c948ef
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=be014761-2ff1-4f51-b28b-e30d8f3567c8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-06 18:29 UTC, merged