chore(lambda): allow the architecture property to be readable from the Function
aws/aws-cdk pull request #17121
Opened 2021-10-22 15:37 UTC by jcstorms1

We currently have layers that are designed specifically for arm64 and x86 based functions, and a single stack may have multiple functions with varying architectures. Applying the correct layer to a large list of functions can be a tedious process that may result in applying the incorrect layer to a function. Exposing the architecture at the Function level would allow a user to easily apply the correct layer automatically during deploy by checking the value and pulling the appropriate layer for that architecture. This would eliminate or greatly reduce the possibility of applying the wrong layer type.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-11-04 13:51 UTC, jcstorms1 commented
Hi @nija-at I was curious if you saw my last comment and if you had any advice on those tests? Thanks!

2021-11-05 17:10 UTC, nija-at requested changes

2021-11-05 17:10 UTC, nija-at commented on packages/@aws-cdk/aws-lambda/lib/function.ts
> +    const architecture = props.architecture ?? (props.architectures && props.architectures[0]) ?? Architecture.X86_64;
Oh no, this is not what I meant by my [previous comment](https://github.com/aws/aws-cdk/pull/17121/files#r736272136). I meant only about fixing the getter. 
The change you have now will cause every CDK user's stack to change (undesirable).

However, I just decided in a [different PR](https://github.com/aws/aws-cdk/pull/17000#discussion_r739116360) to leave such getters as `undefined` if the user has not supplied it. Let's revert this back to returning `undefined` if not specified.

Apologies for the churn.

2021-11-09 17:00 UTC, jcstorms1 commented
@nija-at apologies for the confusion. I've gone ahead and reverted the last two commits as requested and fixed the test assertion.

2021-11-09 17:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 1dacd10743753676d78c9d11f31e3bbf86e3e225
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ebf025b1-281f-4c41-ac82-c12aa5a1ff00%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-09 17:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: ca0a06481f90cb837df97db396c3e7e70e375431
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6ce7b6f0-4316-4311-bf0f-b0c0c1d4ec1f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-10 16:31 UTC, nija-at approved these changes
Thanks for the updates @jcstorms1

2021-11-10 20:00 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 02094269d8f7aa562a5234eac7aff2a011e3bd10
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b5fedce7-8f69-4996-adc4-89595a12bf80%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-15 20:33 UTC, jcstorms1 commented
Hey @nija-at. I was curious if there was anything else you needed from me to get this merged? I'm hoping to have this feature available soon if possible. Thanks again!

2021-11-16 10:05 UTC, nija-at commented
@jcstorms1 - my previous approval was discarded of the manual branch update you triggered. Don't touch the PR once approved. Our bots will do the needed changes and merge.

2021-11-16 10:05 UTC, nija-at approved these changes

2021-11-16 10:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 35f44832957b5dfafaa1811181dbddb0dd4e1c82
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=77165556-a05f-42e0-8546-5e43baf10673%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-16 10:46 UTC, merged