fix(aws-ecs): add precheck name of capacity provider when specify it.
aws/aws-cdk pull request #17291
Opened 2021-11-03 03:37 UTC by neilkuan

fix(aws-ecs): add precheck name of capacity provider when specify it.
chore(aws-ecs): update capacityProviderName Description

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-11-03 04:30 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 666209e5d5431a04fa150d0bfdc01036b329bba7
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1b8aad3d-2ed1-4936-b8ad-245c663bb3e7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-03 04:34 UTC, neilkuan commented
Hi @peterwoodworth, do you have a free to take a look this PR, thank you. :)

2021-11-03 17:20 UTC, peterwoodworth commented
Thanks for the contribution @neilkuan! is there any original issue which this is meant to close? And if not, could you create one to describe the issue that needs to be fixed? Thanks

2021-11-04 01:24 UTC, neilkuan commented
thank @peterwoodworth , already create the issue #17321.

2021-11-04 13:34 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 49e19fc70af6a4533cc3bd38ba449aaf4c3baf4a
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a1e9cf30-e1dc-4139-b0ab-113ce4779572%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-04 18:50 UTC, peterwoodworth commented
I think this looks good - I don't think this would be a breaking change. @madeline-k should verify though

2021-11-07 09:56 UTC, neilkuan commented
Hi @madeline-k , do you have a free to take a look this PR, thank you. :)

2021-11-09 01:28 UTC, neilkuan commented
Hi @peterwoodworth, actually this PR adds a pre-check in CDK to avoid possible deployment failure and does not add any new features. It doesn't make sense to update the README to pass the lint. Let's classify it as chore or fix. wdyt?

2021-11-09 02:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 95292579158b45e71a52f48bb400267ab6d93562
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=786aca48-084d-43b5-8bdc-9e5a11a95da9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-09 02:27 UTC, pahud requested changes

2021-11-09 02:27 UTC, pahud commented on packages/@aws-cdk/aws-ecs/test/cluster.test.ts
> +test('can get error when ASG Capacity Provider define capacityProviderName start with aws, ecs or faragte', () => {
```suggestion
test('throws when ASG Capacity Provider with capacityProviderName starting with aws, ecs or faragte', () => {
```

2021-11-09 02:27 UTC, pahud commented on packages/@aws-cdk/aws-ecs/test/cluster.test.ts
> +    // Ensure not added twice
```suggestion
```
Let's just remove this comment.

2021-11-09 02:27 UTC, pahud commented on packages/@aws-cdk/aws-ecs/test/cluster.test.ts
> +    // Ensure not added twice
```suggestion
```
Let's just remove this comment.

2021-11-09 03:50 UTC, pahud reviewed
LGTM

2021-11-09 04:21 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: fa6b517c2d561d617828adcc2d0e5843f20f607c
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=597898ec-1c93-4d2d-9801-ee22c4eb912e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-09 11:28 UTC, pahud commented
Hi @madeline-k can you take a look please?

2021-11-19 18:35 UTC, upparekh commented
Hi @neilkuan , can you please resolve the conflicts before we can merge this PR?

2021-11-20 01:30 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: eb62f127406be3c5b54a60ec94f681bf8bbaa8f4
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c443abc2-b338-46bc-9ec1-b60a4267832c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-20 01:35 UTC, upparekh approved these changes

2021-11-20 02:13 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 01512c48028932700f30fe3058e62635655580f1
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=29fb0ddc-952c-419a-ad85-6c49902292aa%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-20 02:14 UTC, merged