feat(aws-applicationautoscaling): Allow autoscaling with "M out of N" datapoints
aws/aws-cdk pull request #17441
Opened 2021-11-09 23:32 UTC by stephenwiebe

This PR closes #17433. It adds a `datapointsToAlarm` property to the `StepScalingPolicy` construct which allows auto-scaling activities to trigger when only a portion of the data points in the evaluation periods are breaching.

Motivation: Some metrics may have a certain amount of noise/randomness and in these cases it may make more sense to not require that all data points must be breaching for auto-scaling activity to trigger.
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-11-10 00:11 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 06eaa461c2210ac4f74126a12a106ec4d27d862e
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=48444b6a-fba5-4e3e-9d25-42455a71ca52%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-23 06:22 UTC, stephenwiebe commented
@comcalvi Any way this could be merged in? There's not much to this change and it'd be nice to have this functionality.

2021-11-30 19:19 UTC, comcalvi reviewed
Looks great! A few minor changes and this will be ready to be merged.

2021-11-30 19:19 UTC, comcalvi commented on packages/@aws-cdk/aws-applicationautoscaling/lib/step-scaling-policy.ts
> +        datapointsToAlarm: props.datapointsToAlarm,
CloudFormation docs state that this is an integer with minimum value 1. We should validate this prop before we pass it in here, and throw an error if validation fails.

2021-11-30 19:19 UTC, comcalvi commented on packages/@aws-cdk/aws-applicationautoscaling/lib/step-scaling-policy.ts
> +        datapointsToAlarm: props.datapointsToAlarm,
CloudFormation docs state that this is an integer with minimum value 1. We should validate this prop before we pass it in here, and throw an error if validation fails.

2021-11-30 19:19 UTC, comcalvi commented on packages/@aws-cdk/aws-applicationautoscaling/test/step-scaling-policy.test.ts
> +  test('step scaling with evaluation period & data points to alarm configured', () => {
Once the `dataPointsToAlarm` verification is added, can we add a test to verify that the error is correctly thrown?

2021-12-01 20:56 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 42ae6927338747df29197b1ac69bef2dcde6ef35
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a2898f32-8cc5-4c02-8d69-242f7d4d23b2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-01 21:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: f649dbca5b8ce9b0cbcc88c9524e4e4290d24e5b
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b51adee6-269f-42f0-8541-5e7cb58df60f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-03 02:25 UTC, stephenwiebe commented
@comcalvi Ok, I think this should be resolved now.

2021-12-06 18:51 UTC, comcalvi approved these changes
LGTM!

2021-12-06 19:53 UTC, comcalvi requested changes
To fix the linter error, could you add the new property and brief of explanation of it to the README?

2021-12-08 08:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 9c2968b1560b67beaa1b049130c52e9d53d4a589
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a0263ffb-38e8-4817-ac61-02a7c62e13e9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-09 20:09 UTC, comcalvi approved these changes
LGTM! Thanks for adding this to the readme 😄

2021-12-11 02:14 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: fb0eebcd455ab0ce7d9b1c1d56f2dcd67402c1f1
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=eae32681-b334-4972-a81c-b7f174456c01%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-11 02:34 UTC, stephenwiebe commented
@comcalvi What's the next step to get it merged in? I wasn't sure if I needed to merge the master branch back into mine, so I did that but it looks like it might have nullified your review.

2021-12-13 23:56 UTC, comcalvi approved these changes

2021-12-14 00:42 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 0c30c33b32aa100d9d6813fe016bd271ad914330
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2bcf7c0b-23f9-4568-9065-42ebdd77d70b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-14 00:42 UTC, merged