feat(iot): add Action to put records to firehose stream
aws/aws-cdk pull request #17466
Opened 2021-11-11 13:22 UTC by yamatatsu

I'm trying to implement aws-iot L2 Constructs.

This PR is one of steps after following PR: 
- https://github.com/aws/aws-cdk/pull/16681#issuecomment-942233029

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-11-11 14:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 72d9e0a22d36e260a241f53ba7b40c9b440a9eca
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4436b899-a64d-4185-a7df-ec5bed926452%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-11 22:18 UTC, skinny85 requested changes
Looks great @yamatatsu! A few tiny nitpicky comments, mainly around docs.

2021-11-11 22:18 UTC, skinny85 commented on packages/@aws-cdk/aws-iot-actions/lib/firehose-stream-action.ts
> +  COMMA = ',',
Spaces between please:

```suggestion
  /**
   * Separate by a new line
   */
  NEWLINE = '\n',

  /**
   * Separate by a tab
   */
  TAB = '\t',

  /**
   * Separate by a windows new line
   */
  WINDOWS_NEWLINE = '\r\n',

  /**
   * Separate by a commma
   */
  COMMA = ',',
```

2021-11-11 22:18 UTC, skinny85 commented on packages/@aws-cdk/aws-iot-actions/lib/firehose-stream-action.ts
> +   * @default None -- the stream uses no separator
```suggestion
   * @default - none -- the stream does not use a separator
```

2021-11-11 22:18 UTC, skinny85 commented on packages/@aws-cdk/aws-iot-actions/package.json
> +    "@aws-cdk/aws-kinesisfirehose": "0.0.0",
Can we keep these in alphabetical order please?

2021-11-11 22:18 UTC, skinny85 commented on packages/@aws-cdk/aws-iot-actions/package.json
> +    "@aws-cdk/aws-kinesisfirehose": "0.0.0",
Same here (alphabetical order).

2021-11-12 00:12 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 350859ad907b60d046607aae3e2ba99245d88161
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=50add03f-6749-4be2-b84f-e283b10a6192%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-12 00:13 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: d8cb2fdd3618d6d487bbd8910e601e051b9eab67
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=90804b41-3d9c-479c-964c-3daa90e895d3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-12 12:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: ae9cb888d511826b003d7f8d727e51a49e673af0
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1079eb07-45d1-4dbe-a8e9-991452ae0523%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-12 13:28 UTC, yamatatsu commented
addressed! 😃

2021-11-12 17:52 UTC, skinny85 approved these changes
I missed one comment @yamatatsu, apologies!

2021-11-12 17:52 UTC, skinny85 commented on packages/@aws-cdk/aws-iot-actions/lib/firehose-stream-action.ts
> +export interface FirehoseStreamProps extends CommonActionProps {
Missed this:

```suggestion
export interface FirehoseStreamActionProps extends CommonActionProps {
```

2021-11-12 17:52 UTC, skinny85 commented on packages/@aws-cdk/aws-iot-actions/README.md
> +});
Let's kill the `removalPolicy` in the example, it doesn't add much:

```suggestion
const bucket = new s3.Bucket(this, 'MyBucket');
```

2021-11-12 21:54 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 645766d997d46e225a52fd8dcf22b5370112b144
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6fb8f1a9-9bf7-4641-ad0b-801be213e9ea%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-12 21:54 UTC, merged

2021-11-12 23:55 UTC, skinny85 commented
Hey @yamatatsu, I accidentally approved the PR, when I wanted to "Request changes" 😜. Because of that,  I submitted a PR with the fixes I asked for: https://github.com/aws/aws-cdk/pull/17495.