chore(rds): undeprecated `SnapshotCredentials.fromGeneratedPassword()`
aws/aws-cdk pull request #17683
Opened 2021-11-24 10:41 UTC by nija-at

All deprecated APIs will be removed from CDKv2.

APIs where the proposed alternative will modify the resource in ways that
may impact usability of the resource, must not be deprecated.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-11-24 11:05 UTC, njlynch requested changes
What do you think about only removing them from the deprecated APIs lists, but keeping them deprecated? This means they remain deprecated, but won't be removed in V2.

2021-11-24 11:08 UTC, njlynch approved these changes

2021-11-24 11:23 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 3777ad647aa4b24b619c47c341831e607265f807
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=312aed26-5333-455b-9c84-ea9a8095dc27%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-24 11:30 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: a3e4bacc4173533b1ea8c168924964785c4ea38c
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d998e958-ac6e-43dc-828b-489c789dad5e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-24 12:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 229e57e87e2dd2f77d1d9a32919c1ade056de9e9
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=78a63801-bf49-4eb9-86c6-9569caa92013%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-24 12:16 UTC, merged

2021-11-24 18:47 UTC, skinny85 commented
> What do you think about only removing them from the deprecated APIs lists, but keeping them deprecated? This means they remain deprecated, but won't be removed in V2.

@nija-at why wasn't this option considered?

Additionally, why did we un-deprecate a bunch of unversioned Instance engines? This wasn't included in the description of the PR.

Can we revert this PR?

2021-11-25 09:46 UTC, nija-at commented
> why did we un-deprecate a bunch of unversioned Instance engines? This wasn't included in the description of the PR.

The PR description includes this.

> why wasn't this option considered?

I don't see the value of this option. There is no point of providing warnings on APIs that we likely cannot remove (at least not according how deprecations are modeled today)