feat(cognito): user pool: adds custom sender (Email/SMS) lambda triggers
aws/aws-cdk pull request #17740
Opened 2021-11-28 02:19 UTC by thchia

### Motivation

I would like to use the Custom Sender triggers in my CDK app. They are supported by raw CF (despite the docs claiming otherwise), and I do not wish to use the CfnUserPool construct as I am unable to pass the pool as a reference to other constructs (e.g. API Gateway authorisers/User Pool App Clients/etc.). Please find this PR in support of adding the triggers to CDK. I do not wish to follow the method recommended by the docs either (using the CLI to update the pool post-deployment), as it is hard to automate (requiring me to fetch the ARNs of my functions and KMS Key, not to mention it overrides other properties of the User Pool), and leaks my stack configuration out from CDK and into some post-deploy script.

### Description

Adds support for 2 extra lambda triggers (`CustomEmailSender` and `CustomSMSSender`). These triggers have a different format, requiring both function ARN and version (only supported value is `V1_0`).

Additionally, specifying either of these requires a `KMSKeyId` be specified as well, which appears as a property of the `LambdaTriggers` property in CF.

Additionally, specifying the `CustomSMSSender` requires the `smsRole` be specified (allowing `sns:publish`).

Neither of these requirements are enforced in the code, but CF will throw helpful (IMO) errors if they are not satisfied.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-11-28 03:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 0d4a709cae217f5b9eeca2e749586009a209f8e6
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d5f88d8f-6de4-4b29-97b2-318787858927%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-29 12:12 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 27428713082defbf0400408b10ff006df9542e15
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ef6cda6e-f926-4190-9113-a0d29ba7ecf4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-30 16:00 UTC, nija-at requested changes
Thanks for the PR @thchia.

Please see my first round of comments below.

2021-11-30 16:00 UTC, nija-at commented on packages/@aws-cdk/aws-cognito/lib/user-pool.ts
> +  [trigger: string]: lambda.IFunction | string | undefined;
union types such as these are not supported by jsii.

In Java, they will get incorrectly translated into `java.lang.Object`.

Move the kms key to the top-level `UserPoolProps`.
Call it `customSenderKmsKey` with type `IKey` from the `@aws-cdk/aws-kms` module?

2021-11-30 16:00 UTC, nija-at commented on packages/@aws-cdk/aws-cognito/test/user-pool.test.ts
Can you add a new integration test of this nature - https://github.com/aws/aws-cdk/blob/c62377e14caae677deb7e4eae692eaccb2020c67/packages/%40aws-cdk/aws-cognito/test/integ.user-pool-idp.apple.ts#L4-L12 - with verification steps on how you verified that this actually worked?

(Just for one of them - either email or sms - is sufficient)

2021-12-01 12:13 UTC, thchia commented
@nija-at thank you for the feedback! I will update the PR.

2021-12-04 12:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 67f4694cdd3a91069f0d2728a594b5262e15b63f
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d6587cea-12f2-4f7d-99ac-1d16df494bc1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-04 12:53 UTC, thchia commented
Hi @corymhall. Please see my changes based on feedback by Niranjan. I'm not sure if something went wrong with CodeBuild, as the build commented that it had failed, even though it is still marked as pending in the merge checklist as I write this.

The failure looks like a git checkout error, not sure if it can be re-run?

2021-12-04 13:10 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 4890fbe0ef17e56a7490d0eedef57583689633e3
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4b557718-e2f1-4f47-be33-76fbc02db4fc%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-06 14:45 UTC, corymhall approved these changes
Thanks for the contribution!

2021-12-06 15:49 UTC, merged

2021-12-06 15:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 454ed9e6dca0bcb3b29059e9d8b6bd6f6f53a6ee
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=da1a68b6-c279-4039-b3b1-02a61a84957f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->