Add external network modes to ExternalTaskDefinition and TaskDefinition
aws/aws-cdk pull request #17762
Opened 2021-11-29 21:16 UTC by beezly

Adds support for Host and None network modes when creating Task Definitions with External compatibility.
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-11-29 21:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: fe2c6c192174c18d1d3389026e27682abafa658f
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=25beb5c2-d547-4705-aa2a-04fae889849d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-11-29 22:05 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 30f84322e875d71f13907b0022b453420aea309f
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=65ae102f-cd22-4903-b30e-948dad9aaff5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-01 03:19 UTC, pahud commented
Hey @neilkuan @clarencetw @dwchiang @kimisme9386 can you take a first look?

2021-12-01 04:01 UTC, neilkuan commented on packages/@aws-cdk/aws-ecs/test/external/external-task-definition.test.ts
> +import { NetworkMode } from '../../lib';
```suggestion
```

2021-12-01 04:01 UTC, neilkuan commented on packages/@aws-cdk/aws-ecs/test/external/external-task-definition.test.ts
> +        networkMode: NetworkMode.HOST,
```suggestion
        networkMode: ecs.NetworkMode.HOST,
```

2021-12-01 04:01 UTC, neilkuan commented on packages/@aws-cdk/aws-ecs/test/external/external-task-definition.test.ts
> +          networkMode: NetworkMode.AWS_VPC,
```suggestion
          networkMode: ecs.NetworkMode.AWS_VPC,
```

2021-12-01 07:47 UTC, beezly commented on packages/@aws-cdk/aws-ecs/lib/base/task-definition.ts
> +    if (this.isExternalCompatible && ![NetworkMode.BRIDGE, NetworkMode.HOST, NetworkMode.NONE].includes(this.networkMode)) {
Hi @neilkuan. The behaviour is described in https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-anywhere.html:

> The tasks you run on your external instances must use the bridge, host, or none network modes. The awsvpc network mode isn't supported.

2021-12-01 08:02 UTC, beezly commented on packages/@aws-cdk/aws-ecs/test/external/external-task-definition.test.ts
> +import { NetworkMode } from '../../lib';
@neilkuan I've merged all these into a new commit.

2021-12-01 08:34 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 58ae19d0ce8ea8ea966e8ef99cbe2fbdb2992e27
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=644fccf0-7b97-49ae-b52f-8c2f78fc969e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-01 09:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 62e764f92ce461ac78efb60816ea094a22157351
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6cd9e8b2-d715-4b7f-a032-9b82cdf562d3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-07 11:57 UTC, beezly commented
@pahud is anything else needed for this - I also have a branch building against the v2 code. https://github.com/beezly/aws-cdk/tree/v2_network_modes

2022-02-17 10:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: ae68ec4e6dd9a9bad7dceecd2225eebd9b55565d
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5b9572c5-52d2-4b4b-9ada-678641012dc7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-10 10:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: d0a67c830fb0346f1fedbe3bfec8af7cc26ad251
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=cf066e78-14c9-4a3e-a641-a80e596af8f9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-10 12:43 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: b3fe549a2fbaaa692aabee7e416a3c769d195e1a
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7888df49-dc6b-4d7d-9245-a95d261f42fa%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-16 18:29 UTC, madeline-k requested changes
Thanks for opening this PR, @beezly! Just a few minor comments, and then it is ready to go.

2022-03-16 18:29 UTC, madeline-k commented on packages/@aws-cdk/aws-ecs/lib/external/external-task-definition.ts
> +   * @default - NetworkMode.Bridge
```suggestion
   * @default NetworkMode.BRIDGE
```

2022-03-16 18:29 UTC, madeline-k commented on packages/@aws-cdk/aws-ecs/lib/external/external-task-definition.ts
> +
This public property is not used anywhere, so let's not add it until there is a requirement for it.

2022-03-16 18:29 UTC, madeline-k commented on packages/@aws-cdk/aws-ecs/lib/external/external-task-definition.ts
> +    this.networkMode = props.networkMode ?? NetworkMode.BRIDGE;
```suggestion
```

2022-03-24 00:24 UTC, madeline-k commented on packages/@aws-cdk/aws-ecs/lib/external/external-task-definition.ts
> +
Actually this already exists in the base class, TaskDefinition. It should still be removed from here.

2022-03-24 00:25 UTC, madeline-k commented on packages/@aws-cdk/aws-ecs/lib/external/external-task-definition.ts
> +    this.networkMode = props.networkMode ?? NetworkMode.BRIDGE;
This is already done by passing in `props.networkMode ?? NetworkMode.BRIDGE` to the super constructor.

2022-03-24 00:27 UTC, madeline-k submitted a review, later dismissed
Approving

2022-05-17 07:31 UTC, beezly commented
@madeline-k looks like this didn't merge but I'm not sure why. Are you able to give me a hint?

2022-06-13 21:18 UTC, TheRealAmazonKendra approved these changes

2022-06-14 01:09 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: aa402dc6da2165cf6f18d8b842f6b63eeb78dd67
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=acf7c2ef-2687-4bb2-abca-765315d2f6bf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-14 01:10 UTC, merged