feat(cognito): add new userPoolAddOnsSettings property to allow to se…
aws/aws-cdk pull request #17923
Opened 2021-12-09 10:31 UTC by mirgj

this PR fixes #7405

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-12-09 11:13 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 2139993b22b73d3bfa4c8850e7be620083da44e8
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=faadb990-47a5-4572-bfe9-2037b14dd1cf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-09 18:54 UTC, corymhall commented
@mirgj Thanks so much for submitting this pull request. I am marking this pull request as `p2`, which means that we are unable to work on it immediately, but it's definitely still on our radar. We use +1s to help prioritize our work, and are happy to revaluate this pull request based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

Also, have you seen [this PR](https://github.com/aws/aws-cdk/pull/7755)? It doesn't look like it is currently being worked on so if you want to pick up where they left off it would give you a good head start. As is I don't think it's worth including this _without_ implementing an L2 for `CfnUserPoolRiskConfigurationAttachment`. It's easy enough to use escape hatches to set this property, and setting the mode to `ENFORCED` doesn't actually enable enforcement, it can only be done through `CfnUserPoolRiskConfigurationAttachment`.

2022-04-08 13:31 UTC, rix0rrr requested changes

2022-04-08 13:31 UTC, rix0rrr commented on packages/@aws-cdk/aws-cognito/lib/user-pool.ts
> +  readonly advancedSecurityMode?: AdvancedSecurityMode;
Please move this to the top level

https://github.com/aws/aws-cdk/blob/master/docs/DESIGN_GUIDELINES.md#flat

2022-04-24 19:42 UTC, mrgiba commented
Any expectations of when the same feature will be available in Python ? Thanks

2022-05-05 00:08 UTC, closed without merging