feat(CodeBuildStep): add source code support for BuildSpec.fromSourceFileName
aws/aws-cdk pull request #17952
Opened 2021-12-10 16:17 UTC by tobytipton

This implements #17178 allows using CodeBuildStep for building source code which might contain a buidspec.yml.  Adding two flags `skipDefaultBuildSpec` and `fullBuildSpec` which must be specified in order to override the `commands`, `installCommands` and/or `partialBuildSpec`

closes #17178

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-12-10 16:50 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 0aad7f52e2b794b1190f2cce2b6313a978063943
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=131d70bb-596b-4775-a30f-0299d9f0e340%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-10 19:05 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: a717448c831160ecb6dae27b5e9a452e9967bb94
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fcf01994-acff-4715-8513-877ed63b52ce%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-01-03 14:13 UTC, rix0rrr requested changes
After thinking about it a little more -- does this feature even make sense?

Here are the things that are included in the default buildspec:

- Commands, installCommands: granted, these are easily replaced.
- Artifacts: these are impossible to guess! You would have to provide the exact right artifact ids in the `buildspec.yaml` you provide in the source repository, but the CDK pipelines construct is going to generate some randomized artifact IDs at runtime. You're going to have a bad time trying to copy those IDs over.
- Defaults: you might or might not want these (if you don't want them, why are you putting them in).

So what's the use case we are trying to cover by adding this feature? 

- If the use case is: I want to have my build script in my source repository, that is better achieved by providing a `BuildSpec.runRepositoryScript()` constructor (or something to that effect).
- If the use case is: I want to set defaults on all my CodeBuild projects but I want to skip them on this one project... then I'd like to see the bigger story behind why and how this crops up.

The original request in #17178 ultimately wasn't really around whether the buildspec comes from the CDK app or from the source repository--it was around not having to type `new Dictionary<>` all the time; i.e., `BuildSpec.fromFile()` would have already been good enough for them.

So a little more your need for this feature this would be great!

2022-01-03 14:17 UTC, rix0rrr commented on packages/@aws-cdk/pipelines/lib/codepipeline/codebuild-step.ts
> +  readonly fullBuildSpec?: codebuild.BuildSpec;
I kinda don't like having both the  `fullBuildSpec` AND `skipDefaultBuildSpec` here. In my mind, we have the following options:

* Just add `fullBuildSpec` and have it be mutex with `partialBuildSpec`
* Have `partialBuildSpec` and `autoBuildSpec` -- can't find a good name for this. Needs to encompass both the automatic addition of artifacts as well as the inheriting of defaults from the pipeline.
* Have `buildSpec and `buildSpecIsComplete` -- as before but deprecating `partialBuildSpec` for a new `buildSpec` parameter.

None of these are obviously great, but before we make any decisions here I want to talk use cases first.

2022-01-03 18:04 UTC, tobytipton commented
> After thinking about it a little more -- does this feature even make sense?
> 
> Here are the things that are included in the default buildspec:
> 
>     * Commands, installCommands: granted, these are easily replaced.
> 
>     * Artifacts: these are impossible to guess! You would have to provide the exact right artifact ids in the `buildspec.yaml` you provide in the source repository, but the CDK pipelines construct is going to generate some randomized artifact IDs at runtime. You're going to have a bad time trying to copy those IDs over.
> 
>     * Defaults: you might or might not want these (if you don't want them, why are you putting them in).
> 
> 
> So what's the use case we are trying to cover by adding this feature?
> 
>     * If the use case is: I want to have my build script in my source repository, that is better achieved by providing a `BuildSpec.runRepositoryScript()` constructor (or something to that effect).
> 
>     * If the use case is: I want to set defaults on all my CodeBuild projects but I want to skip them on this one project... then I'd like to see the bigger story behind why and how this crops up.
> 
> 
> The original request in #17178 ultimately wasn't really around whether the buildspec comes from the CDK app or from the source repository--it was around not having to type `new Dictionary<>` all the time; i.e., `BuildSpec.fromFile()` would have already been good enough for them.
> 
> So a little more your need for this feature this would be great!

We have use cases where we have a source code in a different repository than the cdk source.  We want to be able to still manage the `buildspec.yaml` in the source code, because that `buildspec.yaml` is tied to the source code not the cdk.  If a change is made to how the build of the source code is done via a `buildspec.yaml` it would then also need to be made to the cdk.

Leveraging `BuildSpec.fromSourceFilename` would solve that use case, build project default environment variables should be able to be leveraged with path related to to output directory in [outputs](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_pipelines.ShellStep.html#outputs) to provide the path.

We also have use cases in which we leverage the "empty"/"default" build spec.  Which is part of the reason for having the 2 properties vs just the one property.

2022-01-04 13:51 UTC, rix0rrr commented
> because that buildspec.yaml is tied to the source code not the cdk

Yes, I understand that. My question is: what exactly is it you are looking to control via that buildspec?

* Are you looking to control artifact names? Cache directories? Run-as user? I am guessing not.
* Are you looking to control build script? `npm install`, `mvn package`, `./build.sh` ? I'm guessing yes, right?

2022-01-04 16:18 UTC, tobytipton commented
> > because that buildspec.yaml is tied to the source code not the cdk
> 
> Yes, I understand that. My question is: what exactly is it you are looking to control via that buildspec?
> 
>     * Are you looking to control artifact names? Cache directories? Run-as user? I am guessing not.
> 
>     * Are you looking to control build script? `npm install`, `mvn package`, `./build.sh` ? I'm guessing yes, right?
> 
> 
> A little more detail would be helpful, because I think there's a nice middle ground to be had between "everything must be controlled in the source repository" and "everything must be controlled in the CDK app".
> 
> We can have the things you want in the source repo be in the source repo, and the things that are autogenerated, or relate more to the CodeBuild Project, in the CDK code.

For the source repo we are running the buildspec.yaml to generate/package the code.
The output of that we need to be in the assets because we want to be able to leverage that to get access to the code for Lambda using `Code.fromAsset`.

Which means it needs to be an IFileSetProducer, to get it added into the assets as far as I can tell.

2022-01-05 13:34 UTC, rix0rrr commented
I will ask the question in a different way:

Can you go through this page: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax and tell me which one of the buildspec sections you need to use?

For example:

* Are you using `env` ? (If so, for what)
* Are you using `proxy` ? (If so, for what)
* Are you using `phases`? Are you using `runtime-versions`? Are you using `finally`?
* Are you using `reports`?
* ...etc

 (Alternatively, paste your buildspec here)

2022-01-05 14:34 UTC, tobytipton commented
I have multiple projects I am reviewing so looking at a sampling of them to answer your questions.

1.  Are you using `env` ? (If so, for what)
Yes we are using env to export out some env variables, in one example.

2.  Are you using `proxy` ? (If so, for what)
No I didn't see any in the samples I checked.

3.  Are you using `phases`? 
Yes, we are leveraging runtime-versions in install.
Commands in pre_build, build and post_build phases.
I don't think we are using finally.
 
4.  Are you using `reports`?
Yes we are using reports.

We are using cache and artifacts as well.

In one case we are have build spec we are creating a json file template which is one step.
The other build spec (another step) leverages that json file template to update it to produce an output artifact which is used by a deployment action.

2022-04-10 14:25 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in CHANGES REQUESTED for 21 days, and looks abandoned. It will be closed in 10 days if no further commits are pushed to it.

2022-04-20 07:32 UTC, closed without merging