chore(rds): add MariaDB 10.5.13, 10.4.22, 10.3.32, 10.2.41 and Aurora MySQL 3.01.0
aws/aws-cdk pull request #17959
Opened 2021-12-10 22:26 UTC by jumic

Add new RDS versions:

**MariaDbEngineVersion 10.5.13, 10.4.22, 10.3.32 and 10.2.41**
[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/12/amazon-rds-mariadb-supports-new-minor-versions/)

**AuroraMysqlEngineVersion 3.01.0**
[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-aurora-mysql-8-0/)
Version informations retrieved from CLI command: `aws rds describe-db-engine-versions --region us-east-1 --engine aurora-mysql --engine-version 8.0`

Deployment tested successfully:
```ts
new rds.DatabaseCluster(this, 'DatabaseCluster', {
  engine: rds.DatabaseClusterEngine.auroraMysql({ version: rds.AuroraMysqlEngineVersion.VER_3_01_0 }),
  instanceProps: {
    instanceType: ec2.InstanceType.of(ec2.InstanceClass.R5, ec2.InstanceSize.XLARGE),
    vpc,
  },
  removalPolicy: RemovalPolicy.DESTROY,
});
```

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-12-10 23:08 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: a3bc79616dd9f45318730b600b0ff7b19b357d79
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d0593097-ff02-4a69-94fc-708364788898%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-10 23:13 UTC, skinny85 requested changes
Thanks for the contribution @jumic! A tiny change please before we merge this in 🙂.

2021-12-10 23:13 UTC, skinny85 commented on packages/@aws-cdk/aws-rds/lib/cluster-engine.ts
> +  }
I doubt we will ever use this with the second parameter as `false`, so let's just remove it completely for now:

```suggestion
  private static builtIn_8_0(minorVersion: string): AuroraMysqlEngineVersion {
    return new AuroraMysqlEngineVersion(`8.0.mysql_aurora.${minorVersion}`, '8.0');
  }
```

This is a private method, we can always add back the parameter if we need to.

2021-12-10 23:13 UTC, skinny85 commented on packages/@aws-cdk/aws-rds/test/cluster-engine.test.ts
> +
No need for this extra empty line:

```suggestion
```

2021-12-11 09:20 UTC, jumic commented
Thanks for your review. I implemented the suggested changes.

2021-12-11 10:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: ee8f47a2b8a1294fc3b50eb6b473c532ebbc7a0a
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3226f8f5-e963-437a-bd6b-bef62c4b1404%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-13 19:01 UTC, skinny85 approved these changes
Thanks for the contribution @jumic!

2021-12-13 22:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: fbab67bac627dc9325085cff4610ed61b90ef733
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0e5088fc-0495-4bd1-afe6-d2a32a10002e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-13 22:23 UTC, merged