fix(aws-lambda-event-sources): unsupported properties for SelfManagedKafkaEventSource and ManagedKafkaEventSource
aws/aws-cdk pull request #17965
Opened 2021-12-11 07:54 UTC by zehsor

----
This request attempts to fix the issue with creating an event source mapping for a lambda function for kafka using properties that are only supported for kinesis and dynamodb streams. The existing KafkaEventSourceProps Interface extends from an interface which also exports properties for kinesis and dynamodb event sources. 
I created the interface BaseStreamEventSourceProps to overcome this issue. I was not able to see any possibility to run a valid unit test against this change as all existing unit tests seemed to cover the underlying change. Fixes #17934

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-12-11 08:30 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: ae1028bf54b1be8b081f61118d0fbaf3af6e8a95
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=92bb2da5-fc45-41cf-8faf-389f7f347337%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-11 09:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 12426295a44a8c3d66c76175e252339c058d6ace
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ffef97cd-366b-4a4f-bf55-d0703f7b351b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-11 11:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: ae1028bf54b1be8b081f61118d0fbaf3af6e8a95
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0092ba71-bb13-472c-aa06-33585febf18a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-11 14:11 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 4e6736b9742ad266f0dfbffc51e462bbd810c934
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ca543dc8-bd77-4f45-9513-77106d9d2882%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-16 21:29 UTC, iwt-philipzeh commented
@kaizen3031593 not trying to interrupt or stress you, but is there anything i can do to help you review this? :)

2022-01-04 22:49 UTC, kaizen3031593 requested changes
This looks great @zehsor! I'm fine with the breaking change (yes, it is) because it never would have worked in the first place. And no need to test -- I'll mark the PR as exempt. 

I have a few nits involving new lines that I normally would go in and do myself, but you haven't configured the PR to allow me to do this (next time, try PRing from a branch of your fork and the default permissions should allow maintainer contributions). Since I can't go in and change them myself, I'm going to bother you and have you remove them. Then, I'll approve the PR. Thanks for the contribution!

2022-01-04 22:49 UTC, kaizen3031593 commented on packages/@aws-cdk/aws-lambda-event-sources/lib/kafka.ts
> +
excess new line

2022-01-04 22:49 UTC, kaizen3031593 commented on packages/@aws-cdk/aws-lambda-event-sources/lib/stream.ts
> +
Why the extra new line here? I think there are 4 places in this section that have 2 new lines, ideally you help me get rid of them all.

2022-01-04 22:49 UTC, kaizen3031593 commented on packages/@aws-cdk/aws-lambda-event-sources/lib/stream.ts
> +}
There should be a new line between lines 50 and 51

2022-01-05 08:35 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 0c827028591e206a543397cdd37d2c2f91ae8bf3
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6c30e5d7-ce16-42be-861a-61830dec16a1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-01-05 08:36 UTC, zehsor commented
Thanks @kaizen3031593 for the great feedback. I think the formatting issue happened due to trying out different things in the beginning, sorry for that. As i usually work with gitlab i learned something new about github pull requests, will follow your instructions next time :)

2022-01-05 09:23 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 7a9c45721a0a8fe081b6de958dd7ac6b9a8f0aec
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fcbac37c-25dd-422c-a0bb-e50ad156b8d0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-01-07 21:23 UTC, kaizen3031593 approved these changes

2022-01-07 22:10 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: ef9df2da1000f9418be3a24efa4ce69ab29d90dc
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=497d6988-e6ed-4448-a954-14aecf8c3df2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-01-07 22:10 UTC, merged