feat(docdb): logs retention option
aws/aws-cdk pull request #18120
Opened 2021-12-21 20:09 UTC by jumic

Provide an option to configure the number of days log events are kept in CloudWatch Logs.
Properties `cloudwatchLogsRetention` and `cloudwatchLogsRetentionRole` are added to `DatabaseClusterProps`.

Closes #13191.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-12-21 20:53 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: a10032dc091177e31123e607cc656d475f2e775b
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=cc7cad79-93e1-4b46-90d3-e0fba1e3bd8c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-21 21:54 UTC, skinny85 requested changes
Looks great @jumic! Just a small naming comment.

2021-12-21 21:54 UTC, skinny85 commented on packages/@aws-cdk/aws-docdb/lib/cluster.ts
> +  readonly cloudwatchLogsRetention?: logs.RetentionDays;
Let's be consistent with the other property names:

```suggestion
  readonly cloudWatchLogsRetention?: logs.RetentionDays;
```

2021-12-21 21:54 UTC, skinny85 commented on packages/@aws-cdk/aws-docdb/lib/cluster.ts
> +  readonly cloudwatchLogsRetentionRole?: IRole;
```suggestion
  readonly cloudWatchLogsRetentionRole?: IRole;
```

2021-12-21 22:27 UTC, skinny85 submitted a review, later dismissed
You missed changing the docs, and I missed a redundant condition in an `if` 😃.

2021-12-21 22:27 UTC, skinny85 commented on packages/@aws-cdk/aws-docdb/README.md
> +  cloudwatchLogsRetentionRole: myLogsPublishingRole, // Optional - a role will be created if not provided
```suggestion
  cloudWatchLogsRetention: logs.RetentionDays.THREE_MONTHS, // Optional - default is to never expire logs
  cloudWatchLogsRetentionRole: myLogsPublishingRole, // Optional - a role will be created if not provided
```

2021-12-21 22:27 UTC, skinny85 commented on packages/@aws-cdk/aws-docdb/lib/cluster.ts
> +    if (cloudwatchLogsExports && props.cloudWatchLogsRetention) {
No need for the first condition - `cloudwatchLogsExports` is never `undefined`, and an empty array is truthy in JavaScript:

```suggestion
    if (props.cloudWatchLogsRetention) {
```

2021-12-21 22:39 UTC, jumic commented
Thanks for your feedback. The suggested changes have been implemented. :)

2021-12-21 22:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 6415c45b50312ae30c9919c12fda46ebb36113ad
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2122c1d3-6ab2-43ee-80fe-e4976b4bf4c7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-21 23:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 1ce9273533c5ebbe3530c1632113274785e6ba96
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8f33202b-18d8-4873-a86b-8dc4353c96b8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-22 00:06 UTC, skinny85 approved these changes
👍

2021-12-22 00:07 UTC, merged