feat(aws-codepipeline-actions): Added region as prop of LambdaInvokeAction
aws/aws-cdk pull request #18229
Opened 2021-12-30 19:20 UTC by ryparker

## Summary

This PR adds the missing prop `region` to the `LambdaInvokeAction`.

Fixes: https://github.com/aws/aws-cdk/issues/18228

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2021-12-30 19:42 UTC, skinny85 requested changes
This is a good attempt, but the region should be taken from the `Function` passed in the `lambda` property, not separately 🙂.

2021-12-30 20:04 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 1f13ffc50258b2be5c64aa28e6906d0fdd4255e0
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=644dfe36-0fc4-4b75-8551-11d616ee98e2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-30 20:09 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 0e908c5cd74e21b732efd516a554e6effa3f38ae
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2b91fa34-407a-45dd-9bba-fc04ecdd7348%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-30 21:57 UTC, ryparker commented
> This is a good attempt, but the region should be taken from the `Function` passed in the `lambda` property, not separately 🙂.

That sounds ideal however this would cause an error on any pipeline stack that does not have `region` specified.

Here is the error that is thrown if we default to using the Lambda function's region: 

```sh
Error: Resolution error: Resolution error: Resolution error: Pipeline stack which uses cross-environment actions must have an explicitly set region.
```

2021-12-30 22:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: d65995306a77f7cc809707675ba31070fa0e58ab
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=589865d2-76be-4a59-b186-2e22adcb7763%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-12-30 23:58 UTC, skinny85 commented
> > This is a good attempt, but the region should be taken from the `Function` passed in the `lambda` property, not separately 🙂.
> 
> That sounds ideal however it would cause an error on any pipeline stack that does not have `region` specified.
> 
> ```shell
> Error: Resolution error: Resolution error: Resolution error: Pipeline stack which uses cross-environment actions must have an explicitly set region.
> ```
> 
> In this case we're allowing the user to configure the `LambdaInvokeAction`'s `region` only when necessary. If we default to using the Lambda's region then the above error will break any current usage that does not have `region` specified on the pipeline's stack.

Yep, that's expected behavior, like the error message says. If you provide a Lambda function from a specific region, you must also tell us what region the pipeline is in, because if the two are different, this means this is a cross-region CodePipeline, and we must do some additional stuff to make it work. The construct handles all of that in its implementation, but we need to have a specific region to make sure the pipeline is indeed cross-region.

We already take the region from the Lambda function [here](https://github.com/aws/aws-cdk/blob/7df4a587daadbd46c9355097523b39342fafe5c2/packages/%40aws-cdk/aws-codepipeline-actions/lib/lambda/invoke-action.ts#L76-L76), so I'm curious what is causing the incorrect behavior in the original issue.

2022-03-17 17:03 UTC, cgarvis commented
#18228 was closed by #18255.  So seems like this is not needed anymore.

2022-03-17 17:03 UTC, closed without merging