fix(pipelines): use CodeBuildStep role on the CodeBuildAction
aws/aws-cdk pull request #18293
Opened 2022-01-06 16:44 UTC by tobytipton

This fix should address the issue #18291 

fixes #18291 
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-01-06 17:05 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: e7b801898a8cc48a569b7d7fb040467802ad2b23
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=011dc38f-273d-4856-92b2-298adbdbf2e7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-01-06 19:28 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 66837bc3a440c48ddbdcb1a200e321c348a32f4c
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=50539eef-bb20-443f-8d76-4d89fd28a359%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-01-11 12:11 UTC, rix0rrr requested changes
These should be two different roles. Please add a separate configuration field.

But this actually doesn't seem like the right fix. Can we look at the `Maximum policy size of 10240 bytes exceeded` error a little closer ?

How many roles do we have in there? Why is the policy so large?

2022-01-12 13:05 UTC, tobytipton commented
I can change it to a `buildActionRole` property, if that makes better sense.

The `Maximum policy size of 10240 bytes exceeded` happens on the policy associated with the role which the Pipeline itself runs as because for each build role which is created the pipeline role needs to have the ability to assume that role, and because the [CodeBuildAction](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-codepipeline-actions.CodeBuildActionProps.html#role) will create a new role which means if you have to a lot of build actions to multiple stages that will cause those multiple roles to be added to the policy.

Scenario would be having a pipeline which deploys to multiple stages and each stage a code build action to do a test or change.

2022-01-12 16:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 1ad504f48f5ecf1df1bb3c3cb84c6a3d1a42f33e
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5aadae7a-99ea-47da-b6cb-9db5ab8b47e5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-01-24 20:18 UTC, saltman424 commented
@tobytipton if you are going to introduce a new property, you will need to either make that property default to using this.props.role, or else specify that property here (and possibly other places): https://github.com/aws/aws-cdk/blob/72941180a7188e5560a58f1509554ef038544ec4/packages/%40aws-cdk/pipelines/lib/codepipeline/codepipeline.ts#L677-L687

@rix0rrr As a note, it does seem that the intention, in at least the following case, is for them to be the same: https://github.com/aws/aws-cdk/blob/72941180a7188e5560a58f1509554ef038544ec4/packages/%40aws-cdk/pipelines/lib/codepipeline/codepipeline.ts#L807-L812

2022-03-31 13:44 UTC, rix0rrr commented
Is this change still necessary after https://github.com/aws/aws-cdk/pull/19114 ?

2022-03-31 13:56 UTC, saltman424 commented
@rix0rrr yes, but less often. If you have enough assets, you can still get too big of a policy document from having so many roles that the pipeline role needs to be able to assume. However, with #19114 those roles are all listed in a single policy statement rather than many, so the number of assets needed to hit the limit is now a lot larger, but I believe I hit the limit when I tried something similar to #19114 with about 150 or so assets.

2022-03-31 13:56 UTC, ekeyser commented
Thanks for checking. I'm planning on implementing the feature flag for #19114 today or tomorrow and then attempting to test this weekend. I'll update this ticket with my findings. I wanted to wait a few days.

2022-04-02 14:59 UTC, ekeyser commented
Yes, this change is still required. I deployed a stack using 1.150.0 with the  iam minimize feature flag and still get errors regarding policy size exceeding 10240 bytes. Additionally, the `role.without_policy_updates` method appears to have in influence on what role is used for the pipeline.

2022-04-05 18:43 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: d70c85ed8963af45c025f2b7a8e174e0bf55a6de
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4685ebd7-e916-44d1-ba38-b5beb7702f3e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-05-18 12:25 UTC, rix0rrr requested changes
I am actively working on https://github.com/aws/aws-cdk/pull/20189, which will remove the need for manual control of the action role to stay within policy sizes. 

We can still decide to merge this for environments where customers aren't allowed to create IAM roles, and they'll need a mechanism to pass in their custom roles.

2022-05-18 12:25 UTC, rix0rrr commented on packages/@aws-cdk/pipelines/lib/codepipeline/codebuild-step.ts
> +  readonly buildActionRole?: iam.IRole;
Please rename this to `actionRole`.

2022-05-18 18:54 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 19ced3d170e031c54da30a9d4e01fac99a6370d6
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4bd4df17-305a-4597-9538-d23bc3a33fa1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-05-19 13:18 UTC, rix0rrr approved these changes

2022-05-19 14:43 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: a9f937c7c3ef6024bf9af1c52f89b2641f1b8fea
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d5b122b9-fbe4-4e37-8d40-688f474a7e10%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-05-19 14:43 UTC, merged