feat(cloudfront): write lambda at edge with typescript
aws/aws-cdk pull request #18836
Opened 2022-02-05 07:10 UTC by mmuller88

----

As you can see I duplicated a lot from aws-lambda-nodejs/lib/function.ts . It would be great to get rid of that. Let me know how to proceed.

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-02-05 07:28 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 300095e06b229cd0c9bfc93638f2dc381afaeaed
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=12068e69-edf4-4de7-9b4f-9c23e3ab75c3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-05 07:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 28c1350775515c2b0381762b091b33ffe47c9ba4
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2cf9d0cf-8d1b-41f3-8404-a7ec48bb0da0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-05 18:49 UTC, mmuller88 commented
Will start writing the tests if that PR hits interested and after we are happy the the production code part.

2022-02-05 19:06 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 490325add118306259c3ffc48d7cb249fdd68472
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b99c8212-6694-4b30-815d-e06268fd781d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-08 16:08 UTC, mmuller88 commented
@comcalvi  can I have some feedback for how to get rid of those duplicates?

2022-02-17 07:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: aaef3819ba49ca58e1d33f3628c40f93707e9d7c
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=328dd5a8-a50d-4efb-a21c-b3220b2c9240%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-24 14:22 UTC, mmuller88 commented
@rix0rrr @comcalvi what is going on here?

2022-03-31 20:50 UTC, comcalvi requested changes
Thanks for the submission. This will need some changes before we can merge it in.

2022-03-31 20:50 UTC, comcalvi commented on packages/@aws-cdk/aws-cloudfront/lib/experimental/nodejs-edge-function.ts
> +}
Could we get a blank line at EOF?

2022-04-08 03:48 UTC, mmuller88 commented
@comcalvi thx a lot for looking into that. But please read and try to understand the description as that will help to answer most of your questions!

2022-04-10 14:25 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in BUILD FAILING for 21 days, and looks abandoned. It will be closed in 10 days if no further commits are pushed to it.

2022-04-11 22:55 UTC, comcalvi commented
@mmuller88 before we get into the details of the code duplication, please update the PR so that the code build job succeeds.

2022-04-20 07:33 UTC, closed without merging

2022-05-13 10:58 UTC, mmuller88 commented
@comcalvi I didn't feel well supported by you. You didn't understand or looked into much of what I was asking for or didn't understand it and clarified that. You are perhaps quite Junior so then I could understand that. A bit disappointed with you and AWS.

2022-05-13 11:13 UTC, skyrpex commented on packages/@aws-cdk/aws-cloudfront/lib/experimental/nodejs-edge-function.ts
> +function findEntry(id: string, entry?: string): string {
That's what NodejsFunction does, but the `findEntry` helper is not exposed for reuse. It makes sense to keep the same behavior for both NodejsFunction and NodejsEdgeFunction.

2022-05-13 11:14 UTC, skyrpex commented on packages/@aws-cdk/aws-cloudfront/lib/experimental/nodejs-edge-function.ts
> +  readonly entry?: string;
The NodejsFunction does the same as well: it looks for a specific entry file based on the file where the NodejsFunction is created.

2022-05-13 11:23 UTC, skyrpex commented
Similar issue here https://github.com/aws/aws-cdk/issues/14215

2022-05-14 15:26 UTC, mmuller88 commented
@comcalvi sorry for my stupid words. I think I was a bit frustrated and acted quite childish. I should have acted on your comments better and with more patience. I think I was frustrated that it took you so long for looking over my issue. But of course, the CDK team has lots to do. Again, I am very sorry.

2022-06-24 04:39 UTC, TheOrangePuff commented
@comcalvi @skyrpex I'm happy to take this PR on. This is a huge problem for us and is holding us back from upgrading to CDK 2.

2023-01-27 21:37 UTC, comcalvi commented
sorry all! I hadn't seen these since the PR was autoclosed. 

@mmuller88 @TheOrangePuff do you want me to re-open this PR?

2023-06-01 12:05 UTC, hugomallet commented
@comcalvi Yes please I think there's still no solution to this