chore(cdk cli): Disable Pretty Printing CloudFormation JSON Templates
aws/aws-cdk pull request #18886
Opened 2022-02-09 00:06 UTC by mckalexee

Currently the CDK pretty printing JSON files whenever it creates the CloudFormation templates. Since these files are only read by machines, the extra formatting only increases the file size.

This is a practical concern, since CloudFormation only allows template files to be 1mb in size. On a test run, I was able to reduce an output template size from 886kb to 495kb.

Since this change is small, ideally it could be backported to v1.

fixes #18694

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-02-09 00:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 52810aef8de4c06f6122e538c77f8ba5a60bfb21
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=dfa3fc7d-3c63-459a-a988-035b19d335dc%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-02-26 01:57 UTC, rix0rrr submitted a review, later dismissed
I'm not sure this change is safe. 

> Since these files are only read by machines, the extra formatting only increases the file size.

You make this assertion, but we don't actually know that. For one counterexample I know of: we send the template to CloudFormation. In the console, CloudFormation will show the template in the exact same format as it was sent to it.

So, if today someone relies on reading the CDK templates in the CloudFormation console, they would be in for a rude awakening if all their templates become unreadable all of a sudden.

And there are probably more cases that we don't even know about.

This change would need to be more selective.

2022-03-02 15:56 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 3e0ff7b4b1fb2e0c00049af4649dcb83c21f2fcb
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=99e21d4a-ff18-4fc9-bcf1-381383b78d02%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-02 15:56 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 3e0ff7b4b1fb2e0c00049af4649dcb83c21f2fcb
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8a1ca718-267b-4210-aa8b-d0bc58ac4e4f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-31 01:58 UTC, rigsbyt commented
@rix0rrr can you provide any more detail on what you think could make this workable? A cli option, ...?

As someone with stacks that are running into the template size limit, I will gladly sacrifice readability in the console for an easy ~50% reduction in my stack sizes...

2022-03-31 13:39 UTC, rix0rrr requested changes
The line you changed will not be hit in practice anymore (with any recent version of the CDK framework).

The location to change is this one: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/stack.ts#L796

Add property to `StackProps` like `readonly minimizeTemplate?: boolean;`, explaining the behavior and the trade-off (non-human readable template in CloudFormation console).

Don't forget to add a unit test.

2022-03-31 15:14 UTC, rigsbyt commented
Thanks @rix0rrr 

@mckalexee are you still interested in pushing this through? I can probably support if you're not interested or able.

2022-04-30 00:09 UTC, closed without merging

2024-02-26 16:47 UTC, Dan-Wuensch commented
Please re-open this. The 1 MB stack template limit is a huge issue for scaling CDK projects, especially as it pertains to API Gateway. Minification wouldn't solve the problem but is a nice bandaid