feat(aws-eks): support IPv6 for EKS clusters
aws/aws-cdk pull request #18917
Opened 2022-02-10 15:56 UTC by jagu-sayan

fixes #18423

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-03-04 14:33 UTC, otaviomacedo requested changes

2022-03-13 13:39 UTC, wlami commented
I'd like to contribute to this PR and do the suggested changes. Things I'd change are:
1. introduce an enum such as:
```/**
 * EKS cluster IP family.
 */
export enum IpFamily {
  /**
   * Use IPv4 for pods and services in your cluster.
   */
  IP_V4 = 'ipv4',
  /**
   * Use IPv6 for pods and services in your cluster.
   */
  IP_V6 = 'ipv6',
}
``` 

2. Add a dependency to `@aws-cdk/aws-sam` to `@aws-cdk/aws-eks` to get a lambda layer with a newer aws-cli so that eks ipv6 is supported. Currently the build breaks due to a missing dependency. Also an exception is required in `@aws-cdk/pkglint/lib/rules` as `@aws-cdk/aws-sam` is experimental. But as we're using only the auto-generated L1 constructs this should be fine.

3. The introduced check `if (props.serviceIpv4Cidr && props.ipFamily !== 'ipv4')` breaks the test `create a cluster using custom kubernetes network config` in `cluster.test.ts`. Although ipv4 is the default value, the check fails if `ipFamily` it is `null` or `undefined`. I'd propose to change the check to
```
    if (props.serviceIpv4Cidr && props.ipFamily == IpFamily.IP_V6) {
      throw new Error('Cannot specify serviceIpv4Cidr with ipFamily equal to IpFamily.IP_V6');
    }
``` 
and set `IpFamily.IP_V6` as a default value for `ipFamily`. Should this default be set in all cases (and rendered to CloudFormation), or only in case `serviceIpv4Cidr`is set?

2022-03-13 13:39 UTC, wlami commented
I'd like to contribute to this PR and do the suggested changes. Things I'd change are:
1. introduce an enum such as:
```/**
 * EKS cluster IP family.
 */
export enum IpFamily {
  /**
   * Use IPv4 for pods and services in your cluster.
   */
  IP_V4 = 'ipv4',
  /**
   * Use IPv6 for pods and services in your cluster.
   */
  IP_V6 = 'ipv6',
}
``` 

2. Add a dependency to `@aws-cdk/aws-sam` to `@aws-cdk/aws-eks` to get a lambda layer with a newer aws-cli so that eks ipv6 is supported. Currently the build breaks due to a missing dependency. Also an exception is required in `@aws-cdk/pkglint/lib/rules` as `@aws-cdk/aws-sam` is experimental. But as we're using only the auto-generated L1 constructs this should be fine.

3. The introduced check `if (props.serviceIpv4Cidr && props.ipFamily !== 'ipv4')` breaks the test `create a cluster using custom kubernetes network config` in `cluster.test.ts`. Although ipv4 is the default value, the check fails if `ipFamily` it is `null` or `undefined`. I'd propose to change the check to
```
    if (props.serviceIpv4Cidr && props.ipFamily == IpFamily.IP_V6) {
      throw new Error('Cannot specify serviceIpv4Cidr with ipFamily equal to IpFamily.IP_V6');
    }
``` 
and set `IpFamily.IP_V6` as a default value for `ipFamily`. Should this default be set in all cases (and rendered to CloudFormation), or only in case `serviceIpv4Cidr`is set?

2022-03-15 09:04 UTC, jagu-sayan commented
Thanks @wlami,
I wanted to do the asked modification today. But since you already do it in #19397, I close this PR.

Sadly, we can't see the result of CodeBuild, Gitpod not working very well and the setup is complex 🤔

2022-03-15 09:04 UTC, closed without merging