feat(assertions): Add the `hasNoXXX` methods.
aws/aws-cdk pull request #19330
Opened 2022-03-10 16:15 UTC by joe-king-sh

This PR adds `hasNoError`, `hasNoWarning`, and `hasNoInfo` methods to the Annotations assertions toolkit. 

- https://github.com/aws/aws-cdk/issues/18874
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-03-10 16:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 4d70a707c1b629955ea1661c86e4b8a12fd26b60
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4b5aa39e-d8e6-43f1-a9a2-3dd9d4f3f1ee%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-10 19:47 UTC, kaizen3031593 requested changes
Thanks for submitting this @joe-king-sh! Can you add a line or two about these APIs in the README?

2022-03-11 00:54 UTC, joe-king-sh commented
@kaizen3031593 
I added descriptions of `hasNoXXX` APIs.
If I have to go into more detail, please let me know.

2022-03-11 00:55 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 6acd7e9cb4d5a00ac58869a3d2de06217dacef34
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=048ce036-47d6-4ed4-b405-1beb1446a98d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-11 18:37 UTC, kaizen3031593 requested changes
Looks great @joe-king-sh! A few minor nits, along with changing the error message to be more descriptive.

2022-03-11 18:37 UTC, kaizen3031593 commented on packages/@aws-cdk/assertions/lib/private/messages.ts
> +  return `Stack has ${Object.keys(result.matches).length} messages.`;
```suggestion
  return `Expected no matches, but stack has ${Object.keys(result.matches).length} messages.`;
```

2022-03-11 18:37 UTC, kaizen3031593 commented on packages/@aws-cdk/assertions/test/annotations.test.ts
> +      expect(() => annotations.hasNoInfo('/Default/Qux', 'this is an info')).toThrowError(/Stack has 1 messages./);
```suggestion
      expect(() => annotations.hasNoInfo('/Default/Qux', 'this is an info'))
        .toThrowError(/Stack has 1 messages./);
```

2022-03-11 18:37 UTC, kaizen3031593 commented on packages/@aws-cdk/assertions/README.md
> +- `hasInfo()`, `findInfo()` and `hasNoInfo()`
```suggestion
- `hasError()`, `hasNoError()`, and `findError()`
- `hasWarning()`, `hasNoWarning()`, and `findWarning()`
- `hasInfo()`, `hasNoInfo()`, and `findInfo()`
```

2022-03-11 18:37 UTC, kaizen3031593 commented on packages/@aws-cdk/assertions/lib/private/messages.ts
> +  return `Stack has ${Object.keys(result.matches).length} messages.`;
In addition to the above change, I think we should also be returning the matched messages in the error message.

It's possible someone looks for `annotations.hasNoError('/Default/Fred', Match.anyValue())` and they should be able to know what error message they are getting.

2022-03-12 06:18 UTC, joe-king-sh commented
@kaizen3031593
Thank you for your review comments.
I have reflected it and would appreciate a recheck.

2022-03-12 06:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: ef3860a1fbd596a358f608dc828a7cd3ce9c572c
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0e513596-73da-46c4-a7b9-a7e1a3bffade%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-14 19:40 UTC, kaizen3031593 approved these changes
Looks great @joe-king-sh! I just added a bit of formatting to the error message.

2022-03-14 20:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 86972e2b89bdc429551adfeef34765a167d49251
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0e5cebc1-0fa4-4fac-ba03-e89c467bd9f8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-14 20:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: a6ac381d650bfdc1e9a008a02d7013ff21853143
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d28ecadc-3173-4f38-83cf-1d75292cce95%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-14 22:37 UTC, kaizen3031593 submitted a review, later dismissed

2022-03-14 23:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 287b114403e4f95cf140432334ec5f29fcf8b75a
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d565a538-e92e-4cb7-b82e-80fa2b81c7f8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-15 00:02 UTC, kaizen3031593 approved these changes

2022-03-15 00:02 UTC, merged