fix(cli): support attributes of DynamoDB Tables for hotswapping
aws/aws-cdk pull request #19620
Opened 2022-03-29 23:44 UTC by skinny85

Fixes #19421

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `cdk-integ` to deploy the infrastructure and generate the snapshot (i.e. `cdk-integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-03-30 00:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 4b37410a7e73036dfadecb2cd50a06839a4fad3f
* Result: FAILED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bcf8b7e4-1464-4a91-9307-3d93aae9ea53%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-31 13:52 UTC, rix0rrr requested changes
Please explain what's happening in the PR body. This is confusing me to no end.

Is it that we need to have every resource that could potentially be `{ Ref }`ed from a hotswappable resource in a table? Why do we need that table in the first place?

2022-03-31 23:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 4b37410a7e73036dfadecb2cd50a06839a4fad3f
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ad1a748b-159f-4582-bb48-a470a829b923%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-31 23:23 UTC, skinny85 commented
> Please explain what's happening in the PR body. This is confusing me to no end.
> 
> Is it that we need to have every resource that could potentially be `{ Ref }`ed from a hotswappable resource in a table? Why do we need that table in the first place?

That's fair @rix0rrr. I've updated the description of the PR, let me know if this is clear now, or if you need more information.

2022-04-01 00:56 UTC, comcalvi approved these changes

2022-04-01 08:28 UTC, rix0rrr commented
The maintenance burden this brings makes me uncomfortable... but I guess there's not really a way around it...

2022-04-01 08:29 UTC, rix0rrr approved these changes

2022-04-01 11:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 6510dfa70be0c98cf4f08035ff73235525a12f42
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=25beaa74-28a1-43de-8b36-738f8ac4b5c1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-04-01 11:20 UTC, merged