feat(aws-cdk): overridable deployment monitor interval
aws/aws-cdk pull request #19659
Opened 2022-03-31 18:50 UTC by relm923

Workaround for #5637

Add ability to override the default deployment monitor polling interval from `cdk.json` to avoid AWS rate limiting

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-03-31 19:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 34cfa45f2bbd6bf85f279dc25dc6db5f89113c64
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=23adf6a5-769a-4291-8e62-a6bcb8e7e86c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-03-31 22:35 UTC, rittneje commented
I can't tell whether this is supported or not from the PR, but for us being able to specify at the command line would be preferable to cdk.json.

2022-04-01 11:57 UTC, rix0rrr commented
I'm not a fan of pushing this to the customer. The tool should just work, not need fiddling with timeout options, that's a bad experience.

Having said that: I'm pretty sure we already have hefty retries on the CFN client, so it's surprising to me that it would still time out after all that. How many concurrent `cdk deploy`s are you running? And how sure are you it's really the CDK's `DescribeChangeSet` calls causing issues?

I see the following solutions:

* Zero-touch (preferred): right now if throttling occurs, the stack monitor keeps on querying at its regular pace. The `setInterval()` timer should slow down in response to throttling there as well, so that all monitors cooperate to settle on a sustainable pace (a la TCP congestion control). This requires disabling automatic retries and taking control of it in the monitor directly.
* User option: it seems that if are running enough concurrent CDK deploys to run into throttling issues, you're probably not interested in monitoring at all. How about adding a `--no-monitoring` flag instead? The CLI could create a topic and queue and listen for status messages to come in there. It's not very well documented what messages would come in over this topic, but it might just be all stack update messages, in which case we could still monitor as usual, just using a different event source.

2022-04-01 11:57 UTC, rix0rrr requested changes
See my previous comment

2022-04-01 12:50 UTC, relm923 commented
> I can't tell whether this is supported or not from the PR, but for us being able to specify at the command line would be preferable to cdk.json.

Currently it does not but would be trivial to add

2022-04-01 13:00 UTC, relm923 commented
> I'm not a fan of pushing this to the customer. The tool should just work, not need fiddling with timeout options, that's a bad experience.
> 
> Having said that: I'm pretty sure we already have hefty retries on the CFN client, so it's surprising to me that it would still time out after all that. How many concurrent `cdk deploy`s are you running? And how sure are you it's really the CDK's `DescribeStackEvents` calls causing issues?

I personally haven't hit the CF Rate Limiting in a while even with concurrent deployments. I added this change to address concerns raised on:
- https://github.com/aws/aws-cdk/pull/19378#pullrequestreview-926586195 
- https://github.com/aws/aws-cdk/issues/1973

My preference would be to move forward with https://github.com/aws/aws-cdk/pull/19378 as is and if rate limiting becomes a recurring issue we address it then.

> I see the following solutions:
> 
> * Zero-touch (preferred): right now if throttling occurs, the stack monitor keeps on querying at its regular pace. The `setInterval()` timer should slow down in response to throttling there as well, so that all monitors cooperate to settle on a sustainable pace (a la TCP congestion control). This requires disabling automatic retries and taking control of it in the monitor directly.

> * User option: it seems that if are running enough concurrent CDK deploys to run into throttling issues, you're probably not interested in monitoring at all. How about adding a `--no-monitoring` flag instead? The CLI could create a topic and queue and listen for status messages to come in there. It's not very well documented what messages would come in over this topic, but it might just be all stack update messages, in which case we could still monitor as usual, just using a different event source.

This change seems like it would require significantly more thought and testing. Is there a topic/queue per account (in the bootstrap stack)? Is there a topic/queue per stack? Need to ensure concurrent (unrelated) deployments in the same account do not break monitoring.

2022-04-02 04:39 UTC, rittneje commented
Honestly, as has been mentioned a few times, there is no reason for a throttling error (or really any error) from `DescribeStackEvents` to cause `cdk deploy` to fail. This is ultimately a UX nicety that has nothing to do with the actual deployment. It should just keep polling with an appropriate backoff. The exception to this is that once the stack in question finishing deploying (success or failure), cdk should give up polling after a few final tries.

This just leaves potential throttling on the stack deployments themselves. In this, I feel that such throttling errors should just be retried infinitely, with appropriate messaging to the user. The user is still free to abort at any time. Other errors however can still be fatal.

All of that said, until the aforementioned changes are made, allowing the user to adjust the polling interval (or even the retry count) is much better than doing nothing. Today we have our own custom solution for parallel deployment, and while rare, we do sometimes hit these rate limiting issues.

2022-04-06 23:29 UTC, relm923 commented
@rix0rrr let me know how you'd like to proceed here and with https://github.com/aws/aws-cdk/pull/19378

2022-04-30 00:10 UTC, closed without merging