chore: update dependabot and yarn-upgrade config
aws/aws-cdk pull request #19942
Opened 2022-04-15 22:13 UTC by kaizen3031593

Closes https://github.com/cdklabs/cdk-ops/issues/1942

The idea is to copy the configuration we already have for the default branch and target/checkout `v1-main` on June 1. 
It is a bit ugly but -- we are not likely to do this again to any other branch, and I can't think of a better way. I have tested the changes on my own forked repository and confirmed that we do indeed target/checkout a different branch under the new configuration.

Before this PR is merged, we should double-check and make sure that yarn-update has not diverged.

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-04-15 22:16 UTC, kaizen3031593 commented on .github/workflows/yarn-upgrade-v1main.yml
> +          ref: v1-main
This is 1 of 2 changes between this file and `yarn-upgrade.yml`.

2022-04-15 22:16 UTC, kaizen3031593 commented on .github/workflows/yarn-upgrade-v1main.yml
> +          ref: v1-main
This is the other. [`peter-evans/create-pull-request`](https://github.com/peter-evans/create-pull-request) creates a pull request to the branch checked out in the workflow.

2022-04-15 22:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 3ffc6c1d6e4e8042611a7db3ec755490db353145
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=af058bdc-5d08-4dff-85d8-d4838f6147b9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-04-19 18:50 UTC, madeline-k requested changes
@kaizen3031593, it looks like this PR accidentally has a bunch of unrelated changes in it? Integration tests, README, CfnSpec files, etc. Can you remove them?

2022-04-19 20:05 UTC, kaizen3031593 commented
@madeline-k I think the unrelated changes has to do with v1 not being in sync with v2. The forward merge got through to `v2-main` yesterday, so updated the PR and I think the changes have gone away

2022-04-19 20:40 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5ccd837915276393323b04cf23995cb61358cfae
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2cced33a-7a52-443c-bbf1-de0ea0e6fc48%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-04-25 14:00 UTC, madeline-k approved these changes
Approving, but please do not remove the "do-not-merge" label

2022-06-01 21:34 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0c2c071d64674996c1b3db09d40f541772d98b73
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8774a2e0-8a39-4f01-ba0f-4e581ea3fa56%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-01 21:47 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ea048173553e2ffc4245e05e92b45076d8273f99
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8d49c3bf-e1b5-47ad-8f88-29ccfebb10f4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-01 21:47 UTC, merged