chore: flag previous generation instance types
aws/aws-cdk pull request #20422
Opened 2022-05-19 19:09 UTC by PatMyron

https://aws.amazon.com/ec2/previous-generation/
https://instancetyp.es/

related: https://github.com/aws-cloudformation/cfn-lint/pull/2267

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-05-19 19:52 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: 7ee89b7ca8c00720e137ee7edaf8d1c5dc660784
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ef12280b-e6a5-4f56-b5b7-0f5682a962e6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-05-24 11:57 UTC, corymhall requested changes
I think we should just add the message without `@deprecated`. These instance types are not _actually_ deprecated, you can still create instances with these instance classes and I don't know of any plan to remove that ability. 

If we ever release a CDK v3 these would get removed.

2022-05-24 18:36 UTC, PatMyron commented
> you can still create instances with these instance classes and I don't know of any plan to remove that ability

true for the oldest ~half of AWS regions, but the newest ~half of AWS regions (since 2016) and all AWS regions going forward do not support `c3`/`m3`/`r3` instance type families


> If we ever release a CDK v3 these would get removed

Is it not possible to leave values deprecated in future major versions as well? There are other `@deprecated` values that would need to be kept like [Lambda runtime values that cannot be created or updated](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy) but can still exist in existing stacks:
https://github.com/aws/aws-cdk/pull/19938

2022-06-14 20:19 UTC, PatMyron commented
> I would support adding a warning

Is there another annotation to do that visibly other than `@deprecated`? Enabled editing my branch by maintainers, so feel free to switch / drop annotations as desired to merge 👍

2022-07-14 00:55 UTC, TheRealAmazonKendra commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-07-14 00:55 UTC, closed without merging