(aws-cloudwatch-actions): Add the possibility to have SSM Incident Action
aws/aws-cdk pull request #20553
Opened 2022-05-31 12:05 UTC by dosatos

This small PR will add SSM Incident action to cloudwatch alarm.
    The arn format was taken from the UI console (under Incident Manager Response Plan)

closes https://github.com/aws/aws-cdk/issues/20552

2022-05-31 12:50 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject89A8053A-LhjRyN9kxr8o
* Commit ID: a85da2577059f91b9e76a31834aef87622748937
* Result: SUCCEEDED
* [Build Logs](https://xuogv3vm9j.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6820f0a2-8c1e-4798-9923-318da8c3428b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-16 22:25 UTC, comcalvi requested changes
Just a few minor comments on this one.

2022-06-16 22:25 UTC, comcalvi commented on packages/@aws-cdk/aws-cloudwatch-actions/lib/index.ts
> +export * from './ssm-incidents';
```suggestion
export * from './ssm-incidents';
```
```suggestion
export * from './ssm-incidents';


```

2022-06-16 22:25 UTC, comcalvi commented on packages/@aws-cdk/aws-cloudwatch-actions/README.md
> +      'arn:aws:ssm-incidents::123456789012:response-plan/ResponsePlanName'
```suggestion
      'arn:aws:ssm-incidents::123456789012:response-plan/ResponsePlanName'
```
```suggestion
      'arn:aws:ssm-incidents::123456789012:response-plan/ResponsePlanName',
```

2022-06-16 22:25 UTC, comcalvi commented on packages/@aws-cdk/aws-cloudwatch-actions/README.md
> +      'arn:aws:ssm-incidents::123456789012:response-plan/ResponsePlanName'
```suggestion
      'arn:aws:ssm-incidents::123456789012:response-plan/ResponsePlanName',
```

2022-06-16 22:25 UTC, comcalvi commented on packages/@aws-cdk/aws-cloudwatch-actions/lib/ssm-incidents.ts
> +import * as cloudwatch from '@aws-cdk/aws-cloudwatch';
This logic should be moved into `ssm`.

2022-06-16 22:25 UTC, comcalvi commented on packages/@aws-cdk/aws-cloudwatch-actions/lib/ssm-incidents.ts
> +import * as cloudwatch from '@aws-cdk/aws-cloudwatch';
This logic should be moved into `ssm`.

2022-06-16 22:25 UTC, comcalvi commented on packages/@aws-cdk/aws-cloudwatch-actions/lib/ssm-incidents.ts
> +  }
```suggestion
  constructor(private readonly responsePlanArn: string) {
  }
```
```suggestion
  constructor(private readonly responsePlanArn: string) { }
```

2022-06-16 22:25 UTC, comcalvi commented on packages/@aws-cdk/aws-cloudwatch-actions/lib/ssm-incidents.ts
> +  }
```suggestion
  constructor(private readonly responsePlanArn: string) {
  }
```
```suggestion
  constructor(private readonly responsePlanArn: string) { }
```

2022-07-14 00:45 UTC, TheRealAmazonKendra commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-07-14 00:45 UTC, closed without merging

2022-07-19 16:12 UTC, dosatos commented
Sorry, I have been on a month long vacation and could not check-in earlier.
From what I see, this efforts has been carried over in this work: https://github.com/aws/aws-cdk/pull/21167