feat(pipelines): pass role to s3 source action
aws/aws-cdk pull request #20576
Opened 2022-06-01 17:44 UTC by daschaa

Fixes #20556 

Implements the role property for the `S3Source`, which is being passed down to the underlying `S3SourceAction`.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/master/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-06-01 18:11 UTC, kaizencc requested changes
Thanks @daschaa! Just some minor documentation nits but otherwise this looks good to go.

2022-06-01 18:11 UTC, kaizencc commented on packages/@aws-cdk/pipelines/lib/codepipeline/codepipeline-source.ts
> +   * method in the {@link ActionBindOptions.role} property.
```suggestion
   * The role that will be assumed by the pipeline prior to executing
   * the `S3Source` action.
```

Feel free to expand a tad further if you want, but in general, there's no need to go into the implementation detail in the documentation of a property. We also do this `role` property all over the CDK, so generally people should know the drill.

2022-06-01 18:57 UTC, daschaa commented
@kaizencc The PR linter is failing because it wants a change in the README file. Imho this is not needed here, what do you think?

2022-06-02 15:12 UTC, kaizencc approved these changes

2022-06-02 15:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0b91c6d97cae580b2f1f66928609ed522e60b35d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f87bf931-7708-4054-a440-93e6617082d6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-02 15:47 UTC, merged