chore(aws-ec2): add ICMPv6 protocol method
aws/aws-cdk pull request #20626
Opened 2022-06-06 05:21 UTC by philipmw

This allows creation of a security group rule that permits
ICMPv6.
----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-06-06 05:56 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f07b1e2431ac44fac92124f0f2eacd03c431fd9b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=50149463-ce0f-4ed7-8dc8-8ef2aa71c97c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-07 22:17 UTC, TheRealAmazonKendra requested changes
Thank you for your contribution. We cannot review PRs that do not include tests.

2022-06-07 23:32 UTC, philipmw commented
@TheRealAmazonKendra , my change has no logic. That file has no corresponding unit test file, and the surrounding (existing) methods have no unit tests. (Unless I missed them.) So, my PR is following the existing convention. Would you please reconsider? Else please advise on a meaningful unit test for this change.

2022-06-10 19:11 UTC, philipmw commented
@TheRealAmazonKendra - ping.

2022-06-13 23:59 UTC, TheRealAmazonKendra commented
The lack of tests for this file is something that needs to be remedied. We should not have an entire file of functions that are untested. In your case, you should write a test that verifies that your function creates the template you'd expect it to create. Note that the creation of a new function also requires an update to the README. Right now it says we don't have implementations for ICMP. I will however, exempt integ tests.

2022-06-14 00:12 UTC, TheRealAmazonKendra requested changes
The addition of new functions must always have tests. We shouldn't have approved these in the past without them. We need to ensure that the template generated as a result of this function is what you expect it to be. Note that the linter will also fail if no README update is made as well. [Port Ranges](https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk/aws-ec2#port-ranges) should be updated to reflect this change.

2022-06-16 17:28 UTC, philipmw commented
Thanks, @TheRealAmazonKendra . I updated the PR with a new unit test and an updated README.

2022-06-16 18:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 2a20ee985281481a690088bbe09882d4343044e6
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b4196d68-cb93-4d22-969a-b578da3881c2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-20 10:13 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/aws-ec2/test/port.test.ts
> +        expect(Port.allIcmpV6()).toEqual(new Port({
Let's check this against the template generated, not against the data structure itself.

2022-07-13 18:11 UTC, TheRealAmazonKendra commented
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2022-07-19 05:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 281779d5b93098a5946bc950fff7dbeda6bc89a9
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1701463c-6fdc-4bc3-aa11-83feb3b77c1a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-07-19 16:41 UTC, TheRealAmazonKendra approved these changes
My apologies for not being more clear on what I was asking for in the test. A unit test comparing the output to the produced template would have been sufficient but this is great too. It was probably just more work for you than I intended.

Still, thanks for your hard work on this and for contributing!

2022-07-19 17:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 4d1dbaca3a27bf3bcab4fca5bb3ca683a8f98c38
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=dc4b668c-ccc2-462f-80a2-52b98eebfb4b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-07-19 17:20 UTC, merged