feat(ecs-patterns): support runtimePlatform for fargate patterns
aws/aws-cdk pull request #20756
Opened 2022-06-15 21:20 UTC by michaeldrey

feat(aws-ecs-patterns): support runtime platform for fargate patterns

Using the implementation of runtimePlatform from [this previous commit](https://github.com/aws/aws-cdk/issues/17242), I have added this functionality to the L3 constructs for the fargate patterns. The [request](https://github.com/aws/aws-cdk/issues/18462) asked for this feature to be added to `QueueProcessingFargateService` and `NetworkLoadBalancedFargateService`, however I felt it should be added to the rest of the Fargate patterns.

I have added integration tests for each pattern with the runtimePlatform property and have added a section to the readme about how to use it.

closes #18462

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-06-15 21:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b5adca83e4696c40615ead40f26862594e9847a5
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4e3d0ce5-7427-49af-81a5-88839c5baf8a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-15 21:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ef322e81c3eec4791b1b5902b8cf1848fe6887ff
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ab7e3c5e-4f9f-4436-97a4-69dd42d2c13b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-15 23:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1d6a943b6aedd17325cc875033563dd983f0f62d
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a8dadf9f-e827-41f8-9c2b-28d938cb4892%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-16 16:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 766d217a750f26745a792b68ef944f6b841456b5
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9c35f6de-2592-4dc0-a930-2a6b963402d1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-16 16:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 063fee8ea2ac10a096f0a36b102adf94e7dab9c3
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d9413ce2-c7aa-4d48-9656-789d374d7776%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-16 17:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b05a3637502adfd952d37bf3e7e651125cbeb8de
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ef8ea0e6-6c8d-4c76-b239-ac7fea6371a0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-16 21:24 UTC, comcalvi requested changes
This property (along with all the others that these props share, like `cpu`) should be extracted into its own level of props that they all inherit, instead of having to just add this prop everywhere. @rix0rrr thoughts on this?

2022-06-16 21:24 UTC, comcalvi commented on packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
> +   * @default - undefined
```suggestion
   * @default undefined
```

2022-06-16 21:24 UTC, comcalvi commented on packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-multiple-target-groups-fargate-service.ts
> +   * @default - undefined
```suggestion
   * @default undefined
```

2022-06-16 21:24 UTC, comcalvi commented on packages/@aws-cdk/aws-ecs-patterns/lib/fargate/network-load-balanced-fargate-service.ts
> +   * @default - undefined
```suggestion
   * @default undefined
```

2022-06-16 21:24 UTC, comcalvi commented on packages/@aws-cdk/aws-ecs-patterns/lib/fargate/network-multiple-target-groups-fargate-service.ts
> +   * @default - undefined
```suggestion
   * @default undefined
```

2022-06-16 21:24 UTC, comcalvi commented on packages/@aws-cdk/aws-ecs-patterns/lib/fargate/queue-processing-fargate-service.ts
> +   * @default - undefined
```suggestion
   * @default undefined
```

2022-06-16 21:24 UTC, comcalvi commented on packages/@aws-cdk/aws-ecs-patterns/lib/fargate/scheduled-fargate-task.ts
> +   * @default - undefined
```suggestion
   * @default undefined
```

2022-06-16 23:06 UTC, michaeldrey commented
@comcalvi That makes sense. I can do that in this PR (imo scope creep this out a bunch), or create a new issue/PR for it.

Looking at the props, aside from `scheduled-fargate-task`, they're all the same with the exception of a few have the additional `securityGroups` prop. Condensing them into a base interface that they inherit will make all props consistent across the services as they each end up calling `FargateService`

`scheduled-fargate-task` already inherits from `scheduled-ecs-task` base so I don't believe that needs to be included (but i could be wrong)

2022-06-16 23:28 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: cdeeab5e1e401c4ca85eef12d15a39fea84135ec
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=049c1837-124e-4b2a-be09-502383725d61%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-17 18:11 UTC, rix0rrr requested changes

2022-06-17 18:11 UTC, rix0rrr commented on packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
> +   * @default undefined If not specified, `operatingSystemFamily` is LINUX and `cpuArchitecture` is X86_64
Do not use the value undefined in describing @default values. This is part of the language specification. Instead, use a dash (-) as the first word and describe the behavior of the infrastructure the construct exhibits when the value is not supplied (See [Contributing Guide, Defaults](https://github.com/aws/aws-cdk/blob/v1-main/docs/DESIGN_GUIDELINES.md#defaults)).

2022-06-17 23:40 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 529bcb1a839ec295111c3a607dbce69c65a88c43
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=72291ec6-4637-4888-83da-de1d4edee62d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-17 23:40 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 20bb332375e2e4604361c5e58bbd3313823796e6
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=01870570-1186-45f1-ae2d-a51f106df77c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-23 01:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b5843846cec0a928fe060e0c54bc2f68a240c857
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=dda24220-bc6b-4892-a0bb-5224c60eef79%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-28 05:37 UTC, comcalvi requested changes
This would be a good case for a separate PR. Feel free to assign the new PR to me, and please drop a comment on this PR linking the new one. Thanks!

2022-06-28 05:37 UTC, comcalvi commented on packages/@aws-cdk/aws-ecs-patterns/lib/fargate/application-load-balanced-fargate-service.ts
> +   * @default - If the property is undefined, `operatingSystemFamily` is LINUX and `cpuArchitecture` is X86_64
```suggestion
   * @default - `operatingSystemFamily` is LINUX and `cpuArchitecture` is X86_64
```

same for the others.

2022-07-05 19:08 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ade4fb3266450dd8c4460c5993d30c35ae73bd70
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=54d24cd9-5907-416f-a18a-55a2bba6658e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-07-05 19:09 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 030f6121bf3afd145ccad668b3b757fa0da98a84
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=33f455a3-9921-4758-af57-111d64711a59%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-07-19 01:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8a54ac0dcc6b5808064e0bf1a9071201af4dd948
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8331310d-7779-43d2-93a5-f87a3c9bb53c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-02 17:04 UTC, TheRealAmazonKendra commented
@michaeldrey I can't quite tell here if the items Calvin wanted extracted out into a separate PR have been done. Can you let me know and also let me know if this is ready for another round of reviews?

2022-08-03 04:57 UTC, michaeldrey commented
@TheRealAmazonKendra they haven't yet, ill work on getting a PR created for it this week

2022-08-03 16:43 UTC, TheRealAmazonKendra requested changes
Just assigning this to myself and putting this into changes requested so I get the alert when change have been made

2022-08-10 01:19 UTC, michaeldrey commented
New PR opened with this change + the shared props

2022-08-10 01:19 UTC, closed without merging