Update README.md
aws/aws-cdk pull request #20906
Opened 2022-06-28 20:14 UTC by josephedward

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-06-28 20:50 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 43912ad6892d1bdc7546294eed3fbcb7e9fe2934
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9e711e78-c0ab-49f7-9f5a-388187b19f8f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-29 21:11 UTC, comcalvi requested changes
Please update the title and description of this PR to explain why these changes need to be made. The `R5` enum is not wrong, and has the same value as `MEMORY5`. Also, please ensure that your PR title follows conventional commits. See `CONTRIBUTING.md` for details.

2022-06-29 21:31 UTC, peterwoodworth commented
@comcalvi it's because `R5` doesn't get converted through JSII, and so all the non TS examples are failing

https://github.com/aws/aws-cdk/issues/20747

2022-06-29 23:22 UTC, comcalvi commented
thanks @peterwoodworth

2022-06-29 23:24 UTC, comcalvi approved these changes

2022-06-30 00:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 78c0591b4b0f533a6d0b5bc369d4582186bf3da4
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6f3cd5f2-1697-41ad-b0b7-4b2a3c0544cd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-06-30 00:03 UTC, merged