fix(stepfunctions-tasks): EvaluateExpression does not support Context parameters and whole State/Context parameter
aws/aws-cdk pull request #20920
Opened 2022-06-29 16:40 UTC by Hazzard17h

Fixes #14777

Fixes #20882

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-06-29 17:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e7436284b73faeb085753a2641f5d55bfcecbb95
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=17dd954d-0acb-4790-85d9-7f83cec382ce%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-07-15 20:25 UTC, comcalvi submitted a review, later dismissed
Please update the PR description to describe the changes this PR makes.

2022-07-15 20:29 UTC, comcalvi commented on packages/@aws-cdk/aws-stepfunctions-tasks/lib/eval-nodejs-handler/index.ts
> +          new RegExp(`${whole && '(?<=\\()'}${escapeRegex(k)}${whole && '(?=\\))'}`, 'g'),
```
new RegExp(`${whole && '(?<=\\()'}${escapeRegex(k)}${whole && '(?=\\))'}`, 'g')
```

Why?

2022-08-06 00:09 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2022-08-06 14:54 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: de9fb10035c8ca6c627e60115ce420299f677db1
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c5482093-3c36-4936-aa22-3d37e7db5433%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-08 20:24 UTC, TheRealAmazonKendra requested changes
I'm concerned that this fix didn't impact any integration tests. This either means that we're missing test coverage here or that the fix didn't work as intended. I'm guessing it's the former so I'm going task for an integration test that covers this change.

2022-08-30 00:12 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2022-09-06 02:56 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-09-06 02:56 UTC, closed without merging