fix(cli): CLI errors when run as a non-existent user
aws/aws-cdk pull request #21018
Opened 2022-07-06 18:50 UTC by corymhall

The CDK home directory was being created in the users home directory,
but this causes an error if for some reason the user does not have a
home directory. Since the cdk home directory is only being used to
create a cache directory, this PR updates the location from being the
users home directory to being the os tmp directory.

I don't think there
is a strong reason why this directory needs to live in the users home
directory, but if there is I could also change this to have some
fallback logic instead.

fix #7937

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-07-06 19:25 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 4af8b7342c211c867b480717b1d743a09fc3ef5f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c08c6df5-460b-43e4-8eb6-58bd2f9caccd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-07-07 00:58 UTC, kylelaker commented
There are generally security concerns about having predictable and well-known directories in `/tmp`. `/tmp` is world readable and writeable in most cases and hosts may have multiple users. This could result in sharing `/tmp/.cdk` improperly or perhaps even permissions issues over that particular directory (allowing for a potential accidental DoS?). Even worse, not all users on a host may be friendly. CVEs have been issued to other tools for making similar decisions in the past, such as [CVE-2019-3881](https://nvd.nist.gov/vuln/detail/CVE-2019-3881) or [CVE-2020-10870](https://nvd.nist.gov/vuln/detail/CVE-2020-10870); and in an extreme case not applicable to the CDK today since no cached data seems to be executed, [CVE-2020-10174](https://nvd.nist.gov/vuln/detail/CVE-2020-10174). One could still imagine editing `notices.json` to insert additional text or improperly gleaning information from `account_partitions.json`; or even just accidentally having someone else own the file.

This feels like potentially making things harder (or less secure) for the vast majority of users to improve the use case where a user doesn't have a home directory. It may be preferable to use the user's home directory if available and to fallback to a temporary directory. And in that case, it's likely better to use [`fs.mkdtemp`](https://nodejs.org/docs/latest-v14.x/api/fs.html#fs_fspromises_mkdtemp_prefix_options). It'd linger after the fact if not cleaned up but at least it'd be fresh and unpolluted on startup. Something like [`$XDG_RUNTIME_DIR`](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) might be nice too but that's not especially portable outside of a Linux-y environment so `mkdtemp` may be reasonable.

2022-07-07 12:25 UTC, corymhall commented
> There are generally security concerns about having predictable and well-known directories in `/tmp`

I've updated it to have some fallback logic. It will first try and use the home directory and fall back to creating a tmp dir.

2022-07-07 13:00 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 42c6233c6bf0c3900f251ff503de8978c08e7688
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b4992b16-36bb-46b3-a765-ad3e7595a99e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-07-07 13:25 UTC, rix0rrr requested changes

2022-07-07 13:31 UTC, rix0rrr commented on packages/aws-cdk/lib/util/directories.ts
> +    : home || fs.mkdtempSync(path.join(tmpDir, '.cdk')).trim();
I stand corrected, should have read the thread.

2022-07-07 19:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 71fec5b5d184283c47dadcba481ffee5471e2e84
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=36fcfa6f-ed45-436e-b166-bdda28b9dff5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-07-07 19:30 UTC, merged