feat(aws-cloudwatch-actions): add ssm incidents as alarm action
aws/aws-cdk pull request #21167
Opened 2022-07-15 15:00 UTC by callumthomson

Finishes work originally contributed by @dosatos by addressing changes requested by @comcalvi in [#20553](https://github.com/callumthomson/aws-cdk/issues/20553)

closes [#20552](https://github.com/callumthomson/aws-cdk/issues/20552)

2022-07-15 15:43 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e002868538edd394eb348a270334ba899c00f66e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e975e1b6-6be6-4f59-98a3-6c0991d2907c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-07-15 17:00 UTC, TheRealAmazonKendra submitted a review, later dismissed
Overall this looks great! I think we'll need an integration test for this, though. Could you please add one?

2022-07-24 17:39 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b32adc6e86fa67a2d3b9e456d36b879cbccbbee6
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a55ef309-4eae-46e8-8d9c-fd5c966c0b7c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-07-26 10:48 UTC, callumthomson commented
I've added an integration test using `IntegTest`, but I think more is needed. Could you please let me know if this is a step in the right direction, @TheRealAmazonKendra ?

2022-07-26 11:05 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0b1fe8ba885bb43b61930cf37c98aef51b9c53ec
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e565ee4b-829b-4dde-9df4-0bd12df41045%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-07-27 21:26 UTC, TheRealAmazonKendra requested changes
@callumthomson Your integ test file is what we're looking for. We just need you to generate the expected template and assets. See our [integration test guide](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md).

I've also added a few comments inline regarding the specific errors in the build.

2022-08-09 19:55 UTC, callumthomson commented
@TheRealAmazonKendra I've added in the requested changes. Please let me know any further desired amendments.

2022-08-09 20:13 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 51ffb1099b0786fb2a99edc419844960d439c95a
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=360f1341-02e6-49c1-b583-7df00231f906%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-09 23:33 UTC, TheRealAmazonKendra requested changes
Just one comment inline but it also looks like your test `can use SSM Incident as alarm action` isn't working because the partition is a reference in the actual output, but you've used a literal in your expected output. We just need to get this test working so the build passes. If you have any questions about this, please let me know.

2022-08-09 23:33 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/aws-cloudwatch-actions/README.md
> +      'arn:aws:ssm-incidents::123456789012:response-plan/ResponsePlanName',
This needs to be updated with the new contract.

2022-08-10 10:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 43108d488c846938f6bfb759b4ddbe6339628cd0
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0e7dfb60-a001-45bb-a5bb-f1c78ad91496%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-10 10:20 UTC, callumthomson commented
@TheRealAmazonKendra that seems to be working now, but there appears to have been an error in `aws-appsync`:

```
@aws-cdk/aws-appsync: Verifying integration test snapshots...
@aws-cdk/aws-appsync: /codebuild/output/src184008709/src/github.com/aws/aws-cdk/packages/@aws-cdk/aws-appsync/lib/graphqlapi.js:371
@aws-cdk/aws-appsync:             throw Error('API key expiration must be between 1 and 365 days.');
@aws-cdk/aws-appsync:             ^
@aws-cdk/aws-appsync: Error: API key expiration must be between 1 and 365 days.
@aws-cdk/aws-appsync:     at GraphqlApi.createAPIKey (/codebuild/output/src184008709/src/github.com/aws/aws-cdk/packages/@aws-cdk/aws-appsync/lib/graphqlapi.js:371:19)
@aws-cdk/aws-appsync:     at new GraphqlApi (/codebuild/output/src184008709/src/github.com/aws/aws-cdk/packages/@aws-cdk/aws-appsync/lib/graphqlapi.js:188:40)
@aws-cdk/aws-appsync:     at Object.<anonymous> (/codebuild/output/src184008709/src/github.com/aws/aws-cdk/packages/@aws-cdk/aws-appsync/test/integ.auth-apikey.js:23:13)
@aws-cdk/aws-appsync:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
@aws-cdk/aws-appsync:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
@aws-cdk/aws-appsync:     at Module.load (internal/modules/cjs/loader.js:950:32)
@aws-cdk/aws-appsync:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
@aws-cdk/aws-appsync:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
@aws-cdk/aws-appsync:     at internal/main/run_main_module.js:17:47
```

2022-08-10 13:17 UTC, TheRealAmazonKendra commented
@Mergifyio update

2022-08-10 13:55 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c657434d69c922d4cac0fab66366259f462c136b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c7f8e308-43d3-4a5d-8b75-ec4f7440d2e5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-10 14:14 UTC, TheRealAmazonKendra approved these changes

2022-08-10 14:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ee7e8b867d4418794aee55084fce4f7906b48ee2
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=dd177464-12ce-4571-8021-788dca486a4f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-10 14:51 UTC, merged