feat(aws-lambda-event-sources): Validate that SQS Queue visibility timeout is larger than Lambda timeout
aws/aws-cdk pull request #21272
Opened 2022-07-21 22:16 UTC by Gtofig

This PR adds compile time check when SQS Queue is added as event source to Lambda to validate that AWS Lambda timeout is smaller that Queue visibility timeout. AWS CloudFormation deployment will fail if Lambda timeout is larger than Queue visibility timeout when adding Queue as an event source.

To enable this change, PR also makes two related changes:
- In (aws-lambda) module - expose `timeout` prop in `IFunction` interface and all implementations
- In (aws-sqs) module - expose `visibilityTimeout` prop in `IQueue` interface and all implementation

## closes https://github.com/aws/aws-cdk/issues/20527
----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-07-21 22:31 UTC, Gtofig commented
It's not clear to me if this is a (feat) or a (fix), but using (feat) results in a failed linter due to lack of README changes. I'm not sure this validation requires any README changes though. Please let me know how you want to proceed.

2022-07-21 22:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 38993f8b4922653057c43e33e651fb1c0b1e4c73
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=eafdeceb-60ba-4917-938f-0863fcbb5595%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-07-22 16:28 UTC, Gtofig commented on packages/@aws-cdk/aws-lambda-event-sources/lib/sqs.ts
> +      throw new Error(`Queue visibility timeout (given ${this.queue.visibilityTimeout.toSeconds()} seconds) must be larger than Lambda function timeout (given ${target.timeout.toSeconds()} seconds).`
Yes, this is already failing at deploy time

2022-07-22 21:34 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/aws-lambda-event-sources/lib/sqs.ts
> +      throw new Error(`Queue visibility timeout (given ${this.queue.visibilityTimeout.toSeconds()} seconds) must be larger than Lambda function timeout (given ${target.timeout.toSeconds()} seconds).`
Great, then fix is accurate for this.

2022-07-25 21:05 UTC, TheRealAmazonKendra submitted a review, later dismissed
Looks like this is going to need to update the integration tests to get this build passing. Please not that we cannot provide a meaningful review until the build is passing and our various checks are all succeeding. If you have any questions about these build failures, please let me know.

2022-07-26 07:56 UTC, Gtofig commented
Thanks. I will try to clean this up and resubmit later this week

2022-07-26 08:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: a13f067461235416394df550a9cf326d5cc0a08c
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=50ea9f13-3af9-48dc-8710-c192f286eeb8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-07-30 21:45 UTC, TheRealAmazonKendra requested changes
When you want to merge from main, please use `@Mergifyio update` because it won't dismiss my review/request for changes. That helps us know when we need to do another review or when we're still awaiting changes.

2022-07-30 21:45 UTC, TheRealAmazonKendra commented
@Mergifyio update

2022-07-30 22:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 66c77bcc699c75b975907dd067f7660b55572d8c
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=52781a96-d9a8-4d6c-b88f-5c913dbad8bf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-07-31 08:50 UTC, Gtofig commented
@TheRealAmazonKendra - I'm facing some difficulties. When I've tried running `yarn integ --update-on-failed` on `aws-lambda` package, but getting the following error in CloudFormation: `Replacement type updates not supported on stack with disable-rollback.`. 

Correct me if I'm wrong, but this looks unrelated to the changes I've made. Furthermore, I'm quite surprized that integration tests would need to be changed for my change. Can you help me understand how my change might have affected snapshots?

2022-08-02 00:26 UTC, TheRealAmazonKendra commented
> @TheRealAmazonKendra - I'm facing some difficulties. I've tried running `yarn integ --update-on-failed` on `aws-lambda` package, but getting the following error in CloudFormation: `Replacement type updates not supported on stack with disable-rollback.`.
> 
> Correct me if I'm wrong, but this looks unrelated to the changes I've made. Furthermore, I'm quite surprized that integration tests would need to be changed for my change. Can you help me understand how my change might have affected snapshots?

So, what's going on with the failing tests are that this construct is being used in another test package. That test, however, isn't setting the values in a way that meets the validation you've created here. If you can't update the tests with running that command, you can also manually edit the test inputs and expected output. Because this failure is showing up in `ecs-service-extensions`, you'll want to find the tests that set both timeouts to 30 and adjust the input values. Then run `yarn integ --update-on-failed` in that package and it should fix the output for you. It's possible that this construct is being used elsewhere as well so do the same for each package where the error gets thrown. If you get more permission issues, let me know and I can help update the tests.

2022-08-21 00:10 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the BUILD FAILING state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2022-08-28 00:12 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-08-28 00:12 UTC, closed without merging