fix(devcontainer): only do yarn install post create (fixes #21399)
aws/aws-cdk pull request #21403
Opened 2022-08-01 07:13 UTC by Xcalizorz

----

### All Submissions:

Fixes #21399

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-08-01 07:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 842da10b7d6cfc6f1f5682137b97b9b2c73beba6
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a0e74600-ee63-44aa-8f1f-5877a66db2be%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-01 15:03 UTC, TheRealAmazonKendra requested changes
Please make sure that your PR title confirms to the conventional commit standard (fix, feat, chore) and that it is written in a style that will reflect correctly in the change log (See [Contributing Guide, Pull Requests](https://github.com/aws/aws-cdk/blob/v1-main/CONTRIBUTING.md#step-4-pull-request)).

Additionally, please make sure that your PR body describes the problem the PR is solving, and the design approach and alternatives considered. Explain why the PR solves the problem. A link to an issue is helpful, but does not replace an explanation of your thought process

2022-08-02 10:08 UTC, mrgrain commented
@Xcalizorz I'm not sure this is the problem here.

`yarn build` is a shorthand for `./build.sh` and the first meaningul thing that script does is to run `yarn install`...
See: https://github.com/aws/aws-cdk/blob/14da458e0bf44d3e2516870ca99a331ba492817c/build.sh#L48

2022-08-02 10:38 UTC, Xcalizorz commented
> @Xcalizorz I'm not sure this is the problem here.
> 
> `yarn build` is a shorthand for `./build.sh` and the first meaningul thing that script does is to run `yarn install`... See:
> 
> https://github.com/aws/aws-cdk/blob/14da458e0bf44d3e2516870ca99a331ba492817c/build.sh#L48

You're right, I'll close this PR. It seems to be a local issue. Thanks!

2022-08-02 10:38 UTC, closed without merging