fix(aws-ecs): include iam policy generation for firelens cloudwatch_logs log driver
aws/aws-cdk pull request #21457
Opened 2022-08-04 03:27 UTC by rhermes62

### Notes 📝

We recently migrated our FireLens log driver from using `cloudwatch` to using the recommended `cloudwatch_logs`.

`cloudwatch_logs` is the newer and more high performance version as detailed in this guidance from AWS https://github.com/aws/amazon-cloudwatch-logs-for-fluent-bit#new-higher-performance-core-fluent-bit-plugin

However, when doing that, we lost the automatic configuration of the IAM policies to write to CloudWatch which broke our logging.

This PR fixes that.

### Testing 🧪

Added explicit unit tests for this

----

### All Submissions:

* [ ✅] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-08-04 03:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: a00fc75c2895575d72f6cb3999939338db986f35
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2196c853-fbe4-41b1-9337-3429cc573030%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-04 03:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c137fba75c3e86157cba8d2674d48a2bee4a21fa
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5e70d26c-424d-40c6-96bc-2b3efc7669a4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-04 04:34 UTC, TheRealAmazonKendra requested changes
First let's get this build succeeding. I put a correction below that is causing the failure. 

Additionally, please make sure that your PR title confirms to the conventional commit standard (fix, feat, chore) and that it is written in a style that will reflect correctly in the change log (See [Contributing Guide, Pull Requests](https://github.com/aws/aws-cdk/blob/v1-main/CONTRIBUTING.md#step-4-pull-request)). A fix should state the problem that is being addressed, not the solution being implemented.

We'll provide further feedback once we get a working build.

2022-08-04 04:34 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/aws-ecs/test/firelens-log-driver.test.ts
> +    const template = Template.fromStack(stack)
```suggestion
    const template = Template.fromStack(stack);
```

2022-08-04 15:53 UTC, TheRealAmazonKendra submitted a review, later dismissed
This looks good but I'm concerned that this issue wasn't caught by our current integ test coverage. I think we need an integration test for this use case. Can you please add one?

2022-08-04 15:57 UTC, rhermes62 commented
Works with me! None of these plugins have integ coverage AFAIK.

I will add for the `cloudwatch` and `cloudwatch_logs` plugins since those are the primary focus of the PR.

Should I also add them for the `firehose` and `kinesis` options which are also missing integ coverage? Or is that scope creep/more suitable for a separate chore PR?

2022-08-04 16:10 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0df8f01ed47c218847629070548b1edbd3d1c1cd
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f8acdfe3-0ca6-410d-8c96-4a4069e9bc21%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-04 16:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 22eaf9c23a6ed13f929b1d7151659f891125999f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1f870f68-b1df-4921-b77a-9bcacae9cf18%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-04 18:50 UTC, TheRealAmazonKendra commented
> Works with me! None of these plugins have integ coverage AFAIK.
> 
> I will add for the `cloudwatch` and `cloudwatch_logs` plugins since those are the primary focus of the PR.
> 
> Should I also add them for the `firehose` and `kinesis` options which are also missing integ coverage? Or is that scope creep/more suitable for a separate chore PR?

I will never turn down extra test coverage! However, let's do the extra ones in a separate PR so we can get this one merged faster.

2022-08-10 00:42 UTC, TheRealAmazonKendra commented
@rhermes62 Just to clarify, I'd like the tests for `cloudwatch` and `cloudwatch_logs` added to this PR and the others in a separate PR. After reading my own response, I wasn't sure if it sounded like I wanted them all in a separate PR or not.

2022-08-10 00:44 UTC, rhermes62 commented
Makes sense and will do! Will try and squeeze in those extra tests tonight or tomorrow

2022-08-10 02:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: adf336c40cf78fff8952cc1e46841691485c2d4b
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f078f7fd-eb69-41ed-8cf0-63ffcbcd40f2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-10 02:21 UTC, rhermes62 commented
Still working on getting those cleaned up. Builds in flight likely to fail.

These first integ tests for aws-cdk written so learning how this repo does them. I had historically always just used jest's snapshotting feature + the aws-cdk-lib/assertions's Template feature to write snapshot tests like `expect(Template.fromStack(stack).toJSON()).toMatchSnapshot();`.

2022-08-10 02:52 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 9fc41e9e905e69bf085146da3e55094b8dca2cf4
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4bda7eae-851e-485c-9f9b-35905a5e28dd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-10 03:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1c85c546497fdde555047d9f2e95ddedf904855d
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bd051924-5aa0-4b4f-9a35-9c89695838b7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-10 03:23 UTC, TheRealAmazonKendra commented
> Still working on getting those cleaned up. Builds in flight likely to fail.
> 
> These first integ tests for aws-cdk written so learning how this repo does them. I had historically always just used jest's snapshotting feature + the aws-cdk-lib/assertions's Template feature to write snapshot tests like `expect(Template.fromStack(stack).toJSON()).toMatchSnapshot();`.

No worries! If you need any help troubleshooting, please let me know. I'm happy to assist.

2022-08-10 03:32 UTC, TheRealAmazonKendra commented
@rhermes62 Actually, I just took a look and I can make myself useful here immediately. Just run `yarn integ --update-on-failed integ.firelens-log-driver.js` and it will update your test folder to the correct name. I ran it locally and the new test succeeds so I don't think you should have any issue on your end.

2022-08-10 03:35 UTC, TheRealAmazonKendra requested changes
Just putting this back in changes requested so I see when that update has been made.

2022-08-10 03:36 UTC, rhermes62 commented
Sounds good! Thank you! We normally don't have direct access/credentials to do things like `cdk deploy` to AWS accounts since we have strict release processes/security so I was trying to find one to deploy to😂😅

I was about to create a temp account just to do test deploy to in order to generate the artifact files to get the integ to pass.

2022-08-10 04:02 UTC, TheRealAmazonKendra commented
> Sounds good! Thank you! We normally don't have direct access/credentials to do things like `cdk deploy` to AWS accounts since we have strict release processes/security so I was trying to find one to deploy to😂😅
> 
> I was about to create a temp account just to do test deploy to in order to generate the artifact files to get the integ to pass.

The test will need to deploy when you do it that way. It actually runs the test with deployment and deletion of resources. If you have issues doing that. I can upload the output for you. Just let me know if that's needed.

2022-08-31 12:27 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2022-09-08 00:11 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-09-08 00:11 UTC, closed without merging