chore(init-templates): fix import of init templates
aws/aws-cdk pull request #21493
Opened 2022-08-07 23:10 UTC by lune-sta

TypeScript init-templates are not imported `cdk.Duration`.
Fixed to avoid confusion for those new to writing CDK.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-08-07 23:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c0c1a26790522f6ea3e0ca6bf57fe6a32ee66a07
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f3308c3c-b9df-4eb2-b009-3ca89b2dad2d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-08 09:45 UTC, mrgrain commented
Hi @lune-sta thanks for your contribution. Please make sure you have working tests and added or updated tests where appropriate.

I support the motivation behind this change. Currently the created template would run, with your change it won't anymore since `Duration` is unused. I think the right way to solve this will be to move the `core` imports to `import * as cdk from 'aws-cdk-lib'`. We use that elsewhere in the templates already and [recommend it for contributions](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#recommendations) to the libraries as well.

2022-08-08 10:42 UTC, lune-sta commented
@mrgrain Thank you.
I modified it to use `import * as cdk from 'aws-cdk-lib'`.
The test is passing locally, let me check CI.
```
Test Suites: 59 passed, 59 total
Tests:       510 passed, 510 total
Snapshots:   0 total
Time:        18.386 s, estimated 22 s
Ran all test suites.
Tests successful.
```

2022-08-08 11:03 UTC, mrgrain requested changes

2022-08-08 11:09 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8364321c94de8075d785296d100dc61da1238552
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=dc908879-189b-4834-9c35-9b9fbcf7ae44%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-08 11:11 UTC, mrgrain commented
>The test is passing locally, let me check CI.

Looks like this was blip in CI.

2022-08-08 11:42 UTC, lune-sta commented on packages/aws-cdk/lib/init-templates/app/typescript/lib/%name%-stack.template.ts
>  import { Stack, StackProps } from 'aws-cdk-lib';
Understood, Thanks.

2022-08-08 12:17 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: bbeccdb1003ca84142a39755bce10e514e5cd822
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1443cdc7-d0f7-4286-b62d-9122aaf791f5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-08 13:51 UTC, mrgrain approved these changes

2022-08-08 14:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: afb5123697c443148f952d5ab95f1a017235f40b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7d80a5db-9650-4d39-aba3-58f57550ff6a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-08 14:29 UTC, merged