bug(aws-batch): LaunchTemplates with network interfaces do not work with ComputeEnvironments
aws/aws-cdk pull request #21579
Opened 2022-08-12 11:55 UTC by tcutts

closes #21577 

HPC Batch applications frequently require Elastic Fabric Adapters for low-latency networking.  Currently, the `ComputeEnvironment` construct always automatically defines a set of `SecurityGroupIds` in the CloudFormation it generates, and this prevents the stack deploying if the LaunchTemplate contains network interface definitions; Batch does not allow SecurityGroups at the `ComputeEnvironment` level if there are network interfaces defined in the `CfnLaunchTemplate`.

One could allow the user to specify `computeResources.securityGroups: []`, but I don't think that makes for very clear code; it's confusing to the reader, and currently still gets passed through to CloudFormation as a set property with an empty list, and Batch still complains.

I also considered making the empty list a special case; if the user does the above, then we just don't emit SecurityGroupIds in the resulting CloudFormation.  While that doesn't break any existing test cases, and I don't think cases with empty lists are terribly meaningful in the real world, but it would constitute a breaking change, I think.

My solution to this was to allow the user to specify an enum as an alternative to the list of securityGroups.  This enum, `ComputeEnvironmentSecurityGroups` has two values, `NONE` and `AUTOMATIC`.  `AUTOMATIC` has exactly the same behaviour as currently takes place if the user does not define `securityGroups` at all.    Possibly this should be called `AUTOCREATE` instead?

This allows the user to write very clear code about what's going on, and solve the original EFA problem thus:

```ts
declare const vpc: ec2.Vpc;

const efaSecurityGroup = new ec2.SecurityGroup(stack, 'EFASecurityGroup', {
  vpc,
});

const launchTemplateEFA = new ec2.CfnLaunchTemplate(stack, 'LaunchTemplate', {
  launchTemplateName: 'LaunchTemplateName',
  launchTemplateData: {
    networkInterfaces: [{
      deviceIndex: 0,
      subnetId: vpc.privateSubnets[0].subnetId,
      interfaceType: 'efa',
      groups: [efaSecurityGroup.securityGroupId],
    }],
  },
});

const computeEnvironmentEFA = new batch.ComputeEnvironment(stack, 'EFAComputeEnv', {
  managed: true,
  computeResources: {
    securityGroups: batch.ComputeEnvironmentSecurityGroups.NONE,
    vpc,
    launchTemplate: {
      launchTemplateName: launchTemplateEFA.launchTemplateName as string,
    },
  },
});
```

I have written both unit tests for the new enum and a new integration test for this use case.

----

### All Submissions:

* [yes] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [no] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [yes] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [yes] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-08-12 12:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8a9dbf52a9ff3525bc204a73606fbe3310b1190e
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c6f285fb-33af-4501-af96-d235ed5e0bd7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-12 12:35 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6eb2196320cad2fc189c0bd50bb4098386ee8421
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7c868d25-a260-433a-a73d-8a330d3975e8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-12 13:25 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0a404626b2a10682fc9b83a458bc88f37c53e6fb
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a744f20e-8bd5-4118-86bb-48505b131bc4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-12 16:28 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 954d2a61055ddbf954f0a6f81f694eb133a8637e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b578f3aa-116f-498e-84aa-177495c433c4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-15 09:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 26a0367b37593c323c3190b4f878903535153f26
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9efb99ed-d68f-490f-8ad6-8b0220f03a8e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-15 12:29 UTC, corymhall requested changes
@tcutts thanks for taking the time to create this PR! Unfortunately the union type is not currently supported in CDK so I don't think this solution will work.

Without looking into this too much, I think the ideal solution is probably a much bigger effort. I'm thinking that we need to:

1. Add support for network interfaces in the L2 ec2.LaunchTemplate construct.
2. Update the batch.ComputeEnvironment construct to take a `ILaunchTemplate` instead of the name/id.
3. Check the `ILaunchTemplate` for whether the `ComputeEnvironment` needs to create any security groups.

2022-08-15 12:29 UTC, corymhall commented on packages/@aws-cdk/aws-batch/lib/compute-environment.ts
> +  readonly securityGroups?: ec2.ISecurityGroup[] | ComputeEnvironmentSecurityGroups;
Unfortunately we can't use union types due to limitations with JSII.

2022-08-15 15:31 UTC, tcutts commented
> On 15 Aug 2022, at 13:30, Cory Hall ***@***.***> wrote:
> 
> 
> @corymhall requested changes on this pull request.
> 
> @tcutts <https://github.com/tcutts> thanks for taking the time to create this PR! Unfortunately the union type is not currently supported in CDK so I don't think this solution will work.
> 
> 

Ah, I didn’t know that. It did feel a bit dirty.  :-)

> Without looking into this too much, I think the ideal solution is probably a much bigger effort. I'm thinking that we need to:
> 
> Add support for network interfaces in the L2 ec2.LaunchTemplate construct
> Update the batch.ComputeEnvironment construct to take a ILaunchTemplate instead of the name/id.

That would be a breaking change, wouldn’t it?  I suppose the API is currently experimental, so that doesn’t matter quite so much...

> Check the ILaunchTemplate for whether the ComputeEnvironment needs to create any security groups.

… I agree with this, because the combination of all three steps allows us to put a validation in.

> 
> In ***@***.***/aws-batch/lib/compute-environment.ts <https://github.com/aws/aws-cdk/pull/21579#discussion_r945668910>:
> 
> > @@ -142,7 +161,7 @@ export interface ComputeResources {
>     *
>     * @default - AWS default security group.
>     */
> -  readonly securityGroups?: ec2.ISecurityGroup[];
> +  readonly securityGroups?: ec2.ISecurityGroup[] | ComputeEnvironmentSecurityGroups;
> Unfortunately we can't use union types due to limitations with JSII.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/aws/aws-cdk/pull/21579#pullrequestreview-1072575084>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AASQ7CWR6NMK7FQZDAJXUDDVZIZ4VANCNFSM56LNXTZQ>.
> You are receiving this because you were mentioned.
>

2022-08-15 16:40 UTC, tcutts commented
This is potentially an enormous can of worms.  CDK has no abstraction for networkInterfaces at all, anywhere.  That needs to be done first before anything else that ought to support them can do so (Instance, AutoScalingGroup).   This is way beyond by relatively hobbyist ability to implement.

2022-08-15 16:47 UTC, tcutts commented
What I could do is revert to a simpler change, which is to change what happens if the user specifies `[]` as the list of security groups.  If, in that case, we emit no SecurityGroupIds line in the resource, we still fix the bug, and we've no longer created the unsupported union type.  That does leave us with slightly messy and misleading end user code code:

```ts
const computeEnvironmentEFA = new batch.ComputeEnvironment(stack, 'EFAComputeEnv', {
  managed: true,
  computeResources: {
    securityGroups: [],
    vpc,
    launchTemplate: {
      launchTemplateName: launchTemplateEFA.launchTemplateName as string,
    },
  },
});
```

which I don't like very much, but would achieve the desired outcome.  Arguably, ComputeEnvironment needs updating to do this anyway, because emitting an empty list in a set SecurityGroupIds property doesn't seem to be the right behaviour to me.

2022-08-16 12:25 UTC, corymhall commented
> What I could do is revert to a simpler change, which is to change what happens if the user specifies `[]` as the list of security groups. If, in that case, we emit no SecurityGroupIds line in the resource, we still fix the bug, and we've no longer created the unsupported union type. That does leave us with slightly messy and misleading end user code code:

I agree that this isn't what we want, but since this package is experimental and given the complexity of the preferred solution I think I'm fine with this as an interim solution.

2022-08-16 14:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 248f89c1b5958453e188541e65709c20ce110815
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2f55cae8-70a7-4d53-a3fe-a01ea3ce9080%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-16 14:33 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 56ac6b1255a259d6f348e9f7de2a283b97c8e047
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5d0d30a5-8cbf-40fb-9b35-0f002b9a2a4d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-17 14:01 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 97cff0c898903835b1028338e50ac31d44bbf11f
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b006b13e-e045-4232-94cf-a9c7aba58a0d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-17 14:12 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3e9c4c37b8d151c75f927af1fc1cb7c55d7b7705
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c04daf5b-ee3f-4682-9350-d724162acdfe%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-18 09:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 633d23304e5e34ff70da652ea1dbf6d7adc7f8c8
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4a253fcb-b374-48e8-91f7-50e06a892978%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-18 12:19 UTC, corymhall requested changes
Looks good! just 1 minor change requested.

2022-08-18 12:19 UTC, corymhall commented on packages/@aws-cdk/aws-batch/README.md
> +    useLaunchTemplateNetworkInterface: true,
Can you move this property into the `launchTemplate` property? I think it makes sense to provide it as part of the launch template information.

2022-08-18 12:19 UTC, corymhall commented on packages/@aws-cdk/aws-batch/lib/compute-environment.ts
> +   * @default - Create a single default security group.
Good catch!

2022-08-18 12:19 UTC, corymhall commented on packages/@aws-cdk/aws-batch/lib/compute-environment.ts
> +          throw new Error('LaunchTemplate network interfaces must not be set for Fargate compute environments');
👍

2022-08-18 13:52 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 9b6fac32d80b71399357fc5e4dd6b612d9d8581f
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=305967eb-c72b-4d28-99da-1725a674a791%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-18 14:14 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 428073cb6cce259173c8735ed1b9fe1d3bc39be8
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c37a4607-213c-49a3-9a6c-b86eaab7a38a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-18 14:21 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 56f9bc5976ce86bff16ba37abfd4dc2080f3c24b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4d250b38-8fc2-440e-9251-8c99c80e14d5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-18 14:27 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 68d2516af6bdfbeb48c908995749a7cea7c7e12a
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a86fc64e-c779-49fa-9952-a5b8a4a7f882%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-23 15:40 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6ef8b8641ff008ded0ab17d0a6db34dff0d8feb7
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=32dedcee-6134-44ba-bdfd-887ff0eef276%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-23 18:26 UTC, corymhall approved these changes

2022-08-23 18:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0d557b41fe2af787c58a4868df81b034b08c913d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d4b839b1-84d3-4773-be67-13ff8a135435%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-23 19:21 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6d3668a6ca41e46a92be55acedb57df36f9abebd
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d685e76e-2c8a-45db-8dbf-83f10a0d4b83%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-23 19:21 UTC, merged