fix(cli):  arg tags key/value with two equal signs
aws/aws-cdk pull request #21603
Opened 2022-08-15 12:01 UTC by Th3nn3ss

closes #21003

If you need a tag with a key value pair such as

Key : MyKey
Value : MyValue=Something

The stack will have a key value pair that shows

Key: MyKey
Value: MyValue

This fix ensures that the value of the tag will be MyValue=Something

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-08-15 12:38 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d961f9f92b40815c096643caff26a137dc4ffdbe
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5686ceab-165f-45f3-a4ba-f5721f2f28df%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-15 15:25 UTC, TheRealAmazonKendra requested changes
Thank you for your contribution! We need some sort of test for this change.

2022-08-15 15:29 UTC, Th3nn3ss commented
yes @TheRealAmazonKendra. I am having issues passing tags to the `Settings.fromCommandLineArguments` method. I keep getting **tags** as Undefined.  I even tried building a stack and passing Tags to it, but when I inspect the object it's still undefined. I need help with how to write the tests.

2022-09-06 00:09 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2022-09-13 00:11 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-09-13 00:11 UTC, closed without merging