fix(cli): `--exclusively` leads to 0 stacks being selected
aws/aws-cdk pull request #21663
Opened 2022-08-18 16:27 UTC by rix0rrr

The new concurrency logic introduced in #20345 was checking for all
dependencies to a stack to have been deployed previously for the stack
to be unblocked, but if not all stacks are selected, they will never
become unblocked.

Because there was no check on being "complete" at the end, this silently
leads to no stacks being deployed and the CLI no-opping.

Fix by only waiting for selected stacks among the dependencies, and
adding a safeguard at the end to make sure we deployed all stacks
successfully (or failed halfway through).

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-08-18 16:28 UTC, Naumel commented on packages/aws-cdk/lib/deploy.ts
> +    throw new Error(`The following stacks never became unblocked: ${neverUnblocked.join(', ')}`);
Should we add the `Cut us a ticket` prompt too?

2022-08-18 17:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 151d61e122367aaa2ba1f234f540cff19dadcad4
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=38527ad0-f9dd-4073-a3c5-1c3825637279%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-18 23:52 UTC, relm923 commented
@rix0rrr @Naumel happy to take a look at this edge case too. Please let me know if I can help restore the concurrency logic

2022-08-19 02:14 UTC, TheRealAmazonKendra requested changes
Definitely want some tests here.

2022-08-19 09:39 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 64f2247ef7ba6514bba4af03e8e4b3f26c224d4b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=32d4e3fb-dc88-4524-86f9-c802756c6eb3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-19 10:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 742e345b0bf676622da66c958f8131fbcfffde6d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2a54655d-04fb-4520-a463-e6f72edddef6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-25 12:38 UTC, closed without merging