feat(core): `Fn::ToJsonString` intrisic function
aws/aws-cdk pull request #21749
Opened 2022-08-25 09:32 UTC by jogold

Add support for `Fn::ToJsonString`, the `AWS::LanguageExtensions`
transform is automatically added.

See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ToJsonString.html

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-08-25 09:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d7262a7cccdc6abcc08bfcb24c91cc27253cb0d7
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b7e9d9f3-cc54-49b6-bf6b-3dc951d6d283%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-25 13:05 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8bed7f4aa35db7fc34fa4deb1e4e6922c534472c
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7ae4ca63-52ee-4c9f-9522-da9a8acd81c5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-25 13:08 UTC, jogold commented on packages/@aws-cdk/core/lib/cfn-fn.ts
> +  public static len(array: any): number {
cannot do `public static length` here.

```
Static property 'length' conflicts with built-in property 'Function.length' of constructor function 'Fn'.ts(2699)
```

2022-08-25 13:17 UTC, jogold commented
Needs `pr-linter/exempt-integ-test`

2022-08-25 13:43 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ccb521fc84347bcb94d485d7f33d409f3a04376d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b2924145-e4f7-4aee-aae9-55dd643d1fb6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-29 01:58 UTC, TheRealAmazonKendra requested changes
Can you explain why you think that integ tests aren't needed here? I think it would probably be good to add that test coverage.

2022-08-29 07:34 UTC, jogold commented
> Can you explain why you think that integ tests aren't needed here? I think it would probably be good to add that test coverage.

There are currently no integ tests in `core`, and I believe this would create a circular dependency `@aws-cdk/core > @aws-cdk/integ-tests > @aws-cdk/core`. Also I'm not sure it would bring much added value for a CF syntax.

2022-08-30 17:05 UTC, TheRealAmazonKendra commented
> > Can you explain why you think that integ tests aren't needed here? I think it would probably be good to add that test coverage.
> 
> There are currently no integ tests in `core`, and I believe this would create a circular dependency `@aws-cdk/core > @aws-cdk/integ-tests > @aws-cdk/core`. Also I'm not sure it would bring much added value for a CF syntax.

Hmm. I don't like that we don't have any tests for core, but adding them would very much be out of scope for this PR.

2022-08-30 17:05 UTC, TheRealAmazonKendra approved these changes

2022-08-30 17:45 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d072670a500a2d7dd5ff824bdf2559ded5d1120b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7599a0f8-e37e-4096-beee-760067088a65%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-30 17:46 UTC, merged