feat(assets): support drop-in docker replacements
aws/aws-cdk pull request #21838
Opened 2022-08-30 23:56 UTC by misterjoshua

This change introduces the ability for the user to change the command used
for building Docker images to a drop-in replacement like the [depot](https://depot.dev)
Docker shim. To change the docker command, the user provides the alternative
command via an environment variable named `CDK_DOCKER_CMD`.

Fixes #31836

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-08-31 00:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5ae49bf414857bf3fc49a96ea81d256ea132c01a
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=134c9e49-92ae-43b8-af96-1e9596176a7e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-31 00:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 81197ef39ae28051f40ee61016c21b710e481390
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2534e25c-9935-4c7d-96d2-63fed5800660%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-31 01:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3773d32f158594f041ef0cf70f93a3f7156e6924
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9eb5c52c-2075-441c-a714-0d32ad32b026%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-08-31 05:22 UTC, Hi-Fi commented
How about getting that custom executable to replace `docker` to asset running image? Should custom image be used, some installation added to steps or what? I think this should be mentioned in documentation.

2022-08-31 17:40 UTC, misterjoshua commented
> How about getting that custom executable to replace `docker` to asset step's image(s)? Should custom image be used, some installation added to steps or what? I think this should be mentioned in documentation.

@Hi-Fi Thanks for your comments, but I need more clarification. Do you mean to suggest we include documentation on installing third-party tools alongside the AWS CDK and instructions on using those tools with the AWS CDK? i.e., a tutorial on installing and using Depot to build Docker image assets? (`curl https://... | sh && env CDK_DOCKER=depot-shim cdk deploy`)

2022-08-31 18:01 UTC, Hi-Fi commented
> > How about getting that custom executable to replace `docker` to asset step's image(s)? Should custom image be used, some installation added to steps or what? I think this should be mentioned in documentation.
> 
> @Hi-Fi Thanks for your comments, but I need more clarification. Do you mean to suggest we include documentation on installing third-party tools alongside the AWS CDK and instructions on using those tools with the AWS CDK? i.e., a tutorial on installing and using Depot to build Docker image assets? (`curl https://... | sh && env CDK_DOCKER=depot-shim cdk deploy`)

As asset stage is a bit special in pipelines, and it's configuration is just one that is [offered](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines.CodePipeline.html#assetpublishingcodebuilddefaults). So documentation should have recommendation if to use custom build image with executable included or add installation command to some `assetPublishingCodeBuildDefaults`.

Using cdk deploy is different thing, as with that there's no need to worry about stages. And in that I don't think it's needed to tell how to install tool needed.

2022-08-31 19:29 UTC, misterjoshua commented
> > > How about getting that custom executable to replace `docker` to asset step's image(s)? Should custom image be used, some installation added to steps or what? I think this should be mentioned in documentation.
> > 
> > 
> > @Hi-Fi Thanks for your comments, but I need more clarification. Do you mean to suggest we include documentation on installing third-party tools alongside the AWS CDK and instructions on using those tools with the AWS CDK? i.e., a tutorial on installing and using Depot to build Docker image assets? (`curl https://... | sh && env CDK_DOCKER=depot-shim cdk deploy`)
> 
> As asset stage is a bit special in pipelines, and it's configuration is just one that is [offered](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines.CodePipeline.html#assetpublishingcodebuilddefaults). So documentation should have recommendation if to use custom build image with executable included or add installation command to some `assetPublishingCodeBuildDefaults`.
> 
> Using cdk deploy is different thing, as with that there's no need to worry about stages. And in that I don't think it's needed to tell how to install tool needed.

@Hi-Fi Thanks for clarifying! I'll take a crack at adding documentation to the CDK Pipelines README as well.

2022-08-31 23:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: a87da4c86dbaf4041ca4ee17be469eb9ef93bc14
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7404d7f2-1ee3-47f1-80b4-84654243a91f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-06 18:15 UTC, misterjoshua commented
@mergifyio update

2022-09-06 18:53 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d66d686f4af1ff196ed012936c70a11002f06651
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=27fe06c0-226f-49cd-9de8-8f00c7c444bd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-07 06:33 UTC, misterjoshua commented on packages/@aws-cdk/pipelines/README.md
> +  codeBuildDefaults: {
True that the prop you mention applies only to the publishing steps. But, I'm inclined to think that if a customer is trying to use a drop-in Docker replacement like the Depot Docker shim, they'd first think of using it throughout their CDK app, not just in the asset publishing stage.

For instance, it's not obvious to the caller that `aws_lambda.Code.fromDockerBuild()` builds the Docker image in synth and not during asset publishing - an example with `assetPublishingCodeBuildDefaults` fails to cover this case and could result in unexpected behaviour in this light.

That said, `assetPublishingCodeBuildDefaults` is still available if the customer has a preference.

2022-09-07 08:36 UTC, rix0rrr requested changes
I think the `CDK_DOCKER` feature was mostly intended for testing, but I guess I don't mind supporting this. A couple of doc updates and then this is good to go.

(Sidebar: the more I see and learn about Docker, the less I like supporting it. It seems everyone has very specific opinions on how it should be used in their specific use cases, leading to a proliferation of flags and tweaks that are tough to maintain... 😔)

2022-09-07 08:36 UTC, rix0rrr commented on packages/@aws-cdk/pipelines/README.md
> +**Adding to the default CodeBuild image**
```suggestion
### Adding to the default CodeBuild image
```

2022-09-07 08:36 UTC, rix0rrr commented on packages/@aws-cdk/pipelines/README.md
> +**Using a custom build image**
👍 on including an example for this, but it feels repetitive and doesn't have a paragraph explaining what it is you're doing or why.

Can you add a descriptive paragraph, and cut out nonessentials from the example? For example, declare the source with `declarse const source: CodePipelineSource`, pass a symbolic commands array, that kind of thing. Let's try to leave only the most important parts to highlight them.

2022-09-07 08:36 UTC, rix0rrr commented on packages/@aws-cdk/pipelines/README.md
> +  selfMutation: false,
Please don't recommend this :).

2022-09-08 00:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b3bdbbddcd7a597adf0ec1115989a433cde425df
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ae2b4232-c7f8-46f7-9940-6beda084bdf0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-12 20:07 UTC, misterjoshua commented
@mergifyio update

2022-09-12 20:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3abe75a20b6c3639a4c5bd9596b5e2e9b17e159e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=98da3f77-d2d9-4add-bad0-caf832365708%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-21 16:11 UTC, misterjoshua commented
@mergifyio update

2022-09-21 16:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 13bd72bb002ed8c897358f42b9f58d4c2e3fdaa5
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f7f74706-8bd6-41cc-9d30-36a434d9c51e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-22 15:48 UTC, rix0rrr commented
Needs https://github.com/aws/aws-cdk/pull/22194 to be merged first

2022-09-23 07:49 UTC, rix0rrr commented
@Mergifyio update

2022-09-23 08:28 UTC, merged