Make sure ignore strategies receive directories with trailing slash
aws/aws-cdk pull request #22002
Opened 2022-09-12 12:14 UTC by danilobuerger

ignore strategies like git, expect directories to be passed in with a trailing slash in order to properly match.

consider a source tree:

├── hello
│   └── index.html
├── index.html

now we want to exclude everything except all html files (including all subdirectories).

this can be done with a gitignore of:
*
!*/
!*.html

in order for the git ignore strategy to properly match this, it needs to know that hello is a directory.

this patch just does that by appending a trailing slash for the ignore strategies.

Fixes https://github.com/aws/aws-cdk/issues/9146

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-09-12 12:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 143493815a8ecff52cb713a2ff8479346c279a5b
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9d4489f1-137e-4e95-b538-839961a73316%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-12 13:18 UTC, danilobuerger commented
The build failure seems unrelated. At least I can't find the cause from the logs thats related to my code change.

2022-09-12 14:48 UTC, TheRealAmazonKendra submitted a review, later dismissed

2022-09-12 14:48 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/core/lib/fs/copy.ts
> +    const ignorePath = sourceFilePath + (file.name && file.isDirectory() ? path.sep : "");
Build failure message:
```
@aws-cdk/core: /codebuild/output/src689345531/src/github.com/aws/aws-cdk/packages/@aws-cdk/core/lib/fs/copy.ts
@aws-cdk/core:   22:87  error  Strings must use singlequote  quotes
```

2022-09-12 14:48 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/core/lib/fs/ignore.ts
> +      relativePath += absoluteFilePath.endsWith(path.sep) ? path.sep : "";
Build failure message:
```
@aws-cdk/core: /codebuild/output/src689345531/src/github.com/aws/aws-cdk/packages/@aws-cdk/core/lib/fs/ignore.ts
@aws-cdk/core:   121:72  error  Strings must use singlequote  quotes
@aws-cdk/core:   181:72  error  Strings must use singlequote  quotes
@aws-cdk/core:   227:72  error  Strings must use singlequote  quotes
```

2022-09-12 14:52 UTC, TheRealAmazonKendra commented
A few comments: Firstly, please take another look at the build failures, they're directly related to this code change.

Additionally, please make sure that your PR title confirms to the conventional commit standard (fix, feat, chore) and that it is written in a style that will reflect correctly in the change log (See [Contributing Guide, Pull Requests](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request)).

Lastly, PRs with changes that are not statically guaranteed by the type system must have tests to make sure that (a) the new behavior works as intended and (b) it is not accidentally undone by future changes (See [Contributing Guide, Work Your Magic](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-3-work-your-magic)).

2022-09-12 14:54 UTC, TheRealAmazonKendra requested changes
Please make sure that your PR title confirms to the conventional commit standard (fix, feat, chore) and that it is written in a style that will reflect correctly in the change log (See [Contributing Guide, Pull Requests](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request))

PRs with changes that are not statically guaranteed by the type system must have tests to make sure that (a) the new behavior works as intended and (b) it is not accidentally undone by future changes (See [Contributing Guide, Work Your Magic](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-3-work-your-magic) (https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-3-work-your-magic)).

2022-09-12 14:56 UTC, danilobuerger commented
Hi @TheRealAmazonKendra, thanks for your helpful feedback! I really appreciate it. Sorry I didn't see the failures in the build log. I will try to get some meaningful tests in.

2022-09-12 15:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: fd1621aaeeb212047563d5001b9d7822aa00b303
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=20c89358-8284-4e56-865b-cb7f83b23c80%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-12 15:24 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e1395cd9a22ec3eabf0a6f79d17e0be44c1d70da
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4ef7c852-247c-4614-a645-6f10947e4900%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-12 16:09 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 36326ddaede567104d179ac061861fb8486b0a93
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=40f0c134-5f50-46ce-8eac-b34de54c09e0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-12 18:25 UTC, danilobuerger commented
@TheRealAmazonKendra it looks like its all green now. Thanks again for all your help on getting me there!

2022-09-14 13:53 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: fdc3b36cb2c1c0093a9d38505d11692dab3ea29c
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=24959190-3c30-4c81-9823-b6ca7cb9de5b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-31 04:55 UTC, TheRealAmazonKendra commented
@Mergifyio update

2022-10-31 04:57 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2022-10-31 04:57 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-31 04:59 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-31 05:34 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 891b5bb2ca26ec60f619c6a127ce3d05903ed153
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9d5c0ac8-6ab9-4edb-9aa8-809caf38bfa4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-11-22 00:09 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2022-11-30 00:09 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-11-30 00:09 UTC, closed without merging

2022-11-30 00:11 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.