fix(dynamodb): add metricThrottledRequestsForOperation in itable interface
aws/aws-cdk pull request #22000
Opened 2022-09-12 10:36 UTC by VarunWachaspati

### Bug Description

DynamoDB table construct(which extends the ITable interface) has a method called [metricThrotttledRequestsForOperation()](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-dynamodb.Table.html#metricwbrthrottledwbrrequestswbrforwbroperationoperation-props) but unfortunately ITable interface doesn't have a declaration for the same method.
So currently no one call the recommended method `metricThrottledRequestsForOperation()` as per documentation on the ITable type. 

### Solution Description

Added the recommended method `metricThrottledRequestsForOperation()` to the ITable interface.

fixes #21963 

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-09-12 10:57 UTC, VarunWachaspati commented
What would be an appropriate place to add tests for this change?
I couldn't find any tests for ITable interface, `metricThrottledRequests()` or `metricThrottledRequestsForOperation()` in the codebase.

2022-09-12 11:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1b93e94cc8f0a2917f3f2476d6e5a69bd4829b4d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fd23aa0b-941a-4eac-a961-ac9cbd8e88e2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-12 11:41 UTC, Naumel commented
Hi,

Thank you for the submission, but it appears incomplete.

I'd suggest marking the old method as deprecated and mirroring the comment from the [`TableBase`](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-dynamodb/lib/table.ts#L866).

My initial reaction is to check if an [integ test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md) could be added.

2022-09-12 12:25 UTC, marciocadev reviewed
I believe it could be improved by using an interface to pass the parameters

2022-09-12 15:31 UTC, TheRealAmazonKendra requested changes
Putting this in changes requested given @Naumel's feedback. Note that we cannot provide a meaningful review without tests. @Naumel calls out the need for integ tests, which I agree with, but we will also need unit tests.

2022-09-18 17:39 UTC, VarunWachaspati commented
Sorry, I had originally misunderstood the issue description.
Looks like https://github.com/aws/aws-cdk/pull/22097 is already trying to address this issue so closing this PR.

2022-09-18 17:39 UTC, closed without merging