fix(22094): Sort object before stringify
aws/aws-cdk pull request #22095
Opened 2022-09-17 23:37 UTC by jd-carroll

Sort the object before stringification to ensure a deterministic hash.
Fix #22094

2022-09-17 23:45 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 591909bd59c14d58f104596066e745e05cb0277e
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2d4f9677-caa3-41a2-9753-17217f3beeaf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-17 23:51 UTC, jd-carroll commented
Looks like it failed because a test file was not edited.  However, there are currently no tests for the `asset-staging.ts` file and I'm not entirely sure where I would begin to build a test for this small change.

2022-10-09 00:13 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the BUILD FAILING state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2022-10-14 18:13 UTC, TheRealAmazonKendra requested changes
> Looks like it failed because a test file was not edited. However, there are currently no tests for the asset-staging.ts file and I'm not entirely sure where I would begin to build a test for this small change.

The pr-linter is failing for that reason, but the build is failing because this impacted the naming of the hashes in tests. Based off the fact that you closed the issue, I'm not sure if you'll want to take the time to update all the tests this will impact to get the build to pass, but it will impact every single integration test with an asset.

2022-10-16 00:14 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-10-16 00:14 UTC, closed without merging

2022-10-16 00:16 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2022-10-16 00:16 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.