feat: support for Postgres 11.16
aws/aws-cdk pull request #22127
Opened 2022-09-19 20:55 UTC by michal-draftwise

closes #22107

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-09-19 21:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 4c7513a6138d4ce5f97b32e5e02410cf1e746fd9
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7b59c0d1-69dc-4cf1-9a6e-6722f457e12f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-20 01:41 UTC, TheRealAmazonKendra commented
@Mergifyio update

2022-09-20 02:04 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 334256c6be49c94efdd914e7d6c99c234859d5ee
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9cb59536-7a8d-4298-a892-4c510f5ee19a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-20 10:10 UTC, Naumel commented
Thank you for the time and submitting the change.

You are missing the snapshot updates matching the integ test change:
```
@aws-cdk/aws-rds:   CHANGED    integ.proxy 2.827s
@aws-cdk/aws-rds:       Resources
@aws-cdk/aws-rds: [~] AWS::RDS::DBInstance dbInstance4076B1EC 
@aws-cdk/aws-rds:  â””â”€ [~] EngineVersion
@aws-cdk/aws-rds:      â”œâ”€ [-] 11.15
@aws-cdk/aws-rds:      â””â”€ [+] 11.16
@aws-cdk/aws-rds:   UNCHANGED  integ.instance.lit 3.207s
@aws-cdk/app-delivery: $ cdk-build
@aws-cdk/pipelines: $ cdk-build
@aws-cdk/aws-rds:   UNCHANGED  integ.cluster-snapshot 3.171s
@aws-cdk/aws-rds: Snapshot Results: 
@aws-cdk/aws-rds: Tests:    1 failed, 14 total
@aws-cdk/aws-rds: Error: Some tests failed!
@aws-cdk/aws-rds: To re-run failed tests run: yarn integ-runner --update-on-failed
@aws-cdk/aws-rds:     at main (/codebuild/output/src827645417/src/github.com/aws/aws-cdk/packages/@aws-cdk/integ-runner/lib/cli.js:122:19)
@aws-cdk/aws-rds: Error: integ-runner exited with error code 1
@aws-cdk/aws-rds: Tests failed. Total time (20.8s) | /codebuild/output/src827645417/src/github.com/aws/aws-cdk/node_modules/jest/bin/jest.js (17.0s) | integ-runner (3.7s)
```

2022-09-20 14:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 272659c670a72989fb02fa8fc194695a0a937cdd
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c143c659-4ffe-42b1-82cf-81f0715b6ecd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-20 14:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: a644a24fe791cf58ad5e25c777d5dd63ad069ff0
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6efc3940-ba6d-40e9-acd3-d0d1bc06bc98%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-21 13:33 UTC, corymhall requested changes

2022-09-21 13:33 UTC, corymhall commented on packages/@aws-cdk/aws-rds/test/proxy.integ.snapshot/aws-cdk-rds-proxy.template.json
> +    "EngineVersion": "11.16",
@michal-draftwise I'm assuming that you just manually edited this file to fix the snapshot failure? I think in this case it is fine to just leave the integ test at `VER_11_15`. I don't think it is necessary to have an integration test for _every_ minor version.

2022-09-22 14:17 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b554a63f08a5dbe48e693bf6fec7b87cafa92a2e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b850f1b5-d2d9-4620-93d4-8c1d7053ea9a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-23 12:57 UTC, corymhall approved these changes

2022-09-23 13:41 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b0f4dbbccc390f7b87905d9294fcc03a555c30c4
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=50c44aac-829a-4284-a10e-8a62a041472e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-23 13:41 UTC, merged

2022-12-28 23:38 UTC, comcalvi commented
@Mergifyio backport v1-main