feat(ecr): adding ECR pull through cache rule
aws/aws-cdk pull request #22145
Opened 2022-09-20 15:53 UTC by daschaa

Fixes #20464 

With this PR I tried to implement the pull through cache rules from ECR. (See here: [https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache.html](https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache.html))

I was not sure if this needs a L2 Construct but I thought it would be good, because it is then shown in the CDK reference documentation. L1 Constructs are, in my experience, a bit more hidden.
I'm still not sure if we should expose it to the user, because the list of things to consider when creating such a rule is quite long. I've added a hint in the docs and decided against copying all bullet points to the docs. 

Some open questions:
- Should there be a method which automatically grants the `ecr:CreatePullThroughCacheRule` (and others) on a `Grantee` ? 
- Should there be more documentation? I've copied the text from the original AWS docs and I'm not sure if this is enough.

I would appreciate your feedback! ❤️ 

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-09-20 16:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 959a469900a9857559af1b110255819dea673c7b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c3994a8d-071b-4a40-9f87-fd54a83b538f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-21 13:27 UTC, corymhall submitted a review, later dismissed
I haven't looked into pull through cache in detail, but I'm thinking we may want to think about having this extend `IRepository`. The way I understand it it, each image you pull through a cache rule gets it's own private repository.

I would suggest as next steps to iterate on the README so we can settle on the user experience that we want. Some things to think about:

1. If I create a pull through cache, how do I reference an image in an ECS application (for example).
2. If I want to restrict access to the private repository through a repo policy, how do I do that?
3. Is there a better way of modeling the input properties? From the console you can only select ecr-public or quay and each have a specific Url value. Maybe something like `upstream: Upstream.ecrPublic('my-ecr')` etc.

2022-09-23 06:45 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3e4c91ea2225c878f451e3a40ea30f44b3e7bf9b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3ea6e7c4-30c9-471a-8071-9bfb6405c534%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-28 11:30 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7f1b76289b34e4e06e49ce4ce26c5692fa62be49
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3ce063fc-f942-4d7a-81b7-e0ddbd945cd9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-02 15:57 UTC, daschaa commented
@corymhall 
I added a section in the readme for the usage of the repository created by the pull through cache rule. I took the example from this re:Invent talk actually: [AWS re:Invent 2021 - Up-level your container image security with the latest from Amazon ECR](https://www.youtube.com/watch?v=gvzyF0WxQao&t=2083s).

For the access restriction I thought it would be good to have a function where I can put in some principals and repositories and the registry policy is generated out of that. However I'm not sure if that is too 'restrictive'. And I'm not sure if `IPrincipal` is the best interface there, because it **has to** be a user/root principal, otherwise the registry policy won't deploy. (I have learned it the hard way while executing the integration tests).

For the upstream urls I decided to use an enum, because it felt naturally to me. And it divides the 'hard-coded' upstream url and the customizable repository prefix in two parts :)

Next step would be to add more tests and iterate on the `restrictAcess` functionality, because right now it does not feel very CDK-ish. I thought about using `grant..` but I don't know if this is the cleanest way either.

If you have any feedback on the current changes I would be very happy :) Thank you as always for the valuable feedback!

2022-10-02 16:23 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b0e0eef013dbece66da5fff0513b865b79353424
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=922c9218-ad04-4d86-8b21-e26813dc7978%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-15 22:07 UTC, comcalvi requested changes

2022-12-15 22:07 UTC, comcalvi commented on packages/@aws-cdk/aws-ecr/test/pull-through-cache-rule.test.ts
> +});
```suggestion
});

```

2022-12-15 22:07 UTC, comcalvi commented on packages/@aws-cdk/aws-ecr/test/integ.pull-through-cache-rule.ts
> +const stack = new cdk.Stack(app, 'aws-ecr-pull-through-cache-rule');
```suggestion
const app = new cdk.App();
const stack = new cdk.Stack(app, 'aws-ecr-pull-through-cache-rule');
```

2023-01-06 00:07 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2023-01-13 00:08 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2023-01-13 00:08 UTC, closed without merging