fix(aws-events): Make sure index.ts re-exports canned metrics
aws/aws-cdk pull request #22167
Opened 2022-09-21 09:47 UTC by Lewenhaupt

Make sure index.ts re-exports canned metrics to expose EventMetrics

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-09-21 09:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0ddc1cd8f37f305b7a8c7a6a72ab5e9098d219c2
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=60256428-178c-499e-bce3-39d875445821%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-02 05:23 UTC, aws-cdk-automation submitted a review, later dismissed
The Pull Request Linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-02 05:26 UTC, TheRealAmazonKendra approved these changes

2022-10-02 05:46 UTC, TheRealAmazonKendra requested changes
Oh, somehow I missed that the build is failing on this. We'll need a succeeding build before we can accept this change.

2022-10-09 19:44 UTC, Lewenhaupt commented
@TheRealAmazonKendra I've tried looking into the build failures and it seems that this is an issue with jsii not really liking the generated syntax, thus I believe it's a limitation of /tools/@aws-cdk/cfn2ts/canned-metrics-generator.ts
My guess is that changing this isn't very easy since this affects multiple packages?

2022-10-09 19:53 UTC, Lewenhaupt commented
I'll close this for now. Don't think I'm the one to perform such changes, and I think the solution would be to provide helpers instead of the generated metrics.

2022-10-09 19:53 UTC, closed without merging

2022-10-09 19:55 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c82c68b76afa9e5f86749a1290a7c85dcd41751f
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=03a82306-b39c-438c-be0f-0a1570a5ee06%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->