feat(core): allow overriding the stage name
aws/aws-cdk pull request #22223
Opened 2022-09-25 08:40 UTC by danilobuerger

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-09-25 08:47 UTC, danilobuerger commented
The README of core doesn't describe `Stage` in detail, is it really necessary to modify it for this change?

2022-09-25 09:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: efd8225bea367f62e7adf87c22c466774d397a92
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fdd1a7e5-bc0d-4323-b834-fc3a956f5d0b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-26 17:23 UTC, TheRealAmazonKendra requested changes
Please make sure that your PR body describes the problem the PR is solving, and the design approach and alternatives considered. Explain why the PR solves the problem. A link to an issue is helpful, but does not replace an explanation of your thought process (See [Contributing Guide, Pull Requests](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request))

2022-09-28 07:59 UTC, danilobuerger commented
@TheRealAmazonKendra thanks for helping me. I updated the PR to explain my PR better. I hope its enough?

2022-09-28 08:00 UTC, aws-cdk-automation submitted a review, later dismissed
The Pull Request Linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-09-30 13:00 UTC, corymhall approved these changes

2022-09-30 13:22 UTC, corymhall approved these changes

2022-09-30 14:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: cec7eaf997b28015bf3292c89b9778f3c4a30a97
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=84049a20-0ff5-49f8-9cea-fe01d5cb4f51%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-30 14:08 UTC, merged