fix(custom-resources): custom encoding for buffers returned by AwsCustomResource
aws/aws-cdk pull request #22226
Opened 2022-09-26 00:32 UTC by dzsibi

Fixes #19065

PR #9977 made it so that all Buffer objects are encoded as UTF-8 strings. This fixed #9969, but it assumed that whatever data is returned by the SDK as a Buffer is an UTF-8 encoded string. The original bug was related to S3 GetObject, and even in that case that assumption wouldn't always hold true. In the linked issue, the KMS GetPublicKey call returns bytes that cannot be interpreted as an UTF-8 string.

While I think that it would be better to encode Buffer objects as Base64 strings by default, this would break existing code that relies on this behavior. As such, I added a new property to the AwsSdkCall interface that makes it possible to override this. As far as I was able to determine by looking at the SDK, there are no calls where there would be any benefit to customizing this on a per-property level, so there is a single parameter that overrides the encoding for all properties. 

I am not 100% satisfied with the fact that the user of the construct needs to know about this behavior in order to call certain endpoints, and I guess one could add a sort of lookup table to set the default encoding based on the API call that is being made, but I do not have the time to make a comprehensive list of all API calls that could possibly benefit from such a solution. 

----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-09-26 00:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 92924e38720cb860908e6ba45830c2ecca90d2b0
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=02487543-54ed-43a4-81c3-ae9a7bc459f1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-26 09:01 UTC, dzsibi commented
Looking at the build results I can see that the hash of the runtime script is something the unit tests of the @aws-cdk/aws-cognito package check. Searching for the same hash I can see that this hash is also in the snapshots for the following integration tests:

- @aws-cdk/aws-elasticsearch
- @aws-cdk/aws-glue
- @aws-cdk/aws-route53
- @aws-cdk/aws-events-targets
- @aws-cdk/aws-opensearchservice
- @aws-cdk/aws-msk
- @aws-cdk/custom-resources
- @aws-cdk/aws-globalaccelerator-endpoints
- @aws-cdk/aws-stepfunctions-tasks
- @aws-cdk/aws-cognito

I could fix the unit test for Cognito, but I can't run the full integration test suite and there is a disclaimer against manual updates in the contributor's guide, so I would like to "call this out on the pull request so a maintainer can run the tests for you".

2022-09-26 11:15 UTC, jogold commented on packages/@aws-cdk/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts
> +  readonly encoding?: string;
```suggestion
   * @see https://nodejs.org/api/buffer.html#buffers-and-character-encodings
   * @default utf8
   */
  readonly encoding?: BufferEncoding;
```

2022-09-26 11:15 UTC, jogold commented on packages/@aws-cdk/custom-resources/lib/aws-custom-resource/runtime/index.ts
> +export function flatten(object: object, encoding: string): { [key: string]: any } {
```suggestion
export function flatten(object: object, encoding?: BufferEncoding): { [key: string]: any } {
```

2022-09-26 11:15 UTC, jogold commented on packages/@aws-cdk/custom-resources/lib/aws-custom-resource/runtime/index.ts
> +          ...flatten(response, call.encoding ?? 'utf8'),
The default is utf8 in node

```suggestion
          ...flatten(response, call.encoding),
```

2022-09-27 18:37 UTC, dzsibi commented
@jogold Thanks for the review! I accepted the changes, do you have any guidance on how to proceed?

2022-09-29 09:40 UTC, jogold commented
> @jogold Thanks for the review! I accepted the changes, do you have any guidance on how to proceed?

@dzsibi someone from the CDK needs to review this. Can you try fixing the integ tests in the meantime? I would suggest running the integ tests in `@aws-cdk/custom-resources` with

```
$ yarn integ integ.aws-custom-resource-vpc.js integ.aws-custom-resource.js --parallel-regions <your-region> --update-on-failed
```

and then for the other packages consuming the `AwsCustomResource` you do a dry run to update the snapshots:

```
$ yarn integ --parallel-regions <your-region> --update-on-failed --dry-run
```

2022-10-02 05:31 UTC, TheRealAmazonKendra commented
> Looking at the build results I can see that the hash of the runtime script is something the unit tests of the @aws-cdk/aws-cognito package check. Searching for the same hash I can see that this hash is also in the snapshots for the following integration tests:
> 
> * @aws-cdk/aws-elasticsearch
> * @aws-cdk/aws-glue
> * @aws-cdk/aws-route53
> * @aws-cdk/aws-events-targets
> * @aws-cdk/aws-opensearchservice
> * @aws-cdk/aws-msk
> * @aws-cdk/custom-resources
> * @aws-cdk/aws-globalaccelerator-endpoints
> * @aws-cdk/aws-stepfunctions-tasks
> * @aws-cdk/aws-cognito
> 
> I could fix the unit test for Cognito, but I can't run the full integration test suite and there is a disclaimer against manual updates in the contributor's guide, so I would like to "call this out on the pull request so a maintainer can run the tests for you".

I can help run the integration tests on this.

2022-10-02 05:32 UTC, TheRealAmazonKendra commented
> > @jogold Thanks for the review! I accepted the changes, do you have any guidance on how to proceed?
> 
> @dzsibi someone from the CDK team needs to review this. Can you try fixing the integ tests in the meantime? I would suggest running the integ tests in `@aws-cdk/custom-resources` with
> 
> ```
> $ yarn integ integ.aws-custom-resource-vpc.js integ.aws-custom-resource.js --parallel-regions <your-region> --update-on-failed
> ```
> 
> and then for the other packages consuming the `AwsCustomResource` you can do a dry run to update the snapshots:
> 
> ```
> $ yarn integ --parallel-regions <your-region> --update-on-failed --dry-run
> ```

We don't actually want people to run the tests as dry run. We'll run them and update them.

2022-10-02 05:43 UTC, TheRealAmazonKendra requested changes
Interestingly, I ran the tests and the only place that they failed was in that cognito test.

I've been thinking about this one, though, and I think that rather than adding the prop in here, we should just make the fix under a feature flag. What do you think about this?

2022-10-18 00:14 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the BUILD FAILING state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2022-10-25 00:16 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-10-25 00:16 UTC, closed without merging

2022-10-25 00:18 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2022-10-25 00:18 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.