Adding documentation and comments for `--hostwap`
aws/aws-cdk pull request #22278
Opened 2022-09-28 17:36 UTC by jayhelios

----
Added a [couple comments](https://github.com/aws/aws-cdk/blob/7ccc644008d974c91bb789628d23f4f0b510075b/packages/aws-cdk/lib/api/hotswap/ecs-services.ts#L119) and a line to [this Readme](https://github.com/aws/aws-cdk/blob/7ccc644008d974c91bb789628d23f4f0b510075b/packages/aws-cdk/README.md) highlighting points from this [discussion](https://github.com/aws/aws-cdk/discussions/22241). Please feel free to adjust any wording, but if we are changing defaults for any parameters, even with hotswap, it should be documented somewhere. 

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-09-28 17:38 UTC, aws-cdk-automation requested changes
The Pull Request Linter fails with the following errors:

	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/22278/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

PRs must pass status checks before we can provide a meaningful review.

2022-09-28 17:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 13703c07f35488e061357695727d587b363709a2
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6de8daed-58f3-4a3b-93fc-31fdd4c5f010%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-09-28 17:58 UTC, aws-cdk-automation requested changes
The Pull Request Linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/22278/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

PRs must pass status checks before we can provide a meaningful review.

2022-09-29 13:20 UTC, aws-cdk-automation submitted a review, later dismissed
The Pull Request Linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/22278/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

PRs must pass status checks before we can provide a meaningful review.

2022-10-02 17:18 UTC, TheRealAmazonKendra approved these changes

2022-10-02 17:46 UTC, TheRealAmazonKendra requested changes
Comments should be in line with code.

2022-10-02 17:46 UTC, TheRealAmazonKendra commented on packages/aws-cdk/lib/api/hotswap/ecs-services.ts
> +// As CDK HotSwap is development only, this seems the most efficient way to ensure all tasks are replaced immediately, regardless of original amount.
```suggestion
      // Forcing New Deployment and setting Minimum Healthy Percent to 0. 
      // As CDK HotSwap is development only, this seems the most efficient way to ensure all tasks are replaced immediately, regardless of original amount.
```

2022-10-02 18:06 UTC, jayhelios commented on packages/aws-cdk/lib/api/hotswap/ecs-services.ts
> +// As CDK HotSwap is development only, this seems the most efficient way to ensure all tasks are replaced immediately, regardless of original amount.
Thanks for the correction!

2022-10-02 18:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 9a44dc0357d0f8a228502629c5f6e2b31b909f0f
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f9a79e8f-0a6e-4b01-b765-8c6fbe04f656%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-03 11:00 UTC, Naumel commented
[action requested] Update the formatting:
```
aws-cdk: /codebuild/output/src290663950/src/github.com/aws/aws-cdk/packages/aws-cdk/lib/api/hotswap/ecs-services.ts
aws-cdk:   129:74  error  Trailing spaces not allowed  no-trailing-spaces
aws-cdk: âœ– 1 problem (1 error, 0 warnings)
aws-cdk:   1 error and 0 warnings potentially fixable with the `--fix` option.
```

@Mergifyio update

2022-10-03 11:10 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e40b2645da7dadb119695f3613f20837a0240b05
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f4c71722-02df-4b48-a7e8-bb09e84b452b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-03 18:40 UTC, TheRealAmazonKendra commented on packages/aws-cdk/lib/api/hotswap/ecs-services.ts
> +      // Forcing New Deployment and setting Minimum Healthy Percent to 0.
```suggestion
      // Forcing New Deployment and setting Minimum Healthy Percent to 0.
```

2022-10-03 18:41 UTC, TheRealAmazonKendra approved these changes

2022-10-03 19:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0c165a1089257e277452e31464522245ba413dad
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2a0dc364-4ce8-4690-a2f4-f002777e3eb1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-03 20:27 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1edf2659ccbcf161238dd4cd72469b51dd85912a
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e0dae0d2-5afb-47aa-b3ba-d20564551971%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-03 20:27 UTC, merged