Feat/lambda bundling with cdk assets
aws/aws-cdk pull request #22325
Opened 2022-10-02 18:24 UTC by Hi-Fi

Currently there's no code generating asset manifest that would be using bundling. That generation is easier to build when there's some verified way to make bundling with cdk-assets.

- Relates to #19157 and #21848
----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-10-02 18:26 UTC, aws-cdk-automation requested changes
The Pull Request Linter fails with the following errors:

	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

PRs must pass status checks before we can provide a meaningful review.

2022-10-02 18:26 UTC, aws-cdk-automation requested changes
The Pull Request Linter fails with the following errors:

	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

PRs must pass status checks before we can provide a meaningful review.

2022-10-02 18:28 UTC, aws-cdk-automation requested changes
The Pull Request Linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-02 18:29 UTC, aws-cdk-automation submitted a review, later dismissed
The Pull Request Linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-02 18:38 UTC, aws-cdk-automation requested changes
The Pull Request Linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-02 18:38 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e02a2f2e5c17b3ad36b67d3b1b3c426fe1b8a73b
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d2df6209-dcc9-4de7-bff1-49af44edf349%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-02 19:06 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1451315245ab9108c8118d529f12ec281d0ec705
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a0323aed-bbfc-46ba-b8ff-c907eec552e1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-02 19:14 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b4d0c876aafd7cda9950e4e5b199aab8fd0626b1
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=950491bf-2d3a-424d-bfe7-93ae6b2065f5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-03 03:46 UTC, Hi-Fi commented on packages/cdk-assets/lib/private/handlers/bundlable-files.ts
> +    (this.asset.source.path as any) = bundledPath;
Currently added this hack to test things, but how this should be done?
1. add output path to assembly and pre-generate it when generating assemby?
2. modify publish part to allow overriding path with argument?

2022-10-03 12:23 UTC, corymhall requested changes
@Hi-Fi thanks for taking the time to create this PR! Since this is labeled as a `p2` _and_ is adding some pretty significant functionality we will most likely not be able to review this without an RFC. I think there are a lot of ideas around how to enhance/refactor the assets/bundling functionality and it needs a much bigger discussion than is appropriate for a PR review.

2022-10-03 12:46 UTC, Hi-Fi commented
> @Hi-Fi thanks for taking the time to create this PR! Since this is labeled as a `p2` _and_ is adding some pretty significant functionality we will most likely not be able to review this without an RFC. I think there are a lot of ideas around how to enhance/refactor the assets/bundling functionality and it needs a much bigger discussion than is appropriate for a PR review.

Just interested, how that p2 got here? Both referred issues are p1.

2022-10-04 10:00 UTC, aws-cdk-automation requested changes
The Pull Request Linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-25 20:50 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2022-10-26 18:12 UTC, Hi-Fi commented
@corymhall was there something to improve in this PR, or was it just waiting auto-closure die inactivity after change to draft?

2022-11-02 00:10 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-11-02 00:10 UTC, closed without merging

2022-11-02 00:12 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.