fix(cloudfront): OriginShield not easily disabled once enabled on an …
aws/aws-cdk pull request #22334
Opened 2022-10-03 17:05 UTC by bradlead

…origin

----
Fixes #22233. Solution provided by @s-j-white. Fix covered by existing unit test. Updated integ-distribution-snapshots so they expect originShield returns enabled: false where previously tests would ignore this field.
### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-10-03 17:07 UTC, aws-cdk-automation requested changes
The Pull Request Linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-03 17:16 UTC, aws-cdk-automation submitted a review, later dismissed
The Pull Request Linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-03 17:16 UTC, aws-cdk-automation submitted a review, later dismissed
The Pull Request Linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-03 17:17 UTC, aws-cdk-automation requested changes
The Pull Request Linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-03 17:24 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8eb46085d3ad7c121bb8113858ff89610a42542a
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fe986ea4-fe57-4bb9-ae42-f853c51fbb2a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-03 17:26 UTC, bradlead commented
Updated the integration test snapshot only. Please let me know if this will require an entirely new integ test.

2022-10-03 21:01 UTC, aws-cdk-automation requested changes
The Pull Request Linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-03 21:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8f9114a6e42ceb9d28d07186b15a6d5dcef209fc
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=57c241e5-b6ac-4b4d-965e-24ac729c24c5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-04 09:54 UTC, bradlead commented
> ❌ Fixes must contain a change to an integration test file and the resulting snapshot. - 

Changes have been made to snapshots because the change means a value is returned where it was previously undefined. Existing integ tests should cover this scenario, please review and let me know your thoughts. Thanks!

2022-10-04 14:59 UTC, corymhall requested changes

2022-10-04 14:59 UTC, corymhall commented on packages/@aws-cdk/aws-cloudfront/lib/origin.ts
> +      : { enabled: false };
I think I would rather add a new property `originShieldEnabled` which the user can explicitly set to `false` if they want disable it.

2022-11-02 00:10 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-11-02 00:10 UTC, closed without merging

2022-11-02 00:12 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.