feat(ci): replace set-output to GITHUB_OUTPUT
aws/aws-cdk pull request #22484
Opened 2022-10-13 14:44 UTC by k1rnt

Hi!
fixes #22483 

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-10-13 14:46 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2022-10-13 14:46 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to a test file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-13 14:55 UTC, k1rnt commented
Hi aws!

Replace deprecated features in Github Actions Commands.
❌ Feature must include changes to the README file.
❌ Feature must include changes to the test file.
❌ Features must include changes to the integration test file and the resulting snapshot.
These three changes didn't seem necessary to me.

Thanks.

2022-10-13 15:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b3db683d1b31cd2fd531d5415664295bf5ff3c47
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b803d3e3-98a9-441a-bcc6-f0cc24304b4c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-13 19:23 UTC, TheRealAmazonKendra requested changes
I'm not sure that we can necessarily write automated tests for this but we will need documentation of the steps taken for manually testing this before we can accept this change.

2022-10-13 19:23 UTC, TheRealAmazonKendra commented on .github/workflows/yarn-upgrade-v1main.yml
> +        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
No v1 updates on this branch. Only v2 is updated via `main`. In fact, this file should be deleted altogether on `main`.

2022-10-13 22:56 UTC, TheRealAmazonKendra commented
In addition to my comment inline, please make sure that your PR body describes the problem the PR is solving, and the design approach and alternatives considered. Explain why the PR solves the problem. A link to an issue is helpful, but does not replace an explanation of your thought process (See [Contributing Guide, Pull Requests](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request)).

2022-11-04 00:11 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2022-11-11 00:11 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-11-11 00:11 UTC, closed without merging

2022-11-11 00:13 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to a test file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.