chore(eks): add k8s version 1.22, 1.23, deprecate 1.18, 1.19, 1.20
aws/aws-cdk pull request #22544
Opened 2022-10-18 16:03 UTC by cgarvis

EKS supported versions:

```markdown
* 1.23
* 1.22
* 1.21
* 1.20
```

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

2022-10-18 16:19 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2022-10-18 16:19 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to a test file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-18 16:20 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to a test file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-18 16:21 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 72104078e3495a360c4d9aa3be445b84dce09a0b
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8f8486d9-5d30-4f41-a303-5764baf98b18%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-18 17:06 UTC, corymhall requested changes
This was tried and reverted previously https://github.com/aws/aws-cdk/pull/20000.

I think we are dependent on the reduce module size project.

2022-10-18 20:59 UTC, cgarvis commented
Looking at the original PR in #19756 it seems like it might work with the old kubectl lambda layer.  Was hoping to unblock some folks that want to update EKS and aren't using the lambda layer for anything.

2022-10-19 03:17 UTC, TheRealAmazonKendra requested changes
Need integ tests to verify.

2022-10-19 03:18 UTC, TheRealAmazonKendra commented
All hail the mighty PR Linter.

2022-10-25 23:00 UTC, TheRealAmazonKendra commented
The work in this has been superseded by @madeline-k and @kaizencc's PRs. Closing this one.

2022-10-25 23:00 UTC, closed without merging