feat(ec2): support reserving azs space in VPCs
aws/aws-cdk pull request #22553
Opened 2022-10-19 01:17 UTC by yogeshchopra

VPCProps take a new argument `reservedAzs` which can be used to allocate IP space for availability zones in the VPC without actually instantiating the VPC resources.

This commit also resolves following issue - https://github.com/aws/aws-cdk/issues/6683
----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-10-19 01:19 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2022-10-19 01:19 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-19 02:28 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-19 03:12 UTC, TheRealAmazonKendra requested changes

2022-10-19 03:12 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/aws-ec2/README.md
> +space for reserving n availability zones can be done by setting the
I think that n is intentional here to mean that you're not sure how many, but the wording may not sound clear to others.

2022-10-19 03:12 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/aws-ec2/README.md
> +space for reserving n availability zones can be done by setting the
Editing to add that now that I've read the line below, I see that it was indeed intentional, but I think the wording is a little clunky here. Maybe at least make n => `n`.

2022-10-19 03:12 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/aws-ec2/README.md
> +actually provisioned but its IP space is still reserved. If in the future
```suggestion
actually provisioned but its IP space is still reserved. If, in the future,
```

2022-10-19 03:12 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/aws-ec2/lib/vpc.ts
> +  readonly reservedAzs?: number;
I'm not really sure that this is the right fix here. After reading through the comments on the issue, it's clear that we do need a fix here, but how often will people think ahead to reserve additional AZs?

I think our team needs to discuss a path forward on this one so, full disclaimer, this is where I'm stopping this review for now. I don't want to waste your time in edits when I'm just not sure this is the right path forward.

2022-10-19 03:30 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 19e2ff71ebda5fb76a0cd6a6e3dabdc8cd5dd1c0
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=15d5f0d6-8b9c-467d-a4e4-78567ef23228%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-24 16:35 UTC, yogeshchopra commented
Any update from the team on the same?
This is a blocker for us, as when we want to build vpc we want it to be expandable if needed in future, this will enable to keep our service available in all azs in future.

2022-10-27 08:44 UTC, rix0rrr requested changes
Heya! I like the idea here! 

Be aware that we just merged https://github.com/aws/aws-cdk/pull/22458, which changes the IP allocation code substantially. I don't think you necessarily need to change anything about the API, but you may need to move the implementation.

A simple trick that might work for all IP address providers at once might be to just add one or more marker strings to the list of AZ names (`"fake-az"`), let those participate in the calculations as normal, and then not create actual subnet resources for those AZs.

I'd like to see a different form of unit test than the one you currently have though. You have a bunch of numbers in there -- they could be correct, they could be wrong. I'm dumb, and I don't have the inclination to check your math 😬.

But what I'm really interested in is not the CIDR values of some subnets under some conditions. I'm actually more interested in a specific *property*:

> **GIVEN** a Vpc has been created with reserved AZs
> **WHEN** those reserved AZs are replaced with *real* AZs
> **THEN** none of the subnets that already existed would suffer any CIDR changes

This is a test we could be writing, and it doesn't even involve any math! It's a more robust test as well. I don't care about the exact CIDRs for any specific combination of settings -- I just care that whatever the values are, they don't change when I finally go to add that AZ!

Something like (spitballing here):

```ts
const stack1 = new Stack();
const stack2 = net Stack();

new Vpc(stack1, 'Vpc', {
  mazAzs: 2,
  reservedAzs: 1,
});
new Vpc(stack2, 'Vpc', {
  mazAzs: 3,
  reservedAzs: 0,
});

const template1 = Template.fromStack(stack1);
const template2 = Template.fromStack(stack2);

const subnets1 = template1.findResource('AWS::EC2::Subnet');

for (const [logicalId, subnet1] of Object.entries(subnets1)) {
  const subnet2 = template2.template.Resources[logicalId];
  expect(subnet2).toEqual(subnet1);
}
```

Or something, not entirely sure this is 100% but you see what I'm doing here.

Once we have code that tests this *property* (instead of code that tests a *case*), we can even drop a `test.each()` around it to test it for multiple cases, for nearly free:

```ts
test.each([
 [{ mazAzs: 2, reservedAzs: 1 }, {maxAzs: 3 }],
 [{ mazAzs: 2, reservedAzs: 2 }, {maxAzs: 2, reservedAzs: 1 }],
 [/* maybe something with subnetconfig? */],
})('subnets should remain the same going from %p to %p', (props1, props2) => {
  // ....

  new Vpc(stack1, 'Vpc', { ...props1 });
  new Vpc(stack2, 'Vpc', { ...props2 });

  // ...
});
```

2022-10-27 17:27 UTC, closed without merging

2022-10-27 17:29 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2022-10-27 17:29 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to a test file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-27 18:04 UTC, yogeshchopra commented
How do I reopen this, a merge in my repository closed this pr 😅

2022-10-27 18:05 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 66d1ed36b1628c116d5f1b3397688308d888c9de
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=170bb7fd-0134-4eb3-a526-d06940b3d097%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-27 21:54 UTC, yogeshchopra commented
@rix0rrr that's really good feedback, will update it, not able to open this pr, will create a new pr incorporating your feedback

2022-10-31 03:09 UTC, yogeshchopra commented
https://github.com/aws/aws-cdk/pull/22705