bugfix(opensearch): Don't throw a Az count mismatch (imported VPC)
aws/aws-cdk pull request #22654
Opened 2022-10-26 14:37 UTC by stijnbrouwers

Creating a domain fails for imported vpc/subnets when zone awareness is enabled and the cdk context is cleared.
When the CDK context is already retrieved and the VPC is in the context, the deployment works.

This is due to the fact that when there is no context yet, the subnet count is always 0.
That's why I decided to disable it. If it's not correct, it will fail when applying the cloudformation template.
----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-10-26 14:39 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2022-10-26 14:40 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

PRs must pass status checks before we can provide a meaningful review.

2022-10-26 14:45 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-26 15:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: caaeed334611b567ef550a05ccb8c63d3b450b02
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e3d39a3d-a59e-4dde-9632-e14e9bc6cca2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-26 16:06 UTC, TheRealAmazonKendra submitted a review, later dismissed
We need a succeeding build and the PR linter to pass before we can provide a meaningful review.

2022-10-26 17:17 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3fd2d287da27f7877fcb05a0cbda207d08541686
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6c84c2da-88a0-4328-9e37-a13eae8b0fc3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-26 18:15 UTC, stijnbrouwers commented
> We need a succeeding build and the PR linter to pass before we can provide a meaningful review.

Thanks, It should be OK now. I was still figuring out how to work with the integration tests :-)

2022-11-14 10:39 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 64a9ea5207a974c669a77a8fa7ef180b4b3f70eb
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=cbe24955-0cf8-4bb9-b61b-230d81819748%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-11-14 11:04 UTC, Naumel commented
> The linter and build should be OK now

The build is not...
```
@aws-cdk/aws-opensearchservice:   NEW        integ.opensearch.imported-vpc 0.913s
@aws-cdk/aws-opensearchservice:   UNCHANGED  integ.opensearch.cognitodashboardsauth 1.893s
@aws-cdk/aws-opensearchservice:   UNCHANGED  integ.opensearch.vpc 2.063s
@aws-cdk/aws-globalaccelerator-endpoints: warning JSII6: A "peerDependency" on "@aws-cdk/aws-ec2" at "0.0.0" means you should take a "devDependency" on "@aws-cdk/aws-ec2" at "0.0.0" (found "undefined")
@aws-cdk/aws-globalaccelerator-endpoints: warning JSII6: A "peerDependency" on "@aws-cdk/aws-elasticloadbalancingv2" at "0.0.0" means you should take a "devDependency" on "@aws-cdk/aws-elasticloadbalancingv2" at "0.0.0" (found "undefined")
@aws-cdk/aws-globalaccelerator-endpoints: warning JSII6: A "peerDependency" on "@aws-cdk/aws-globalaccelerator" at "0.0.0" means you should take a "devDependency" on "@aws-cdk/aws-globalaccelerator" at "0.0.0" (found "undefined")
@aws-cdk/aws-globalaccelerator-endpoints: warning JSII6: A "peerDependency" on "@aws-cdk/core" at "0.0.0" means you should take a "devDependency" on "@aws-cdk/core" at "0.0.0" (found "undefined")
@aws-cdk/aws-globalaccelerator-endpoints: warning JSII6: A "peerDependency" on "constructs" at "^10.0.0" means you should take a "devDependency" on "constructs" at "10.0.0" (found "undefined")
@aws-cdk/aws-opensearchservice:   UNCHANGED  integ.opensearch.advancedsecurity 3.694s
@aws-cdk/aws-opensearchservice:   UNCHANGED  integ.opensearch.ultrawarm 3.68s
@aws-cdk/aws-opensearchservice:   UNCHANGED  integ.opensearch.unsignedbasicauth 3.838s
@aws-cdk/aws-opensearchservice:   UNCHANGED  integ.opensearch 3.957s
@aws-cdk/aws-opensearchservice:   UNCHANGED  integ.opensearch.custom-kms-key 3.949s
@aws-cdk/aws-opensearchservice: Snapshot Results: 
@aws-cdk/aws-opensearchservice: Tests:    1 failed, 8 total
@aws-cdk/aws-opensearchservice: Error: Some tests failed!
@aws-cdk/aws-opensearchservice: To re-run failed tests run: yarn integ-runner --update-on-failed
@aws-cdk/aws-opensearchservice:     at main (/codebuild/output/src720397436/src/github.com/aws/aws-cdk/packages/@aws-cdk/integ-runner/lib/cli.js:131:19)
@aws-cdk/aws-opensearchservice: Error: integ-runner exited with error code 1
@aws-cdk/aws-opensearchservice: Tests failed. Total time (19.1s) | /codebuild/output/src720397436/src/github.com/aws/aws-cdk/node_modules/jest/bin/jest.js (14.4s) | integ-runner (4.7s)
@aws-cdk/aws-opensearchservice: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
@aws-cdk/aws-opensearchservice: error Command failed with exit code 1.
@aws-cdk/aws-opensearchservice: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@aws-cdk/aws-autoscaling:   UNCHANGED  integ.amazonlinux2 3.625s
@aws-cdk/aws-opensearchservice: error Command failed with exit code 1.
```

2022-11-16 12:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8e95142b48b2c43c8c3cf7cde1927a7bd23866ef
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=15618922-8d03-4a17-9b3d-9303b6d479c8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-11-16 13:46 UTC, stijnbrouwers commented
> > The linter and build should be OK now
> 
> The build is not...
> 
> ```
> @aws-cdk/aws-opensearchservice:   NEW        integ.opensearch.imported-vpc 0.913s
> @aws-cdk/aws-opensearchservice:   UNCHANGED  integ.opensearch.cognitodashboardsauth 1.893s
> @aws-cdk/aws-opensearchservice:   UNCHANGED  integ.opensearch.vpc 2.063s
> @aws-cdk/aws-globalaccelerator-endpoints: warning JSII6: A "peerDependency" on "@aws-cdk/aws-ec2" at "0.0.0" means you should take a "devDependency" on "@aws-cdk/aws-ec2" at "0.0.0" (found "undefined")
> @aws-cdk/aws-globalaccelerator-endpoints: warning JSII6: A "peerDependency" on "@aws-cdk/aws-elasticloadbalancingv2" at "0.0.0" means you should take a "devDependency" on "@aws-cdk/aws-elasticloadbalancingv2" at "0.0.0" (found "undefined")
> @aws-cdk/aws-globalaccelerator-endpoints: warning JSII6: A "peerDependency" on "@aws-cdk/aws-globalaccelerator" at "0.0.0" means you should take a "devDependency" on "@aws-cdk/aws-globalaccelerator" at "0.0.0" (found "undefined")
> @aws-cdk/aws-globalaccelerator-endpoints: warning JSII6: A "peerDependency" on "@aws-cdk/core" at "0.0.0" means you should take a "devDependency" on "@aws-cdk/core" at "0.0.0" (found "undefined")
> @aws-cdk/aws-globalaccelerator-endpoints: warning JSII6: A "peerDependency" on "constructs" at "^10.0.0" means you should take a "devDependency" on "constructs" at "10.0.0" (found "undefined")
> @aws-cdk/aws-opensearchservice:   UNCHANGED  integ.opensearch.advancedsecurity 3.694s
> @aws-cdk/aws-opensearchservice:   UNCHANGED  integ.opensearch.ultrawarm 3.68s
> @aws-cdk/aws-opensearchservice:   UNCHANGED  integ.opensearch.unsignedbasicauth 3.838s
> @aws-cdk/aws-opensearchservice:   UNCHANGED  integ.opensearch 3.957s
> @aws-cdk/aws-opensearchservice:   UNCHANGED  integ.opensearch.custom-kms-key 3.949s
> @aws-cdk/aws-opensearchservice: Snapshot Results: 
> @aws-cdk/aws-opensearchservice: Tests:    1 failed, 8 total
> @aws-cdk/aws-opensearchservice: Error: Some tests failed!
> @aws-cdk/aws-opensearchservice: To re-run failed tests run: yarn integ-runner --update-on-failed
> @aws-cdk/aws-opensearchservice:     at main (/codebuild/output/src720397436/src/github.com/aws/aws-cdk/packages/@aws-cdk/integ-runner/lib/cli.js:131:19)
> @aws-cdk/aws-opensearchservice: Error: integ-runner exited with error code 1
> @aws-cdk/aws-opensearchservice: Tests failed. Total time (19.1s) | /codebuild/output/src720397436/src/github.com/aws/aws-cdk/node_modules/jest/bin/jest.js (14.4s) | integ-runner (4.7s)
> @aws-cdk/aws-opensearchservice: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> @aws-cdk/aws-opensearchservice: error Command failed with exit code 1.
> @aws-cdk/aws-opensearchservice: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> @aws-cdk/aws-autoscaling:   UNCHANGED  integ.amazonlinux2 3.625s
> @aws-cdk/aws-opensearchservice: error Command failed with exit code 1.
> ```

Sorry, for that, I thought this was working...
Anyway, It should be fixed now!

2022-11-17 10:14 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: fce9d31a0a020e38befc6bd138f4052294f3f404
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1cbbc72e-0886-4a06-94f5-0871284b4f4e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-08 14:17 UTC, mrgrain requested changes

2022-12-08 14:17 UTC, mrgrain commented on packages/@aws-cdk/aws-opensearchservice/test/integ.opensearch.imported-vpc.ts
> +/// !cdk-integ * pragma:enable-lookups
Please update the integ test to use the lasted style (I know, it's a tad confusing).

You'll need to drop this line and at the end needs something like this
```ts
new integ.IntegTest(app, '...', {
  testCases: [stack],
});
```

See: https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md

2022-12-08 14:17 UTC, mrgrain commented on packages/@aws-cdk/aws-opensearchservice/lib/domain.ts
> +    let skipZoneAwarenessCheck:boolean = false;
```suggestion
    let skipZoneAwarenessCheck: boolean = false;
```

2022-12-10 13:20 UTC, stijnbrouwers commented on packages/@aws-cdk/aws-opensearchservice/lib/domain.ts
> +    let skipZoneAwarenessCheck:boolean = false;
See last commit

2022-12-10 13:36 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 9cba3ba811be32c81673608b259ed37d762a8de6
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=82d0315a-e85b-443e-897b-710408c6156f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-10 13:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b1fec5b67e96cdb029ebdf324cd6abe3885a675a
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=232ece79-c584-4184-9ec1-a8cbebcbd41d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-12 08:34 UTC, mrgrain commented on packages/@aws-cdk/aws-opensearchservice/test/integ.opensearch.imported-vpc.ts
> +app.synth();
```suggestion
app.synth();

```

2022-12-12 08:34 UTC, mrgrain commented on packages/@aws-cdk/aws-opensearchservice/test/integ.opensearch.imported-vpc.ts
> +    /// !show
```suggestion
```

2022-12-12 08:34 UTC, mrgrain commented on packages/@aws-cdk/aws-opensearchservice/test/integ.opensearch.imported-vpc.ts
> +    /// !hide
```suggestion
    const vpc: IVpc = ec2.Vpc.fromLookup(this, 'Vpc', {
      vpcName: 'my-vpc-name',
    });
```

2022-12-12 08:36 UTC, mrgrain commented
@mergifyio update

2022-12-12 09:12 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 274cbdf34763cf03f0f45e29ccd4375f22e54f92
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=27395d48-ff74-450f-9fe5-72d058643e07%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-12 09:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 695538929b74f394b6724d380aefac17af05211f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2a988e39-c3a4-4403-ba63-5a36dabaf93e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-12 09:56 UTC, mrgrain submitted a review, later dismissed
Code is looking good now and thanks for adding the integ test.

However the integ test does not appear to deploy successfully. Did you run it?
```
Context lookups have been disabled. Make sure all necessary context is already in 'cdk.context.json' by running 'cdk synth' on a machine with sufficient AWS credentials and committing the result. Missing context keys: 'vpc-provider:account=ACCOUNT:filter.tag:Name=my-vpc-name:region=us-east-1:returnAsymmetricSubnets=true'
  FAILED     integ.opensearch.imported-vpc-cdk-integ-opensearch-vpc-test/DefaultTest (undefined/us-east-1) 10.216s
      Integration test failed: Error: Command exited with status 1
```

Given that the repro steps for the issue includes "clear the context" this error seems related?!

2022-12-12 10:40 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: eaffe2530513145618bc569732381e1a244af48f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d451e77e-e697-44ee-9afe-0349bb25b395%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-12 10:55 UTC, stijnbrouwers commented
@mrgrain 

Yes, I ran it and it used to work
<img width="573" alt="image" src="https://user-images.githubusercontent.com/9864443/207027212-a58405de-03fb-433c-afc6-ed9cfc6bd6e3.png">

After applying the app dependency change however, it failed again...
It is not clear what to do here. 
I tried adding
```
/// !cdk-integ * pragma:enable-lookups
```
Which you removed (but also doesn't seem to do anything at the moment)
and I tried setting 
```
"enableLookups": true
```
in integ.json.
But again, to no avail.

The unit test NEEDS to do a lookup, if the VPC is already in the context the bug does not occur.
So if we want to trigger the issue we need to have an empty context and do a lookup but the integration test framework does not seem to support this scenario.

2022-12-12 11:08 UTC, mrgrain commented
Thanks for the detailed response @stijnbrouwers I think I misunderstood the source of the issue. Apologies for this.
If I re-phrase the test scenario in my own words, I think this needs to happen:
- We need an exiting Stack with a VPC
- Then we need to do a lookup, forced by the empty context

I'm not sure we can actually create this order in a single deployment (which is was the integ framework does). Because any lookups would happen before the Stack with the VPC would be deployed as well, thus failing the lookup. I'll need to think a bit more about this. This _might_ be okay with a unit test only.

2022-12-12 11:09 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7fc68947996d4776929fd38dd81432e9a8307398
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7daf65bd-a99e-4e7f-959f-c63e2cc07812%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-12 11:18 UTC, stijnbrouwers commented
@mrgrain thank you very much for your quick response.
And that's 100% correct what you are saying.

The issue that I fixed is:
Whenever the opensearch is created, it does a sanity check to see that the minimum or provided availabilityZone count is present in the VPC subnets. However, when the VPC is provided by lookup, the subnet array is still empty when the check is being run, and thus always returns 0. 

To mitigate this, I skip the check whenever one of the subnets has the isPendingLookup-property set to "true".

Should the minimum amount of availability zones not be present, it will fail upon creation of the actual resource in AWS instead of upon creation of the cloudformation template.

That should give a little insight into why I need to do the lookup in the integration test. Another solution would be to just always drop the sanity check and let AWS complain upon resource creation, but I liked this better :-)

2022-12-12 13:57 UTC, mrgrain commented
I'm following now and I agree with the assessment to skip the check in case the lookup is pending. We don't need an integ test for this, because it's not possible to test this with the current setup. Let's remove the test and get it merged.

2022-12-12 14:29 UTC, stijnbrouwers commented
@mrgrain , great thanks!
I removed the integ test.

2022-12-12 15:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 4fd65e4192666d5d3dc350a4c03adfa040ab4634
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0e9ba62e-99bf-4f98-84c9-e339e38cfd98%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-12 15:08 UTC, mrgrain approved these changes

2022-12-12 15:47 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: dafd14d4e137c509c14e841cccf1c861d15d80af
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f2c51350-7627-436e-8b84-37b154be230c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-12 15:47 UTC, merged