fix(custom-resoures): custom handler status not being used by framework
aws/aws-cdk pull request #22698
Opened 2022-10-28 23:37 UTC by ianmarmour

### Describe the bug

The current implementation of custom-resources provider-framework does not correctly reflect what handlers are expect to respond with based on [CFN's own resource specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-responses.html).

Specifically the Status parameter of the response object is being ignored by the provider-framework and always returning success even when a Lambda properly returned a formatted failure, this has lead to custom resources that we've created incorrectly returning CREATE_COMPLETE even though there was an error. It's noted in the documentation for the custom-resources provider that onEvent handlers are expected to throw in the case of an error however CFN does not expect them to throw and instead expects them to either throw or more ideally return with a formatted error message.

### Root Cause

Original implementation ignored the schema of CFN and instead always succeeded.

### Solution

Optionally allow for Status to be utilized if it's provided by the response from a custom resource handler.

fixes #22696 
----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-10-28 23:38 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2022-10-28 23:38 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-28 23:39 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-28 23:46 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-28 23:47 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-28 23:53 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 827589f635f5607c6c554eba3a29c52d64c7e8d6
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=cd203b4d-52bc-4875-a308-a8102dd782c7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-29 00:01 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7ff57f074e56dfc09687f661cc20fce46cdda070
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0d9b6da2-4e33-4b69-8e96-004a2fe17ae9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-29 01:12 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-29 01:26 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 2983f42cffb0f5bf5cab1d4ef0512624c6f750cb
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=89582eb4-3a8b-4034-957f-5b0953086569%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-29 14:21 UTC, pflorek requested changes
@ianmarmour nice Feature

Please implement both `OnEvent` and `IsComplete`.


Please update the response types
https://github.com/aws/aws-cdk/blob/fadbfc1eb07f4f2daecfe623812fee029c81e31a/packages/%40aws-cdk/custom-resources/lib/provider-framework/types.d.ts#L53

2022-10-29 14:21 UTC, pflorek commented on yarn.lock
> +aws-cdk-lib@2.47.0:
```suggestion
aws-cdk-lib@^2.47.0:
```

Revert this

2022-10-31 05:10 UTC, TheRealAmazonKendra requested changes
Thank you for your contribution. We need a succeeding build and for all PR linter status checks to pass before we can provide a meaningful review.

2022-10-31 05:10 UTC, TheRealAmazonKendra commented on yarn.lock
> +aws-cdk-lib@2.47.0:
No changes to yarn.lock, please.

2022-10-31 19:52 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-31 19:56 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-31 20:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f28ac60706fca8c2dc2a2d9d25b34f0a31360b96
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ee28849d-7483-46e3-8f12-ee9df7b97cfe%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-31 20:11 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 890a7ef9c57eb464c34dc44daf5e8de0c4ab0b41
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b7217dfd-d36b-43a6-9412-c1dd24d35ab2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-31 20:18 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-31 20:22 UTC, mrgrain commented
Hi @ianmarmour Before you go off and invest much more work on this, we need to check if this is a possible change. I am confirming the original design with the team, so please bear with me and I might be wrong.

--- 

1) To go with lambda exit "status" was a conscious design. See the big yellow box on [this documentation page](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources-readme.html):
>N.B.: if you use the provider framework in this module you will write AWS Lambda Functions that look a lot like, but aren't exactly the same as the Lambda Functions you would write if you wrote CloudFormation Custom Resources directly, without this framework.
>
>Specifically, to report success or failure, have your Lambda Function exit in the right way: return data for success, or throw an exception for failure. Do not post the success or failure of your custom resource to an HTTPS URL as the CloudFormation documentation tells you to do.

2) You are arguing that the CFN specification stipulates a certain response format for the Lambda. However the page you've linked states (highlight is mine):
> The following are properties that the custom resource provider includes **_when it sends the JSON file to the presigned URL_**.

Again, this describes a different interface.

3) The proposed change would also break any Customers that currently return a `Status` other than `SUCCESS`. This might not affect many, but it would be a breaking change that at least has to go behind a feature flag.


---

If you'd rather use the original CloudFormation Custom Resource framework, that's also available: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.CustomResource.html

2022-10-31 20:22 UTC, mrgrain requested changes
Until resolved, see above.

2022-10-31 20:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 2caa1a08869380c73ca738d9739ca2a53ef23657
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=983c1eb9-813d-4177-9a9b-510563d10284%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-10-31 21:37 UTC, ianmarmour commented
@mrgrain

> To go with lambda exit "status" was conscious design. See the big yellow box on [this documentation page](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources-readme.html):

I very much missed that when implementing our custom resources 😆. 

> The following are properties that the custom resource provider includes when it sends the JSON file to the presigned URL.

I think my confusion here mostly stemmed from the fact that the provider-framework is actually invoking a lambda and that lambda isn't really a custom resource handler it's a provider-framework handler with it's own behavior specifically needed to conform with this framework (the framework provides some things that are very nice to have). When I was originally working on our code that leveraged this I kind of assumed the framework was much less opinionated then it is in practice.

> The proposed change would also break any Customers that currently return a Status other than SUCCESS. This might not affect many, but it would be a breaking change that at least has to go behind a feature flag.

I would wonder in what case returning FAILURE and not failing wouldn't be an anti-pattern? I agree that it would break existing customers however I can't imagine a time when a customer is intentionally emitting a failure but wants the resource to be added to the stack successfully (though I suppose there could be a valid use case there). If that use case exists it seems like something that the CFN team should support directly? 

I'm happy to close this issue for now though and update my personal code to throw rather then return a status.

2022-10-31 21:48 UTC, mrgrain commented
> I very much missed that when implementing our custom resources 😆.
> I think my confusion here mostly stemmed from the fact that the provider-framework is actually invoking a lambda and that lambda isn't really a custom resource handler it's a provider-framework handler with it's own behavior specifically needed to conform with this framework (the framework provides some things that are very nice to have). When I was originally working on our code that leveraged this I kind of assumed the framework was much less opinionated then it is in practice.

I'm glad we could clear this up! 👍🏻 It seems like we could still improve how we highlight the difference between the two. If you've got any suggestions on what we could improve documentation wise, they would be very welcome.

> I would wonder in what case returning FAILURE and not failing wouldn't be an anti-pattern? I agree that it would break existing customers however I can't imagine a time when a customer is intentionally emitting a failure but wants the resource to be added to the stack successfully (though I suppose there could be a valid use case there). If that use case exists it seems like something that the CFN team should support directly?

Agreed, it's very unlikely. I wasn't actually thinking about returning `FAILURE` specifically, but literally anything else. Like `OK` or just passing through the response from a library and ending up with an arbitrary status (e.g. HTTP status codes).

> I'm happy to close this issue for now though and update my personal code to throw rather then return a status.
👍🏻

2022-10-31 21:48 UTC, closed without merging

2023-10-20 09:12 UTC, Lewenhaupt commented
I'm using [aws-cloudformation-custom-resource](https://www.npmjs.com/package/aws-cloudformation-custom-resource) and it returns FAILED when failing but I just discovered this when Cloudformation thought everything was working but all our db migrations were missing in a new stack. Sure one could use the old Provider, but that (for some reason) decided you can't add an existing lambda to it, only create a new one, which doesn't really fit what we're doing.

I think it's very strange this doesn't adhere to the custom resource framework of CFN.