fix build errors on generated test
aws/aws-cdk pull request #22701
Opened 2022-10-29 13:44 UTC by hakanson

The current generated Go test sample doesn't pass a required argument to `assertions.Template_FromStack`.  A `cdk init --language go` using v2..49.0 generates the error below when running `go test`.  

```bash
$ go test
# goscratch [goscratch.test]
./goscratch_test.go:21:44: not enough arguments in call to assertions.Template_FromStack
        have (awscdk.Stack)
        want (awscdk.Stack, *assertions.TemplateParsingOptions)
FAIL    goscratch [build failed]
```

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-10-29 13:46 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2022-10-29 13:46 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

PRs must pass status checks before we can provide a meaningful review.

2022-10-29 13:50 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-10-29 13:57 UTC, hakanson commented
Since this golang template code doesn't build today, there is no integration test file to update.

2022-10-29 14:21 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 171ce46f34c60e636f3496e44f714cc7525fef1b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=70497411-fc70-47af-8771-e05263330e08%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-11-02 19:18 UTC, TheRealAmazonKendra requested changes
We do actually have tests for init templates and the `sample-app` file is what's used in it. Have you run that test to verify this change? If it's the correct change, it also needs to get fixed in the actual init template as well.

2022-11-02 23:36 UTC, hakanson commented
@TheRealAmazonKendra - I'm sorry but I can't find that test for the init template.  Can you give me the direct path?

2022-11-03 01:18 UTC, TheRealAmazonKendra commented
Yep! Here are the [unit tests](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk/test/init.test.ts), which it looks like we're missing coverage on (OOOPS!). We also have [integ tests](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk/test/integ/init/test-go.sh) that you can run against it. It doesn't need an update, I don't think, just confirmation that the run succeeds after your update.

2022-11-24 00:10 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2022-11-24 01:55 UTC, hakanson commented
Unfortunately I don't know how to make progress on fixing this and would like help.

2022-12-01 00:10 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-12-01 00:10 UTC, closed without merging

2022-12-01 00:12 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.