fix: MSK SASL password special chars
aws/aws-cdk pull request #22833
Opened 2022-11-08 13:59 UTC by pjoe

Secret Manager generated password fails if containing chars "/\ when used with Lambda Kafka trigger.

Also return generated Secrets, so can be used from other constructs.

fixes #22813, #16975

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-11-08 14:01 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2022-11-08 14:52 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-11-08 15:04 UTC, pjoe commented
Forgot it also needs snapshot for integration test, running the test now, will add later when completed.

2022-11-09 07:56 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ea1d1a0dce31f38b292173bba30f525562924fef
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7d57bf9d-96cd-4041-a7ba-2d2698a290d0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-12 02:05 UTC, TheRealAmazonKendra requested changes
Thank you for your contribution! We prefer to have one issue per PR so please split this PR up into the two issues you're solving for. The PR titles write automatically the changelog for us. Additionally, I have some feedback inline. Please see that.

2023-01-12 02:05 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/aws-msk/lib/cluster.ts
> +  public addUser(...usernames: string[]): secretsmanager.Secret[] {
I'm not sure that this change is the correct approach. I think that I'd recommend making the list of usernames and associated passwords a private property in Cluster and adding a function that takes in a username and returns the associated secret.

2023-02-03 00:08 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2023-02-10 00:08 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2023-02-10 00:09 UTC, closed without merging