feat(synthetics): expose lifecycle rules for auto-generated artifact …
aws/aws-cdk pull request #22863
Opened 2022-11-10 15:09 UTC by mackensen

…buckets

This change exposes the lifecycle rules property for new and existing auto-generated artifact buckets so that workload owners can easily manage growth.

fixes #22634

I'm not able to run the integration tests.

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-11-10 15:11 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2022-11-10 15:11 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-11-10 15:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7d6d05ae32ddb04da07cbea992a681940849516d
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d5b1ed6e-0766-4977-8f51-981aa7d02708%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-11-10 15:40 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-11-10 15:46 UTC, kaizencc requested changes
Hi @mackensen! This looks good! I'll run the integ test sometime today. In the meantime, can you add this somewhere to the readme?

2022-11-10 15:46 UTC, kaizencc commented on packages/@aws-cdk/aws-synthetics/lib/canary.ts
> +   */
```suggestion
   * Lifecycle rules for the generated canary artifact bucket. Has no effect
   * if a bucket is passed to `artifactsBucketLocation`. If you pass a bucket
   * to `artifactsBucketLocation`, you can add lifecycle rules to the bucket
   * itself.
   *
   * @default - no rules applied to the generated bucket.
   */
```

2022-11-10 15:46 UTC, kaizencc commented on packages/@aws-cdk/aws-synthetics/test/canary.test.ts
> +    runtime: synthetics.Runtime.SYNTHETICS_1_0,
```suggestion
    runtime: synthetics.Runtime.SYNTHETICS_NODEJS_PUPPETEER_3_8,
```

2022-11-10 18:07 UTC, mackensen commented
@kaizencc thanks for the feedback, I've updated the branch.

2022-11-10 18:09 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-11-10 18:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0541c2589098f17518879d6c010b067afa1314b4
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=77010041-a1c4-4ac0-a31e-cf7b1bb0be97%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-11-10 20:59 UTC, kaizencc commented
@mackensen I ran the integ test for you. It is somehow [here](https://github.com/LafColITS/aws-cdk/compare/22634-artifacts-bucket-lifecycle...aws:aws-cdk:22634-artifacts-bucket-lifecycle). Not sure what went on to make it not a part of this particular branch, but Ill leave it to you to merge your branch with the commit that has the updated snapshot.

In addition, this PR needs a readme update that mentions the ability to add lifecycle rules to the created s3 bucket.

2022-11-12 23:11 UTC, mackensen commented
@kaizencc thanks, cherry-picked your commit and updated the README.

2022-11-12 23:47 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e54e78324b268ff5fb1d259b5ecce5d86139345e
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=371b0368-e776-4077-8236-6ac96dc7a6a3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-02 00:09 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2022-12-02 15:07 UTC, kaizencc requested changes
Hi @mackensen! Apologies for not getting back to you sooner. This is ready to go once the build succeeds. My comments on the readme, when addressed, should fix the build.

2022-12-02 15:07 UTC, kaizencc commented on packages/@aws-cdk/aws-synthetics/README.md
> +const canary = new synthetics.Canary(this, 'MyCanary', {
Looks like the build is failing because we are creating two `canary` consts in the same example.

2022-12-02 15:07 UTC, kaizencc commented on packages/@aws-cdk/aws-synthetics/README.md
> +Artifact bucket examples:
Lets delete this line and move it in to the ts example

2022-12-02 15:07 UTC, kaizencc commented on packages/@aws-cdk/aws-synthetics/README.md
> +// Auto-generated bucket with lifecycle rules.
```suggestion
```ts
// configure lifecycle rules on the auto-generated artifact bucket.
```

2022-12-02 15:07 UTC, kaizencc commented on packages/@aws-cdk/aws-synthetics/README.md
> +// Custom bucket as artifact bucket.
github ui doesn't like when my suggestions involve `"```"` so I'll just describe what i want here.

we should split up the example into two here and change the comment to the one below:

```ts
// configure lifecycle rules on a custom artifact bucket.
```

2022-12-04 00:09 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the BUILD FAILING state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2022-12-11 00:09 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-12-11 00:10 UTC, closed without merging