fix(ec2): VpnConnection sets VPNGateway to same ASN as CustomerGateway
aws/aws-cdk pull request #22866
Opened 2022-11-10 17:22 UTC by nwouda

When creating a VpnConnection while specifying an ASN outside the Vpc construct, the ASN for the VPNGateway is set to the same ASN as the CustomerGateway.

fixes #22848

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Unconventional Dependencies:

* [ ] This PR adds new unconventional dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-new-unconventional-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-11-10 17:24 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2022-11-10 17:59 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7ce69118e04500c8e3c1bfd949d0be0aa71f774a
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=81596653-aef6-49b4-a0f6-6ee1f9a869f8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-02-02 23:24 UTC, comcalvi requested changes

2023-02-02 23:24 UTC, comcalvi commented on packages/@aws-cdk/aws-ec2/lib/vpn.ts
> -        amazonSideAsn: props.asn,
This is definitely a breaking change. Please add a feature flag for this and add a new optional property, `amazonSideAsn`, to the `VpnConnectionProps`. Take a look at #20765 for an example of how to add feature flags. 

Then this becomes 

```
     props.vpc.enableVpnGateway({
        type: 'ipsec.1',
        amazonSideAsn,
```

2023-02-24 00:08 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2023-03-03 01:49 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2023-03-03 01:49 UTC, closed without merging

2023-03-22 16:11 UTC, sree7k7 commented
Following this doc:
https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_ec2/VpnConnection.html

Result:
VpnConnection sets VPNGateway to same ASN as CustomerGateway

Can you provide an example? 

Thanks!