fix(core-stage): Fix stage name check to be aligned with stack name
aws/aws-cdk pull request #23089
Opened 2022-11-25 15:10 UTC by yuyokk

Hi folks,

I faced the following errors today: 

- error 1

```bash
invalid stage name "Stage acme.example.com". Stage name must start with a letter and contain only alphanumeric characters, hypens ('-'), underscores ('_') and periods ('.')
```

- error 2 (after fixing error 1)

```bash
Stack name must match the regular expression: /^[A-Za-z][A-Za-z0-9-]*$/, got 'DeploymentStage_acme.example.com-TenantCore'
```

I believe there is discrepancy in stage and stack names checks.

Please check changes on the PR and let me know if they make sense.
Thank you

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-11-25 15:12 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2022-11-25 15:12 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-11-25 15:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: a7cfdc1e8aa1c478deb15c654bbc95b006d3dae5
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7a936a12-2a9a-4cb7-809d-c6edf2a69aba%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-11-25 16:02 UTC, mrgrain commented
Hi @yuyokk  I think this makes sense, but am very concerned about the implications of introducing more restrictive checks.

Could you please provide a reproduction example of how you run into this error, ideally by [creating a new bug report](https://github.com/aws/aws-cdk/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug-report.yml&title=%28module+name%29%3A+%28short+issue+description%29) or by linking an existing issue.

2022-11-25 16:04 UTC, mrgrain requested changes
Reproduction example required.

2022-11-26 08:33 UTC, yuyokk commented
@mrgrain here is the bug https://github.com/aws/aws-cdk/issues/23098

2022-11-29 00:25 UTC, peterwoodworth commented
@mrgrain the reproduction posted looks good to me. Since stack names are built in part from stage names, would there be any case in which a stage is defined with `.` or `_` and wouldn't contain a stack with these characters in the stack name? I don't think so, but maybe there's some edge case or functionality that isn't being accounted for here.

Essentially, for this to not be a breaking change that means that EVERY stage defined in any application also necessarily contains at least one stack whose name contains the stage name.

2022-11-29 00:38 UTC, mrgrain commented
Thanks @peterwoodworth I agree with that assessment. I just haven't had time to look into the code path to confirm yet.

2022-12-17 00:08 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2022-12-19 09:36 UTC, mrgrain commented
Okay @peterwoodworth  and @yuyokk  This will be a breaking change and I'm really not sure if it's a good to have this fixed.

More discussions on the issue please, but here's what makes this breaking. The following code works right now but won't with the suggested change.
```ts
// somewhere in the pipeline stack
pipeline.addStage(new AppStage(this, "Stage_per_acme.example.com "));

// This is the Stage, note the provided stack name
class AppStage extends Stage {
  constructor(scope: Construct, id: string, props?: StageProps) {
    super(scope, id, props);

    new HelloCdkStack(this, "HelloCdkStack", {
      stackName: "hello"
    });
  }
}
```

2022-12-25 00:08 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2022-12-25 00:08 UTC, closed without merging

2022-12-25 00:10 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.