refactor(route53): favor `grant` method over precreated role
aws/aws-cdk pull request #23083
Opened 2022-11-25 11:43 UTC by rix0rrr

`PublicHostedZone` allows creating exactly one role for cross-account delegation.

Because of limitations of trust policy size, some teams inside Amazon are creating a role per opt-in region, in which case the "one precreated role" feature doesn't help at all.

Instead, add a `grantDelegation()` helper which works for both cases.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-11-26 00:58 UTC, ryparker reviewed
Should we have a test for `.grantDelegation()`?

2022-12-05 19:38 UTC, comcalvi requested changes
:+1: to @rypaker's comment, would like to see a `grantDelegation()` test.

2022-12-19 11:21 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 053373405d742a5317a19d5e60b386a1a14f086c
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=62a8945f-1ec8-423b-b61f-30dfdd75229a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-19 23:43 UTC, comcalvi approved these changes

2022-12-19 23:44 UTC, comcalvi commented on packages/@aws-cdk/aws-route53/lib/hosted-zone.ts
> +  public grantDelegation(grantee: iam.IGrantable) {
from the build logs:

```
@aws-cdk/aws-msk: Build times for @aws-cdk/aws-msk: Total time (21.3s) | /codebuild/output/src805351294/src/github.com/aws/aws-cdk/node_modules/jsii/bin/jsii (9.6s) | cfn2ts (0.3s)
@aws-cdk/aws-route53: error: [awslint:grant-result:@aws-cdk/aws-route53.PublicHostedZone.grantDelegation] "grant" method must return @aws-cdk/aws-iam.Grant  (expected="@aws-cdk/aws-iam.Grant",actual="void")
```

2022-12-19 23:44 UTC, comcalvi commented on packages/@aws-cdk/aws-route53/lib/hosted-zone.ts
> +  public grantDelegation(grantee: iam.IGrantable) {
Maybe worth adding an explicit return type? Up to you.

2022-12-23 16:12 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1f3368a6dbee27e5d5ac0df7289c8dfb6830e04d
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=665a4a73-6614-4dc5-aac0-410597da5b19%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-23 16:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 89bd12f6f1d37b31c5ee0057ef7f9178caf63747
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fb60eaf1-9537-45d2-99b7-1cdd49902265%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-23 17:36 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f3d82a64575321242e3b9bb63e5d6f2cb072acf7
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ab59dd07-2270-4d4f-a5a3-7a8e1bcef3e9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-23 17:37 UTC, merged