feat(aws-efs): Adding the new enums for throughputmode and lifecyclepolicy
aws/aws-cdk pull request #23200
Opened 2022-12-01 21:52 UTC by smsruthi

----

### All Submissions:

* [ yes] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-12-01 21:54 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2022-12-01 21:54 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to a test file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-12-01 22:05 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 4df234403e6e6bf684c0c1e25cf77eda45d824c0
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b32802b6-e6b4-4594-87bf-91b1412dcb6d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-01 22:17 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to a test file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-12-01 22:53 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5a20554754beda761623cbd9c71934ab89ec2ff2
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=318a3a35-c922-48b2-9c04-c2b8eb2679ce%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-02 10:36 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to a test file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

PRs must pass status checks before we can provide a meaningful review.

2022-12-02 10:54 UTC, mrgrain commented
Hey @smsruthi thanks for the PR!

I've exempted the integration test as I don't think we need one here.

However, would you mind updating the README: https://github.com/aws/aws-cdk/tree/5a20554754beda761623cbd9c71934ab89ec2ff2/packages/%40aws-cdk/aws-efs#create-an-amazon-efs-file-system

Particular the part about replacement seems out of date now. (see [Restrictions on switching throughput modes and changing provisioned amount](https://docs.aws.amazon.com/efs/latest/ug/performance.html#throughput-modes))

Additionally, with "Elastic Throughput mode is available only for file systems that are configured with the General Purpose performance mode."  we need to add some validation for this constraint. Similar to the one we have for [PROVISIONED](https://github.com/aws/aws-cdk/blob/5a20554754beda761623cbd9c71934ab89ec2ff2/packages/@aws-cdk/aws-efs/lib/efs-file-system.ts#L343).

Lastly, we also need unit tests covering the validation cases.

2022-12-02 10:56 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to a test file.

PRs must pass status checks before we can provide a meaningful review.

2022-12-05 20:50 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 925dd768c46fb51606644116602689a79106aa6c
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7757cf4a-7d77-423f-833e-c1230106b43d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-05 20:54 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f8058b571561bb2a92edcbecd16df9486cc0e06e
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=49b60d54-47d6-467f-80af-5072cd4dbae3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-05 21:50 UTC, sbyooki commented
- You still need to put comma at the end of
```
performanceMode: PerformanceMode.MAX_IO
```
If fails the build

- A test failed with this:
- ```
 Expected pattern: /PerformanceMode cannot be MaxIO when using ThroughputMode ELASTIC/
    Received message: "Property performanceMode cannot be MAX_IO when throughputMode is ELASTIC"
```
^^ Other than making the two strings the same, I suggest you change the language more towards ELASTIC ThroughputMode is not supported for file systems with PerformanceMode of MaxIO

2022-12-05 22:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 9b30b11f86b846943ae63036f13198e7223df9f2
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=cb4bdaa7-6eea-45cc-9cef-8a8584f63e88%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-05 23:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d3ed3f0d4a1f49409cf69c104a65069dd21965ce
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8b564193-c3f0-4b61-901a-ef01e983d09f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-05 23:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e6ced8fccbb3bd01cc9daf4d85db4305a10b7ed3
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2b521970-592c-45bb-9810-ded33f47369b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-06 00:24 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 604cfaca5fcaabd16d034dd9466b6be0f452cab7
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2f9de5f9-3ed8-458c-8790-edc63a51fc53%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-06 12:59 UTC, mrgrain requested changes
Looks good now, thank you. I'll take care of the text changes.

2022-12-06 12:59 UTC, mrgrain commented on packages/@aws-cdk/aws-efs/test/efs-file-system.test.ts
> +  }).toThrowError(/Elastic ThroughputMode is not supported for file systems with PerformanceMode of MaxIO/);
```suggestion
  }).toThrowError(/ThroughputMode ELASTIC is not supported for file systems with performanceMode MAX_IO/);
```

2022-12-06 12:59 UTC, mrgrain commented on packages/@aws-cdk/aws-efs/lib/efs-file-system.ts
> +      throw new Error('Elastic ThroughputMode is not supported for file systems with PerformanceMode of MaxIO');
```suggestion
      throw new Error('ThroughputMode ELASTIC is not supported for file systems with performanceMode MAX_IO');
```

2022-12-06 13:00 UTC, mrgrain commented on packages/@aws-cdk/aws-efs/README.md
> +⚠️ An Amazon EFS file system's performance mode can't be MaxIo while its throughputMode is ELASTIC.
```suggestion
⚠️ An Amazon EFS file system's performance mode can't be MAX_IO when its throughputMode is ELASTIC.
```

2022-12-06 13:00 UTC, mrgrain approved these changes

2022-12-06 13:38 UTC, merged