refactor(cx): typo in decryption policy
aws/aws-cdk pull request #23298
Opened 2022-12-09 11:54 UTC by kamil-forys

Decryption policy in cx contains a typo.
In few places non-existing word `Descryption` is used. It is confusing, because it could mean either `Decryption` or `Description`. This resolves this by changing it to `Decryption`.

----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-12-09 12:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 4856e1285dd3474742fdca135a89e80fc386214e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=693f9fb0-8f75-4311-9e49-3eee34370a67%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-09 12:34 UTC, mrgrain requested changes

2022-12-09 13:44 UTC, kamil-forys commented
Closing due to inability of changing existing feature flag.
Thank you for review @mrgrain.

2022-12-09 13:44 UTC, closed without merging

2024-03-22 23:24 UTC, ryanwilliams83 commented
@kamil-forys, please consider adding an additional feature flag for the same thing, but with the correct spelling.

if both the old and new flags are present and set to different values; you could error instructing people to remove one.