fix(cli): cdk deploy output hook failure reason if cloudformation failed by hook
aws/aws-cdk pull request #23397
Opened 2022-12-19 16:38 UTC by btan-godaddy

fix for issue: https://github.com/aws/aws-cdk/issues/21674
Reopen PR for https://github.com/aws/aws-cdk/pull/21675
----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2022-12-19 16:40 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2022-12-19 16:40 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/23397/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

PRs must pass status checks before we can provide a meaningful review.

2022-12-19 16:41 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/23397/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

PRs must pass status checks before we can provide a meaningful review.

2022-12-19 16:44 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/23397/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

PRs must pass status checks before we can provide a meaningful review.

2022-12-19 16:47 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 91902d2a05a2d165389d1dcfcea299bc714e0af9
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=64dbc38f-6819-4f1e-aefb-a74f5a29cbf2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-19 16:47 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b05c4b29d44317e2367b46c9eac4d56eef1b1811
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=cc71717e-dadd-49f8-8c38-9972f8812b94%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-19 16:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3a75fa76d50b6a8e777d2cbd645bd54a551f4909
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8489a59c-db47-4cf2-84e6-3d1876419d1b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2022-12-20 03:35 UTC, TheRealAmazonKendra requested changes
Looks like this has some formatting issues that are causing the build failure here. Please take a look to fix the build:
```
aws-cdk: /codebuild/output/src990062387/src/github.com/aws/aws-cdk/packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
aws-cdk:   420:1   error  Trailing spaces not allowed         no-trailing-spaces
aws-cdk:   422:44  error  Missing space before opening brace  space-before-blocks
aws-cdk:   423:7   error  Expected space(s) after "for"       keyword-spacing
aws-cdk:   424:9   error  Expected { after 'for-of'           curly
aws-cdk:   424:53  error  Missing space before opening brace  space-before-blocks
aws-cdk:   428:33  error  Trailing spaces not allowed         no-trailing-spaces
aws-cdk:   479:1   error  Trailing spaces not allowed         no-trailing-spaces
aws-cdk:   480:69  error  Missing space before opening brace  space-before-blocks
aws-cdk:   482:8   error  Expected space(s) before "else"     keyword-spacing
aws-cdk:   482:8   error  Expected space(s) after "else"      keyword-spacing
aws-cdk: /codebuild/output/src990062387/src/github.com/aws/aws-cdk/packages/aws-cdk/lib/cli.ts
aws-cdk:   28:1  warning  `./platform-warnings` import should occur before import of `./util/tracing`  import/order
aws-cdk: /codebuild/output/src990062387/src/github.com/aws/aws-cdk/packages/aws-cdk/lib/platform-warnings.ts
aws-cdk:   3:1  warning  `fs-extra` import should occur before import of `./logging`  import/order
aws-cdk: /codebuild/output/src990062387/src/github.com/aws/aws-cdk/packages/aws-cdk/test/api/stack-activity-monitor.test.ts
aws-cdk:   245:27  error  Strings must use singlequote  quotes
aws-cdk:   245:41  error  Missing trailing comma        comma-dangle
aws-cdk:   246:1   error  Trailing spaces not allowed   no-trailing-spaces
aws-cdk:   258:31  error  Strings must use singlequote  quotes
aws-cdk:   258:48  error  Missing trailing comma        comma-dangle
aws-cdk: âœ– 17 problems (15 errors, 2 warnings)
```
We need a passing build before we can provide a meaningful review.

2022-12-20 17:34 UTC, btan-godaddy commented
> Looks like this has some formatting issues that are causing the build failure here. Please take a look to fix the build:
> 
> ```
> aws-cdk: /codebuild/output/src990062387/src/github.com/aws/aws-cdk/packages/aws-cdk/lib/api/util/cloudformation/stack-activity-monitor.ts
> aws-cdk:   420:1   error  Trailing spaces not allowed         no-trailing-spaces
> aws-cdk:   422:44  error  Missing space before opening brace  space-before-blocks
> aws-cdk:   423:7   error  Expected space(s) after "for"       keyword-spacing
> aws-cdk:   424:9   error  Expected { after 'for-of'           curly
> aws-cdk:   424:53  error  Missing space before opening brace  space-before-blocks
> aws-cdk:   428:33  error  Trailing spaces not allowed         no-trailing-spaces
> aws-cdk:   479:1   error  Trailing spaces not allowed         no-trailing-spaces
> aws-cdk:   480:69  error  Missing space before opening brace  space-before-blocks
> aws-cdk:   482:8   error  Expected space(s) before "else"     keyword-spacing
> aws-cdk:   482:8   error  Expected space(s) after "else"      keyword-spacing
> aws-cdk: /codebuild/output/src990062387/src/github.com/aws/aws-cdk/packages/aws-cdk/lib/cli.ts
> aws-cdk:   28:1  warning  `./platform-warnings` import should occur before import of `./util/tracing`  import/order
> aws-cdk: /codebuild/output/src990062387/src/github.com/aws/aws-cdk/packages/aws-cdk/lib/platform-warnings.ts
> aws-cdk:   3:1  warning  `fs-extra` import should occur before import of `./logging`  import/order
> aws-cdk: /codebuild/output/src990062387/src/github.com/aws/aws-cdk/packages/aws-cdk/test/api/stack-activity-monitor.test.ts
> aws-cdk:   245:27  error  Strings must use singlequote  quotes
> aws-cdk:   245:41  error  Missing trailing comma        comma-dangle
> aws-cdk:   246:1   error  Trailing spaces not allowed   no-trailing-spaces
> aws-cdk:   258:31  error  Strings must use singlequote  quotes
> aws-cdk:   258:48  error  Missing trailing comma        comma-dangle
> aws-cdk: âœ– 17 problems (15 errors, 2 warnings)
> ```
> 
> We need a passing build before we can provide a meaningful review.

Will take a look! Thanks

2023-01-03 19:12 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/23397/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

PRs must pass status checks before we can provide a meaningful review.

2023-01-03 19:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c06539a138239277c8e025d3a925f71967bb5b36
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9573a5c6-504a-47cd-80d5-f3fe8f51be20%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-05 06:26 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/23397/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

PRs must pass status checks before we can provide a meaningful review.

2023-01-05 06:27 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/23397/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

PRs must pass status checks before we can provide a meaningful review.

2023-01-05 06:34 UTC, btan-godaddy commented
@TheRealAmazonKendra hey, I fixed build and test,   it cannot pass pr linter, but there is no existing integration test for this, what can I do?

2023-01-05 07:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: afcd425e7e9f2c03ef047494988aeeeff78b7fa8
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=55a64723-8de1-405e-8cc8-828118b55cc0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-05 07:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6d60f183e4b393f109b58c6293ae595959166275
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5f741660-2339-4a48-83d0-aae4f88d942b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-09 18:23 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f1d679b701d6d355aac5249268b3e65d24225046
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1d0e9179-91d2-4072-88df-a21ad5394403%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-11 00:09 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2023-01-19 00:08 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2023-01-19 00:08 UTC, closed without merging

2023-01-19 00:11 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/23397/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

PRs must pass status checks before we can provide a meaningful review.