feat(appsync): js resolver support
aws/aws-cdk pull request #23551
Opened 2023-01-04 00:53 UTC by MrArnoldPalmer

Adds support for resolvers using the APPSYNC_JS runtime. Adds new props for specifying `Code` and `Runtime` on both `Resolver` and `Function` constructs. Adds test covering basic JS resolver usage
----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-01-04 00:55 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2023-01-04 00:55 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

PRs must pass status checks before we can provide a meaningful review.

2023-01-04 00:56 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

PRs must pass status checks before we can provide a meaningful review.

2023-01-04 00:56 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

PRs must pass status checks before we can provide a meaningful review.

2023-01-04 01:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 07f705736c5e61a1a25ba5bc9f15a9c85decc328
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fbe09197-9980-4942-aaa0-d63429823356%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-04 20:44 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

PRs must pass status checks before we can provide a meaningful review.

2023-01-04 21:21 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 94ca30261055b762b8acd111e4c3b9e6a3686bc2
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ee530d15-3533-451c-a838-6d5d3d3f8009%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-04 21:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 657894488691439d229a0281e3e711863c5f3b2d
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5317ce73-54aa-4c04-9d3e-314b83cd586d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-04 22:42 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 61a081f4fa5c329f7273ef766f6bf16a581ef14b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=67f86297-48d5-4d76-995b-7e8c0097ea32%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-05 14:13 UTC, corymhall requested changes
Just a couple of comments

2023-01-05 14:13 UTC, corymhall commented on packages/@aws-cdk/aws-appsync/lib/appsync-function.ts
> +   * @default - no function runtime, VTL maping templates used
```suggestion
   * @default - no function runtime, VTL mapping templates used
```

2023-01-05 14:13 UTC, corymhall commented on packages/@aws-cdk/aws-appsync/lib/resolver.ts
> +   * @default - no function runtime, VTL maping templates used
```suggestion
   * @default - no function runtime, VTL mapping templates used
```

2023-01-05 14:13 UTC, corymhall commented on packages/@aws-cdk/aws-appsync/lib/runtime.ts
> +  public toProperties(): CfnFunctionConfiguration.AppSyncRuntimeProperty {
I don't think we should expose the L1 layer since this is a public API. I think
we should create a new interface that matches.

2023-01-05 14:13 UTC, corymhall commented on packages/@aws-cdk/aws-appsync/test/integ.js-resolver.ts
> +new IntegTest(app, 'JsResolverIntegTest', { testCases: [stack] });
Since this resolver is writing a record to dynamodb can also write an assertion
that asserts that the record exists in the table?

2023-01-05 17:54 UTC, onlybakam commented on packages/@aws-cdk/aws-appsync/lib/appsync-function.ts
> +    if (props.runtime && !props.code) {
mapping templates and code should also be mutually exclusive. can we add a check here as well?

2023-01-05 17:54 UTC, onlybakam commented on packages/@aws-cdk/aws-appsync/lib/resolver.ts
> +    if (props.runtime && !props.code) {
mapping templates and code should also be mutually exclusive. can we add a check here as well?

2023-01-05 18:04 UTC, onlybakam commented on packages/@aws-cdk/aws-appsync/test/appsync-js-resolver.js
> +  return JSON.stringify({
you shouldnt stringify this. just return an object.

2023-01-05 18:05 UTC, onlybakam commented on packages/@aws-cdk/aws-appsync/test/appsync-js-resolver.js
> +  return JSON.stringify(ctx.result)
no need to stringify the result

2023-01-05 21:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0417d20bf33dc245021bb0f6c6a5bc0e5e0a8c30
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c28a7808-5602-4c87-b613-d8a0949bd315%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-05 23:20 UTC, onlybakam approved these changes
LGTM

2023-01-06 20:21 UTC, corymhall approved these changes

2023-01-06 21:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 529f3320b8790b622d3e9a6bc8511c925f8b232a
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=01a3c3f5-7225-4dcd-81da-0d3962674807%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-06 21:02 UTC, merged

2023-01-13 09:56 UTC, abhi211199 commented
Thanks for this feature! 
When can we expect the latest version(2.60.0) of `aws-appsync-alpha` in https://www.npmjs.com/package/@aws-cdk/aws-appsync-alpha package?

2023-01-13 11:50 UTC, hoegertn commented
AppSync was merged to core in 2.60.0 so no alpha package needed anymore.