feat(core): allow asset bundling on docker remote host / docker in docker
aws/aws-cdk pull request #23576
Opened 2023-01-05 15:41 UTC by webratz

Fixes #8799 

This implements an alternative variant on how to put get files into bundling containers. This is more flexible in its use cases for complex Docker setup scenarios but more complex and slower. Therefore it is not enabled as a default, but as an additional option.

For details to the approach please refer to the linked issue.

----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [X] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-01-05 15:43 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2023-01-05 15:43 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

PRs must pass status checks before we can provide a meaningful review.

2023-01-05 15:44 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

PRs must pass status checks before we can provide a meaningful review.

2023-01-05 16:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e804023fa6d2df1b3272a638027c02a8e220a563
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=67b4a8fc-f349-493d-929a-9ce2f119fddd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-05 18:25 UTC, mrgrain commented
This is great! What I'm currently wondering is if this should be a prop, feature flag or ENV variable. 🤔 

Having it as a prop feels odd in the sense that it's very environment dependent. But then we do the same with local bundling already. @rix0rrr do you have a view how these kind of options should be enabled/disabled?

2023-01-09 08:04 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e66743622707ced510dbeda9840db13e3171354b
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f971e339-2f2c-4f49-b956-cb68afc4ee5c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-13 08:32 UTC, webratz commented
did you get to a decision on how enabling of this mode should be implemented?

2023-01-14 12:15 UTC, mrgrain commented
Still on it sorry. Had a busy week.

2023-01-16 10:48 UTC, mrgrain commented
Okay I've arrived at the conclusion that a prop is the best option here. It's the only way to enable other uses as well, so if a team wants to implement this based on an environment variable they could do something like:
```ts
{
   fileCopyVariant: process.env.BUNDLING_FILE_COPY_VARIANT 
}
```
Similar applies to using a Context value.

Still need to think about naming, reviewing and manually testing this locally.

---

Apologies in advance but this PR will likely take me a couple more weeks. Just so you know in case your planning depends on it.

2023-01-16 13:12 UTC, webratz commented
Sure, no problem. Feel also free to edit the branch / fork it again or so, if that helps you to speed up things. The overall important thing is the outcome in the end: A more flexible way that allows to use docker bundling in more situations than today.

2023-01-18 15:21 UTC, mrgrain requested changes
I'm going back and fourth on the naming of things. Will need to sleep over it.

You can get started on the other changes, but mostly if you could make the build pass (rosetta documentation error), I can use this branch to do a full build and run some proper tests using Docker in Docker

2023-01-18 15:21 UTC, mrgrain commented on packages/@aws-cdk/core/lib/bundling.ts
> +export class DockerImageBundlingCopyHelper {
I'd also suggest this class takes `options` in the constructor and exposes a run() method.
Then you do the same for `AssetStagingBindMount`.

In `AssetStaging.bundle()` you can replace the code with a switch:
```ts
switch (options.assetStagingType) {
  case BundlingFileCopyVariant.VOLUME_COPY:
    new AssetStagingVolumeCopy(options).run();
    break;
  case BundlingFileCopyVariant.BIND_MOUNT:
  default:
    new AssetStagingBindMount(options).run();
    break;
}

2023-01-18 15:21 UTC, mrgrain commented on packages/@aws-cdk/core/lib/asset-staging.ts
> +        }
See other comments
```ts
switch (options.assetStagingType) {
  case BundlingFileCopyVariant.VOLUME_COPY:
    new AssetStagingVolumeCopy(options).run();
    break;
  case BundlingFileCopyVariant.BIND_MOUNT:
  default:
    new AssetStagingBindMount(options).run();
    break;
}
```

2023-01-20 08:09 UTC, webratz commented on packages/@aws-cdk/aws-lambda-go/README.md
> +       fileCopyVariant: BundlingFileCopyVariant.DOCKER_COPY,
i'm not entirely sure why it fails though, it seems like the import i added to one did not help either.

2023-01-20 08:11 UTC, webratz commented on packages/@aws-cdk/core/lib/bundling.ts
> +export class DockerImageBundlingCopyHelper {
no, i think it should be private. was just not sure on how to achieve it there, as it depends on the dockerExec which is also private and only available there

2023-01-20 08:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 871da219a93756bf2ee0decd84de9121dfebae8e
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9b245dbd-f27f-47bd-af4a-cae2bafed6a2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-20 08:17 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ed23041ce214c2981c8919155d7cf796fafd4ed8
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=15af1960-1491-4dce-8198-6cc81cf349f0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-20 08:17 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 813c8b77b22f60d58c4dfb0b16bd46664dc1a4bc
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=af32ed69-07f5-4b17-a244-c1ee718705ea%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-20 08:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1ca84966c760376a7b07fe4bbc17295b70f823ab
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=de767fb0-e79c-43dc-9a10-9993ae1a9399%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-20 09:08 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6bc93e1c0e137527aa323f9bc515046bc5d32f24
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b1403cb7-9b07-4d35-8b5b-5b33e2280530%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-20 09:56 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7b3798e0b0da1372d51bb669c6e1adf49ec61bae
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7977383f-2b1d-4b68-843b-74195f4ed803%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-20 09:58 UTC, webratz commented on packages/@aws-cdk/aws-lambda-go/README.md
> +       fileCopyVariant: BundlingFileCopyVariant.DOCKER_COPY,
should be fixed now. build passes with this.
the structural changes are not included yet, but should be good enough to test the approach now

2023-01-20 11:01 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 54b3a80e4d144ecf1974a1d207362bfd1ca914f3
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4b2da4ef-abe7-491a-bdee-ca17447d7692%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-20 11:09 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d94e232a1d03cabf0b18acb4a04bbecdfa72205e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b7be7dbd-c661-4cdc-abaf-cefe055c3aad%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-23 07:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5c98592a6c96eaf984fd600d9b3c0df18256cafe
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9f5784ef-22e6-4d04-8f5d-0cb4404a87cf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-23 07:59 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 056f48b10c54112549f5703bb55e678d99cc5f62
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=10e60b0a-89ab-43b1-8166-eb73573e550d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-23 10:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ace87a4fefc969aab30f041677c31ae457c33066
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ed3dba58-3ffe-4bd5-9f3a-0e751aaeb952%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-23 11:02 UTC, webratz commented
@mrgrain the current status should reflect the requested changes.
i hope i did not miss anything as I did it in a few batches in between other stuff :)

2023-01-24 14:38 UTC, mrgrain commented
Full build reference `7ab5371a-dd69-46a8-8c19-3cf0d68654d9`

2023-01-25 09:17 UTC, webratz commented
I have run a full local build of CDK also and run it on a sample project on our internal CICD system that has the docker by docker (with mounted docker socket) and all worked fine with the VOLUME_COPY mode.

2023-01-25 12:15 UTC, mrgrain commented on packages/@aws-cdk/core/lib/private/asset-staging.ts
> +    this.options.image.run({
I know this is currently unused but let's get ahead of ourselves.
```suggestion
    return this.options.image.run({
```

2023-01-25 12:18 UTC, mrgrain commented on packages/@aws-cdk/core/test/bundling.test.ts
> +
;)
```suggestion
```

2023-01-25 12:18 UTC, mrgrain commented on packages/@aws-cdk/core/lib/private/asset-staging.ts
> +}
```suggestion
}

```

2023-01-25 12:19 UTC, mrgrain commented on packages/@aws-cdk/core/lib/bundling.ts
> +
```suggestion
```

2023-01-25 12:33 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7be1cc521e83017b1d4dcb4b3678263ce8d6b5bc
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f6af7657-22e4-4d31-babe-c0d87b6d183d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-25 12:33 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: fa11118b2acf9b267b81e019b4a1ecd22bfffe49
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=755423e7-ceb0-4ff7-8fa4-798621106713%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-25 12:35 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 381e5bf5d3b6cc13be2963544c2bf2b729419cf1
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3de19c00-8088-4a37-a794-635e80c5497d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-25 12:35 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5a9b75eb091dbbbdcb49caff4bffb7365103abb6
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9d24b3d4-3511-403d-bf6e-d20c84551383%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-25 12:41 UTC, webratz commented on packages/@aws-cdk/core/test/docker-stub-cp.sh
> +echo "$@" > /tmp/docker-stub.input
made some more adjustments, hope i catched all occurences, but local test looks good.

2023-01-25 13:18 UTC, mrgrain commented on packages/@aws-cdk/core/lib/bundling.ts
> +   * The Which option to use to copy the source files to the docker container and output files back
```suggestion
   * The mechanism used to make source files available to the bundling container and to return the bundling output back to the host.
```

2023-01-25 13:19 UTC, mrgrain commented on packages/@aws-cdk/core/lib/bundling.ts
> + * The type of file copy that should be used for bundling
```suggestion
 * The mechanism used to make source files available to the bundling container and to return the bundling output back to the host
```

2023-01-25 13:20 UTC, mrgrain commented on packages/@aws-cdk/core/lib/bundling.ts
> +   * This is faster and simpler, but less portable than the other option.
```suggestion
   * This is faster and simpler, but less portable than `VOLUME_COPY`.
```

2023-01-25 13:21 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8640305efea70de7ae67be40d3079bab678267d6
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b2a5bd7c-28d2-4710-8ee8-4f882dc74155%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-25 13:22 UTC, mrgrain commented on packages/@aws-cdk/core/lib/bundling.ts
> +
```suggestion
  BIND_MOUNT = 'BIND_MOUNT',
```

2023-01-25 13:25 UTC, mrgrain commented on packages/@aws-cdk/core/lib/bundling.ts
> +export enum BundlingFileCopyVariant {
```suggestion
export enum BundlingFileAccess {
```

2023-01-25 13:26 UTC, mrgrain commented on packages/@aws-cdk/core/lib/bundling.ts
> +  readonly assetStagingType?: BundlingFileCopyVariant;
```suggestion
   * @default - BundlingFileAccess.BIND_MOUNT
   */
  readonly bundlingFileAccess?: BundlingFileAccess;
```

2023-01-25 13:28 UTC, mrgrain commented on packages/@aws-cdk/core/lib/private/asset-staging.ts
> +class AssetStagingBase {
```suggestion
abstract class AssetStagingBundlingBase {
```

2023-01-25 13:28 UTC, mrgrain commented on packages/@aws-cdk/core/lib/private/asset-staging.ts
> +interface AssetStagingCopyOptions extends BundlingOptions {
```suggestion
interface AssetStagingBundlingOptions extends BundlingOptions {
```

2023-01-25 13:30 UTC, mrgrain commented on packages/@aws-cdk/core/lib/private/asset-staging.ts
> +export class AssetStagingBindMount extends AssetStagingBase {
```suggestion
export class AssetBundlingBindMount extends AssetBundlingBase {
```

2023-01-25 13:30 UTC, mrgrain commented on packages/@aws-cdk/core/lib/private/asset-staging.ts
> +export class AssetStagingVolumeCopy extends AssetStagingBase {
```suggestion
export class AssetBundlingVolumeCopy extends AssetBundlingBase {
```

2023-01-25 13:30 UTC, mrgrain requested changes
update naming

2023-01-25 16:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 4750a5f3b88fa0a5805351e738baa343a0cc8a27
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e17d6c19-15b1-45ac-b384-818713695506%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-25 16:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 27026e5e3cc7fd8dbb6310d63c7597a836f7ec20
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e1bcbd66-b5a6-495a-97ce-78cf169da41f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-25 16:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 2890d541fa5bf3c2b327e2934fb5a20e41f333ae
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8ab5798a-e74b-4c20-9cab-3d302f8ab28b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-25 16:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 974762a169206d1dd3725a8f5edc23b8fcd3f990
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f5ee8f08-4e6a-4c48-8067-546eb391cab1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-25 16:39 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 325fdbb9bf64eddffbd4edda7166227b61e65a52
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=645f3043-f09a-4394-8eda-4085afe4328a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-26 14:29 UTC, mrgrain commented on packages/@aws-cdk/aws-lambda-go/README.md
> +import { BundlingFileAccess } from '@aws-cdk/core';
Let's move this import to `packages/@aws-cdk/aws-lambda-go/rosetta/default.ts-fixture`
Same for the other packages.

2023-01-26 14:31 UTC, mrgrain commented on packages/@aws-cdk/aws-lambda-go/lib/bundling.ts
> +import { BundlingFileAccess } from '@aws-cdk/core';
Use `cdk. BundlingFileAccess` instead
```suggestion
```

2023-01-26 14:31 UTC, mrgrain commented on packages/@aws-cdk/aws-lambda-go/lib/bundling.ts
> +  readonly bundlingFileAccess?: BundlingFileAccess;
```suggestion
  readonly bundlingFileAccess?: cdk.BundlingFileAccess;
```

2023-01-26 14:31 UTC, mrgrain commented on packages/@aws-cdk/aws-lambda-nodejs/README.md
> +import { BundlingFileAccess } from '@aws-cdk/core';
import -> rosetta fixture

2023-01-26 14:32 UTC, mrgrain commented on packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts
> +import { BundlingFileAccess } from '@aws-cdk/core';
Use `cdk. BundlingFileAccess` instead
```suggestion
```

2023-01-26 14:32 UTC, mrgrain commented on packages/@aws-cdk/aws-lambda-nodejs/lib/bundling.ts
> +  readonly bundlingFileAccess?: BundlingFileAccess;
```suggestion
  readonly bundlingFileAccess?: cdk.BundlingFileAccess;
```

2023-01-26 14:33 UTC, mrgrain commented on packages/@aws-cdk/aws-lambda-python/README.md
> +```
```suggestion
import -> rosetta and remove some whitespace
```ts
const entry = '/path/to/function';

new python.PythonFunction(this, 'function', {
  entry,
  runtime: Runtime.PYTHON_3_8,
  bundling: {
    bundlingFileAccess: BundlingFileAccess.VOLUME_COPY,
   },
});
```
```

2023-01-26 14:34 UTC, mrgrain commented on packages/@aws-cdk/core/test/private/asset-staging.test.ts
> +
```suggestion
```

2023-01-26 14:35 UTC, mrgrain commented on packages/@aws-cdk/core/test/private/asset-staging.test.ts
> +});
```suggestion
  });
});
```

2023-01-26 14:36 UTC, mrgrain commented on packages/@aws-cdk/core/test/staging.test.ts
> +// import * as child_process from 'child_process';
```suggestion
```

2023-01-26 15:06 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6590681f39ef8722c29564dcbfe64743340fca49
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b42465eb-1911-45f4-b85e-4d55271b1a57%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-26 15:30 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 4ecaf47d1f47980a0b57f8180cc2dc63cd316486
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c9c75301-fcbc-4c35-a97c-41a11520457f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-26 18:41 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: cb54c28750b5d14440736f9a95c8bc42f912938d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b74c0aa9-a721-49be-8614-fb478fe29336%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-27 13:28 UTC, mrgrain approved these changes

2023-01-27 14:11 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c4b09ee59f69d55a044a24ed748130e80fcffb92
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0d5d0227-1e49-427e-aabe-25eb998b6a63%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-27 14:11 UTC, merged