feat(logs): add unit to metric filter
aws/aws-cdk pull request #23608
Opened 2023-01-09 00:01 UTC by msambol

Allows attaching unit to a metric filter.

----

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [x] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [x] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-01-09 00:14 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f3dd69b5ada3fb8c3393cc936223a37d97faee6e
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4b6bd92d-7d30-472e-9a61-71c9e62a0ed4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-09 00:34 UTC, mcowgill-stripe commented
the packages folder shouldn't be in there?

2023-01-09 01:05 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3904e20254a8c53007f7119c036de8d5521a1aec
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7bb59ad5-4b19-4dd9-93f8-2ac6b7519fc5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-09 15:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7e15658172ba17f0b0dea981af21b21e9329e000
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e4783cc9-9fa0-4905-b0d5-2bbd23be9753%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-11 04:03 UTC, msambol commented
@TheRealAmazonKendra Can I ping you for a review here? :)

2023-01-12 01:22 UTC, TheRealAmazonKendra requested changes
Thank you for your contribution! I have one question/comment/suggestion inline.

2023-01-12 01:22 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/aws-logs/lib/metric-filter.ts
> +        unit: props.unit ?? Unit.NONE,
If this were just the following, what would the CloudFormation behavior be?

```suggestion
        unit: props.unit,
```
I'm leaning toward not wanting the conditional of adding `Unit.NONE` to this but I want to make sure I understand what CloudFormation does in this case. Does it assign `Unit.NONE` under the hood?

In general, we don't want to make a change to a template if it isn't changing the behavior of that template. It concerns users when they see changes to their template without changing their code.

2023-01-12 16:31 UTC, msambol commented
@TheRealAmazonKendra Thanks for the feedback! I did confirm the unit is undefined when not specified (left below), so I removed the default of `NONE`. 

<img width="1480" alt="Screen Shot 2023-01-12 at 11 13 26 AM" src="https://user-images.githubusercontent.com/3310356/212124934-b4282da9-f4bc-47f0-8be4-7764822c578f.png">

2023-01-12 21:35 UTC, TheRealAmazonKendra approved these changes
This looks great! Thank you for the work on this!

2023-01-12 21:35 UTC, merged