feat(aws-lambda-event-sources): Allow for IBucket in S3 Event Source
aws/aws-cdk pull request #23797
Opened 2023-01-23 21:56 UTC by piotrmoszkowicz

In my case I have S3 Bucket in different Stack than lambdas and therefor I need to create new reference to properly add Event Source (to avoid circular dependency between stacks). While I tried getting reference by bucket name with `s3.Bucket.fromBucketName` I saw that in returns `s3.IBucket`, but `S3EventSource` accepts only `s3.Bucket`, but it uses only one method, which is available in `IBucket` interface. I've also checked for other event sources and they tend do it that way. I am unsure how shall I name this PR (technically I see it as a feature, but also maybe fix..?) - any help is welcome!

----

### All Submissions:

* [X] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### New Features

* [X] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [X] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-01-23 21:59 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.

2023-01-23 21:59 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to a test file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.
	❌ The title of the pull request should omit 'aws-' from the name of modified packages. Use 'lambda-event-sources' instead of 'aws-lambda-event-sources'.

PRs must pass status checks before we can provide a meaningful review.

2023-01-23 22:25 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f66d2e87c881820ca5c9e1c2aa1a461cac3526ef
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=82f1cdd3-0fe1-41a2-9e95-67f18bcfd41b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-24 04:58 UTC, TheRealAmazonKendra requested changes
I think that this is going to cause a breaking change in other languages, even thought it's fine in typescript. So, this will need to be under a feature flag. This is just my initial response. I need to dig a little deeper to see if this is going to potentially cause more issues.

From your comments, however, I think this is a fix, so this will require testing. The pr linter will yell at you when you change it to a fix.

2023-01-26 08:24 UTC, piotrmoszkowicz commented
I will come back to that, thanks!

2023-02-14 00:09 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the BUILD FAILING state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2023-02-22 00:09 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2023-02-22 00:09 UTC, closed without merging