feat(redshift): Tables can include comments
aws/aws-cdk pull request #23847
Opened 2023-01-26 10:56 UTC by Rizxcviii

Adds comments to tables.

closes #22682

----

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing guide?](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md)

### Adding new Construct Runtime Dependencies:

* [ ] This PR adds new construct runtime dependencies following the process described [here](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md/#adding-construct-runtime-dependencies)

### New Features

* [ ] Have you added the new feature to an [integration test](https://github.com/aws/aws-cdk/blob/main/INTEGRATION_TESTS.md)?
	* [ ] Did you use `yarn integ` to deploy the infrastructure and generate the snapshot (i.e. `yarn integ` without `--dry-run`)?

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-01-26 11:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: dc504a70f7881b934f9c46053e7e51d8e4e88378
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7f588d1d-f32f-41c9-a77a-4422f51bd5a4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-01-30 20:56 UTC, comcalvi requested changes
nice work 🙂 could we change the name from `comment` to `tableComment`, since SQL supports comments on columns as well?

2023-01-30 20:56 UTC, comcalvi commented on packages/@aws-cdk/aws-redshift/lib/table.ts
> +  readonly comment?: string;
```suggestion
  readonly tableComment?: string;
```

2023-01-30 20:56 UTC, comcalvi commented on packages/@aws-cdk/aws-redshift/lib/private/handler-props.ts
> +  readonly comment?: string;
```suggestion
  readonly tableComment?: string;
```

2023-01-30 20:56 UTC, comcalvi commented on packages/@aws-cdk/aws-redshift/lib/private/database-query-provider/table.ts
> +  if (tableAndClusterProps.comment) {
```suggestion
  if (tableAndClusterProps.tableComment) {
```

2023-01-31 11:36 UTC, Rizxcviii commented on packages/@aws-cdk/aws-redshift/lib/table.ts
> +  readonly comment?: string;
Done

2023-01-31 11:36 UTC, Rizxcviii commented on packages/@aws-cdk/aws-redshift/lib/private/database-query-provider/table.ts
> +  if (tableAndClusterProps.comment) {
Done

2023-01-31 12:43 UTC, Rizxcviii commented on packages/@aws-cdk/aws-redshift/lib/private/handler-props.ts
> +  readonly comment?: string;
Done

2023-01-31 18:19 UTC, comcalvi approved these changes

2023-02-01 00:05 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 058de7189978af1edfcce792af4718e9cb359397
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5226260b-9b04-48fa-9a13-c0dbf474f7fa%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-02-02 22:58 UTC, comcalvi submitted a review, later dismissed

2023-02-03 10:39 UTC, Rizxcviii commented
@mergifyio refresh

2023-02-03 10:44 UTC, Rizxcviii commented
@Mergifyio refresh

2023-02-03 10:51 UTC, Rizxcviii commented
@Mergifyio refresh

2023-02-03 10:59 UTC, Rizxcviii commented
@Mergifyio refresh

2023-02-03 11:04 UTC, Rizxcviii commented
@Mergifyio refresh

2023-02-03 11:13 UTC, Rizxcviii commented
@Mergifyio refresh

2023-02-03 11:19 UTC, Rizxcviii commented
@comcalvi Within my fork, I've created a personal access token with read/write access to workflows, added it as a secret to the repository, and the merge cannot happen for these issues.

> Base branch update has failed

> refusing to allow a GitHub App to create or update workflow .github/workflows/close-stale-prs.yml without workflows permission
err-code: 9AD93

2023-02-03 12:13 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f15ea45c3e82015055947bb149f1b0c2b55b8d1e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b32c44ae-36a9-42f2-bb7b-7d71b4363f67%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-02-03 17:19 UTC, comcalvi commented
very strange...not sure what's going on here

2023-02-03 17:19 UTC, comcalvi approved these changes

2023-02-03 17:59 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f30fb7617960fa0372b8baf49b66d733a48dcf9d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=de312847-ca52-48e1-85a4-2a086f5bcdac%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-02-03 17:59 UTC, merged