feat(core): support setting size class in bytes
aws/aws-cdk pull request #24136
Opened 2023-02-13 15:24 UTC by pattasai

> REPLACE THIS TEXT BLOCK
>
> Describe the reason for this change, what the solution is, and any
> important design decisions you made. 
>
> Remember to follow the [CONTRIBUTING GUIDE] and [DESIGN GUIDELINES] for any
> code you submit.
>
> [CONTRIBUTING GUIDE]: https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md
> [DESIGN GUIDELINES]: https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md

Closes #<issue number here>.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-02-13 15:26 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-02-13 15:26 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-02-13 15:27 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-02-13 15:27 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-02-13 16:04 UTC, rix0rrr requested changes

2023-02-13 16:04 UTC, rix0rrr commented on packages/@aws-cdk/aws-apigateway/lib/restapi.ts
> +  readonly minimumCompressionSize?: number;
Oops! This change wasn't supposed to be in this PR :)

2023-02-13 16:04 UTC, rix0rrr commented on packages/@aws-cdk/aws-apigateway/lib/restapi.ts
> +      minimumCompressionSize: props.minimumCompressionSize,
Nor this one.

2023-02-13 16:04 UTC, rix0rrr commented on packages/@aws-cdk/aws-apigateway/test/restapi.test.ts
> +    });
Nor this one.

2023-02-13 16:04 UTC, rix0rrr commented on packages/@aws-cdk/core/lib/size.ts
>    public static readonly Tebibytes = new StorageUnit('tebibytes', 1024 * 1024 * 1024);
The `1 / 1024` makes me uneasy. Computers aren't good at representing fractional numbers and getting math with them correct.

Can we shift all fractions up by `1024` ? Make `bytes = 1`, `kibibytes = 1024`, etc ?

2023-02-13 16:04 UTC, rix0rrr commented on packages/@aws-cdk/core/test/size.test.ts
> +  });
Couple more tests here to be sure. Especially conversions between bytes and other units will be interesting.

2023-02-13 16:04 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 55040792840eaa9f1fbeb0596c7bf6f43de23bb2
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e7b0732d-88ee-498a-925c-3fa029226d68%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-02-13 16:38 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-02-14 13:09 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-02-14 13:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 18a15e24ae52b4675c21ec80970d2da03dadc949
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0f922378-4ed2-4005-b9eb-46b85ca1548b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-02-15 10:11 UTC, rix0rrr requested changes
Please fix the formatting of the PR body:

![image](https://user-images.githubusercontent.com/524162/218997965-05a060a5-34e8-4b5e-a09f-e7041f166c4f.png)

And try to write your PR body as a couple of sentences that introduce the motivation for the change and the changes that were made.

Also please still get rid of the changes that weren't supposed to be in this PR.

2023-02-15 10:14 UTC, rix0rrr commented
If you don't know what to write, in the PR body, take a look at some other PRs to get inspiration. I will link a couple of mine here:

https://github.com/aws/aws-cdk/pull/24175
https://github.com/aws/aws-cdk/pull/24053
https://github.com/aws/aws-cdk/pull/24027
https://github.com/aws/aws-cdk/pull/23986

2023-02-15 15:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f7c5bac4a05f393935dac6588094faf0fa2b7cb4
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=32e1643b-3776-4fd2-a692-9bef144a2c7f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-02-15 16:53 UTC, rix0rrr approved these changes

2023-02-15 19:06 UTC, kaizencc commented on packages/@aws-cdk/core/test/size.test.ts
> +
```suggestion
```

2023-02-15 19:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 50c83fe398202873382ef44008c3096461fc1549
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=66c17c05-f4bd-4bf0-a01c-047bebfa9931%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-02-15 19:51 UTC, kaizencc approved these changes

2023-02-15 20:35 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0ea40c6eb950aa163638c633165845e22ed2e8ba
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=59a52d97-9fc3-4b45-be6e-23f4f06e899b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-02-15 20:36 UTC, merged