feat(custom-resources): AwsCustomResource passthrough physicalResourceId when omit it in onUpdate
aws/aws-cdk pull request #24194
Opened 2023-02-16 02:43 UTC by konokenj

AwsCustomResource is now able to omit `physicalResourceId` in `onUpdate` with passthrough it from request. This is useful when users want to call an update API without resoure replacing.

Some `UPDATE` AWS APIs responses with an empty body. When users want to call these APIs using AwsCustomResource, users can't specify physicalResourceId by `PhysicalResourceId.fromResponse()`. Furthermore, when the Create API generates an unpredictable ID and this must be passed to the Update API, this Construct could not be used. For example, following APIs match this situation:

- https://docs.aws.amazon.com/athena/latest/APIReference/API_UpdateNotebook.html
- https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_UpdateUser.html

Closes #23843.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-02-16 02:45 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-02-16 02:45 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-02-16 03:24 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d9e1d9b5efce6b6ebab7daeed8ac814fe4114cdb
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=943730c5-9477-4902-b07b-1aa1193a1695%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-02-16 03:36 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f248f90c0272898c53915e6d6a727571507d888e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3ca0cd04-40fa-4600-b8b5-88b1dd02838c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-02-16 03:41 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f14dfd1405b9d4f42c4ff8215bf06a13863979ae
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bcafca07-125c-49fb-b764-a37051c19582%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-02-16 21:13 UTC, comcalvi commented
>AwsCustomResource is now able to omit physicalResourceId in onUpdate with passthrough it from request. This is useful when users want to call an update API without resoure replacing.

I'm not sure what "passthrough it from request" means, could you please elaborate? 

>call an update API without resoure replacing.

I don't understand this either. Does it mean that today, it is impossible to call `onUpdate` without a replacement of the custom resource?

2023-02-17 03:56 UTC, konokenj commented
Hi @comcalvi, thank you for response.

> I'm not sure what "passthrough it from request" means, could you please elaborate?

Lambda backed custom resources recieves `physicalResourceId` in request event on update. The handler function has responsibility to return same `physicalResourceId` when the resource is not replaced.

> The value returned for a PhysicalResourceId can change custom resource update operations. If the value returned is the same, it is considered a normal update. If the value returned is different, AWS CloudFormation recognizes the update as a replacement and sends a delete request to the old resource.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-requesttypes-update.html

But currently, users of AwsCustomResource construct must specify `physicalResourceId` by hand (`fromResponse()` or `.of()`). There is no way to copy from request, although there are AWS APIs that response with empty bodies. This PR adds ability to copy that.

>> call an update API without resoure replacing.
>
> I don't understand this either. Does it mean that today, it is impossible to call onUpdate without a replacement of the custom resource?

No, I intended to allow users to indicate their intention to copy PhysicalResourceId.

(I'm sorry if this is a problem caused by my poor English skill.)

2023-03-01 21:36 UTC, comcalvi submitted a review, later dismissed
To confirm, leaving the `PhysicalResourceId` undefined will tell CFN to use the value that was passed to`onCreate`? If so, this makes perfect sense. Please create a new unit test in `test/aws-custom-resource` that verifies the updated error checking logic you've added

2023-03-02 05:52 UTC, konokenj commented
I added unit tests.

> To confirm, leaving the `PhysicalResourceId` undefined will tell CFN to use the value that was passed to `onCreate`?

`PhysicalResourceId` is not rendered in CFn template when omit in `onUpdate`. When handler function doesn't recieve `PhysicalResourceId` from request, it uses previous value. 
https://github.com/aws/aws-cdk/blob/0ebbf58bdd3307f536334beb5d1153e3ef660f18/packages/%40aws-cdk/custom-resources/lib/aws-custom-resource/runtime/index.ts#L153

2023-03-02 06:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 028a439ff3a5efcd23f725e789db27054af99683
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2350ed62-3dfe-41f3-a3aa-bae82104683b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-03 22:25 UTC, comcalvi requested changes

2023-03-06 09:24 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 734ea2da7b40f4facd01df1fb4422e0d36071fac
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f71bdf17-16bf-490c-ad92-5728d9d47640%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-06 11:38 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: cf5dd09e611dffc468c8277b1c7366c09e8bc095
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8bb06160-912d-470e-9033-c0e9b3c3c31d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-06 12:54 UTC, konokenj commented on packages/@aws-cdk/custom-resources/test/aws-custom-resource/aws-custom-resource.test.ts
> +  ).toThrow(/`onCreate`.+`onUpdate`.+`onDelete`/);
I reverted style changes.

2023-03-06 12:55 UTC, konokenj commented
I fixed code style and error messages. Could you review again?

2023-03-06 13:56 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1880369541ba27a8d74fb4eee1f370d8a2270c71
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1bef61a4-2e65-4326-8ef5-71bfb805bbf3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-08 23:18 UTC, comcalvi approved these changes

2023-03-08 23:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7627daddccd50595f58911a9df6fdd3f0ac4b95f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0ac4f17b-c55e-4929-876c-394919edc952%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-08 23:58 UTC, merged