Fix missing lerna dependency
aws/aws-cdk pull request #24217
Opened 2023-02-17 17:13 UTC by timmattison

Either lerna needs to be installed as a dependency or run through npx. Otherwise build.sh fails in the middle of a build on a system without it installed.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-02-17 17:15 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-02-17 17:15 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-02-17 17:38 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-02-17 17:40 UTC, timmattison commented
Exemption Request

My changes un-break the build. I'm not sure how I would write a test for it.

2023-02-17 17:42 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-02-17 17:53 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: bb36d371c20ec34d04d9d7115190a0618da7fe44
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2120d67c-c7a3-4541-b1fb-6e40560a1c67%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-09 22:12 UTC, madeline-k approved these changes
Thanks for the PR @timmattison! Changing this to a "chore" instead of a "fix" because it's developer/contributor facing and not customer facing. (Anything labeled as "fix" or "feat" ends up in the changelog and release notes, which is not necessary here.)

2023-03-09 22:59 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f280be384b4a068e8d4c5ec4a3c71e9d1e05baaf
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2110652a-1276-4f6d-9ad4-141a65415831%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-10 10:02 UTC, mrgrain requested changes
@timmattison @madeline-k  Are you sure that's what's going on? Because in line 38 the scripts adds `node_modules/.bin` to the path and in line 48 it does a `yarn install` which would install lerna at the right version.

And this does work on my machine (I know, I know) and in CI. So something else must be going on.

Either way, if we want to use `npx` it would at least have to be qualified to the correct version `npx lerna@^4.0.0`


PS: @madeline-k feel free to just dismiss my review if I'm blocking something =)

2023-03-17 00:03 UTC, madeline-k commented
> @timmattison @madeline-k Are you sure that's what's going on? Because in line 38 the scripts adds `node_modules/.bin` to the path and in line 48 it does a `yarn install` which would install lerna at the right version.
> 
> And this does work on my machine (I know, I know) and in CI. So something else must be going on.
> 
> Either way, if we want to use `npx` it would at least have to be qualified to the correct version `npx lerna@^4.0.0`
> 
> PS: @madeline-k feel free to just dismiss my review if I'm blocking something =)

@mrgrain You are completely correct, the script does install `lerna`. And the goal of this change is to actually use the version of `lerna` installed locally in the projects dependencies. The problem now is that running the `lerna` command will run whatever version is installed globally, if there is one. I think the original title of the PR was a bit misleading. The `lerna` dependency is not missing, we just need the script to execute it from the projects dependencies. 

(The `npx` command will run requested packages from the local project dependencies first, before trying to get it from the npm cache or the internet. See [docs](https://docs.npmjs.com/cli/v7/commands/npx).)

2023-03-17 00:04 UTC, madeline-k approved these changes

2023-03-17 00:06 UTC, madeline-k commented
@mrgrain, dismissing your review. We can always revert this if I am incorrect on something, but I think the change is good as is.

2023-03-17 00:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f9202d8643b0151a416ca78bab379059b19785fd
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5e18e7cb-9c47-4fbc-8dfc-ccaae77fc2cb%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-23 00:08 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2023-03-24 00:08 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2023-03-25 00:08 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2023-03-26 00:09 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2023-03-27 00:08 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2023-03-28 00:09 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2023-03-28 20:01 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2023-03-29 00:10 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2023-03-29 00:21 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2023-03-29 12:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d89d4925e4e63a29ad8a98f9e4e1fb9cb93bb9bc
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=91360af2-f89c-437f-9df4-9ed83b5425bb%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-04-03 20:49 UTC, TheRealAmazonKendra approved these changes
Looks like our automations weren't working correctly here when previously approved.

2023-04-03 20:51 UTC, TheRealAmazonKendra submitted a review, later dismissed
Actually, it looks like a piece of the command got removed with this change. We want the concurrency setting left in there.

2023-04-11 22:26 UTC, madeline-k requested changes

2023-04-11 22:26 UTC, madeline-k commented on build.sh
> +time npx lerna run $bail --stream $runtarget || fail
Add back the concurrency flag (which was added after the original authoring of this PR):
```suggestion
time npx lerna run $bail --stream --concurrency=$concurrency $runtarget || fail
```

Thanks @TheRealAmazonKendra for catching that.

2023-04-11 22:26 UTC, madeline-k submitted a review, later dismissed

2023-04-11 23:11 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: bc3cdba7ced504ed88f9fd20363ebfae600c9598
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0678ae81-9b9e-4f5c-904a-acf3e10196a9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-04-12 21:45 UTC, TheRealAmazonKendra approved these changes

2023-04-12 22:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 63077f33b07a86a3c56619a8f22e38998e7ef450
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=86205210-2d68-43a1-ad5e-f4091985910e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-04-12 23:52 UTC, merged

2023-04-12 23:52 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e1b4180306a08c3811c3df16c92dcc1bfe7d5684
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f1b6631c-d0ae-49f1-930d-dc56100b18e5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->