feat(s3): added excludedKeyActions parameter to grantWrite
aws/aws-cdk pull request #24211
Opened 2023-02-17 11:36 UTC by lpizzinidev

I've added an optional array parameter `excludedKeyActions` that will exclude the specified actions from the permissions given by the `grantWrite` method call.

Closes #24074 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-02-17 11:38 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-02-17 11:38 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-02-17 12:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: dbdce48128b240b407a01a9bb313d062967490d7
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=955773cc-9aa8-48de-a61c-cd387ae3b1b9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-02-17 15:02 UTC, lpizzinidev commented
> The pull request linter fails with the following errors:
> 
> ```
> ❌ Features must contain a change to a README file.
> ```
> 
> PRs must pass status checks before we can provide a meaningful review.
> 
> If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

Exemption Request.

The [S3 README](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-s3/README.md) doesn't contain references to the `grantWrite` method so there is nothing to change there.
Let me know if you'd like me to add an explanation of the method.

2023-02-17 15:05 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-02-20 21:57 UTC, TheRealAmazonKendra submitted a review, later dismissed
Adding an exclusion filter doesn't really fit the pattern of any of the rest of these functions. I would prefer to see a function that explicitly adds the patterns a user wants than one that filters out patterns.

2023-02-22 08:38 UTC, lpizzinidev commented
@TheRealAmazonKendra 
Thanks for the feedback!
I've changed the parameter to `allowedActions`, granting permission only to specified actions.
Please let me know if this is ok or if you need more changes.

2023-02-22 09:13 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 04115e0ecc890e07fc90106013da7c0ae9af2e77
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0c27fc02-2b98-4f47-8192-72f77d0289f5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-02-23 01:05 UTC, TheRealAmazonKendra requested changes
Just a few suggested changes to the contract here.

2023-02-23 01:05 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/aws-s3/lib/bucket.ts
> +   * @param allowedActions: Include only certain actions in the permissions
```suggestion
   * @param allowedActionPatterns: Restrict the permissions to certain list of action patterns (default '*')
```

2023-02-23 08:33 UTC, lpizzinidev commented
@TheRealAmazonKendra 
Just a note, I removed the default value from the rest parameter since TS doesn't allow it and handled the default to `this.writeAction` in the function logic.

2023-02-23 08:59 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f383804fb4434a37f2c8e44de05dd5fbdfdf683b
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f768a644-6884-4fac-8ad3-f2a0eaf4e4d9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-02-23 13:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: be958189045827d64833ffaf3cd63a89d7be9529
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c3f7f32c-4435-4d6a-9c5c-247787589135%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-01 00:23 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/aws-s3/lib/bucket.ts
> +  grantWrite(identity: iam.IGrantable, objectsKeyPattern?: any, allowedActions?: string[]): iam.Grant;
Ah, that's right. Fine as is.

2023-03-01 00:24 UTC, TheRealAmazonKendra commented
Go ahead and change that back to an optional array. It becomes a breaking change if the field is required.

2023-03-01 08:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c77175d96fd9e2fc4df3e6c1a9f877ab30df6a9b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1fd3f481-b311-4577-8eab-887ca4d136b5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-28 20:35 UTC, TheRealAmazonKendra approved these changes

2023-03-28 22:11 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3d792544950c55c0356f639a0415638a35ae6d80
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f2a2e52f-437c-4580-adc0-1931ef465447%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-28 22:11 UTC, merged