feat(rds): Support SQL Server for RDS proxy
aws/aws-cdk pull request #24438
Opened 2023-03-03 11:21 UTC by daschaa

Closes #22164

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-03-03 11:23 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-03-03 11:23 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-03-03 11:28 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-03-03 11:38 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 9cdc79d5a2f21cb47fce7701eb476781795054f7
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9ea6e704-7ddc-4f89-8767-aca67db18ee0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-03 11:56 UTC, daschaa commented
Exemption Request: This PR does not need a change to the README file, because there is no section about the supported database instances.

2023-03-03 11:57 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-03-03 11:58 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-03-03 12:12 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-03-03 12:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 16a3e58528b00a8e272e15070fa819264a175a8c
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=00ae76eb-46ab-4ba3-80cf-b97cf4cfc97c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-03 12:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 2bfee22987d074893264954605c069f039140c24
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bbe81413-9f22-4793-81b0-f8742486604e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-05 09:00 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-03-05 09:40 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3b63de9599d74a2ec096e19d65873a49892ddf90
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=07faf2b3-4518-4238-a4ce-e0a8151faeaf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-25 00:08 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2023-03-28 21:39 UTC, TheRealAmazonKendra requested changes

2023-03-28 21:39 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/aws-rds/lib/instance-engine.ts
> +  readonly engineFamily?: string
From the CloudFormation documentation it looks like this could be an enum or an enum like class. Let's use one of those to enforce values here.

2023-03-28 21:39 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/aws-rds/lib/instance-engine.ts
> +  readonly engineFamily?: string
Actually, is there any instance where this wouldn't just be `SQLSERVER`? If not, we might as well just set that directly in `SqlServerInstanceEngineBase`.

2023-04-01 00:08 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the MERGE CONFLICTS state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2023-04-09 00:08 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2023-04-09 00:08 UTC, closed without merging