feat(ecs-patterns): add executionRole argument to ScheduledFargateTask to allow specifying an existing  iam-role
aws/aws-cdk pull request #24475
Opened 2023-03-06 14:46 UTC by sakurai-ryo

Adds executionRole argument to ScheduledFargateTask to allow specifying an existing Role.
This change will allow users to customize the IAM Role used by EventBridge.

```ts
    // Users can create IAM Role in advance
    const executionRole = new iam.Role(this, 'ExecutionRole', {
      roleName: 'customized-role',
      path: '/',
      assumedBy: new iam.ServicePrincipal('events.amazonaws.com'),
    });

    // Create the scheduled task
    new ScheduledFargateTask(this, 'ScheduledFargateTask', {
      cluster,
      scheduledFargateTaskImageOptions: {
        image: new ecs.AssetImage(path.join(__dirname, '..', 'demo-image')),
        memoryLimitMiB: 512,
        cpu: 256,
        environment: { TRIGGER: 'CloudWatch Events' },
      },
      desiredTaskCount: 2,
      schedule: events.Schedule.rate(cdk.Duration.minutes(2)),
      executionRole,
    });
```

Closes #22673

Issue was left unattended, so I sent a PR. Is there a problem?
If there is a problem, I will close the PR.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-03-06 14:48 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-03-06 14:48 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-03-06 14:54 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The title of the pull request should omit 'aws-' from the name of modified packages. Use 'ecs-patterns' instead of 'aws-ecs-patterns'.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-03-06 15:26 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 49b7a8b6eb099d2d7b918bb8cce0b753c55a70ce
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d636f4b4-6113-46d5-b733-fdc12889e725%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-09 22:30 UTC, comcalvi requested changes
I don't think there's a compelling reason to add this feature right now, unfortunately. This L3 is supposed to hide the complexity of the underlying L2 as much as possible, and unless there's a compelling to expose it, it should not be exposed.

2023-03-11 05:30 UTC, sakurai-ryo commented
@comcalvi Thanks for the feedback. I know I can use L2 to address my problem, so I'll use that. close the PR.

2023-03-11 05:30 UTC, closed without merging