chore(cloudformation-diff): Changed to a more abstract type.
aws/aws-cdk pull request #24537
Opened 2023-03-09 03:47 UTC by taichi

Stream that formatSecurityChanges accepts as its first argument, because it does not require a tight coupling with TTY.
This declaration is probably a typo.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-03-09 04:26 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d6275e2262f60661453216955ecc04106f436ff7
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ed81e885-d7b8-4ebc-b327-3f5348dd20e3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-29 03:42 UTC, TheRealAmazonKendra requested changes
Can you please elaborate more on the problem you're trying to solve here? Is there an open issue for this? If not, I'm not sure I'm understanding why this change is needed.

2023-03-29 06:03 UTC, taichi commented
In the current code, since it accepts WriteStream, attempting to compile with formatSecurityChanges in code intended to operate only in memory, such as in a browser, results in an error. I would like to run the code that uses this function in an environment without a TTY.

However, upon examining the contents of formatSecurityChanges, the processing itself does not have any dependencies on TTY and is written as portable code that can operate in any environment.

In other words, the author of this code likely intended to require a WriteableStream as an argument, rather than a WriteStream. These are two classes with very similar names, so I believe it may simply be a typo.

2023-03-30 01:51 UTC, TheRealAmazonKendra approved these changes

2023-04-12 21:45 UTC, TheRealAmazonKendra approved these changes

2023-04-12 22:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 066e077def94ab5408202f6aad3b7375b7201bcf
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=cbf8d2a5-f64e-4d25-9d5d-e43424e0e0ce%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-04-13 00:25 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 186bfe7d45e31dd0449a947293e3194666ea3917
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0bbc1fea-cdd6-4185-ac10-279a787172ab%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-04-13 00:25 UTC, merged