fix(iam): added roleName parameter validation for fromRoleName function
aws/aws-cdk pull request #24549
Opened 2023-03-09 15:33 UTC by lpizzinidev

The `validateRoleName` function validates the `roleName` parameter passed to the `fromRoleName` function following the pattern specified in the [docs](https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateRole.html).

Closes #24503.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-03-09 15:35 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-03-09 15:35 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-03-09 16:13 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1aabc944f12d9d91aac47569e062f359523b5779
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7da98357-48b7-4daa-875a-3e5d58e2812b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-09 16:48 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-03-10 08:06 UTC, lpizzinidev commented
> The pull request linter fails with the following errors:
> 
> ```
> ❌ Fixes must contain a change to an integration test file and the resulting snapshot.
> ```
> 
> PRs must pass status checks before we can provide a meaningful review.
> 
> If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

Exemption Request.
This PR introduces validation on a parameter and will throw an exception in case of a wrong pattern so a unit test should be enough to check the behavior.

2023-03-10 08:08 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-03-10 08:08 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-03-29 02:42 UTC, TheRealAmazonKendra requested changes
Thank you for your contribution!

So, yes, the failing integ test is a matter of an error in implementation. The feature flag shouldn't be needed but you will need to add handling for the value being a token. 

The best you can do here is to only validate when it isn't a token so I would add in an if statement checking if `roleName` is a token and only calling `validateRoleName` if it is not. Check out the `Token` class for our functions for checking if something is a token or not, you can use those here.

2023-03-29 02:44 UTC, TheRealAmazonKendra commented
Granted integ test exception.

2023-03-29 09:54 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 983e6a4c1ccf66d63957abce031fc82a06afaefa
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=98b1d9ee-3244-4b80-8483-1b1e511cd481%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-30 01:48 UTC, TheRealAmazonKendra approved these changes

2023-03-30 02:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8bcca4d673f9d5fd67812ed4e4a8d52d261d42d0
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fb18f151-1ae1-4cf1-8745-a2f3adda990e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-30 02:37 UTC, merged