feat(aws-ecr-assets): Support Docker BuildKit secret from environment
aws/aws-cdk pull request #24791
Opened 2023-03-26 15:05 UTC by danwiltshire

Closes #24691

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-03-26 15:07 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-03-26 15:07 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The title of the pull request should omit 'aws-' from the name of modified packages. Use 'ecr-assets' instead of 'aws-ecr-assets'.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-03-26 15:47 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 2ba02f249fabc8bdef51c0179521ac2cead6cc4b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=60e6f51b-2acd-4701-bc16-2b80a658d184%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-03-27 18:44 UTC, TheRealAmazonKendra requested changes
Thank you for your contribution! Please see my comments inline. My only real concern, besides wanting another test is how the error message will be surfaced and if the user will have enough context where it does surface to ensure they know where it's coming from.

2023-03-27 18:44 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/core/test/bundling.test.ts
> +    expect(fromEnvironment).toEqual('env=TEST_FIXTURE_ENV');
Could you please add a test case where the env variable isn't correctly set but `fromEnvironment` is called?

2023-03-27 18:44 UTC, TheRealAmazonKendra commented on packages/@aws-cdk/core/lib/bundling.ts
> +      throw new Error(`Environment variable ${environmentVariable} is not set`);
At what point does this error message get surfaced? Will it be in a context that this message will be clear enough to a user?

2023-04-01 00:09 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2023-04-01 09:11 UTC, danwiltshire commented
Closing this PR after the repo refactor, will create new.

2023-04-01 09:11 UTC, closed without merging

2023-04-01 09:14 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-04-01 09:14 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-04-01 09:53 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ab08a5dd06c6558a31721a52e5b11e15e65b1f6f
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0a9a7260-2bce-4b03-8605-1f88aec98080%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->