fix(appmesh): add missing `port` property
aws/aws-cdk pull request #25112
Opened 2023-04-13 18:38 UTC by sumupitchayan

Closes #22452 

Adds `port` property to the `HttpGatewayRouteMatch` interface along with a unit test to validate the change.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-04-13 18:40 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-04-13 18:40 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-04-13 18:41 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-04-13 18:41 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-04-13 19:08 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 714c08df3f4adc1ed328d8081d43a45287adabe4
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ebc26032-6178-4cf5-a456-22faba5a4da3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-04-13 19:10 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e2000ee22977cff8209bb765131faced802f11d6
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2c108a8b-ed04-48a0-9b32-9fc96e558175%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-04-14 19:34 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-04-14 19:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ccc68a1964a3fbb53c1b4bf6c7bf441173a4ed61
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2ecc5a4f-7e0c-4b69-b5f0-3b14ad998f80%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-04-17 15:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 9a9fbdc231da21d1a2d11692097209f11c8ec001
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d0cf6453-6c56-4a3e-8188-ae7c34c73698%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-04-17 18:15 UTC, corymhall requested changes
@sumupitchayan great job! The only thing I think we should add is to add some validation that will throw an error if the user has not set `port` when required. The linked issues seems to indicate that the match port is required when the virtual gateway has >=2 listeners or else it will throw an error like:

```Gateway route must define a match port if the parent Virtual Gateway has multiple listeners.```

I think we can add a validation somewhere in [this class](https://github.com/aws/aws-cdk/blob/428bfc2dc566cff17b5856b2b346e473ea3642c4/packages/aws-cdk-lib/aws-appmesh/lib/gateway-route.ts#L111). It might look something like:

```ts
    this.node.addValidation({
      validate() {
        if (Resource.isOwnedResource(props.virtualGateway)) {
          const cfnGateway = props.virtualGateway.node.defaultChild as CfnVirtualGateway;
          const listeners = (cfnGateway.spec as CfnVirtualGateway.VirtualGatewaySpecProperty).listeners;
          if (Array.isArray(listeners) && listeners.length > 1) {
            return ['some error message'];
          }

        }
        return [];
      },
    });
```

2023-04-18 15:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b8424442f866daafbdbeb9c1708ea6839ab3658a
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=45ac2db6-d7de-496d-b8d0-d89a11075c8e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-04-18 15:32 UTC, sumupitchayan commented
Thanks for the feedback @corymhall ! Just added the validation - let me know if you spot anything else to improve!

2023-04-18 15:32 UTC, sumupitchayan commented
> Thanks for the feedback @corymhall ! Just added the validation - let me know if you spot anything else to improve!

xzx

> @sumupitchayan great job! The only thing I think we should add is to add some validation that will throw an error if the user has not set `port` when required. The linked issues seems to indicate that the match port is required when the virtual gateway has >=2 listeners or else it will throw an error like:
> 
> `Gateway route must define a match port if the parent Virtual Gateway has multiple listeners.`
> 
> I think we can add a validation somewhere in [this class](https://github.com/aws/aws-cdk/blob/428bfc2dc566cff17b5856b2b346e473ea3642c4/packages/aws-cdk-lib/aws-appmesh/lib/gateway-route.ts#L111). It might look something like:
> 
> ```ts
>     this.node.addValidation({
>       validate() {
>         if (Resource.isOwnedResource(props.virtualGateway)) {
>           const cfnGateway = props.virtualGateway.node.defaultChild as CfnVirtualGateway;
>           const listeners = (cfnGateway.spec as CfnVirtualGateway.VirtualGatewaySpecProperty).listeners;
>           if (Array.isArray(listeners) && listeners.length > 1) {
>             return ['some error message'];
>           }
> 
>         }
>         return [];
>       },
>     });
> ```

2023-04-19 09:47 UTC, corymhall commented
> Thanks for the feedback @corymhall ! Just added the validation - let me know if you spot anything else to improve!

Can you also add a test for that validation case? You can assert that a validation throws an error by doing

```ts
expect(() => app.synth()).toThrow(/the error message/);
```

2023-04-19 15:10 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 2de9a0e0f078513bd32677cfa842b802f6fe8296
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=314d2983-53c9-4950-8085-882792686944%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-04-19 15:10 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 625f995b351bab3840235e66e3b6a722c70b2958
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d5bca20a-4f03-4dea-819b-f7667d9fdf42%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-04-20 11:54 UTC, corymhall approved these changes
@sumupitchayan great job 🚀

2023-04-20 13:14 UTC, merged