feat(aws-logs): add filterName property in MetricFilter
aws/aws-cdk pull request #25246
Opened 2023-04-21 21:40 UTC by vinayak-kukreja

This PR is recreating and adding to https://github.com/robertd PR: https://github.com/aws/aws-cdk/pull/23053

Here, `filterName` property is being added for `MetricFilter`
And, also adding an existing integ test: `integ.expose-metric.ts` with the `IntegTest` construct.

Closes https://github.com/aws/aws-cdk/issues/17626

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-04-21 21:42 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-04-21 21:42 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ The title of the pull request should omit 'aws-' from the name of modified packages. Use 'logs' instead of 'aws-logs'.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-04-21 21:42 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ The title of the pull request should omit 'aws-' from the name of modified packages. Use 'logs' instead of 'aws-logs'.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-04-21 21:45 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-04-21 22:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5a439e8655c09fe1989f91b71c238b3c8ce27b9e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3923dab5-483f-4054-a2db-b73ee721bf52%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-04-21 22:12 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: a967d95bef4f5355d9f8869e4aaafeedfa8c194c
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e83bd675-1d9c-4caf-b720-4c4cb96b1487%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-04-24 12:10 UTC, corymhall requested changes
Just 2 minor things

2023-04-24 12:10 UTC, corymhall commented on packages/@aws-cdk-testing/framework-integ/test/aws-logs/test/integ.metricfilter-unit.ts.snapshot/manifest.json
> +{
It looks like these are all `ts` snapshots, probably a result of running
integ-runner with `--language typescript`. Can you remove these? We probably
should add a gitignore rule for this as well.

2023-04-24 18:26 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: fb9d29e7f2c91979e7421fe76662af22a7c76b60
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8c7e2297-f925-4f52-8548-16c52edd8084%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-04-24 18:26 UTC, robertd commented
> You can also add robertd@ as a co-author to the merge commit (if you're reusing his code) but adding `co-authored-by:` in the PR description: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors.
> 
> We do this on occasion in cdk: https://github.com/aws/aws-cdk/pulls?q=is%3Apr+co-authored-by%3A+is%3Aclosed

Appreciate the love @kaizencc and @vinayak-kukreja 🫶

2023-04-24 18:28 UTC, robertd commented
Side topic… I wasn’t aware `co-authored-by:`, does it take @username as an argument?

2023-04-24 18:58 UTC, vinayak-kukreja commented
> Side topic… I wasn’t aware `co-authored-by:`, does it take @username as an argument?

I just followed the format: `Co-authored-by: NAME <NAME@EXAMPLE.COM>`. So adding the name and the email :)

2023-04-24 19:09 UTC, robertd commented
You learn something new every day :). Thanks for leading the charge on this PR @vinayak-kukreja 🙌

2023-04-24 19:28 UTC, vinayak-kukreja commented
Thank you for your initial contribution @robertd. :)

2023-05-05 15:40 UTC, corymhall requested changes
@vinayak-kukreja sorry I missed one thing on my first pass.

2023-05-15 14:17 UTC, vinayak-kukreja commented on packages/aws-cdk-lib/aws-logs/lib/metric-filter.ts
> +      filterName: props.filterName,
No worries, will make the update.

2023-05-15 18:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 16d79806c4c5bb61ce0b02b7001e7c433917d33e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fcd8bbad-9599-40c9-a8e2-1d7b7222deb6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-05-15 18:43 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8266955d82c48be70e7de5ffbf06e73bec19becc
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a1629a97-616a-4220-97a2-726ebcf3aeed%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-05-15 20:27 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7b13bda0dc37caa438043ea0c6214281b4e1126a
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=114d6999-380b-42f3-b243-589d56898ba6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-05-24 14:33 UTC, corymhall approved these changes

2023-05-24 15:00 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d0f2306263cf25cce91ede060781b79ba2994cae
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b4442c82-647e-421a-9ca6-3b26c86117e9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-05-24 15:00 UTC, merged