chore(batch): make batch dev-preview
aws/aws-cdk pull request #25619
Opened 2023-05-16 20:27 UTC by comcalvi

Makes `aws-batch-alpha` developer preview

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-05-16 20:45 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 676bd45dc7a562e6bbbab6c93b01ec102af336fb
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2e38cff9-36f8-476b-ae17-fa1f560eb37b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-05-16 21:47 UTC, TheRealAmazonKendra requested changes
We also need to update this in package.json at the bottom:

```
  "stability": "experimental",
  "maturity": "experimental",
```

2023-05-16 22:00 UTC, comcalvi commented
I think stability is still `experimental`, like the one in synthetics: https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-synthetics-alpha/package.json#L103

2023-05-16 22:25 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e13f88989431408331bf48482f5c904bbc50313b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2d9f5471-6a8b-4072-be06-2d3e091f0692%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-05-22 15:41 UTC, TheRealAmazonKendra requested changes

2023-05-22 15:41 UTC, TheRealAmazonKendra approved these changes

2023-05-22 16:08 UTC, merged