feat(aws-vpclattice-alpha): L2 Construct for Vpc Lattice
aws/aws-cdk pull request #26063
Opened 2023-06-21 02:01 UTC by mrpackethead

This is for RFC 506

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-06-21 02:03 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-06-21 02:03 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The title of the pull request should omit 'aws-' from the name of modified packages. Use 'vpclattice-alpha' instead of 'aws-vpclattice-alpha'.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-06-21 02:27 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f87b170864b5879dccc31fd9a45c04ab103cbeba
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=413913a6-8e01-4997-a864-607ba86b87ad%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-09-18 21:48 UTC, indrora commented
What's keeping this PR from moving forward? 

The resources checklist check fails due to something unrelated. @mrgrain -- what's the news?

2023-09-18 21:55 UTC, mrgrain commented
> What's keeping this PR from moving forward? 
> 
> The resources checklist check fails due to something unrelated. @mrgrain -- what's the news?

The RFC for it is still open.

2023-09-18 21:56 UTC, indrora commented
if the RFC for this feature is still open, do we want to close this PR until we've hammered out the RFC?

2023-09-18 22:39 UTC, mrgrain commented
Any reasons the PR need to be closed? I assume the author is still working on it.

2024-04-25 20:37 UTC, paulhcsun commented
Hi @mrpackethead, it looks like the linked RFC has been approved and merged. Are you still planning to continue working on this?

2024-06-11 20:50 UTC, TheRealAmazonKendra requested changes
I'm putting this into changes requested as it is still in draft mode and hasn't been worked on in a while. Doing this won't close it immediately but it will close it after four weeks if this remains unchanged. If you are still working on it, feel free to push any changes and/or open a new PR if the bot does deem this one abandoned.

2024-06-11 21:49 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-06-11 21:49 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The first word of the pull request title should not be capitalized. If the title starts with a CDK construct, it should be in backticks "``".

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-06-11 21:55 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The first word of the pull request title should not be capitalized. If the title starts with a CDK construct, it should be in backticks "``".

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-07-03 00:08 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2024-07-10 00:09 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2024-07-10 00:09 UTC, closed without merging

2024-07-10 00:11 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The first word of the pull request title should not be capitalized. If the title starts with a CDK construct, it should be in backticks "``".

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-07-10 00:58 UTC, mrpackethead commented
Not abadonded my the requesters. Abandoned by the AWS CDK team, who set us up to fail.