chore(apprunner): expose instanceRole from Service instance
aws/aws-cdk pull request #26130
Opened 2023-06-27 08:04 UTC by lpizzinidev

Exposes the [`instanceRole`](https://github.com/aws/aws-cdk/blob/636841c380ccc3a6da372117cf0317f351a75cff/packages/%40aws-cdk/aws-apprunner-alpha/lib/service.ts#L998) from `Service` for convenience (eg. granting privileges).

The `obtainInstanceRole` method returns the already defined `instanceRole` or creates a default one if not specified.
I used a getter method since making the variable `readonly` was not possible as it is assigned inside the [`addSecret`](https://github.com/aws/aws-cdk/blob/636841c380ccc3a6da372117cf0317f351a75cff/packages/%40aws-cdk/aws-apprunner-alpha/lib/service.ts#L1137) method.

Closes #26089.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-06-27 08:33 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7e4292c06a305548ef639b682bfcd4045cc54b6a
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=91821ca4-44bf-4162-a76a-8ce354e5f9cb%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-06-27 11:58 UTC, corymhall requested changes

2023-06-27 11:58 UTC, corymhall commented on packages/@aws-cdk/aws-apprunner-alpha/lib/service.ts
> +  public obtainInstanceRole(): iam.IRole {
What if we instead made `Service` implement `IGrantable`? Then we could just do
things like

```ts
bucket.grantRead(service);
```

2023-06-28 08:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b784781c5f3d36069afd1e6af006d0b590fe49fd
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=683f7a15-e509-4674-856d-40b052c01207%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-06-29 10:04 UTC, corymhall requested changes
Can you also add an `addToRolePolicy` method? I'm also going to change this to a `feat`. Adding the auto creation of the role should cause the integ test to update and we'll need a README update.

2023-06-29 10:04 UTC, corymhall commented on packages/@aws-cdk/aws-apprunner-alpha/lib/service.ts
> +    this.grantPrincipal = this.instanceRole || new iam.UnknownPrincipal({ resource: this });
I think we should just go ahead and create the role if the user doesn't provide it. I'm not sure why we try to only generate one if needed.

2023-06-29 10:05 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-06-29 10:05 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-06-30 08:01 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-06-30 08:28 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0c623471603ce1797812dc5038ae9590606c7a7b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a30a8d1e-a932-4741-9092-22f08a318912%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-15 15:26 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-07-15 15:37 UTC, lpizzinidev commented
Exemption request.
I've updated the related integration tests.

2023-07-15 15:39 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-07-15 15:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b550db3d98a20e1563711bb1daeff95a3ea7a729
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2f4ded87-c49c-4e93-be28-8ea3bc349d70%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-17 09:30 UTC, mrgrain approved these changes

2023-07-21 00:08 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2023-07-21 06:47 UTC, lpizzinidev commented
> Can you also add an `addToRolePolicy` method? I'm also going to change this to a `feat`. Adding the auto creation of the role should cause the integ test to update and we'll need a README update.

@corymhall I've implemented the requested changes.

2023-07-21 07:14 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 69ecdccc25fec287a07f2202dfb83c7e719b8ca9
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=022f507b-f467-4644-b324-46d95b110413%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-24 12:05 UTC, corymhall approved these changes

2023-07-24 12:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: dfbe8d52156fcbd48a6835e3ad134980760c5b25
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4cda588c-90d0-4036-be48-d9cccc76b8f8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-24 12:33 UTC, merged