chore(aws-lambda): add toString to lambda architecture
aws/aws-cdk pull request #26145
Opened 2023-06-28 13:30 UTC by lukey-aleios

Add  toString to Lambda Architecture property

When throwing errors during synthesis, you can't see the architecture chosen for a lambda. Adding this toString method solves that

Closes #26117

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-06-28 13:32 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-06-28 13:32 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The title of the pull request should omit 'aws-' from the name of modified packages. Use 'lambda' instead of 'aws-lambda'.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-06-28 13:59 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 95a23bf34a20a77aa0af0a329d9edeefdf3d3ba5
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1e206e97-6ed0-4c70-a029-e68bd13e269a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-06-29 11:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5f4a004eb1e3ac25190340c6e1d7c734bf9a35a2
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f0dba443-a4c6-49de-997e-b2b45a9e9aae%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-06-30 12:00 UTC, corymhall requested changes
Can you add a unit test for this?

2023-06-30 12:00 UTC, corymhall commented on packages/aws-cdk-lib/aws-lambda/lib/architecture.ts
> +  public toString(): string {
Can you add a docstring here?

2023-06-30 13:41 UTC, lukey-aleios commented on packages/aws-cdk-lib/aws-lambda/lib/architecture.ts
> +  public toString(): string {
Yep! Great point

2023-06-30 14:26 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 46261ac73d1b7c5601e0ee91c6af193a1fbd1e44
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=16d9066d-f449-4847-9a7c-5fe905ba3e46%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-06-30 14:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d71c33458d90610e2e63de16e6266443d3ab0ebe
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d0c5563e-6ab6-427e-afd7-95f027044d30%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-06-30 14:52 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 60c1b9f51257719a98bbdd7defffefccb9f4bff3
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7bc95913-eaca-4a73-83d2-7fc4c7930889%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-06-30 15:35 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e5b29bee9bf0b5bb4b903db0a9b8f6e7e488f31b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7b3bd16d-b54b-4a3c-a480-a91ab17d7784%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-06-30 15:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 00b9c84ecf17c05a4c794ba7b5bdc9d83b2fba16
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1eeb9e70-1691-4312-833c-eb2f16ac6991%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-06-30 15:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 64141863991054b33cf942f1a6c88e725394f8fa
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e747df36-7a70-424a-9042-4ad55d37b5b6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-06-30 15:47 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7fcce5acbe7ac5f99043e85e8f0d71a40030cf3d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d5727d62-9d85-47de-97d6-0d9a1e5e7c21%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-06-30 16:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3aa874bf7bcd02235d1e69e1e9ef98c4cf04b446
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f9d5dab5-ebc1-49f9-b1e0-14e0346620ad%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-06-30 17:12 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7ca8b18b28ff672b0e9ddab07386154b20a8b267
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=80904c4d-431a-4472-b426-274635dd3260%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-14 11:54 UTC, mrgrain submitted a review, later dismissed
@lukey-aleios How are you doing with the unit test? If you need any help checkout the Community Slack on cdk.dev channel #contributing

2023-07-14 12:02 UTC, lukey-aleios commented
> @lukey-aleios How are you doing with the unit test? If you need any help checkout the Community Slack on cdk.dev channel #contributing

Hey! I've been away for the past two weeks so will be able to get to this early next week 😄

2023-07-14 12:12 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f37fb2282f0a7fd45e932da086de1f2f1a8dde40
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a659964e-acaf-454c-8a7c-f285a8910eab%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-14 12:43 UTC, mrgrain commented
> Hey! I've been away for the past two weeks so will be able to get to this early next week 😄

Awesome, thank you!

2023-07-14 12:46 UTC, mrgrain commented
If the automation closes your PR, please just open a new one once you have had time to address any issues. Pro tip: Open the PR in Draft mode and our automation won't touch it.

2023-07-15 16:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: a0f343d198da605a87a0b62d38c756c52f531aa9
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0a0eed33-b8cd-4cf1-92ad-fe25647192c8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-15 16:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f2a595bfda5090d550a8d0077e133dcd8b6331df
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5b99cb0b-f25e-4e15-ac61-beb89ce5b712%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-17 09:29 UTC, mrgrain commented
Your test case doesn't quite work out
```
aws-cdk-lib: FAIL aws-lambda/test/architecture.test.js
aws-cdk-lib:   â— architecture â€º toString to return the architecture name
aws-cdk-lib:     expect(received).toEqual(expected) // deep equality
aws-cdk-lib:     Expected: "x86_64"
aws-cdk-lib:     Received: {"dockerPlatform": "linux/amd64", "name": "x86_64"}
aws-cdk-lib:     [0m [90m 17 |[39m[0m
aws-cdk-lib:     [0m [90m 18 |[39m     [90m// THEN[39m[0m
aws-cdk-lib:     [0m[31m[1m>[22m[39m[90m 19 |[39m     expect(testLambda[33m.[39marchitecture)[33m.[39mtoEqual(testLambda[33m.[39marchitecture[33m.[39mname)[33m;[39m[0m
aws-cdk-lib:     [0m [90m    |[39m                                     [31m[1m^[22m[39m[0m
aws-cdk-lib:     [0m [90m 20 |[39m   })[33m;[39m[0m
aws-cdk-lib:     [0m [90m 21 |[39m })[33m;[39m[0m
aws-cdk-lib:     [0m [90m 22 |[39m[0m
```

2023-07-17 10:38 UTC, lukey-aleios commented
> Your test case doesn't quite work out
> 
> ```
> aws-cdk-lib: FAIL aws-lambda/test/architecture.test.js
> aws-cdk-lib:   â—� architecture â€º toString to return the architecture name
> aws-cdk-lib:     expect(received).toEqual(expected) // deep equality
> aws-cdk-lib:     Expected: "x86_64"
> aws-cdk-lib:     Received: {"dockerPlatform": "linux/amd64", "name": "x86_64"}
> aws-cdk-lib:     �[0m �[90m 17 |�[39m�[0m
> aws-cdk-lib:     �[0m �[90m 18 |�[39m     �[90m// THEN�[39m�[0m
> aws-cdk-lib:     �[0m�[31m�[1m>�[22m�[39m�[90m 19 |�[39m     expect(testLambda�[33m.�[39marchitecture)�[33m.�[39mtoEqual(testLambda�[33m.�[39marchitecture�[33m.�[39mname)�[33m;�[39m�[0m
> aws-cdk-lib:     �[0m �[90m    |�[39m                                     �[31m�[1m^�[22m�[39m�[0m
> aws-cdk-lib:     �[0m �[90m 20 |�[39m   })�[33m;�[39m�[0m
> aws-cdk-lib:     �[0m �[90m 21 |�[39m })�[33m;�[39m�[0m
> aws-cdk-lib:     �[0m �[90m 22 |�[39m�[0m
> ```

Should be fixed now!

2023-07-17 11:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 2782aaaf96333832ad5b9d25c889a886403f67d2
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b18ff2d2-222f-4f1e-8652-bf856ad2cd17%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-17 11:33 UTC, mrgrain approved these changes

2023-07-17 11:33 UTC, merged