fix(ecs): DeploymentAlarms property is specified for ECS service with CODE_DEPLOY and EXTERNAL deployment controller
aws/aws-cdk pull request #26317
Opened 2023-07-11 10:48 UTC by tam0ri

From #25840, ECS L2 construct sets the default configuration for the `CfnService.deploymentConfiguration.alarms` property to:
```
alarmNames: [],
rollback: false,
enable: false,
```

However, alarm based rollback feature is only supported for ECS services that use the rolling update (ECS) deployment controller.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-alarm-failure.html

Due to this limitation, when deploymentController is set to CODE_DEPLOY or EXTERNAL, creation for the service will fail by conflict with `deploymentConfiguration.alarms` property.

This PR solves the issue by skipping to set default configuration for the `CfnService.deploymentConfiguration.alarms` property for CODE_DEPLOY and EXTERNAL deployment controller.

Closes #26307

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-07-11 10:50 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-07-11 10:50 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-07-11 10:52 UTC, tam0ri commented
Exemption Request for this quick fix. If integration tests and snapshot are still needed, please let me know.

2023-07-11 10:54 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-07-11 13:05 UTC, tam0ri commented
I checked failed build. I want to take a new snapshot for @aws-cdk-testing
/framework-integ/test/aws-codedeploy/test/ecs/integ.deployment-group.ts, but I can't execute integ-runner now. `npx lerna run build --scope=@aws-cdk-testing/framework-integ` failed with the following error.

```
$ cdk-build
       
       /workspace/aws-cdk/packages/aws-cdk/lib/commands/migrate.ts
         5:24  error  Unable to resolve path to module '../vendor/noctilucent'  import/no-unresolved
       
       ✖ 1 problem (1 error, 0 warnings)
       
       Error: /workspace/aws-cdk/node_modules/eslint/bin/eslint.js . --ext=.ts --resolve-plugins-relative-to=/workspace/aws-cdk/tools/@aws-cdk/cdk-build-tools/lib exited with error code 1
```

I usually use devcontainer, so I tried to use Gitpod, but the problem does not solved.

2023-07-11 13:14 UTC, mrgrain commented
@tam0ri Is your branch up-to-date? We made a change to how we import `noctilucent` recently. 
Also did you receive any errors during the build?

2023-07-11 13:17 UTC, mrgrain commented on packages/aws-cdk-lib/aws-ecs/lib/base/base-service.ts
> +      props.deploymentController?.type !== DeploymentControllerType.EXTERNAL && this.deploymentAlarmsAvailableInRegion()) {
Any particular reason you are checking for the negative here (not CODE_DEPLOY, not EXTERNAL) and not if the controller is ECS?

2023-07-11 13:19 UTC, mrgrain requested changes
Code looks good. Thank you! Just the one small question. If you add the test I can run the snapshots for you.

2023-07-11 13:34 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-07-11 13:39 UTC, tam0ri commented
I pushed the fix. If you have any comment, please feel free to point it out!

> Is your branch up-to-date? We made a change to how we import noctilucent recently.

Yes, I already pulled the latest main branch. I'll dig it further more later, but it really helpful that you add a new snapshot.

2023-07-11 13:54 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6d44c3562555ec647e6bb91fd8868dc74f27f1df
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=80f34ac3-825d-43e1-9ea6-2670133ff7f6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-11 15:50 UTC, tam0ri commented
I could execute integ-runner on Gitpod, so I added a new snapshot by myself.

The previous snapshot includes the invalid configuration (alarm based rollback + CODE_DEPLOY deployment controller).
https://github.com/aws/aws-cdk/blob/9fca7909797e71788b65bd1bf7bd2c0c85a75159/packages/%40aws-cdk-testing/framework-integ/test/aws-codedeploy/test/ecs/integ.deployment-group.js.snapshot/aws-cdk-codedeploy-ecs-dg.template.json#L445-L462

So, I created the new snapshot with `--disable-update-workflow`.

2023-07-11 16:17 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3021a971bef73dbafdc85d804cfdda7794a93253
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=32f6300c-3f4b-4d0a-8adf-3dc2c98fd88b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-12 10:45 UTC, mrgrain approved these changes

2023-07-12 11:13 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1bcdeb9bdc6063a891fadbdb76e02311b5294248
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7643d254-1635-4216-ae91-1115494c2ae8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-12 11:13 UTC, merged