fix(eks): Changing EKS helm chart handler runtime from Python 3.7 to 3.8
aws/aws-cdk pull request #26385
Opened 2023-07-17 02:20 UTC by youngjeong46

Currently the Helm Chart handler for aws-eks package is using Python 3.7. We have seen, as from the issue listed below, that there are issues with certificates that won't be accepted when running with Python 3.7 (i.e. JupyterHub). 

This PR replaces the Lambda Handler for Helm Chart runtime from Python 3.7 to 3.8.
Closes #25747.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-07-17 02:22 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-07-17 02:22 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-07-17 02:41 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 43c0486af3b41201cdef869262071f5b4437558f
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f67da79b-1413-4dd8-bcbc-a0406e33a07f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-25 14:25 UTC, kaizencc requested changes
@youngjeong46 thanks for the PR! Are you able to continue working on this? There are quite a few integration tests that are failing because they need to be tested with python 3.8. 

I don't think I can do them for you because you're on your own main branch so if you don't have the time I can spin up my own PR and update the runtime.

2023-08-02 05:10 UTC, youngjeong46 commented
> @youngjeong46 thanks for the PR! Are you able to continue working on this? There are quite a few integration tests that are failing because they need to be tested with python 3.8.
> 
> I don't think I can do them for you because you're on your own main branch so if you don't have the time I can spin up my own PR and update the runtime.

@kaizencc Can you work on the PR? I keep running out of heap space on all of my environments building integration tests.

2023-08-02 14:11 UTC, kaizencc commented
@youngjeong46 I can't do them on this PR, so I'd have to open a new one. 

If you're running out of heap space, you can try `export NODE_OPTIONS="--max-old-space-size=8192" &&  npx lerna run build --scope=aws-cdk-lib`

2023-08-04 09:34 UTC, rix0rrr commented
Or create a branch in your fork, and change the PR to be based off the branch.

2023-08-08 00:08 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the BUILD FAILING state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2023-08-16 00:07 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2023-08-16 00:07 UTC, closed without merging

2023-08-16 00:10 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.