feat(neptune-alpha): added support for Neptune serverless
aws/aws-cdk pull request #26445
Opened 2023-07-20 10:09 UTC by lpizzinidev

Adds support for [Neptune serverless](https://docs.aws.amazon.com/neptune/latest/userguide/neptune-serverless-using.html).

Example of how to launch a Neptune serverless cluster:
```
new DatabaseCluster(stack, 'Database', {
  vpc,
  instanceType: InstanceType.SERVERLESS,
  clusterParameterGroup,
  removalPolicy: cdk.RemovalPolicy.DESTROY,
  serverlessScalingConfiguration: {
    minCapacity: 1,
    maxCapacity: 5,
  },
});
```

Closes #26428 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-07-20 10:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 10c027551a4aa5f85668d231f40de928f855a188
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c3afd44c-c3ba-4ccb-a11e-5230c73041c7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-20 10:59 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c58ffc6d6bfbbffeda26b5bf29e4b936bf307177
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=29a30dce-79ce-47b0-8209-561c2373fe77%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-24 15:47 UTC, jumic approved these changes
From my perspective (as a community reviewer) this looks good. Thanks.

2023-07-24 20:12 UTC, kaizencc requested changes
Thanks @lpizzinidev and @jumic! My only comment is that wherever possible, I'd like to return the actual values received in the error messages

2023-07-24 20:12 UTC, kaizencc commented on packages/@aws-cdk/aws-neptune-alpha/lib/cluster.ts
> +      throw new Error('ServerlessScalingConfiguration maxCapacity must be between 2.5 and 128');
```suggestion
      throw new Error(`ServerlessScalingConfiguration maxCapacity must be between 2.5 and 128, received ${serverlessScalingConfiguration.maxCapacity}`);
```

2023-07-24 20:12 UTC, kaizencc commented on packages/@aws-cdk/aws-neptune-alpha/lib/cluster.ts
> +      throw new Error('ServerlessScalingConfiguration minCapacity must be less than serverlessScalingConfiguration maxCapacity');
```suggestion
      throw new Error(`ServerlessScalingConfiguration minCapacity (${serverlessScalingConfiguration.minCapacity)}) must be less than serverlessScalingConfiguration maxCapacity (${serverlessScalingConfiguration.maxCapacity})`);
```

2023-07-25 08:43 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c74ef0216d97dffce2dd339026bfedec9d001aa1
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=98c79e8a-d16e-47d2-9b97-9262cc07cf2d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-25 13:29 UTC, kaizencc approved these changes
Thanks! This got in extremely smoothly :).

2023-07-25 13:56 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8f1959bb500ef80a7064813dbaa79a8d548fd861
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5080165a-fe10-4b55-9559-4d8290689489%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-25 13:57 UTC, merged