Run projen for node-bundle
aws/aws-cdk pull request #26468
Opened 2023-07-21 17:55 UTC by matt9ucci

Run projen for node-bundle

Execute `npx lerna run projen --scope=@aws-cdk/node-bundle` and commit the updated files.
The updates include:

* Bump `@types/node` from 14 to 16
* Fix some issues of projen (e.g. https://github.com/projen/projen/pull/2719)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-07-21 17:58 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-07-21 17:58 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-07-21 18:01 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-07-21 18:09 UTC, matt9ucci commented
`Exemption Request`
This PR does not affect the test.

2023-07-21 18:11 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-07-21 18:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 57d1acccf8ceb64960a0cf2afb10b8052a95abfb
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ec77f9f6-2432-4465-b3c7-9d594ccc96c4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-07-21 18:25 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-07-25 16:06 UTC, mrgrain requested changes
Hey @matt9ucci Thanks for this PR! I see why you did this. But I'd actually rather have projen removed from this package. Doesn't really make sense to mix the tooling here. LMK if you want to take this, otherwise feel free to close the PR.

2023-07-26 09:22 UTC, matt9ucci commented
@mrgrain Thank you for your reply. I will close the PR.

I was trying to build `aws-cdk-lib` on Windows, but `node-bundle` threw the following error:
```
$ npx lerna run build --scope=aws-cdk-lib
...
> @aws-cdk/node-bundle:build

yarn run v1.22.19
$ projen build
\"" was unexpected at this time.
👾 unable to evaluate environment variable PATH=$(npx -c "node -e \"console.log(process.env.PATH)\""): unknown error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
It is due to the old version of projen. If projen is removed, the error is removed too. That's okay.

2023-07-26 09:23 UTC, closed without merging