fix: removes the requirement to have a domain name when using SSL certificates
aws/aws-cdk pull request #26605
Opened 2023-08-02 13:56 UTC by nsmith-amplience

This PR allows for domain names to be optional when creating a Cloudfront Distribution that has a certificate attached to it. As Cloudfront Distributions allow for domains to be transferred with the `associate-alias` command there are scenarios where having an SSL certificate attached without a domain are valid, and attaching the SSL certificate in the CDK creation phase minimises the amount of stack drift.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-08-02 13:58 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-08-02 13:58 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-08-02 14:01 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-08-02 14:05 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 99a4e30b92383bd24fe6aaf3650e5bb1d37f3909
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9a77c68b-9423-4064-a99f-13d530de7af7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-08-02 15:41 UTC, nsmith-amplience commented
Exemption Request

This PR is rolling back a previous change rather than implementing new functionality, it doesn't seem to meet the criteria in `When are Integration Tests` required.

2023-08-02 15:44 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-08-17 16:19 UTC, kaizencc requested changes
Hi @nsmith-amplience, before we can look at this PR the build needs to succeed. The current issue is:

```
aws-cdk-lib: aws-cloudfront/test/distribution.test.ts:514:1 - error TS1128: Declaration or statement expected.
aws-cdk-lib: 514 });
aws-cdk-lib:     ~
aws-cdk-lib: aws-cloudfront/test/distribution.test.ts:514:2 - error TS1128: Declaration or statement expected.
aws-cdk-lib: 514 });
```

2023-08-24 00:07 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the BUILD FAILING state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2023-08-31 00:07 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2023-08-31 00:07 UTC, closed without merging

2023-08-31 00:10 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.