fix(rds): fixed grantConnect with no user specified for instances with secret credentials
aws/aws-cdk pull request #26647
Opened 2023-08-05 14:42 UTC by lpizzinidev

Calling `grantConnect` on instances with secret credentials not specifying the user was causing the deploy to fail because the secret was not resolved.
This fix solves the bug.

Closes #26603.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-08-05 15:08 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: a43af0043dcdafa27d316fa7083632222c2d442a
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=87190ec6-1599-40bc-a057-9560add8fe43%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-08-07 08:41 UTC, rix0rrr requested changes
Looks good, and I'm ready to ship it! However, I'm noticing your PR titles have not followed the contributing guide best practices at least a couple of times, so I'm going to set this to "Request changes" to make sure that you see this comment 😇

-----

Please make sure that your PR title confirms to the conventional commit standard (`fix`, `feat`, `chore`) and that it is written in a style that will reflect correctly in the change log. In particular, if this is a bug fix, please describe the bug that was fixed, *not* the change you made. (See [Contributing Guide, Pull Requests](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request))

Specifically, this part: 

> Titles for feat and fix PRs end up in the change log. Think about what makes most sense for users reading the changelog while writing them.
> * feat: describe the feature (not the action of creating the commit or PR, for example, avoid words like "added" or "changed")
> * fix: describe the bug (not the solution)

2023-08-07 10:09 UTC, lpizzinidev commented
@rix0rrr Thanks for the feedback 👍

2023-08-08 11:29 UTC, rix0rrr approved these changes

2023-08-08 11:56 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 08c5a356368880c1d92f95ed41087432331af7cf
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ac9094bf-1bf0-4be3-932d-4d137aaf06c7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-08-08 11:56 UTC, merged