refactor(aws-stepfunctions): deprecate unused DISCARD variable and include JsonPath.DISCARD in docs
aws/aws-cdk pull request #26770
Opened 2023-08-16 09:13 UTC by kirkwat

The `DISCARD` variable is removed because it unused. The docs are updated to be more clear to use `JsonPath.DISCARD` for `CatchProps` and `ChoiceProps`.

Closes #26760 .

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-08-16 09:15 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-08-16 09:15 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The title of the pull request should omit 'aws-' from the name of modified packages. Use 'stepfunctions' instead of 'aws-stepfunctions'.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-08-16 09:39 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8485da87b637c425cfade124f4adf458b8d82a3e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=671cb60a-e86a-49ef-b68f-8e627b143a8b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-08-16 12:45 UTC, lpizzinidev commented on packages/aws-cdk-lib/aws-stepfunctions/lib/types.ts
> -export const DISCARD = 'DISCARD';
Removing the variable can potentially result in a breaking change if some previous versions were using it.
It's better to mark it as `@deprecated` and explain that `JsonPath.DISCARD` should be used instead.

2023-08-16 12:46 UTC, lpizzinidev requested changes
Thanks for the contribution!
I left you a comment regarding the deprecation.
Also, there is another `DISCARD` reference to update [here](https://github.com/aws/aws-cdk/blob/b23252b99559ad1a1f0e05b6936c60f9c52522ff/packages/aws-cdk-lib/aws-stepfunctions/lib/states/state.ts#L577).

2023-08-17 08:25 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5a528702639f11676ed1489735fbd39bba78ed16
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7e349014-6dbd-49d7-b756-bd9a630ed411%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-08-17 08:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 45a9b5fcbfffd2ff81fd3aec344cd83582209617
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a9ab9ecf-640b-4564-a434-c53b18687789%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-08-17 09:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: da3ea5506be98aa9c71297d20c36fda3fabf94b6
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ffad67d4-2958-45a5-a7cf-d17b49d98b9a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-08-17 09:38 UTC, lpizzinidev approved these changes

2023-08-17 14:45 UTC, rix0rrr approved these changes

2023-08-17 15:38 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1a872119e9cba02c314d5d2b17c756b69f70ceae
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f759c806-5d9f-41fc-b100-31221d6dcdfb%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-08-17 15:38 UTC, merged