fix(core): update resource logical ID validation regex to be consistent with docs
aws/aws-cdk pull request #26821
Opened 2023-08-21 01:34 UTC by kirkwat

The resource logical ID validation regex (`VALID_LOGICALID_REGEX`) is updated to be consistent with the [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html) which says that logical IDs are alphanumeric.

Closes #26075.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-08-21 01:54 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1752ab2f0b102316bb01fd674ebe8b111459e39c
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b5c3d981-318c-454f-b11c-124c45a76796%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-08-21 15:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 82c72a8f39f1bdc10ea836e3cc35427303ca045c
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=aedb0c7e-1c28-4fbf-aba5-c722ff6ff07f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-08-22 07:17 UTC, lpizzinidev commented on packages/aws-cdk-lib/core/test/logical-id.test.ts
> +    return alphaNumericChars.charAt(Math.floor(Math.random() * 62));
Better to go with `Math.random() * alphaNumericChars.length`

2023-08-22 07:24 UTC, lpizzinidev commented on packages/aws-cdk-lib/core/test/logical-id.test.ts
> +function generateAlphaNumericString(chars: number) {
We should use `generateAlphaNumericString` also [here](https://github.com/aws/aws-cdk/blob/26dcc1e11a07d93681145049aa06d80a7d2114b9/packages/aws-cdk-lib/core/test/logical-id.test.ts#L171-L176).

2023-08-22 07:26 UTC, lpizzinidev requested changes
Thanks for the contribution! 💪
Looks good overall, just a couple of minor changes on the tests should be done in my opinion.

2023-08-22 11:49 UTC, rix0rrr approved these changes

2023-08-22 12:57 UTC, rix0rrr approved these changes

2023-08-22 13:23 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: aa7946a1cc91279541e3b34bd1d1621592d62872
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=99f34a1f-1b31-4350-8dd3-10d75adfd43d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-08-22 14:17 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 197d363bfa5b94ab79cd65286ab73b06d2bd04b3
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ac48cfb2-ef38-49a6-8569-455ea1999a60%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-08-22 14:17 UTC, merged