feat(s3): Reduce notifications handler permissions (#5925)
aws/aws-cdk pull request #27274
Opened 2023-09-25 13:03 UTC by alFReD-NSH

This restricts them to resources only the buckets that is required. To ensure permissions don't get too large minimize is also enabled on the policy.

Closes #5925

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-09-25 13:05 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-09-25 13:05 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-09-25 13:05 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-09-25 13:05 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-09-25 13:07 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-09-25 13:15 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-09-25 13:15 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-09-25 13:34 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 05663d21766a60f8f4a775f81ce5bb0fb2afff02
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=de9705f6-359f-4250-a0d6-022a9196ca5b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-09-25 13:37 UTC, alFReD-NSH commented
Clarification Request: I'm not sure if this falls as a feature or a bugfix. In either case no changes to readme or integration tests are required as there's no changes to end users and there isn't any changes in how the reosource reacts.

2023-09-25 13:39 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-09-25 13:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f245a220fef20a85436029283fddf8402c1dc038
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d1a03935-01b5-48cc-b69d-2f7bdd240a1b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-10-10 22:59 UTC, vinayak-kukreja requested changes
Hey, I see the build is failing right now. We would not be able to prioritize review for this PR till the build succeeds. 

This could be a high impact PR since it is modifying permissions. I am not sure if this can be merged in. It looks like the integration tests were not run with this change. Could you run those?

2023-10-10 22:59 UTC, vinayak-kukreja commented on packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource-handler.ts
> +  private readonly policy: iam.Policy;
This is breaking. A user could be using this property which now would become `private`

2023-10-10 23:01 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-10-10 23:02 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-10-10 23:02 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-10-17 00:08 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the BUILD FAILING state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2023-10-25 00:09 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2023-10-25 00:09 UTC, closed without merging

2023-10-25 00:11 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-10-25 06:46 UTC, alFReD-NSH commented
Hi @vinayak-kukreja, Thanks for the review. I had a busy week but now I'm happy to make the PR again, while adding back the `role` as public to make sure it's not breaking. In the meantime, other than locally running the integration tests, what needs to be done here?

Could you also let me know whether this should a bugfix or feature and what kind of change I can put in the README and also integration test file?