feat(aws-synthetics-alpha): Add latest CloudWatch Synthetics NodeJS Runtime
aws/aws-cdk pull request #27339
Opened 2023-09-28 15:51 UTC by Abdu03

Added `syn-nodejs-puppeteer-6.0` version to avaiable synthetic runtimes.
This version runs on Node 18 allowing users to move away from node 16 (which is now at EOL).

Changed an exisiting test to refrence the latest runtime and also updated the examples in the readme to refrence the latest runtime.

Closes #27337.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-09-28 15:53 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-09-28 15:55 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-09-28 16:00 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 99225da66ecb163ff6ddecee51529a13088ff6b2
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ee13c936-2807-4081-aa1d-6a07f0c81858%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-09-28 20:41 UTC, peterwoodworth requested changes
Hey @Abdu03, according to the build logs, the build is failing because the indentation isn't correct in `runtime.ts` on lines 125 and 138

Regarding integration tests, we'll need to modify and run the tests found in [this folder](https://github.com/aws/aws-cdk/tree/main/packages/%40aws-cdk-testing/framework-integ/test/aws-synthetics/test).

2023-09-28 20:41 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-09-28 20:43 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-09-29 08:33 UTC, mrgrain submitted a review, later dismissed
🎉🎉

2023-09-29 08:36 UTC, mrgrain commented on packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts
> +   public static readonly SYNTHETICS_NODEJS_PUPPETEER_6_0 = new Runtime('syn-nodejs-puppeteer-6.0', RuntimeFamily.NODEJS);
```suggestion
  public static readonly SYNTHETICS_NODEJS_PUPPETEER_6_0 = new Runtime('syn-nodejs-puppeteer-6.0', RuntimeFamily.NODEJS);
```

2023-09-29 08:36 UTC, mrgrain commented on packages/aws-cdk-lib/aws-synthetics/lib/runtime.ts
> +   /**
```suggestion
  /**
```

2023-09-29 08:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 4be5db2d51efd190ab27b366f0dc98215c12869d
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9a472eb4-f69a-43ec-b7f7-d9e3c6d9843f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-09-29 08:52 UTC, mrgrain approved these changes

2023-09-29 08:53 UTC, Abdu03 commented
thank you for clarifiying @peterwoodworth 🙌 and thank you for sorting it out @mrgrain 🚀

2023-09-29 09:06 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6fdacaed55342fa9326f684f05b16d4744029c1c
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=814225f1-edb7-4348-be80-c7d2c8626095%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-09-29 09:33 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3d1914440f39b355c19e024708be611bf5e40c33
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b2c2dce6-d670-4325-a0f9-0895ab27ce9b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-09-29 09:34 UTC, merged