feat(glue-alpha): adding partition projection
aws/aws-cdk pull request #27485
Opened 2023-10-10 19:02 UTC by guyernest

The [partition projection feature in Athena and Glue](https://docs.aws.amazon.com/athena/latest/ug/partition-projection.html) needed to be supported correctly in the S3Table implementation. The table properties from the partition project were not added to the Parameters section of TableInput.

The new implementation allows the definition of the different types of partition projection, including date, integer and enum,

Closes https://github.com/aws/aws-cdk/issues/27365

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-10-10 19:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8374d0c7f0d7fd9104f49f6ef79508c9cc5c6e2c
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1308d441-f7db-425a-8454-a87582561b4a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-10-11 00:55 UTC, scanlonp requested changes
Thank you for the contribution! A couple comments.

First, we require that pulls are made from non-main branches on your fork (see https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request for more info). Please move this on to a different branch.

Removing the unused variable names in the tests should fix the immediate errors in the build. Then we can give a meaningful review.

2023-10-11 00:55 UTC, scanlonp commented on packages/@aws-cdk/aws-glue-alpha/test/s3-table.test.ts
> +    const table = new glue.S3Table(stack, 'Table', {
```suggestion
    new glue.S3Table(stack, 'Table', {
```

2023-10-11 00:55 UTC, scanlonp commented on packages/@aws-cdk/aws-glue-alpha/test/s3-table.test.ts
> +    const table = new glue.S3Table(stack, 'Table', {
```suggestion
    new glue.S3Table(stack, 'Table', {
```

2023-10-11 04:07 UTC, closed without merging

2023-10-11 04:08 UTC, guyernest commented
Cleaning and opening a new PR