feat(glue-alpha): add description to database
aws/aws-cdk pull request #27744
Opened 2023-10-29 22:55 UTC by msambol

Closes #27740.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-10-29 23:24 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5053fd8f5c9a7a8b858f4a157daa846d73b23a2d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b08c6e3b-5a88-4afb-8cb6-64cb585e7912%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-10-30 13:51 UTC, lpizzinidev requested changes
Thanks!
The implementation looks correct, just some adjustments are needed in my opinion.
Also, can you please add validation for the property according to [this](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-database-databaseinput.html#cfn-glue-database-databaseinput-description)?

2023-10-30 14:18 UTC, msambol commented
@lpizzinidev Updated per your recommendations. Thanks!

2023-10-30 14:33 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 32c27d37e4867ed69c955042ccd647dd0bd86c14
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5e437db9-645d-406c-8c50-3e6965b5e162%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-10-30 14:59 UTC, kaizencc approved these changes

2023-10-30 16:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 728ee213d56150c74916d3614753e844e9133e39
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b456b000-ab28-4242-a500-bc8999c945ce%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-10-31 13:43 UTC, kaizencc commented
@msambol I am good with this PR but I want to throw this by @TheRealAmazonKendra because she is working on Glue changes that may or may not impact this PR.

2023-11-06 09:05 UTC, scanlonp requested changes
Should `description` be a public attribute of the `Database` class? It is added in the interface but not in the class. Also two very small nits.

Otherwise this looks great! Thank you.

2023-11-06 09:05 UTC, scanlonp commented on packages/@aws-cdk/aws-glue-alpha/test/database.test.ts
> +  ).toThrow();
```suggestion
  ).toThrow(\description length must be less than or equal to 2048, got 2049\);
```
nit: add error message to test.

2023-11-06 09:05 UTC, scanlonp commented on packages/@aws-cdk/aws-glue-alpha/lib/database.ts
> +    throw new Error(`description length must be less than or equal to 2048, but was ${description.length}`);
```suggestion
    throw new Error(`description length must be less than or equal to 2048, got ${description.length}`);
```
extremely small nit: 'got' is a bit more standardized with the design guidelines.

2023-11-06 13:25 UTC, msambol commented
> Should `description` be a public attribute of the `Database` class? It is added in the interface but not in the class. Also two very small nits.

@lpizzinidev mentioned this may not need to be exposed for now. I can add it if necessary.

2023-11-06 13:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 25abe43ba12de40b50d73e997df6abf0219f13de
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0f745dfc-b8fb-43b5-9167-d303854c4d15%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-11-09 20:45 UTC, msambol commented
@TheRealAmazonKendra Can I nudge you for a review here?

2023-12-03 12:49 UTC, msambol commented
@kaizencc Could we push this one through?

2023-12-07 15:31 UTC, kaizencc submitted a review, later dismissed
Done. Sorry for the delay. Thanks for the review @lpizzinidev. I thought we had some blocker on the glue construct but it's been too long now, and this is an easy win.

2023-12-08 17:51 UTC, paulhcsun commented
Added a `pr/do-not-merge` tag on this for the time being as there is a group working on a Glue refactor (approved RFC) so we are not currently accepting any Glue PRs. We will push this through as soon as that is completed, we appreciate
 your patience @msambol

2023-12-15 23:13 UTC, natalie-white-aws commented
Per Kendra's request, I reviewed these changes and can confirm that these changes do not conflict with the glue-alpha L2 work in flight. Safe to merge pending all other CDK service team checks without impacting our work.

2023-12-22 22:13 UTC, msambol commented
@kaizencc can we push this through? I think an issue with the queue?

2023-12-28 00:08 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the MERGE CONFLICTS state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2023-12-28 18:56 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 73703d765772d1c25c77b37a425ecedb28ab2e50
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=de2829e6-ce2b-471f-8994-5f73cee97508%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-29 14:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: bbfe2f33169e18206eea05a956143e69e314cbc9
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=148912e4-957c-407c-a82c-0bd54bee2222%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-30 21:20 UTC, kaizencc approved these changes

2023-12-30 21:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 021e41c2d786720166fc4d6507bd15f80dba542f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=044cd058-8cc8-4b16-9499-e9cbf16ebb59%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-30 21:48 UTC, merged