fix(ec2): two undefined tunnelInsideCidr should not throw error
aws/aws-cdk pull request #27778
Opened 2023-10-31 17:37 UTC by msambol

Closes #27772.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-10-31 18:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 037538df53340731dc5ce73e6825a2856d518eac
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4d406cb0-9e62-430c-9515-cac26f884752%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-10-31 18:38 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 993de6e4666273d43c79049a53d7b07fc65a0265
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3b83fe39-0f35-4f60-938f-f55154cd2d69%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-11-01 10:15 UTC, lpizzinidev requested changes
Looks good!
Just some adjustments on tests in my opinion.

2023-11-01 10:15 UTC, lpizzinidev commented on packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.vpn-two-tunnels.ts
> +new integ.IntegTest(app, 'aws-cdk-redshift-elastic-ip-test', {
```suggestion
new integ.IntegTest(app, 'aws-cdk-ec2-vpn-two-tunnels-test', {
```

2023-11-01 10:15 UTC, lpizzinidev commented on packages/aws-cdk-lib/aws-ec2/test/vpn.test.ts
> +
```suggestion
  test('with two tunnel options and no tunnelInsideCidr', () => {
    // GIVEN
    const stack = new Stack();

    // WHEN
    new Vpc(stack, 'VpcNetwork', {
      vpnConnections: {
        VpnConnection: {
          ip: '192.0.2.1',
          tunnelOptions: [
            {
              preSharedKeySecret: SecretValue.unsafePlainText('secretkey1234'),
            },
            {
              preSharedKeySecret: SecretValue.unsafePlainText('secretkey5678'),
            },
          ],
        },
      },
    });

    // THEN
    Template.fromStack(stack).hasResourceProperties('AWS::EC2::VPNConnection', {
      CustomerGatewayId: {
        Ref: 'VpcNetworkVpnConnectionCustomerGateway8B56D9AF',
      },
      Type: 'ipsec.1',
      VpnGatewayId: {
        Ref: 'VpcNetworkVpnGateway501295FA',
      },
      StaticRoutesOnly: false,
      VpnTunnelOptionsSpecifications: [
        {
          PreSharedKey: 'secretkey1234',
        },
        {
          PreSharedKey: 'secretkey5678',
        },
      ],
    });
  });

```
Let's check also the template for better coverage.

2023-11-01 15:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c45ce404bcaf995add12672b5d9145b5c4d5073d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a41fee92-a972-44c7-8142-94ba27b99752%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-11-02 17:20 UTC, sumupitchayan approved these changes
Thanks for your contribution!

2023-11-02 18:17 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 651371daaa893c4ddf8aae419d57e7004435b21f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=df5936a3-4c29-451d-b28d-7f091321d67e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-11-02 18:17 UTC, merged