fix(cli): cdk destroy does not throw error for a non-existent stack
aws/aws-cdk pull request #27921
Opened 2023-11-10 03:34 UTC by go-to-k

This PR for cli is to throw an error if stacks with wrong cases (=not exist) specified in `cdk destroy`.

Closes #27179.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-11-10 03:35 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-11-10 03:35 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-11-10 03:37 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-11-10 03:38 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-11-10 03:38 UTC, go-to-k commented
Exemption Request: this should be covered with cli-integ tests. In my environment, the behavior was confirmed as expected.

2023-11-10 03:41 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-11-10 03:44 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-11-10 04:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b16eb1f7f7b75b64d33fd2157a4ab061d4476dad
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6ea31a67-41d4-4a58-a484-1026a84257c4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-11-17 17:33 UTC, vinayak-kukreja commented
Hey, thank you for opening a contribution with us. 
Looks like @SankyRed and @TheRealAmazonKendra were taking a look at the original PR. Will reach out to them if they want to take a look.

2023-11-17 20:35 UTC, go-to-k commented
@vinayak-kukreja Thanks. I would be glad for them to see it.

2023-12-02 00:08 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2023-12-04 05:02 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-04 05:28 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: df5002fc1bbe02dee51f4a30540771df6ec8d6fa
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bb71332f-dd9d-4272-9964-7726e1c82354%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-05 06:27 UTC, go-to-k commented
@lpizzinidev 

Thanks, I changed the message. Please look at this.

2023-12-05 06:28 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-05 06:35 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-05 06:53 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: cb396c19ea309405d8ffd41c1e09878bdf03f21a
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8e8f4d1a-7cd9-45cd-af2e-30cb06c51455%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-05 07:01 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f757fa36011f8be9c61b85bbfdde0c7586595449
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a95a3673-4b81-40f9-8252-b41b6605160e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-05 07:20 UTC, lpizzinidev approved these changes
Thanks 👍

2023-12-05 07:22 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-05 07:24 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-05 16:04 UTC, vinayak-kukreja commented
Hey @go-to-k, apologies that no one has yet got to this. I will take a look today. I have also added a label to not have this PR closed automatically. 
Apologies for the delay.

2023-12-05 16:05 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-05 22:44 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-05 22:44 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-05 22:47 UTC, aws-cdk-automation commented
:arrow_right: **PR build request submitted to `test-main-pipeline`** :arrow_left:

A maintainer must now check the pipeline and add the `pr-linter/cli-integ-tested` label once the pipeline succeeds.
<!-- thollander/actions-comment-pull-request "request-cli-integ-test" -->

2023-12-05 22:49 UTC, vinayak-kukreja approved these changes
Hey @go-to-k , the changes looks good to me. I have started a test run for this CLI change in our pipeline. If that succeeds, I will merge this PR in. 

Thank you for this contribution. Really appreciate your patience.

2023-12-05 22:50 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-05 22:50 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-05 22:51 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-05 23:12 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-06 07:51 UTC, go-to-k commented
@vinayak-kukreja 

I changed it to try it out. (But I don't still confirm the behavior because cli-integ-tests itself does not work in my environment.) Please give it a try.

Here are [the tests](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts#L581-L587).

```ts
['typescript', 'python', 'csharp', 'java'].forEach(language => {
  integTest(`cdk migrate ${language}`, withCDKMigrateFixture(language, async (fixture) => {
    if (language === 'python') {
      await fixture.shell(['pip', 'install', '-r', 'requirements.txt']);
    }

    const stackArn = await fixture.cdkDeploy(fixture.stackNamePrefix, { neverRequireApproval: true, verbose: true, captureStderr: false }, true);
    const response = await fixture.aws.cloudFormation('describeStacks', {
      StackName: stackArn,
    });

    expect(response.Stacks?.[0].StackStatus).toEqual('CREATE_COMPLETE');
    await fixture.cdkDestroy(fixture.stackNamePrefix);
```

In these tests, `true` is specified as the third arg (`skipStackRename`) for `fixture.cdkDeploy`, `fixture.stackNamePrefix` is specified as the first arg (`stackNames`). And, at the `fixture.cdkDestroy`, `fixture.stackNamePrefix` is used.

In `cdkDeploy`, `stackNames` is used instead of `this.fullStackName(stackNames)` when skipStackRename is `true`.

```ts
  public async cdkDeploy(stackNames: string | string[], options: CdkCliOptions = {}, skipStackRename?: boolean) {
    stackNames = typeof stackNames === 'string' ? [stackNames] : stackNames;

    const neverRequireApproval = options.neverRequireApproval ?? true;

    return this.cdk(['deploy',
      ...(neverRequireApproval ? ['--require-approval=never'] : []), // Default to no approval in an unattended test
      ...(options.options ?? []),
      // use events because bar renders bad in tests
      '--progress', 'events',
      ...(skipStackRename ? stackNames : this.fullStackName(stackNames))], options);
  }
```

https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk-testing/cli-integ/lib/with-cdk-app.ts#L331

On the other hand, in the `cdkDestroy`, only `this.fullStackName(stackNames)` is used.

```ts
  public async cdkDestroy(stackNames: string | string[], options: CdkCliOptions = {}) {
    stackNames = typeof stackNames === 'string' ? [stackNames] : stackNames;

    return this.cdk(['destroy',
      '-f', // We never want a prompt in an unattended test
      ...(options.options ?? []),
      ...this.fullStackName(stackNames)], options);
  }
```

https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk-testing/cli-integ/lib/with-cdk-app.ts#L347

So, in the tests, I changed to pass `fixture.fullStackName(fixture.stackNamePrefix)` instead of `stackNames` into `fixture.cdkDeploy`.

2023-12-06 08:51 UTC, go-to-k commented on packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
> +    const stackArn = await fixture.cdkDeploy(fixture.fullStackName(fixture.stackNamePrefix), { neverRequireApproval: true, verbose: true, captureStderr: false }, true);
https://github.com/aws/aws-cdk/pull/27921#issuecomment-1842282221

2023-12-06 08:53 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-06 12:06 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-06 12:06 UTC, go-to-k commented on packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
> +    const stackArn = await fixture.cdkDeploy(fixture.stackNamePrefix, { neverRequireApproval: true, verbose: true, captureStderr: false });
https://github.com/aws/aws-cdk/pull/27921#issuecomment-1842282221

2023-12-06 12:08 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-06 12:37 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-06 12:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6e5ca799136ac5ce16d9569372c701ad6f684d14
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0b2bc485-a777-4308-99e5-1ce8f08902fa%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-06 17:17 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-06 17:19 UTC, aws-cdk-automation commented
:arrow_right: **PR build request submitted to `test-main-pipeline`** :arrow_left:

A maintainer must now check the pipeline and add the `pr-linter/cli-integ-tested` label once the pipeline succeeds.
<!-- thollander/actions-comment-pull-request "request-cli-integ-test" -->

2023-12-06 17:19 UTC, vinayak-kukreja commented
Running in pipeline.

2023-12-06 17:42 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 896db29fb0a513ef40cc8be963994b42df9fea0f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=779f99ae-3c92-42e7-b072-520c4767c23d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-06 19:01 UTC, vinayak-kukreja commented
I see it failed in pipeline,

```
No stacks match the name(s) cdk-migrate-typescript-integ-0vtozm4x3czs-cdk-migrate-typescript-integ-0vtozm4x3czs
[18:35:22] Error: No stacks match the name(s) cdk-migrate-typescript-integ-0vtozm4x3czs-cdk-migrate-typescript-integ-0vtozm4x3czs
[INTEG TEST::cdk migrate typescript] Failed: Error: 'cdk -v deploy --require-approval=never --progress events cdk-migrate-typescript-integ-0vtozm4x3czs-cdk-migrate-typescript-integ-0vtozm4x3czs' exited with error code 1.

2023-12-07 01:30 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-07 01:31 UTC, go-to-k commented
@vinayak-kukreja 

I see, I think the `cdkDestroy` function should be changed. 

I fixed, please give it a try.

2023-12-07 01:32 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-07 01:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e62c782a7179ae96af1aff81b2b1600b32128732
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=396ab8e5-c176-4eec-914a-8bfe88e28d23%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-07 01:49 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-07 01:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e985e72fd8a31369c50cb2725c81ef2d3aaa797e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a39153d8-c13b-4970-b1c6-e8bdb14a0c0b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-07 02:13 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: a22025b858f3e3f7faadb6c8ca9533b75b41307f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1e759e57-8e5d-4391-9edc-e8f78acada64%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-07 02:14 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0ea97b81687e9f95d09e8eb061ca3d08ae22ccf6
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2c54f0ad-74a1-4cea-963c-fd2449221347%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-07 18:28 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-07 18:29 UTC, aws-cdk-automation commented
:arrow_right: **PR build request submitted to `test-main-pipeline`** :arrow_left:

A maintainer must now check the pipeline and add the `pr-linter/cli-integ-tested` label once the pipeline succeeds.
<!-- thollander/actions-comment-pull-request "request-cli-integ-test" -->

2023-12-07 18:53 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 749f755022b48af96671b968d93ccbda49e70c14
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4b56e1f2-e570-4c45-aa7d-201211b4ff30%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-07 21:24 UTC, vinayak-kukreja commented
Hey it is still failing. I will pull the code and try to take a look today.

2023-12-09 00:32 UTC, go-to-k commented
@vinayak-kukreja I see. I agree with you.

If so, what exactly would be the method to log this to the user? For example, there is annotation in construct, but is there an alternative in CLI?

2023-12-09 14:33 UTC, go-to-k commented
@vinayak-kukreja 

I've made the change for now, what do you think?

2023-12-09 14:34 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-09 14:37 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-09 14:38 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-09 14:43 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-09 15:00 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: eb363c7371a534a46032e62a4b6e2165bb1403b2
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=05720c7e-74d8-43da-969d-6c44d46556c0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-09 17:08 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to a test file.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-08 16:28 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to a test file.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-08 16:54 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: df4c865aedc512161e9232b962dc5de882051327
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a7ac75a1-066f-421a-865f-df3203b4615e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-11 11:09 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to a test file.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-11 11:35 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 13359260b2942101c50f87ae7753120790669c3e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e74d0ed1-3820-412e-9dc1-554a9986b894%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-23 18:45 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to a test file.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-23 19:11 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1e90fedb072d520dbca094194ef2c8cef721556f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0f31cacc-98ee-4005-a176-d84b90ab031e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-23 19:25 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to a test file.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-23 19:26 UTC, aws-cdk-automation commented
:arrow_right: **PR build request submitted to `test-main-pipeline`** :arrow_left:

A maintainer must now check the pipeline and add the `pr-linter/cli-integ-tested` label once the pipeline succeeds.
<!-- thollander/actions-comment-pull-request "request-cli-integ-test" -->

2024-01-23 19:50 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ce29bb93f0d007852144d1333d55a30916cd860e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=74f24cf5-78a4-4cfb-ba91-be1e58b9d196%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-23 21:45 UTC, aws-cdk-automation commented
:arrow_right: **PR build request submitted to `test-main-pipeline`** :arrow_left:

A maintainer must now check the pipeline and add the `pr-linter/cli-integ-tested` label once the pipeline succeeds.
<!-- thollander/actions-comment-pull-request "request-cli-integ-test" -->

2024-01-23 21:47 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-23 21:48 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-23 21:48 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-23 21:52 UTC, aws-cdk-automation commented
:arrow_right: **PR build request submitted to `test-main-pipeline`** :arrow_left:

A maintainer must now check the pipeline and add the `pr-linter/cli-integ-tested` label once the pipeline succeeds.
<!-- thollander/actions-comment-pull-request "request-cli-integ-test" -->

2024-01-23 22:13 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: a2de8172d605d8db8a338fc77ffb977f9976ab65
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7f1ccd67-b866-419d-aec9-0ecbc65ee229%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-24 00:05 UTC, paulhcsun requested changes

2024-01-24 00:05 UTC, paulhcsun commented on packages/aws-cdk/lib/cdk-toolkit.ts
> +      warning(`${notExistPatterns.join(', ')} ${notExistPatterns.length === 1 ? 'does' : 'do'} not exist.`);
The wording in this warning doesn't really tell the user why the stack does not exist. If it's the case that we're just checking for case insensitive matches then maybe we can explicitly tell the user that's the case or point out that they need to change their capitalization. Using the `iamstack` vs `IAMStack` example, something like:

 ```
iamstack does not exist. Do you mean IAMStack?
``` 
or 
```
iamstack does not exist but closely matches IAMStack (or simply another stack name). Please check your casing.
```

2024-01-24 00:08 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-24 00:08 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-24 06:03 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-24 06:13 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-24 06:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6e9f2ce3528ab1affa1638c048a2b686c3dcb61a
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f462a863-c995-4ff6-8db4-1b5b339c609f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-24 06:23 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-24 06:24 UTC, go-to-k commented
@paulhcsun 

Thanks for your review. I fixed it and I hope you take a look at it.

And I also changed to not display the message `Are you sure you want to delete:` if there is no matching stack.

![destroy-stacks-no-exists](https://github.com/aws/aws-cdk/assets/24818752/5f66f92a-5393-4c79-8633-c6585d73ddbf)

2024-01-24 06:26 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 707f92bde7a1c4a168ee6ceedcafd157593c84ad
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=50772589-3f1b-4853-9c2c-d81b45899979%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-24 06:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 01d7c2155d5cb383c6d24dca7bcb209c4d571513
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=399382ba-a90c-4e77-9db8-198efdec997f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-24 22:36 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-24 22:37 UTC, aws-cdk-automation commented
:arrow_right: **PR build request submitted to `test-main-pipeline`** :arrow_left:

A maintainer must now check the pipeline and add the `pr-linter/cli-integ-tested` label once the pipeline succeeds.
<!-- thollander/actions-comment-pull-request "request-cli-integ-test" -->

2024-01-24 22:43 UTC, paulhcsun commented
@go-to-k Thanks for updating the warning message! It looks a lot better to me. Let me run it by the UX team and I'll let you know if there's any additional feedback they have. I've run the cli-integ tests but one of the regression tests failed. It may just be flaky but I will rerun and update you once that's done.

2024-01-24 23:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: aa9e08062b597373b3cec0057628b7bb2347f82d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e4b0b822-44b1-4cf7-a307-dc2df410f77f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-24 23:17 UTC, aws-cdk-automation commented
:arrow_right: **PR build request submitted to `test-main-pipeline`** :arrow_left:

A maintainer must now check the pipeline and add the `pr-linter/cli-integ-tested` label once the pipeline succeeds.
<!-- thollander/actions-comment-pull-request "request-cli-integ-test" -->

2024-01-25 21:41 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-25 22:06 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1ac0cf949cf319e78ae7b3dcda6cd325f90c3edc
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f90287e7-d8fd-4303-b19a-906cbf3d2d47%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-26 07:32 UTC, go-to-k commented
@paulhcsun 

> I've run the cli-integ tests but one of the regression tests failed.

Oh...

> And I also changed to not display the message Are you sure you want to delete: if there is no matching stack.

I thought it may be due to [this change](https://github.com/aws/aws-cdk/pull/27921/commits/01d7c2155d5cb383c6d24dca7bcb209c4d571513#diff-8cff125f4b53b025add8740ab74f39ee6c20221c0d3ac5ab7db184a6bb077398R578-R580) that alters the interaction flow, but cli-integ uses [the cdkDestroy](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk-testing/cli-integ/lib/with-cdk-app.ts#L344-L345) with `-f` so it may be not...

Once I see the results of the cli-integ details, I will think about it. Let me know if you discover anything else.

2024-02-02 00:41 UTC, go-to-k commented
@paulhcsun 

Could you please tell me the result of the cli integ test? Knowing which regression tests failed, etc., might give us a clue as to how to fix it.
Or are we in a state of waiting for another team?

2024-02-19 10:07 UTC, go-to-k commented
@paulhcsun 

Could you please confirm the above comments? Thanks.

2024-03-03 15:38 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-03 15:40 UTC, go-to-k commented
@paulhcsun

Could you please confirm the above comments?

2024-03-03 16:05 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7a64baee78c31ed81af74b5a65c9be6e1d67d087
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0c859efc-59ef-44aa-b0d8-a5923df69635%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-03-13 05:43 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-15 18:07 UTC, aws-cdk-automation commented
:arrow_right: **PR build request submitted to `test-main-pipeline`** :arrow_left:

A maintainer must now check the pipeline and add the `pr-linter/cli-integ-tested` label once the pipeline succeeds.
<!-- thollander/actions-comment-pull-request "request-cli-integ-test" -->

2024-03-15 18:12 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-15 18:20 UTC, aws-cdk-automation commented
:arrow_right: **PR build request submitted to `test-main-pipeline`** :arrow_left:

A maintainer must now check the pipeline and add the `pr-linter/cli-integ-tested` label once the pipeline succeeds.
<!-- thollander/actions-comment-pull-request "request-cli-integ-test" -->

2024-03-15 18:25 UTC, paulhcsun commented
Hi @go-to-k, I'm very sorry for not getting back to you on this, we were in a state of waiting for another team but this was on me for not noticing your comments. I'm running the CLI integ tests through the pipeline now and will update you with the results soon. After which I will delegate this review to someone with more knowledge on the CDK CLI.

2024-03-15 18:30 UTC, go-to-k commented
@paulhcsun Thank you! I'm looking forward to hearing from you and the team after this!

2024-03-15 18:38 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 95f2caabdb3dbaeb2ae31eadb781655e6a34a9ab
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=63ca39a9-d21f-43f5-bc1f-4e59312e671b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-03-18 16:28 UTC, paulhcsun commented
Apologies @go-to-k, there were some additional runs queued in the pipeline before this one so I couldn't check the results in time. It looks like it was skipped for some reason though, I will retry running it now.

2024-03-18 16:29 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/27921/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-18 16:29 UTC, aws-cdk-automation commented
:arrow_right: **PR build request submitted to `test-main-pipeline`** :arrow_left:

A maintainer must now check the pipeline and add the `pr-linter/cli-integ-tested` label once the pipeline succeeds.
<!-- thollander/actions-comment-pull-request "request-cli-integ-test" -->

2024-03-18 16:55 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e5ac121189dac015752b20a5473a39f9e8bc6624
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=de7fd484-be19-4d42-b946-1d0b49be342b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-03-18 19:16 UTC, paulhcsun commented
@go-to-k I've added the `cli-integ-tested` label as the most recent run of the pipeline has passed all checks. Seems like it was just flaky integ tests the last time around. Thanks for your patience.

2024-03-18 21:44 UTC, aws-cdk-automation commented
:arrow_right: **PR build request submitted to `test-main-pipeline`** :arrow_left:

A maintainer must now check the pipeline and add the `pr-linter/cli-integ-tested` label once the pipeline succeeds.
<!-- thollander/actions-comment-pull-request "request-cli-integ-test" -->

2024-03-18 22:10 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ab639fa06bde988490f3fec93e44cb8446e0d05b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6e8cdb43-0a41-4141-8545-a15dddaa7750%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-03-18 22:46 UTC, paulhcsun approved these changes

2024-03-18 22:47 UTC, merged