Typo in RDS docs
aws/aws-cdk pull request #28115
Opened 2023-11-22 23:05 UTC by zerj9

Fix typo found in RDS Performance Insights prop documentation.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-11-22 23:07 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-11-22 23:07 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-11-22 23:09 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-11-22 23:16 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-11-22 23:17 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-11-22 23:18 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-11-22 23:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c579947deaeb7a99921c3faacf42c3feb3a91c5a
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=65fbe528-6673-41da-8f55-d77d48ab1e85%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-11-22 23:40 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b86a0cc5d5dc47cd95cb9d22c1a2a1aaafd68886
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9502f7a3-2ea6-4c75-8a8c-420d4c4ae961%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-11-22 23:42 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 398431715aad2a4ed7ea1a41d8006767764885a5
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=87d63185-5a67-4ed1-ac88-e9f871203ad2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-11-24 14:18 UTC, go-to-k requested changes
Thanks for the contribution.

Can you please change the title to `docs(rds): ...`?

2023-11-24 14:42 UTC, go-to-k approved these changes
Thanks!

2023-11-27 15:07 UTC, scanlonp submitted a review, later dismissed
Thanks!

2023-11-27 22:49 UTC, vinayak-kukreja approved these changes

2023-11-27 23:14 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0c410c6207f055257afdf65b0640defa6af136c0
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ed5541a0-9a40-4365-9575-dc939b291c96%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-11-27 23:15 UTC, merged