fix(s3): lifecycle rule dates require trailing Z
aws/aws-cdk pull request #28149
Opened 2023-11-27 14:05 UTC by msambol

The trailing `Z` is now required: 

- [ExpirationDate](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-rule.html#cfn-s3-bucket-rule-expirationdate)
- [TransitionDate](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-transition.html#cfn-s3-bucket-transition-transitiondate)

Closes #28065, #28124.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-11-27 14:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 13a38d1ddbc98d24743a0a4b8b381ca48de38df7
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c1893523-6114-47e7-9c2d-a11ae2e6dc35%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-11-28 09:14 UTC, lpizzinidev requested changes
Looks good 👍
I left you a note on an added file.

Also, the `dateToCloudFormation` method is used when parsing dates for [`ScheduledAction`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-applicationautoscaling-scalabletarget-scheduledaction.html)'s `StartTime` and `EndTime`.
Can you please add integration/unit tests for that as well?
(You can use [this](https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk-testing/framework-integ/test/aws-lambda/test/integ.autoscaling.lit.ts) as a starting point).

Finally, I'm not sure about the title, it should [describe the bug (not the solution)](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request).
Something like `fix(core): wrong CloudFormation date formatting` is probably more aligned.

2023-11-28 09:14 UTC, lpizzinidev commented on packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
Should this file be included?

2023-11-28 10:55 UTC, wakeupmh commented on packages/@aws-cdk/cli-lib-alpha/THIRD_PARTY_LICENSES
I think he added the EOF only

2023-11-28 10:57 UTC, wakeupmh approved these changes

2023-11-28 13:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0690e09f206b78359b24eac0babcbc0963d4bbe9
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1da40b0a-e9ad-434a-ba88-c47fd2e50a12%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-11-28 13:59 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6123c1df4875f8ca5ddc8bec5c346e5da4ec8a35
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b16e6997-8ebe-4f6f-9ca5-9b3e71b2aabe%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-11-28 14:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: a891cbde54f0a8b683451115f507b52a162bef8e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ed3c3ceb-0eab-4ab5-b981-d34988fd4127%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-11-28 14:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3ff4bb81c12550a81fd9717eba55eb19ec72dcce
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c90cd202-cded-4a3f-812a-111de66559c8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-11-28 14:03 UTC, msambol commented
@lpizzinidev I updated the PR with the other integration test. 👍🏼

2023-11-28 15:25 UTC, SankyRed approved these changes
The change looks good to me. Thank you for your contribution.

2023-11-28 15:26 UTC, merged