feat(core): add support for AccountIdFromAlias #27642
aws/aws-cdk pull request #28180
Opened 2023-11-28 23:35 UTC by YYang30

**reason for this change:**
- Cloud Formation team introduced the support for referencing an AWS account via a new intrinsic function `Fn::AccountIdFromAlias`. This function can be used in cloud formation templates to reference another account(s) using a conventional alias string. We can get rid of hardcoding AWS account ID(s) in cloud formation templates. So it's helpful for automating region build process. 
- However, `cfn-parse` in the `aws-cdk/core` module has not yet added the support for this new CFN function, as a result of which, `cfn-parse` would fail to recognize this function as a valid/supported CFN function. 

fix #27642 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-11-28 23:36 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-11-28 23:36 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-11-28 23:39 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-11-28 23:54 UTC, YYang30 commented
Exemption Request

- (justification for requesting exemption on integration test) The test does not require a stack deployment. `cfn-parse` is an internal helper class for validating a cloud formation template. Please feel free to suggest. Will appreciate any guidance/suggestion and be happy to adopt them. 

- (need clarification on doc/readme change). Checked this readme file for aws-cdk-lib/core module [link](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/core/README.md#intrinsic-functions-and-condition-expressions). Is this the right file/place to use?

2023-11-28 23:56 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-11-29 00:01 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1bd4042bdc67de8ddf204bac81e3bc0ff9bd35c2
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0e2fb3f9-63ec-475e-9cb8-c9c59828ff9d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-11-29 00:04 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-11-30 19:10 UTC, YYang30 commented
`Exemption Request`

(justification for requesting exemption on integration test) The test does not require a stack deployment. cfn-parse is an internal helper class for validating a cloud formation template. Please feel free to suggest. Will appreciate any guidance/suggestion and be happy to adopt them.

(need clarification on doc/readme change). Checked this readme file for aws-cdk-lib/core module [link](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/core/README.md#intrinsic-functions-and-condition-expressions). Is this the right file/place to use?

2023-12-05 08:10 UTC, scanlonp requested changes
This change looks great! 

On the exemption, I do not think you need either an integ test or a readme update.

However, I could not find any documentation on the Fn::AccountIdFromAlias cloudformation function. For example it is not here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html. Can you provide some documentation on this function?

2023-12-05 16:28 UTC, YYang30 commented
@scanlonp  Thanks for the review.
Please check this document - https://w.amazon.com/bin/view/AWS/CloudFormation/Teams/SkyTrain/Projects/AccountIdFromAlias/

2023-12-05 17:36 UTC, scanlonp commented
Hey @YYang30, that is an internal page that specifically says it is an internal only function. First, this is a public github. We should not be posting internal information here. Second, since it is internal, we will not be including the code here.

Please be careful in the future!

2023-12-05 17:36 UTC, closed without merging

2023-12-05 17:45 UTC, YYang30 commented
Thanks @scanlonp for the notes. Will keep in mind on document sharing.
Wanted to follow up on this code change. 

- What's risk of including this improvement into core/internal-helper module? All it does is just having `cfn-parse` to be able to recognize this internal as a valid CFN function.  
- Is this an "internal" version of `aws-cdk-lib` or another repo that is dedicated for internal use? 
- What's the workaround to have `cfn-parse` support this? 

It will be greatly appreciated if you could shed some lights on above questions. That would be helpful to unblock our progress. Thank you.