docs(apigateway): set integrationHttpMethod for vpc link integration
aws/aws-cdk pull request #28299
Opened 2023-12-08 04:35 UTC by tmokmss

As written in #6404, a VPC link integration fails to deploy unless we set `integrationHttpMethod` prop explicitly.

In this PR we fix the document accordingly.
 
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-12-08 05:01 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b8c9ecc2ba47b34991c5c96347d83dda37440bf7
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a3dd5ce9-c33d-492f-91e8-2db7df45c0d7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-08 13:32 UTC, lpizzinidev requested changes
I think we should also add validation for the property and update the documentation [here](https://github.com/aws/aws-cdk/blob/020bf18c214199cb124a44fee9a3bb4a8f115ebc/packages/aws-cdk-lib/aws-apigateway/lib/integration.ts#L138) and [here](https://github.com/aws/aws-cdk/blob/020bf18c214199cb124a44fee9a3bb4a8f115ebc/packages/aws-cdk-lib/aws-apigateway/lib/integrations/aws.ts#L59) according to the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-method-integration.html#cfn-apigateway-method-integration-integrationhttpmethod).

2023-12-08 18:10 UTC, kaizencc approved these changes
@tmokmss thanks! @lpizzinidev feel free to create an issue out of that, can be addressed in a future PR

2023-12-08 20:35 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: a167e1108bb833cb7339c70c4e90e6586583a450
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=afbf3130-7cd2-401e-8ac3-19263bde25e4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-11 14:30 UTC, kaizencc approved these changes

2023-12-11 14:55 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f445339cfe500c75913a16fcfc24a23a765a158f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5356de1b-fb95-4623-98cc-f2fc05d23392%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-11 15:24 UTC, merged