feat(ecs): Implement grantTaskProtection method for ECS cluster task role permissions
aws/aws-cdk pull request #28486
Opened 2023-12-25 10:20 UTC by badmintoncryer

Added a `grantTaskProtection` method to the ECS (Elastic Container Service) Cluster. This method grants ECS tasks the necessary permissions to interact with the task protection API.

Closes #26233

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-12-25 10:22 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2023-12-25 10:22 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-25 10:24 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-25 10:47 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7447b10474ac04147e0f74d89f9316654d6dcbe3
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e0fdc58e-8950-4197-8d95-396e42df9a9f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-25 12:51 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2023-12-25 13:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 91e1d1ad9b6c5ac8e43d04e3d7c47899cb6bee40
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=38e53bac-7424-4558-b301-2946e89cfd25%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-25 13:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8867b77bdea2e86d09bdfef0366d95ff6b3dbaed
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e2f0ddeb-71ad-4c13-a4de-d85c8f544031%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-26 12:37 UTC, go-to-k requested changes
Thanks for your contribution!

It looks good. I have only minor comments.

2023-12-26 12:37 UTC, go-to-k commented on packages/aws-cdk-lib/aws-ecs/lib/cluster.ts
> +  * @param grantee - The entity (e.g., IAM role or user) to grant the permissions to.
```suggestion
  * @param grantee The entity (e.g., IAM role or user) to grant the permissions to.
```

2023-12-26 12:37 UTC, go-to-k commented on packages/aws-cdk-lib/aws-ecs/README.md
> +The grantTaskProtection method simplifies the process of granting ECS Task Protection API permissions to a specified IAM entity. This is particularly useful for scenarios where you need to allow an I
Could you please insert appropriate line breaks?

2023-12-26 12:59 UTC, go-to-k commented on packages/aws-cdk-lib/aws-ecs/README.md
> +The grantTaskProtection method simplifies the process of granting ECS Task Protection API permissions to a specified IAM entity. This is particularly useful for scenarios where you need to allow an I
Also, it might be a good idea to enclose CDK-specific words in backquotes, like `grantTaskProtection` and `ecs: UpdateTaskProtection`.

2023-12-26 13:16 UTC, go-to-k commented on packages/aws-cdk-lib/aws-ecs/lib/cluster.ts
> +  * permission, enabling the grantee to manage task protection in the ECS cluster.
```suggestion
  * Grants an ECS Task Protection API permission to the specified grantee.
  * This method provides a streamlined way to assign the 'ecs:UpdateTaskProtection'
  * permission, enabling the grantee to manage task protection in the ECS cluster.
```

2023-12-27 03:22 UTC, go-to-k commented on packages/aws-cdk-lib/aws-ecs/README.md
> +The grantTaskProtection method simplifies the process of granting ECS Task Protection API permissions to a specified IAM entity. This is particularly useful for scenarios where you need to allow an I
The explanation could be simplified a bit more.
For example, as follows.

```suggestion
To manage task protection settings in an ECS cluster, you can use the `grantTaskProtection` method.
This method grants the `ecs:UpdateTaskProtection` permission to a specified IAM entity.
```

2023-12-27 04:38 UTC, badmintoncryer commented
@go-to-k Thank you for the review. I have made the revisions as you suggested.

2023-12-27 05:01 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: dc173eaa0719480a8b163262f3dc187f064a6873
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3b11bcb6-d00f-4555-9dff-cbd2c05a2ff8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-27 05:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d0f6594cb767cec6848d7a57b5c89a39aec80901
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=17ad4952-d77c-4a7d-a7d4-6a6b838617a8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-27 05:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3654e6e0790ca3a0ced54b2d9a8376a3fd4dd631
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=812aa3a6-f42e-4b86-91b2-277ce3371e0b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-27 05:06 UTC, go-to-k approved these changes
Looks good!

2023-12-27 15:50 UTC, sumupitchayan approved these changes

2023-12-27 16:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 21665f10178cb92e1b12738f379425fdea5055a5
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=75f45dd1-e5e2-4698-9323-62709ae349cd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-27 16:18 UTC, merged