feat(ses): Auto Setting for DMARC
aws/aws-cdk pull request #28507
Opened 2023-12-28 08:43 UTC by watany-dev

Introducing DMARC functionality to Amazon SES Construct to enhance email security by authenticating sender identity. This feature allows users to enable DMARC for their email domains with minimal configuration.

- Changes
Added autoDmarc flag in EmailIdentity for automatic DMARC TXT record creation.
Optional dmarcReportEmail for custom DMARC report destination.

- Example

```ts
new ses.EmailIdentity(this, 'Identity', {
  identity: ses.Identity.publicHostedZone(myHostedZone),
  autoDmarc: true,
  dmarcReportEmail: 'custom-report@domain.com',
});
```

- Impact
Facilitates easy DMARC setup for Amazon SES users, enhancing domain security against email spoofing.
https://support.google.com/a/answer/2466580

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2023-12-28 09:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: fdb96205e16e7ab709888d51925f1a339f7bc43f
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2a25d1f8-17d0-4127-a00e-03ec1083bb04%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2023-12-28 09:24 UTC, watany-dev commented
The integ test should have passed locally.

2023-12-29 04:04 UTC, kaizencc submitted a review, later dismissed
just one comment @watany-dev, which should also have its own unit test, and then we are good to go. Thanks!

2023-12-29 04:04 UTC, kaizencc commented on packages/aws-cdk-lib/aws-ses/lib/email-identity.ts
> +    if (props.autoDmarc && props.identity.hostedZone) {
If `props.dmarcReportEmail` is set but `props.autoDmarc` is not, then the email will be ignored, which I argue is unexpected. Instead, we should assume that `autoDmarc` is true if `dmarcReportEmail` is set.

2023-12-29 13:47 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6966a4eb498eead502c24bfb724b702cd3fbeaea
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e558010e-3058-4f74-9333-f30d686d2a52%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-02 11:38 UTC, kaizencc requested changes
Looks good @watany-dev but looks like the integ test needs updating?

2024-01-02 11:56 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6110517c6a1a27eb0da3fa28a7ecaece5c8aff57
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=04d7cea3-ceb2-4863-aaa9-350b28cfa0a0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-24 00:08 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2024-02-01 00:09 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2024-02-01 00:09 UTC, closed without merging