Update Kinesis Stream buffering interval limits
aws/aws-cdk pull request #28589
Opened 2024-01-05 14:11 UTC by abogaziah

According to aws updates of December 2023, Kinesis Stream buffering interval can be as low as five seconds, however that's not yet reflected in the CDK https://aws.amazon.com/about-aws/whats-new/2023/12/amazon-kinesis-data-firehose-zero-buffering/

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-01-05 14:13 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-01-05 14:13 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-05 14:15 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-05 14:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 17ee7cc6a2af15bebee829f4bb223af73be109f9
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f8525c5e-dabe-45d7-b218-b53c9f18fe92%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-08 20:56 UTC, kaizencc requested changes
This PR is not in a state where we would be willing to take a look at it. @abogaziah to get a review, you need to:

- make sure your title fits "conventional commits"
- make sure you have a unit test and that the build is succeeding

Otherwise we cannot review this PR and it will eventually be closed

2024-01-08 20:58 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-15 22:19 UTC, humanzz commented
I just realized I created a feature request for supporting zero buffering at #28714 along with a PR at #28716

2024-01-17 00:08 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2024-01-18 00:08 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2024-01-19 00:08 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2024-01-20 00:08 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2024-01-21 00:09 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2024-01-22 00:09 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2024-01-23 00:08 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2024-01-24 00:08 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2024-01-25 00:05 UTC, closed without merging