feat(aws-ec2) export NatGatewayProvider for consistency with NatInstanceProvider
aws/aws-cdk pull request #28810
Opened 2024-01-22 13:11 UTC by crh23

Export `NatGatewayProvider` for two reasons: to allow instantiation with `new`, and to make docs present it as an implementation of `NatProvider`.
Also added a unit test for the same "functionality" for `NatInstanceProvider`, for symmetry with the added test for `NatGatewayProvider`. 
Unit test and integration test for new functionality added.

Closes #28372.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-01-22 13:13 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-01-22 13:15 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-22 13:17 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ The title of the pull request should omit 'aws-' from the name of modified packages. Use 'ec2' instead of 'aws-ec2'.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-22 13:27 UTC, crh23 commented
Clarification Request: this change is somewhere between a feature and a bug fix ([actual change is tiny](https://github.com/aws/aws-cdk/pull/28810/files#diff-1228e5eb29751308416d9af171ef17872ef911c3b2f1249a78e120a1f22c3565)).

1. Should I relabel it as a bug fix?
2. If not, is a README change required? The enabled functionality is very minor, and the previously-available version isn't in the README currently (closest is "[Using NAT instances](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2-readme.html#using-nat-instances)")

2024-01-22 13:29 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-22 13:29 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-26 14:57 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-26 15:24 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b4e77b663c021d7db5facf0b71b22ef05f200774
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=79ff7776-7ef8-4c02-adeb-0d3784672a6c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-26 15:27 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-30 16:45 UTC, crh23 commented
Applying a bit more thought, I think this is a bug fix more than a feature - the change to actual functionality is the addition of a single `export`, and it seems unintentional that that wasn't already present,

2024-03-05 00:07 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the MERGE CONFLICTS state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2024-03-05 12:26 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: adc54b08b042cee5b39268b2aaffe3128a0c76e5
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2cdfab5d-ca8e-408c-922a-c54fd97cb261%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-03-21 23:42 UTC, msambol commented on packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts
> +    test('Can instantiate NatGatewayProvider directly with new', () => {
`Can instantiate NatInstanceProvider directly with new`

2024-03-21 23:42 UTC, msambol commented on packages/aws-cdk-lib/aws-ec2/test/vpc.test.ts
> +    test('Default NAT gateway provider instantiated directly with new', () => {
nit: `Can instantiate NatGatewayProvider directly with new`

2024-03-21 23:43 UTC, msambol commented on packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-gateway-provider.ts
> +    /// !show
what's `/// !show` ?

2024-03-21 23:44 UTC, msambol requested changes
Few nits but looks good to me.

2024-04-16 23:32 UTC, TheRealAmazonKendra commented
Hmm, not totally sure how I feel about this one, not because anything you've done here is invalid but because it looks to me like the error here was exporting the other function, not the lack of export on this one. We can't undo the export because that would be a breaking change, but I'm not sure if it's better to have it consistently wrong in both places or inconsistent.

2024-04-16 23:53 UTC, TheRealAmazonKendra commented on packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-gateway-provider.ts
> +    /// !show
We don't use pragma anymore.

2024-04-16 23:53 UTC, TheRealAmazonKendra commented on packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.nat-gateway-provider.ts
> +    Array.isArray(natGatewayProvider.configuredGateways);
What are these for?

2024-04-17 11:06 UTC, crh23 commented
> Hmm, not totally sure how I feel about this one, not because anything you've done here is invalid but because it looks to me like the error here was exporting the other function, not the lack of export on this one. We can't undo the export because that would be a breaking change, but I'm not sure if it's better to have it consistently wrong in both places or inconsistent.

I've seen folks be confused by the current inconsistency. In the design of the CDK docs, the natural way (for me) to find the implementations of an abstract class (such as `NatProvider`) is to view the classes listed in _Implemented by_. Currently this misses `NatGatewayProvider`, but includes `NatInstanceProvider`. The new `NatInstanceProviderV2`, which was added since I raised this CR, is also `export`ed.

I think I agree that it would be best to `export` none of them (and add a usage note to the docs of `NatProvider`), but that's not an option now, and I think `export`ing one but not the other (current situation) is worse than `export`ing all (this CR).

2024-04-17 11:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 661bed1a7ff0b5667cbd10a8104555d232f26dcf
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f8060c68-a8f3-4fe8-bae8-92e84cc73342%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-07-31 17:14 UTC, TheRealAmazonKendra approved these changes
> I've seen folks be confused by the current inconsistency. In the design of the CDK docs, the natural way (for me) to find the implementations of an abstract class (such as NatProvider) is to view the classes listed in Implemented by. Currently this misses NatGatewayProvider, but includes NatInstanceProvider. The new NatInstanceProviderV2, which was added since I raised this CR, is also exported.
>
> I think I agree that it would be best to export none of them (and add a usage note to the docs of NatProvider), but that's not an option now, and I think exporting one but not the other (current situation) is worse than exporting all (this CR).

Fair point. 

YOLO

2024-07-31 17:14 UTC, TheRealAmazonKendra submitted a review, later dismissed

2024-07-31 17:43 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: fa0c7ae0ff01f30048a28caa1a4b4c919859f606
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ca8adbbd-bae4-4b2a-9cb8-5e5bfff80b9b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-07-31 17:50 UTC, TheRealAmazonKendra commented
Drat. This failing test has nothing to do with your change and everything to do with how long your waiting on this approval. I'll fix it.

2024-07-31 18:35 UTC, crh23 commented
> Drat. This failing test has nothing to do with your change and everything to do with how long your waiting on this approval. I'll fix it.

Ack - I recall getting integ tests working in my environment was a bit of a chore, so happy to let you do it this time 😁 
(assuming that is what the issue is)

2024-07-31 18:53 UTC, TheRealAmazonKendra approved these changes
YOLO Again. I should probably stop saying that in official PR reviews... ¯\_(ツ)_/¯

2024-07-31 19:23 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: bd8294c1d105b81d5d4a41314f2aeb98d4a9c5bc
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5be6f325-bc58-4131-9e98-e366e3e868e5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-07-31 20:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 08579ca08f124a53d5206a3827851b6f383b318d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3fb2a0db-5607-4ad0-8bc1-799be2cf4e7e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-07-31 20:03 UTC, merged