correct installLatestAwsSdkDefault flag docs
aws/aws-cdk pull request #28887
Opened 2024-01-26 19:14 UTC by joshlartz

Correcting docs about this flag as the implementation still defaults to true. 

https://github.com/aws/aws-cdk/blob/v2.123.0/packages/aws-cdk-lib/custom-resources/lib/aws-custom-resource/aws-custom-resource.ts#L471-L473

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-01-26 19:16 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-01-26 19:16 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-26 19:18 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-01-26 19:42 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e3e27bad9e9d9a613c257a68414ec13abe78fcaa
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1178a17c-1368-439a-a49b-a5e9e8bc0073%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-26 22:08 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1a9c429a651ea7ad9e0e3ebe394e9dee43802a73
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e47a0928-a0ed-42a1-8392-a532ce2ab6a0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-27 01:04 UTC, kylelaker requested changes
That markdown file will get overwritten the next time the package is built. If this documentation change is correct, I believe this needs to be changed by specifying `defaults: { v2: true }` in `features.ts`. I am not sure if that will have any other downstream effects.

The change would be somewhere around here:
https://github.com/aws/aws-cdk/blob/6a7a24afcc1ebebf71c267b890732a455e865cc8/packages/aws-cdk-lib/cx-api/lib/features.ts#L647-L649

This is the code that performs the generation of that markdown file:
https://github.com/aws/aws-cdk/blob/6a7a24afcc1ebebf71c267b890732a455e865cc8/packages/aws-cdk-lib/cx-api/build-tools/flag-report.ts#L95-L99

2024-01-29 15:42 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1e77d056ce0c078b6b6c0bebc028aef3d39068af
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b97a7e44-98db-422b-bcac-2394a681e2f8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-30 00:13 UTC, kylelaker reviewed
Thanks! I think there should be some other files that are modified as a consequence of this if you were to build the `aws-cdk-lib` package. `CONTRIBUTING.md` has details on how to do that, but you probably would want to do the following:

1. In the base of the repo run `yarn install` to install all the CDK dependencies
2. Move into the `aws-cdk-lib` directory with `cd packages/aws-cdk-lib`
3. Build that package and its dependencies with `../../scripts/buildup`

From there, you can run tests locally with `yarn test`. The CodeBuild check on the PR will also run the full test suite after you push.

2024-01-30 00:13 UTC, kylelaker commented on packages/aws-cdk-lib/cx-api/lib/features.ts
> +    defaults: { v2: true }
```suggestion
    defaults: { v2: true },
```

To fix the build error

2024-01-30 16:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0b033935473c81b4acfadd2456a23c686d6303c1
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b4e8764b-7011-4659-be72-afd01fba5699%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-01-30 16:51 UTC, joshlartz commented
@kylelaker You were right that there were unintended changes from this. It looks like there was an assumption built in that flags would always end up being true in v2. It is causing the "Flags with a different default in v2" section to be updated incorrectly. 

Example:
| Flag | Summary | Type | Since | v1 default | v2 default |
| ----- | ----- | ----- | ----- | ----- | ----- |
| [@aws-cdk/customresources:installLatestAwsSdkDefault](#aws-cdkcustomresourcesinstalllatestawssdkdefault) | Whether to install the latest SDK by default in AwsCustomResource | (default) |  | `false` | `true` |

Here is an example of a `cdk.json` file that restores v1 behavior for these flags:

```json
{
  "context": {
    "@aws-cdk/core:newStyleStackSynthesis": false,
    "@aws-cdk/core:stackRelativeExports": false,
    "@aws-cdk/aws-rds:lowercaseDbIdentifier": false,
    "@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId": false,
    "@aws-cdk/aws-lambda:recognizeVersionProps": false,
    "@aws-cdk/aws-cloudfront:defaultSecurityPolicyTLSv1.2_2021": false,
    "@aws-cdk/customresources:installLatestAwsSdkDefault": false
  }
}
```

2024-02-21 00:08 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the BUILD FAILING state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2024-02-28 18:46 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2024-02-28 18:46 UTC, closed without merging

2024-02-29 00:19 UTC, joshlartz commented
Not stale, just waiting on an answer still :( 
@kylelaker