fix(s3-notifications): bug fix to address the issues deleting the existing S3 event notifications and adding new event notifications on top of existing notifications
aws/aws-cdk pull request #29022
Opened 2024-02-07 20:11 UTC by sarangarav

### Issue # (if applicable)

Closes#28915

### Reason for this change

Fix to address the issues deleting the existing S3 event notifications and adding new event notifications on top of existing notifications.

### Description of changes

We fixed the hashing logic used to identify old vs external S3 event notifications

### Description of how you validated changes

Manually tested the changes

### Checklist
- [ ] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-02-07 20:13 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-02-07 20:13 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-02-07 20:15 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-02-07 20:15 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-02-07 20:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 2dc37f2b629bec0f6df5ad3a619a9532dea5128f
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3f7d9d9f-f245-40b1-b3dc-0d9fe504c679%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-02-07 20:51 UTC, sarangarav commented
Exemption Request

2024-02-07 20:53 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-02-16 15:06 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-02-29 00:08 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2024-02-29 22:35 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-02-29 22:41 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-02-29 22:54 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0d7983183ba59d063bf900a600153d9b27ddcbbf
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d0793e61-37c9-4740-8451-2d1328c21d8b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-02-29 23:01 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c1560b29649e6841d84cc4816b6ab22686bb208c
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=821e3c28-5730-4cbe-bd77-ec21061afcd8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-03-01 16:24 UTC, sarangarav commented
> The pull request linter fails with the following errors:
> 
> ```
> ❌ Fixes must contain a change to a test file.
> ❌ Fixes must contain a change to an integration test file and the resulting snapshot.
> ❌ Breaking changes in stable modules [s3-notifications] is disallowed.
> ```
> 
> PRs must pass status checks before we can provide a meaningful review.
> 
> If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.
> 
> ✅ A exemption request has been requested. Please wait for a maintainer's review.

The breaking changes should be permitted to address the issues with deleting the existing S3 event notifications and adding new event notifications on top of existing notifications

2024-03-01 16:26 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-01 18:59 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-01 19:13 UTC, paulhcsun requested changes
Hi @sarangarav, we don't allow any breaking changes in stable modules, however, you can still add this fix behind a feature flag: https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#feature-flags. 

I'm not sure exactly how it would work for changes to the `index.py` file but let me check with the team and get back to you. Also have you run the integ tests for `s3-notifications`? And if so could you also push the test snapshots if any were changed.

2024-03-01 19:13 UTC, paulhcsun commented on packages/@aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py
>          ids = [with_id(n) for n in old.get(t, [])]
this line can be removed

2024-03-01 19:15 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-01 19:15 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-01 19:15 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-01 19:15 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-01 22:53 UTC, paulhcsun commented
Hey @sarangarav,

So the `index.py` file won't have any knowledge on whether or not a feature flag is enabled so what you can do is add a new property [here](https://github.com/aws/aws-cdk/blob/7205143d563449ab211406da04d99bbbcdc7c8cc/packages/aws-cdk-lib/aws-s3/lib/notifications-resource/notifications-resource.ts#L129-L137), something like:
```
this.resource = new cdk.CfnResource(this, 'Resource', {
        type: 'Custom::S3BucketNotifications',
        properties: {
          ServiceToken: handler.functionArn,
          BucketName: this.bucket.bucketName,
          NotificationConfiguration: cdk.Lazy.any({ produce: () => this.renderNotificationConfiguration() }),
          Managed: managed,
		  IsFeatureFlagEnabled: true,
        },
      });
```
and then access that within the `handlers()` method in `index.py` through the [`props = event["ResourceProperties"]` variable](https://github.com/aws/aws-cdk/blob/7205143d563449ab211406da04d99bbbcdc7c8cc/packages/%40aws-cdk/custom-resource-handlers/lib/aws-s3/notifications-resource-handler/index.py#L15) which will allow you to use the new logic if that property is set to true.

2024-03-22 00:09 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the BUILD FAILING state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2024-03-30 00:08 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2024-03-30 00:09 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-04-04 22:53 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-04-04 22:53 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-04-04 22:53 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-04-04 22:53 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-04-04 22:54 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-04-04 23:13 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 43e6543de5b0eef485129f9a105e37a4d9000500
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=afa53cee-365a-4498-ad70-7e675ea1d157%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-08 20:18 UTC, paulhcsun commented
hey @sarangarav, are you still planning to work on this?

2024-04-11 01:25 UTC, paulhcsun commented
Going to close this for now. Feel free to open a new PR if you would like to continue to work on this fix with the suggested changes.

2024-04-11 01:26 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-04-11 17:19 UTC, closed without merging

2024-06-21 15:02 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Breaking changes in stable modules [s3-notifications] is disallowed.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.