feat(cloudwatch): add TableWidget
aws/aws-cdk pull request #29078
Opened 2024-02-12 12:07 UTC by humanzz

### Issue # (if applicable)

closes #28975.

### Reason for this change

add support for table widget https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/add_remove_table_dashboard.html

### Description of changes

add a new `TableWidget` and its supporting property classes/interfaces

### Description of how you validated changes

added both unit/integ tests

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-02-12 12:08 UTC, humanzz commented
In lack of an updated JSON schema - which I've asked the cloudwatch team to provide - in https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/CloudWatch-Dashboard-Body-Structure.html, I went ahead with this implementation based on
- documentation/examples given in https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/add_remove_table_dashboard.html
- manual experimentation via console

2024-02-12 12:34 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 444161b77a81da781f508e27c669a5fdebc61522
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ff7a345f-3e21-4a44-a208-c49bcb97d52c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-02-13 17:03 UTC, kaizencc requested changes
Hi @humanzz, this all looks pretty reasonable and you've got a nice looking README + unit tests. Just a few minor things and then I'm ready to ship

2024-02-13 18:53 UTC, humanzz commented on packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.table-widget.ts
I've only generated the snapshots, but haven't really looked in console.
let me do that as part of addressing the other comments

2024-02-13 19:18 UTC, humanzz commented on packages/aws-cdk-lib/aws-cloudwatch/lib/graph.ts
> +   * @see TableSummary
I removed it

2024-02-13 19:21 UTC, humanzz commented on packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.table-widget.ts
Here are a couple of screenshots for the dashboard/metrics deployed

<img width="726" alt="Screenshot 2024-02-13 at 19 19 10" src="https://github.com/aws/aws-cdk/assets/5001/5314f1d7-f686-4edc-b711-97c062b6139c">
<img width="1371" alt="Screenshot 2024-02-13 at 19 19 40" src="https://github.com/aws/aws-cdk/assets/5001/28afc2d3-2844-4709-be75-bbd356c4af92">
<img width="1372" alt="Screenshot 2024-02-13 at 19 20 15" src="https://github.com/aws/aws-cdk/assets/5001/31e3e680-a1e4-4823-a0fb-9c876071cfdf">

2024-02-13 19:45 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1cc428067a504ca6e4814b272d82ac9c1322f684
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2172c1c2-6cc7-46bc-9e95-a018c76aec43%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-02-13 19:50 UTC, kaizencc commented on packages/@aws-cdk-testing/framework-integ/test/aws-cloudwatch/test/integ.table-widget.ts
I assume that is what you expected!

2024-02-13 19:50 UTC, kaizencc approved these changes
Nice! Thanks @humanzz. The API looks good to me, happy to send this one off

2024-02-13 20:20 UTC, merged