fix(aws-cdk-lib) - Allow create explicitly empty trees on aws-cdk-lib core
aws/aws-cdk pull request #29217
Opened 2024-02-22 10:58 UTC by Rondineli

### Issue # (if applicable)

Closes #[29165](https://github.com/aws/aws-cdk/issues/29165).

### Reason for this change

Using `addOverride` calls `deepMerge`, and few edge cases like wafv2 rules needs Actions and other keys with objects and empty objects.

### Description of changes

Changing the code to be more realistic with the comment, where only null data is deleted

### Description of how you validated changes

No tests, just making sure the current change would be compatible with current tests, should not break anything

### Checklist
- [ x ] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-02-22 11:00 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-02-22 11:00 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-02-22 11:02 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-02-22 11:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 24e6d9ded08c0858b816bc79dec3c141302295ec
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1be4f3c9-1b85-4803-bb0a-bc281d66a00d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-02-22 12:10 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ The first word of the pull request title should not be capitalized. If the title starts with a CDK construct, it should be in backticks "``".

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-02-22 20:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b2f915af9131a229b9fd03b3dbd84978d05dabc1
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9c3c2c4d-d85a-4a74-a03e-6612807a04a2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-02-27 13:42 UTC, jeffersonfrazer commented
+1

2024-03-08 17:34 UTC, paulhcsun requested changes
Left some comments

2024-03-08 17:34 UTC, paulhcsun commented on packages/aws-cdk-lib/core/lib/cfn-resource.ts
> -
can you add back the linebreak here

2024-03-08 17:34 UTC, paulhcsun commented on packages/aws-cdk-lib/core/lib/cfn-resource.ts
> +// https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-webacl-ruleaction.html
```suggestion
/**
 * Availabe WAFv2 empty objects
 *
 * @see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wafv2-webacl-ruleaction.html
 */
```

2024-03-08 17:34 UTC, paulhcsun commented on packages/aws-cdk-lib/core/lib/cfn-resource.ts
> +// Availabe wafv2 empty objects
This description is vague and doesn't explain what these are used for, nor how "empty objects" relates to `DELETE_MERGE_EXCLUDE_KEYS`. Maybe provide a short snippet of context, you can reference the description for `MERGE_EXCLUDE_KEYS` on line 617

2024-03-08 17:34 UTC, paulhcsun commented on packages/aws-cdk-lib/core/test/resource.test.ts
> +    test('addOverride(p, {object: {object: {}}}) will respect empty trees', () => {
prefer different wording like `support` over `respect` here

2024-03-08 17:34 UTC, paulhcsun commented on packages/aws-cdk-lib/core/lib/cfn-resource.ts
> +          * some empty trees are needed in some edge cases
```suggestion
          * Some empty trees are needed in some edge cases
```

2024-03-08 17:34 UTC, paulhcsun commented on packages/aws-cdk-lib/core/lib/cfn-resource.ts
> +          * ie: wafv2 Rules (for Action, OverrideAction, etc...)
Please clarify which `some empty trees` and maybe combine the `ie` into the `some edge cases` like `... are needed when WAFv2 rule action is one of 'Action', 'Block', 'Captcha', 'Challenge' or 'Count'.`

2024-03-12 16:47 UTC, paulhcsun commented
@Rondineli I have some concerns about this change breaking existing customers so please add it behind a [feature flag](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md?rgh-link-date=2024-03-12T16%3A45%3A17Z#feature-flags).

2024-03-15 00:08 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the BUILD FAILING state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2024-03-15 16:17 UTC, Rondineli commented
> @Rondineli I have some concerns about this change breaking existing customers even behind a feature flag. Please have a look at the comments on the original issue.

Sorry, but I really dont get the backwards compatibility bit? As I am explicitly setting the keys to it ignore. And trust me, I tried the way it is right now and cloudformation broke because those missing keys on waf rules, so, my guess is if someone tried to use it, it did not work.

I would be happy to change the PR for another approach, but this is definitely something broken and wont cause regression, quite the opposite.

2024-03-22 00:09 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2024-03-22 00:09 UTC, closed without merging