fix(codebuild): aws/codebuild/amazonlinux2-aarch64-standard:3.0 is no…
aws/aws-cdk pull request #29580
Opened 2024-03-22 17:11 UTC by nikovirtala

### Issue # (if applicable)

Closes #<issue number here>.

### Reason for this change

AWS CodeBuild Docker image `AMAZON_LINUX_2_ARM_3` aka `AMAZON_LINUX_2_STANDARD_3_0` aka `aws/codebuild/amazonlinux2-aarch64-standard:3.0` is not deprecated but the currently actively maintained one according to https://github.com/aws/aws-codebuild-docker-images and https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html

### Description of changes

I removed the JSDoc Deprecated flag for the currently active image and added its image name as a comment so that one can find the image also using that reference.

### Description of how you validated changes

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-03-22 17:13 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-03-22 17:13 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-03-22 17:15 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-03-22 17:18 UTC, nikovirtala commented
Exemption Request: this change doesn't change any feature or functionality — thus, no test should and does not change

2024-03-22 17:39 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 12f21ab6ccd84f87f6edee03a3f07e2cd2cefbc7
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=922306a3-305d-4da6-9c73-6f9789c5bd37%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-03-22 17:42 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-22 21:24 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-22 21:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: aaeff9d41cdb01094bdb0b1ab54022a2b95f9c6b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a3bb5aec-63b9-4b53-8a51-af4c36181653%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-03-23 06:59 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-23 07:25 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b6cc639e5fe70a6792522fe965d697de4f5318ea
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=60b90574-0f3b-4106-8932-534e393547ae%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-03-23 16:45 UTC, lpizzinidev requested changes
Thanks 👍
Left a comment for updating v2 documentation as well.
I think you can mark the PR as a `chore` (CI won't require tests).
Also, can you please update the title to not be truncated?

2024-03-23 16:45 UTC, lpizzinidev commented on packages/aws-cdk-lib/aws-codebuild/lib/project.ts
>     * @deprecated Use LinuxArmBuildImage.AMAZON_LINUX_2_STANDARD_3_0 instead.
v2 seems not to be deprecated as well.
Can you please update the comment accordingly?

2024-03-23 16:47 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-23 16:47 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-23 16:48 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-25 06:36 UTC, nikovirtala commented
> Thanks 👍 Left a comment for updating v2 documentation as well. I think you can mark the PR as a `chore` (CI won't require tests). Also, can you please update the title to not be truncated?

I removed the `@deprecated` flag also for v2 image and update the pr title and description to cover that change too.

2024-03-25 07:00 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 185f86d06c54c1de5c976087a73c28f87108b565
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ff17ef8d-faee-46c2-bce2-04102155392e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-03-25 10:36 UTC, nmussy commented
Hey, guess I didn't open a PR for this (I was sure I did), but I already have a runner ready to update all of the CodeBuild images (`WindowsBuildImage`, `LinuxBuildImage`, `LinuxArmBuildImage`, `LinuxLambdaBuildImage`, and `LinuxArmLambdaBuildImage`). I'll try to take care of this soon.

Regardless, you can confirm that these images are still available by using the [`codebuild:ListCuratedEnvironmentImages`](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ListCuratedEnvironmentImages.html) API command:

```sh
$ aws codebuild list-curated-environment-images | jq '.platforms[] | select(.platform == "AMAZON_LINUX_2") | .languages[] | select(.language == "STANDARD") | .images[] | select(.name == "aws/codebuild/amazonlinux2-aarch64-standard:3.0")'

{
  "name": "aws/codebuild/amazonlinux2-aarch64-standard:3.0",
  "description": "AWS CodeBuild - Docker image based on Amazon Linux 2023 (aarch64) with multiple language support",
  "versions": [
    "aws/codebuild/amazonlinux2-aarch64-standard:3.0-23.04.25",
    "aws/codebuild/amazonlinux2-aarch64-standard:3.0-24.01.29",
    "aws/codebuild/amazonlinux2-aarch64-standard:3.0-24.03.06",
    "aws/codebuild/amazonlinux2-aarch64-standard:3.0-24.03.21"
  ]
}
```

```sh
$ aws codebuild list-curated-environment-images | jq '.platforms[] | select(.platform == "AMAZON_LINUX_2") | .languages[] | select(.language == "STANDARD") | .images[] | select(.name == "aws/codebuild/amazonlinux2-aarch64-standard:2.0")'
{
  "name": "aws/codebuild/amazonlinux2-aarch64-standard:2.0",
  "description": "AWS CodeBuild - Docker image based on Amazon Linux 2 (aarch64) with multiple language support",
  "versions": [
    "aws/codebuild/amazonlinux2-aarch64-standard:2.0-20.06.15",
    "aws/codebuild/amazonlinux2-aarch64-standard:2.0-20.08.13",
    "aws/codebuild/amazonlinux2-aarch64-standard:2.0-21.01.12",
    "aws/codebuild/amazonlinux2-aarch64-standard:2.0-21.03.02",
    "aws/codebuild/amazonlinux2-aarch64-standard:2.0-21.08.20",
    "aws/codebuild/amazonlinux2-aarch64-standard:2.0-21.10.15",
    "aws/codebuild/amazonlinux2-aarch64-standard:2.0-24.01.29",
    "aws/codebuild/amazonlinux2-aarch64-standard:2.0-24.03.06",
    "aws/codebuild/amazonlinux2-aarch64-standard:2.0-24.03.21"
  ]
}
```

2024-03-26 08:26 UTC, nmussy commented
I opened another PR to fix this issue, among other things: #29616
Sorry about that, I had everything ready but forgot to actually make the changes 😞

2024-04-17 01:22 UTC, TheRealAmazonKendra approved these changes

2024-04-17 01:23 UTC, TheRealAmazonKendra commented
@Merfigyio update

2024-04-17 01:25 UTC, TheRealAmazonKendra approved these changes

2024-04-17 01:54 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 545e3d349b70300bb22c302f1feabf5f70b59217
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1a1b4c68-1b6c-428e-8277-30bf358e361c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-17 02:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: eecb081942afaa9bd054898977931a28edbcc629
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7c17762a-48b7-48c8-904d-af7847a1dbf7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-17 02:22 UTC, merged