feat(ec2): add support for environment files and variables in systemd
aws/aws-cdk pull request #29629
Opened 2024-03-27 12:34 UTC by razin99

### Reason for this change

Allow users to define `Environment` and `EnvironmentFile` in a systemd service file.

### Description of changes

Added 2 new properties for `ec2.InitService.systemdConfigFile`:
1. `environmentVariables` which is a string key value pair
2. `environmentFiles` which is a list of file paths

### Description of how you validated changes

I have added a unit test.
Documentations referred to:
- https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#EnvironmentFile=
- https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#Environment= 

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-03-27 12:36 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-03-27 12:36 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-03-27 12:38 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-03-27 13:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e26fdfec8b8e226d71e4509f566eeaa28fa6e3c5
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2ae1904a-34d6-4ba5-859b-ad9354a4d700%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-03-27 22:32 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-03-27 22:50 UTC, razin99 commented
Exemption Request

No README updates needed since this added optional features that goes beyond basic systemd service creation

2024-03-27 22:52 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-27 22:59 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 123a69be8b0fe6f793ff97f68faac4a79808bb20
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=312a73d2-b23b-4f41-831a-b40373d593de%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-03-27 23:02 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-31 09:16 UTC, lpizzinidev requested changes
Thanks for contributing 👍
Left some comments for adjustments.
Also, you could add some documentation in [Configuring Instances using CloudFormation Init (cfn-init)](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-ec2/README.md#configuring-instances-using-cloudformation-init-cfn-init).

2024-03-31 09:16 UTC, lpizzinidev commented on packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
Why is this file included? 🤔

2024-03-31 09:16 UTC, lpizzinidev commented on packages/aws-cdk-lib/aws-ec2/lib/cfn-init-elements.ts
> +   * Include file to load environment variables from when process is running
```suggestion
   * Loads environment variables from files when the process is running.
```

2024-03-31 09:16 UTC, lpizzinidev commented on packages/@aws-cdk-testing/framework-integ/test/aws-ec2/test/integ.instance-init.ts
> +          environmentVariables: {
Can you please add the `environmentFiles` variable to the test?

2024-03-31 09:18 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-31 09:18 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-31 09:18 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-31 09:19 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-31 11:14 UTC, razin99 commented on packages/@aws-cdk/cx-api/FEATURE_FLAGS.md
Yeah im not too sure :/
It popped up when I was doing some integ tests. Will remove :)

2024-03-31 11:16 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-03-31 11:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: be5303c19ac4e362ee9ae8736b6e031ca1504478
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=120b5427-296d-4610-927a-a4b35a318030%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-03-31 12:35 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: a09e94097aac45e3f3c6a6d65384080cbc95756a
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ae86b7f1-6ef3-4f4a-8058-68ef1e140895%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-01 06:18 UTC, lpizzinidev approved these changes
Thanks 👍 Added a suggestion to change the wording for the documentation

2024-04-01 06:18 UTC, lpizzinidev commented on packages/aws-cdk-lib/aws-ec2/README.md
> +```ts
```suggestion
You can use the `environmentVariables` or `environmentFiles` parameters to specify environment variables
for your services:

```ts
```

2024-04-01 11:36 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8687ad1c9ccf058097e3b9699b717b466a016a98
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e64d866a-fd01-4a10-ab96-52e0bcbd9e77%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-02 10:08 UTC, razin99 commented
@lpizzinidev what do I do from here? Never got a PR this far in this repo. Do I just wait for it to be merged?

2024-04-17 21:33 UTC, TheRealAmazonKendra reviewed
Thank you for your work on this. I'm thinking that it's likely that this change is good to go with one clarifying question: can a user provide both environmentVariables and environmentFiles or is it an either/or situation?

If they can provide both, this looks ready.

2024-04-20 12:32 UTC, razin99 commented
> Thank you for your work on this. I'm thinking that it's likely that this change is good to go with one clarifying question: can a user provide both environmentVariables and environmentFiles or is it an either/or situation?
> 
> If they can provide both, this looks ready.

They can provide both, as this is a supported behaviour by systemd. From what I've read ([here](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#EnvironmentFile=:~:text=Settings%20from%20these%20files%20override%20settings%20made%20with%20Environment%3D.%20If%20the%20same%20variable%20is%20set%20twice%20from%20these%20files%2C%20the%20files%20will%20be%20read%20in%20the%20order%20they%20are%20specified%20and%20the%20later%20setting%20will%20override%20the%20earlier%20setting.)), anything `EnvironmentFile` can override `Environment`

Quote from documentation:
> Settings from these files override settings made with Environment=. If the same variable is set twice from these files, the files will be read in the order they are specified and the later setting will override the earlier setting.

2024-05-01 20:54 UTC, GavinZZ approved these changes
Thanks for answering the questions. Approving on behalf for Kendra since her question is answered and this PR looks good to me.

2024-05-01 21:36 UTC, GavinZZ approved these changes

2024-05-01 22:05 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 2792352acdd8c95d2789a1654c05a3499455d12f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9e89b8dd-fbed-46ba-80d4-ffc2479b84c3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-05-01 22:49 UTC, merged

2024-07-25 21:19 UTC, aws-cdk-automation commented
Comments on closed issues and PRs are hard for our team to see. If you need help, please open a new issue that references this one.