fix(triggers): store provider as class property
aws/aws-cdk pull request #29669
Opened 2024-04-01 02:29 UTC by automartin5000

### Issue # (if applicable)

Closes #29657

### Reason for this change

Unable to modify Triggers provider using conventional escape hatches

### Description of changes

Stored Trigger provider as class property to be user-accessible

### Description of how you validated changes

Was unable to test changes due to issues getting project installed locally

### Checklist
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-04-01 02:31 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-04-01 02:31 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-04-01 02:33 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-04-01 02:39 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5781a360dc6b26785646834e9691143af8e658b1
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3b5b695e-738b-4558-b2b8-8eee3f0942d3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-02 04:13 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-04-02 04:21 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 37c62509e08730f9e0234d3ffcb841f6a7762f33
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=60e88d4d-82e9-465d-af1c-da914b743ebf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-02 04:22 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-04-02 04:30 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 4ffae9b601841c2b5b31ffe6428cf25021578e66
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=049f8815-a3b7-4db3-9f02-b2a2a678d014%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-02 12:37 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-04-02 12:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 27f155909073ce102b3e3972e06b28dd6fa09ecc
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=cf2f7369-b75f-4b44-88c7-7e59796440e2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-03 02:07 UTC, automartin5000 commented
Clarification Request
I can't tell why builds are failing. There seem to be a lot of unrelated failures? The only thing I can tell is a linting error in the Trigger file, but that looks to have already been there?

Also does this need an integration test beyond the tests I already added? If so where would it go/what would it do?

2024-04-03 02:09 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-04-08 22:54 UTC, TheRealAmazonKendra requested changes
Thank you for your contribution! I have just one comment inline but I think we also need to see an integ test added for this to show that it works for your intended use case.

2024-04-08 22:54 UTC, TheRealAmazonKendra commented on packages/aws-cdk-lib/triggers/lib/trigger.ts
> +  crProvider: CustomResourceProvider;
Can we either call this `provider` or use the whole `customResourceProvider`?

2024-04-08 22:54 UTC, TheRealAmazonKendra commented
Also, please note that the title of a fix should describe the bug, not the solution. Could you please adjust that?

2024-04-08 22:56 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-04-09 19:30 UTC, TheRealAmazonKendra commented
@Mergifyio update

2024-04-09 19:33 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-04-09 19:35 UTC, TheRealAmazonKendra commented
Also, I hadn't noticed that your build failed and that you asked a question about it. The failure lines here are pretty hard to find but they're:
```
aws-cdk-lib:   116:36  error  Trailing spaces not allowed  no-trailing-spaces
aws-cdk-lib: âœ– 1 problem (1 error, 0 warnings)
aws-cdk-lib:   1 error and 0 warnings potentially fixable with the `--fix` option.
```
The docstring on line 116 of `trigger.ts` is running afoul of our linter. The other lines that look like failures are just jsii warnings. They are noisy but they don't cause failures.

2024-04-09 19:39 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-04-09 19:40 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 541331531c45d50583afa994fc8a5d9a6c6d6cb5
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6a897683-61a6-4adf-9e6c-c485a97c81d3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-30 00:08 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2024-05-07 00:08 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2024-05-07 00:08 UTC, closed without merging

2024-05-07 00:10 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.