fix(appsync): Correct appsync.HttpDataSourceProps type
aws/aws-cdk pull request #29689
Opened 2024-04-02 10:51 UTC by ScottRobinson03

### Reason for this change

In #11185, the `HttpDataSource` class was updated to extend `BackedDataSource` instead of `BaseDataSource`, however the `HttpDataSourceProps` type wasn't updated to reflect this change.

### Description of changes

Makes the `HttpDataSourceProps` type extend `BackedDataSourceProps`, instead of `BaseDataSourceProps`.

### Description of how you validated changes

N/A

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-04-02 10:52 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-04-02 10:52 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ The first word of the pull request title should not be capitalized. If the title starts with a CDK construct, it should be in backticks "``".

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-04-02 10:54 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ The first word of the pull request title should not be capitalized. If the title starts with a CDK construct, it should be in backticks "``".

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-04-02 11:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7d3051acbb5a7c6c5db805a3c5c29c1d17320040
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=91f77c34-25f0-4f0f-9dbd-3d45437638b9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-02 12:43 UTC, ScottRobinson03 commented
Exemption Request

This PR is just fixing a type, so updating tests isn't appropriate.

2024-04-02 12:44 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-04-02 12:45 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-04-02 12:46 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-04-08 21:32 UTC, TheRealAmazonKendra requested changes
This PR doesn't give me any reason to believe that the choice to only update on set of props wasn't intentional. 

Given that it was a change made in 2020 and there are no linked issues on this PR, we need more context on why this change is necessary.

2024-04-08 21:34 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-04-08 21:37 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-04-08 22:57 UTC, TheRealAmazonKendra commented
Which props are present/missing that shouldn't be? Is there an open issue for this? Updating this will likely be a breaking change.

2024-04-10 20:51 UTC, ScottRobinson03 commented
> Which props are present/missing that shouldn't be? Is there an open issue for this? Updating this will likely be a breaking change.

You can look at the types yourself to see this. The only difference is that `BackedDataSource` include the `serviceRole` prop, which `BaseDataSource` doesn't. See [the source code](https://github.com/ScottRobinson03/aws-cdk/blob/7d3051acbb5a7c6c5db805a3c5c29c1d17320040/packages/aws-cdk-lib/aws-appsync/lib/data-source.ts#L38-L48). It wouldn't be a breaking change since there's no keys removed, just one key added.

2024-04-10 21:59 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-04-10 22:10 UTC, TheRealAmazonKendra commented
> > Which props are present/missing that shouldn't be? Is there an open issue for this? Updating this will likely be a breaking change.
> 
> You can look at the types yourself to see this. The only difference is that `BackedDataSource` includes the `serviceRole` prop, which `BaseDataSource` doesn't. See [the source code](https://github.com/ScottRobinson03/aws-cdk/blob/7d3051acbb5a7c6c5db805a3c5c29c1d17320040/packages/aws-cdk-lib/aws-appsync/lib/data-source.ts#L38-L48). It's not a breaking change since there's no keys removed, just one key added. To be clear, in an ideal world this PR wouldn't be necessary, and this would've been noticed in #11185 some 3½ ish years ago. This PR is SOLELY to fix a mistake from that PR that wasn't noticed.
> 
> From what I found, there's not an open issue, hence I didn't link one to this PR. Such a tiny change that's obviously correct also shouldn't need an issue, hence I didn't create one -- there's nothing to discuss here, the type is just blatantly wrong and this PR fixes it.

Please review the [Pull Request](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#step-4-pull-request) section of our [Contributing Guide](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md).

Your pull request should contain all the information we need to assess the change. From our contributing guide:
```
- Pull request body should describe motivation. Think about your code reviewers and what information they need in order to understand what you did. If it's a big commit (hopefully not), try to provide some good entry points so it will be easier to follow.
  - For bugs, describe bug, root cause, solution, potential alternatives considered but discarded.
  - For features, describe use case, most salient design aspects (especially if new), potential alternatives.
```

Adding properties can, in fact, be a breaking change. If we are adding a mandatory prop that is breaking. From the information provided here, I can't tell which props specifically are being removed/added and if the props you are removing/adding are required.

Your explanation of this change should include that information.

Also from our contributing guide:
```
- If not obvious (i.e. from unit tests), describe how you verified that your change works.
```

In order to accept this change, we will need to have tests. This change would change the contract for this construct so it would require unit tests and integ tests. From the contributing guide regarding integ tests:
```
#### When are integration tests required?

The following list contains common scenarios where we know that integration tests are required. This is not an exhaustive list and we will, by default, require integration tests for all new features and all fixes unless there is a good reason why one is not needed.

1. Adding a new feature
2. Adding a fix to an existing feature
3. Involves configuring resource types across services (i.e. integrations)
4. Adding a new supported version (e.g. a new [AuroraMysqlEngineVersion](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.AuroraMysqlEngineVersion.html))
5. Adding any functionality via a [Custom Resource](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.custom_resources-readme.html)

```
Lastly, as this is a fix, please note this section of the contributing guide regarding PR titles:
```
- Titles for feat and fix PRs end up in the change log. Think about what makes most sense for users reading the changelog while writing them.
  - feat: describe the feature (not the action of creating the commit or PR, for example, avoid words like "added" or "changed")
  - fix: describe the bug (not the solution)
```

2024-04-11 09:16 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-04-11 09:22 UTC, ScottRobinson03 commented
> Your pull request should contain all the information we need to assess the change. From our contributing guide:
> ```
> - Pull request body should describe motivation. Think about your code reviewers and what information they need in order to understand what you did. If it's a big commit (hopefully not), try to provide some good entry points so it will be easier to follow.
>   - For bugs, describe bug, root cause, solution, potential alternatives considered but discarded.
> ```
I included these. The bug, cause, and solution are all in the PR description. Alternatives isn't applicable since there's only one possible sensible fix (the one implemented).

>  I can't tell which props specifically are being removed/added and if the props you are removing/adding are required.

As I said in my previous message the ONLY difference is the ADDITION of the `serviceRole` prop, which as shown in the linked source code is optional. Adding an optional prop is not a breaking change.

> In order to accept this change, we will need to have tests. This change would change the contract for this construct so it would require unit tests and integ tests. From the contributing guide regarding integ tests:

This is changing a type. Not runtime code. What has this got to do with unit and integration tests?

> Lastly, as this is a fix, please note this section of the contributing guide regarding PR titles:
> ```
> - Titles for feat and fix PRs end up in the change log. Think about what makes most sense for users reading the changelog while writing them.
>   - fix: describe the bug (not the solution)
> ```
Have updated the title to be clearer.

2024-04-24 18:33 UTC, ScottRobinson03 commented
@TheRealAmazonKendra I'd like to see this PR get merged, so would you please expand on what exactly you're eluding to by your comment around unit and integration tests.

Even after looking into the pre-existing unit and integration tests, I still don't understand how updating a type requires updating tests that ultimately check runtime behaviour.

No runtime logic is changed in this PR, so there's no new functionality for me to update the tests to check against. I suppose you could argue that editor autocomplete is an added functionality in this PR but I don't see how you can unit/integration test this.

2024-04-30 00:08 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2024-05-01 08:37 UTC, ScottRobinson03 commented
@TheRealAmazonKendra bump

2024-05-07 00:09 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2024-05-07 00:10 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-11-07 09:01 UTC, ScottRobinson03 commented
The details of this PR are now properly documented within #31979, so this can be re-opened.

I still need an "Exemption Request" -- there's no test changes, since this PR is just fixing a broken type (as detailed within #31979).

2024-11-07 09:05 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-11-07 09:05 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-11-07 09:06 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-11-07 09:06 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-11-07 09:09 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-11-07 18:44 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-11-07 18:45 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-11-08 00:10 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2024-11-08 00:10 UTC, closed without merging

2024-11-08 00:12 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.