feat(ecs): support adding labels after container construction
aws/aws-cdk pull request #29734
Opened 2024-04-05 00:27 UTC by msambol

Closes #29728. 

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-04-05 00:30 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ef82ce6db56830d39749d9cdc7ea21889f1757cf
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2a46e862-4874-4162-b085-8774ccd57dc5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-05 00:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ee027ea2fc6fefc58354be8ae7eca32b0318a834
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b49d0ec0-e14c-43ba-bb39-8c3392f4a6fe%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-05 13:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 2a3f6fe5386151e114e97bb3505f327fdb95f1c9
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e4b6d761-40c5-411a-9c74-cc6f76a39f7b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-05 16:04 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d0d31d834aaed1f06e9268d894aa2b61e31fd49a
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c545af19-b376-4925-b63b-57ec08ace1ac%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-05 17:25 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0290eba5aec2769f38bb359b32aed75f57a0bc04
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ccfc20cf-043f-4ef3-84b5-da6ad0e62954%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-06 15:30 UTC, lpizzinidev requested changes

2024-04-06 15:30 UTC, lpizzinidev commented on packages/aws-cdk-lib/aws-ecs/lib/container-definition.ts
> +    }
```suggestion
    this.dockerLabels = { ...props.dockerLabels };
```
Am I missing something? 🤔

2024-04-06 15:30 UTC, lpizzinidev commented on packages/aws-cdk-lib/aws-ecs/README.md
> +You can add labels to the container with the `dockerLabels` prop or `addDockerLabel`:
```suggestion
You can add labels to the container with the `dockerLabels` property or  with the `addDockerLabel` method:
```

2024-04-06 15:30 UTC, lpizzinidev commented on packages/aws-cdk-lib/aws-ecs/test/container-definition.test.ts
> +  test('can add docker label to the container definition', () => {
Can you please add a test for `dockerLabels: {}`? (should `Match.absent()` in cfn)

2024-04-06 17:05 UTC, msambol commented
@lpizzinidev Updated. Thank you as always!

2024-04-06 17:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0ea9435d4d3925d1d74ee9eb027a2248b74005f9
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=cf9adc13-6966-4b57-ab34-1bc00c6eee1b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-06 17:44 UTC, lpizzinidev approved these changes
Thanks 👍 Please adjust the test case

2024-04-06 17:44 UTC, lpizzinidev commented on packages/aws-cdk-lib/aws-ecs/test/container-definition.test.ts
> +      memoryLimitMiB: 1024,
```suggestion
  test('docker labels should be absent if empty object is provided', () => {
    // GIVEN
    const stack = new cdk.Stack();
    const taskDefinition = new ecs.Ec2TaskDefinition(stack, 'TaskDef');

    // WHEN
    taskDefinition.addContainer('cont', {
      image: ecs.ContainerImage.fromRegistry('test'),
      memoryLimitMiB: 1024,
      dockerLabels: {},
```
I was thinking about this case 🙂

2024-04-06 17:48 UTC, msambol commented on packages/aws-cdk-lib/aws-ecs/test/container-definition.test.ts
> +      memoryLimitMiB: 1024,
Fixed 👍🏼

2024-04-06 18:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 825260aab5872d24695840429226019987a01ed9
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f1fda9bc-24ee-4240-91a5-43e89e4ddccf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-12 01:57 UTC, msambol commented
@scanlonp This one is ready though. 😄

2024-04-16 17:13 UTC, blimmer approved these changes
Awesome, thanks!!

2024-04-18 17:27 UTC, godwingrs22 submitted a review, later dismissed
Awesome!! Thank you @msambol for your contribution and @blimmer @lpizzinidev for the reviews.

2024-04-18 17:45 UTC, godwingrs22 commented
@Mergifyio update

2024-04-18 17:53 UTC, godwingrs22 commented
@Mergifyio update

2024-04-18 18:04 UTC, godwingrs22 commented
@Mergifyio update

2024-04-18 18:09 UTC, godwingrs22 approved these changes

2024-04-18 18:11 UTC, godwingrs22 commented
@Mergifyio update

2024-04-18 18:28 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b9c0eec1484a92b058a688ecf7a18e231af906f1
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9ba40f10-c765-4828-a51b-5ecd77ff9349%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-04-18 18:29 UTC, merged

2024-07-25 21:17 UTC, aws-cdk-automation commented
Comments on closed issues and PRs are hard for our team to see. If you need help, please open a new issue that references this one.