feat(cognito): add defaultRediretUri to UserPoolClient
aws/aws-cdk pull request #30481
Opened 2024-06-07 13:19 UTC by mazyu36

### Issue # (if applicable)

N/A

### Reason for this change
The `defaulrRedirectUri` property missing in the current `UserPoolClient` class,

The DefaultRedirectURI setting is essential when using Amazon Cognito Hosted UI because it specifies the primary destination where users will be redirected after successful authentication, ensuring a seamless and secure OAuth 2.0 or OpenID Connect flow.

### Description of changes
Add missing property.

### Description of how you validated changes
Add unit tests and integ tests.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-06-07 13:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b8c14b09c3aed3aef4e405def0bdacfa7dda3e8f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7414b907-018d-48c0-96a7-d0fc849cddbd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-06-08 16:10 UTC, lpizzinidev requested changes
Thanks 👍 Some minor TODOs

2024-06-08 16:10 UTC, lpizzinidev commented on packages/aws-cdk-lib/aws-cognito/README.md
> +Its value must be in the `callbackUrls`.
```suggestion
To set a default redirect URI, use the `defaultRedirectUri` property.
Its value must be present in the `callbackUrls` list.
```

2024-06-08 16:10 UTC, lpizzinidev commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool-client.ts
> +    }
```suggestion
    if (props.oAuth?.defaultRedirectUri && !Token.isUnresolved(props.oAuth.defaultRedirectUri)) {
      if (callbackUrls && !callbackUrls.includes(props.oAuth.defaultRedirectUri)) {
        throw new Error('defaultRedirectUri must be included in callbackUrls.');
      }
    } 

    const defaultRedirectUriPattern = /^(?=.{1,1024}$)[\p{L}\p{M}\p{S}\p{N}\p{P}]+$/u
    if (!defaultRedirectUriPattern.test(props.oAuth.defaultRedirectUri)) {
      throw new Error(`defaultRedirectUri must match the \`${defaultRedirectUriPattern}\` pattern, got ${props.oAuth.defaultRedirectUri}`);
    }
```
Suggestion for cleanup

2024-06-08 17:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5327c07724f775223e435842a5709ddcd8c6457e
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=144dc456-73d7-4a2e-84fe-a58b6f0d28de%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-06-08 17:24 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5000fc111524fbb14694ff39deee8b4e5fdcce5a
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1579f2b3-1992-4946-bf3f-5a1579911a88%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-06-08 17:45 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5e34546fc543d1ceac19ebbf771b2f2a8a7e1398
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=875f8092-7dae-4807-9244-ace8508d016a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-06-08 17:53 UTC, mazyu36 commented
@lpizzinidev 
Thank you. I have incorporated your suggestions and made modifications.
The error message has been modified to display only the regular expression pattern.

2024-06-08 18:21 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6e7ab475f05da45eb1407e6f0b63b033ffd3a7ba
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1778e87d-1fb3-46a8-9bd1-916e62f07483%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-06-09 12:46 UTC, lpizzinidev approved these changes
Thanks 👍

2024-06-20 00:10 UTC, paulhcsun reviewed
Hi @mazyu36, thanks for the contribution! The code changes look good to me for the most part, I've just left a couple of clarifying questions.

2024-06-20 00:10 UTC, paulhcsun reviewed
Hi @mazyu36, thanks for the contribution! The code changes look good to me for the most part, I've just left a couple of clarifying questions.

2024-06-20 00:41 UTC, mazyu36 commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool-client.ts
> +   * * Be registered with the authorization server.
Thanks.
This is quoted from CFn document.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-defaultredirecturi

2024-06-20 00:47 UTC, mazyu36 commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool-client.ts
> +      const defaultRedirectUriPattern = /^(?=.{1,1024}$)[\p{L}\p{M}\p{S}\p{N}\p{P}]+$/u;
Obtained from CFn document.

> Pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}]+

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-defaultredirecturi

In my understanding, Most strings will match the pattern, but strings containing only whitespace characters or only special characters/symbols will not match.

2024-06-20 00:48 UTC, mazyu36 commented
@paulhcsun 
Thank you for the review!
I've replied to all your comments.

2024-06-20 22:45 UTC, paulhcsun commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool-client.ts
> +      const defaultRedirectUriPattern = /^(?=.{1,1024}$)[\p{L}\p{M}\p{S}\p{N}\p{P}]+$/u;
Thanks for clarifying! Should we also add some validation on the length here?

2024-06-20 22:46 UTC, paulhcsun approved these changes
Looks good, nice work @mazyu36!

And thanks for the review @lpizzinidev!

2024-06-20 22:46 UTC, paulhcsun commented
@mergifyio update

2024-06-20 22:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5ca0a7e0ef22acbf45b9f1de31114cb4982b9359
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8db297fd-339c-41d0-bbb3-33af3ef6e0d1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-06-21 00:04 UTC, mazyu36 commented
@Mergifyio update

2024-06-21 00:34 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 29398d059b4b2acbf6260291065e6c9e1700bf89
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f0170db3-63b0-4c1d-9840-1914e608cf8e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-06-21 00:35 UTC, merged

2024-07-25 20:48 UTC, aws-cdk-automation commented
Comments on closed issues and PRs are hard for our team to see. If you need help, please open a new issue that references this one.