fix(eks): add correct helm asset snapshot
aws/aws-cdk pull request #30835
Opened 2024-07-12 05:22 UTC by shikha372

### Issue # (if applicable)

Closes #

### Reason for this change

PR#https://github.com/aws/aws-cdk/pull/29454  introduced incorrect snapshot changes for the helm asset.

### Description of changes

Modified helm asset integration test file to add below flag as part of existing chart installation('rds-chart-release')

`atomic: true`

### Description of how you validated changes

Successful deployment for integration test `integ.eks-helm-asset.ts` 

### Checklist
- [ ] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-07-12 05:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ae9f68271e671bb87c6cca1086e24128ffcafeb1
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=623f34bb-cb82-429d-ab1d-b993db25fd39%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-07-12 22:39 UTC, TheRealAmazonKendra requested changes

2024-07-12 22:39 UTC, TheRealAmazonKendra commented on packages/@aws-cdk-testing/framework-integ/test/aws-eks/test/integ.eks-helm-asset.js.snapshot/aws-cdk-eks-helm-test.assets.json
> +    "0ab01c1684677dce72948d48cdd47d31aef3137c741b066737be81fe5944e6fe": {
This asset hash update means that there should also be changes to the asset files. At the very least, they should be renamed.

2024-07-23 20:25 UTC, closed without merging

2024-07-23 20:25 UTC, shikha372 commented
closing this one as snapshots are updated in this [PR](https://github.com/aws/aws-cdk/pull/30829)