fix(cli): remove deprecated validation around ARM build image types
aws/aws-cdk pull request #30879
Opened 2024-07-17 19:33 UTC by PeterEckIII

### Issue # (if applicable)

Closes #30869 .

### Reason for this change

Now that ARM images support all compute types (not just `ComputeType.SMALL` and `ComputeType.LARGE`) the validate function is outdated.

### Description of changes

Removed the `validate` method from `aws-cdk/packages/aws-cdk-lib/aws-codebuild/lib/linux-arm-build-image.ts` and the accompanying comment

### Description of how you validated changes

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-07-17 19:35 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-07-17 19:35 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-07-17 19:37 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to a test file.
	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-07-17 19:41 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 223785f92f7b094ffab8b4e5f9b897defcb43644
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=63c8ef1a-74dd-4703-b3cd-75feca4e0a3f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-07-17 19:59 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-07-17 20:04 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b820a2ca6a532569757927821182bcd18b4d48da
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=71ac9b9f-454c-480c-87ce-8d54253dc95c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-07-17 20:12 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-07-18 00:51 UTC, scanlonp requested changes
This looks like a good start, but still needs a couple things:

1. Do we call the validate function anywhere? We should clean up that invocation.
2. There are a lot of changes to these test files that are spacing or changing ' to ". Let's not change the formatting, and only remove the impacted tests.
3. This would be a great change to add in an integ test for some of the other instance sizes. They are in `packages/@aws-cdk-testing/framework-integ`. If there are codebuilds with ARM images, lets add one in the same test file where the compute type was previously disallowed. That way we have verification that these sizes are indeed supported!

2024-07-18 00:53 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-07-18 16:40 UTC, PeterEckIII commented
@scanlonp , thanks for the feedback here. Working on this today and had a few questions:

1. These are the files that also mention that function.
- https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-codebuild/lib/linux-gpu-build-image.ts#L144-L153 does this need to be removed as well?
- https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-codebuild/lib/project.ts#L1727 this would presumably need to be removed as well so `LinuxArmBuildImage` can properly implement `IBuildImage`

Other that those two files I didn't see other mentions of this specific implementation or calling of `validate` (that is, one that takes a `buildEnvironment` as its first and only parameter).

2. That must be something my editor is doing. I'll take a look and amend the commit
3. Sounds good, I'll get to work on that as well
Thanks!

2024-07-18 17:10 UTC, scanlonp commented
@PeterEckIII, I may have been wrong about removing the validate function. It does need to be present and implemented to correctly implement `IBuildImage`. It should not be removed since it's valuable on every image type. Looking at the other validate functions, I am sure there are configurations that are not allowed for ARM images that do not relate to the size of the compute type!

Also, would you mind amending the title of the PR? Thankfully we are fixing codebuild, not the cli :)

2024-07-18 17:30 UTC, PeterEckIII commented
@scanlonp, oh no! 😅  Ok, in that case I may withdraw the PR altogether and just start fresh if that's ok.

2024-08-09 00:11 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2024-08-17 00:10 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2024-08-17 00:10 UTC, closed without merging

2024-08-17 00:12 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.