feat(cognito): add `tags` property for user pool
aws/aws-cdk pull request #31108
Opened 2024-08-14 15:33 UTC by kdnakt

### Issue # (if applicable)

### Reason for this change

The userPoolTags property existed in the L1 construct but was not present in the L2 construct

### Description of changes

Add the tags property for UserPool

### Description of how you validated changes

Added a unit test and an integration test.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-08-14 15:35 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-08-14 15:35 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-14 15:37 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-15 02:12 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0d94f6f5b40e878a1b2b0b93647a3dce320dc458
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4306a6d6-f468-4825-9934-dd03a7cce43d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-23 08:59 UTC, badmintoncryer requested changes
Thank you for your contribution! I've added 2 minor comments.

2024-09-23 08:59 UTC, badmintoncryer commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
> +   */
```suggestion
  /**
   * The tags applied to the user pool.
   *
   * @default - no tags
   */
```

2024-09-23 08:59 UTC, badmintoncryer commented on packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-tags.ts
> +app.synth();
```suggestion
```

2024-10-05 12:36 UTC, kdnakt commented
@badmintoncryer Thank you for the suggestion, I've just committed them.

2024-10-05 12:39 UTC, badmintoncryer approved these changes
Thanks!

2024-10-05 13:05 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 23f440067ffbebcef04a9b86f27e513f1cc49725
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bc94ffff-08bc-4f8d-b560-f4d55008be76%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-10-05 13:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 88fa9012df80f2bc606a44950f3ef9c82a9d5e40
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0d742cb3-9cb3-4ca8-bb5c-cc92e3d0c296%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-10-05 13:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5ae2e4ff8ed351bdadc64471b3f9601db8fb6a6c
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5232b9a4-bee0-48b6-9a59-dec0d6cbd231%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-10-07 19:20 UTC, GavinZZ reviewed
In L2 construct, we don't directly provide `tags` property even though it's supported in the relevant L1 construct.

The typical way of adding tag is through `Tags.of(this).add`. Does this method work for you?

2024-10-12 04:23 UTC, kdnakt commented
Thank you, the `Tags.of(this).add` solution worked for me.
Would you recommend that I close this PR now?

2024-10-12 04:27 UTC, GavinZZ commented
As a side note, if you use `this`, it will default to result in tags being added at stack level this propagating to all resources created in the stack.

If this is not the ideal solution you could also do `Tags.of(resource)`.

Let’s close this PR as I believe this change is not needed anymore.

2024-10-12 10:34 UTC, closed without merging