feat(core): configure SNS topics to receive stack events on the Stack construct
aws/aws-cdk pull request #31107
Opened 2024-08-14 15:29 UTC by comcalvi

### Issue # (if applicable)

#8581.

### Reason for this change

It is easier and clearer to specify the SNS Topic ARNs on the stack construct itself instead of passing it as a command line argument.

### Description of changes

Added a new optional stack prop, `notificationArns`, that is written to the CloudAssembly and concatenated with the CLI option `--notification-arns`. 

When I added CLI integ tests, I discovered that the existing framework is unable to use your local code. It always retrieves the latest release, which is not what you want when running it locally. This fixes that. 

Don't forget to select stacks by hierarchical ID (currently display name, in our tests) when writing certain test code. Otherwise, the tests may not select the stack you expected. 

### Description of how you validated changes

Unit tests + CLI integ test.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-08-14 15:31 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-08-14 15:31 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-14 15:32 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-14 15:33 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-14 15:33 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-14 15:34 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6b447a16c7a6ea3a204a26b48eb4c0ff6f3d6fbf
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=89a7f65c-5af5-45a0-b748-670c80af9a0b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-08-14 16:37 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-08-14 16:37 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-09-05 14:50 UTC, rix0rrr reviewed
I don't necessarily have a problem with this, but I'm a bit dubious on the practical use cases.

2024-09-05 14:50 UTC, rix0rrr commented on packages/aws-cdk-lib/core/lib/stack.ts
> +    this._notificationArns = props.notificationArns ?? [];
We should probably validate that these strings don't contain any tokens.

2024-09-05 14:50 UTC, rix0rrr requested changes
See previous review

2024-09-10 21:56 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-09-10 21:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: a4288099fbc9c5c4f3ec00bb8ffad9e8300ace89
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=127a5eb2-d992-4c01-87a0-ac1cee9e3aea%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-10 22:27 UTC, comcalvi commented
@rix0rrr could you review: https://github.com/cdklabs/cloud-assembly-schema/pull/29? That needs to merge before this PR can merge.

2024-09-10 22:30 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-09-10 22:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 817c959f3b2fd9e170dcf8b5182ba6475c6f4906
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=eba8ac73-9d48-4f4a-802c-4d87799c7605%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-18 20:49 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.
	❌ The title of this pull request does not follow the Conventional Commits format, see https://www.conventionalcommits.org/.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-09-18 21:01 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f5aafadb0209d33af5ac8428350b0b9f83899d42
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e8281b4c-6699-4adb-8863-00c1a2c60550%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-18 21:01 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-09-18 21:38 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-09-18 21:38 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-09-18 22:02 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.
	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-09-18 22:18 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-09-18 22:18 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-09-18 22:18 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-09-18 22:22 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-09-18 22:35 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8dd5ce91c2891d784f5bff022bf1a8975673b537
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8437bf8b-af4f-498b-b230-fdf8d51d573b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-18 22:35 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-09-18 22:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b376437f31904c47ebef868e4dd8eafd64d3bad2
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6dbeb532-4ad0-4e69-b57e-30ca1dd21cd3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-19 19:50 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31107/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-09-19 20:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b8ad5f3bd867ea300b1f06ad5625c5a9eaae24f4
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=55f1f648-fc15-4f74-93af-e2465b9449f4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-19 21:12 UTC, aws-cdk-automation commented
:arrow_right: **PR build request submitted to `test-main-pipeline`** :arrow_left:

A maintainer must now check the pipeline and add the `pr-linter/cli-integ-tested` label once the pipeline succeeds.
<!-- thollander/actions-comment-pull-request "request-cli-integ-test" -->

2024-09-23 08:35 UTC, rix0rrr approved these changes

2024-09-23 09:06 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 497720300457dd00b987645039c051fa79028025
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ef8278dd-537f-49e6-b546-040ae1a5a610%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-23 09:07 UTC, merged