feat(efs): allow AccessPoint to set client token
aws/aws-cdk pull request #31184
Opened 2024-08-22 15:43 UTC by perrylson

### Reason for this change

The [CfnAccessPoint](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_efs.CfnAccessPoint.html) construct supports client token specification. However, the current L2 implementation of [AccessPoint](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_efs.AccessPoint.html) does not support this property. 

It should be noted that the `disable-update-workflow` option was needed when running the updated integration test.

### Description of changes

Updated the existing props of AccessPoint. 
### Description of how you validated changes

Validated with unit and integration testing. 

### Checklist
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-08-22 16:14 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: bdd4b635253379e8c8f165f9cadd13470437c220
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=11755cf8-ef46-4823-b131-1fcd759399d7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-10-02 12:00 UTC, badmintoncryer requested changes
Thank you for your contribution! I've added some comments.

2024-10-03 04:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 19b3884b86f2b31bef18ba33f0adf4e821ffd71e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1c43026f-eadc-4793-8e66-70365c9c206b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-10-03 11:14 UTC, badmintoncryer approved these changes
Thanks! I am proposing just one refactor, but I approve it.

2024-10-03 11:14 UTC, badmintoncryer commented on packages/aws-cdk-lib/aws-efs/test/access-point.test.ts
> +    clientToken: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
```suggestion
    clientToken: 'a'.repeat(65),
```

2024-10-03 14:16 UTC, perrylson commented on packages/aws-cdk-lib/aws-efs/test/access-point.test.ts
> +    clientToken: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
Updated 👍

2024-10-03 14:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 98f2519432b7d1e9476debd6877d7b6b4371e16f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=259b3a5c-39f9-42e4-9615-e33b4296a2e0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-10-17 19:39 UTC, perrylson commented on packages/aws-cdk-lib/aws-efs/lib/access-point.ts
> +    if ((clientToken?.length === 0 || (clientToken && clientToken.length > 64)) && !Token.isUnresolved(clientToken)) {
An empty string is considered falsy. In the above condition, `clientToken` will evaluate to false for empty strings. Hence, no errors will be thrown.  Only a non-empty string will pass the `clientToken` check. 

That's why the current validation checks for a length of 0 to detect empty string values.

2024-10-17 21:42 UTC, GavinZZ commented on packages/aws-cdk-lib/aws-efs/lib/access-point.ts
> +    if ((clientToken?.length === 0 || (clientToken && clientToken.length > 64)) && !Token.isUnresolved(clientToken)) {
Good catch! I missed the empty string case. Thanks for pointing it out.

2024-10-17 21:42 UTC, GavinZZ submitted a review, later dismissed

2024-10-18 04:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: cd55ff45aa834ec42e42ba1693143a0fe8633c05
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=957550f9-d79e-4dad-a737-70884b2d1aa6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-10-18 19:06 UTC, GavinZZ approved these changes

2024-10-18 19:38 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6b48d2d110215b7417459a4e1dc98a47f9f9f44b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=cb9a6221-09be-4d2d-bfe9-abba6abd528f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-10-18 19:39 UTC, merged