chore: add option unread to notices
aws/aws-cdk pull request #31250
Opened 2024-08-29 14:31 UTC by awslukeguan

### Issue # (if applicable)

Closes #23078

### Reason for this change

`cdk notices` will show all the notices the cdk version is affected by.
The additional command `cdk notices --unread` will show the notices the customer hasn't acknowledge with `cdk acknowledge <NUMBER>`.

The output will display the number of unacknowledged notices, with the following line as the last statement:
`There are <NUMBER> unacknowledged notice(s).`
Customer or automation tools can use this command to filter for the number of unacknowledged notices.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-08-29 14:34 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-08-29 14:34 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31250/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-29 15:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8dc43c64e38db04dbe9707df7f02152cf969184b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7116aadb-8476-42ab-87f1-b19f222d49d9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-08-29 16:12 UTC, comcalvi requested changes

2024-08-29 16:14 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31250/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-29 18:07 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31250/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-29 18:07 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31250/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-29 18:14 UTC, mrgrain commented on packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
> +    const regexVersionGreaterThan = /^2\.(154\.[2-9]|154\.1\d{1,}|15[5-9]{1}\.|1[6-9].{1,}|[2-9]\d{2}\.)/;
Drop the `-only` maybe? Seems redundant.

2024-08-29 18:16 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31250/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-29 19:00 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31250/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-29 19:00 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31250/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-29 19:55 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31250/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-29 19:58 UTC, comcalvi commented on packages/@aws-cdk-testing/cli-integ/tests/cli-integ-tests/cli.integtest.ts
> +    const regexVersionGreaterThan = /^2\.(154\.[2-9]|154\.1\d{1,}|15[5-9]{1}\.|1[6-9].{1,}|[2-9]\d{2}\.)/;
@mrgrain thoughts on naming? Should it be `--unacknowledged` or `--unread`, or something else?

2024-08-29 20:01 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31250/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-29 20:24 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 2d34876ea8d81ae590a1ece19ee0007ee8b38909
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5ff43f5d-4893-4d84-b8ac-dd6472af8d95%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-08-30 13:46 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31250/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-30 13:49 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31250/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-30 13:54 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31250/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-30 14:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d961665965bd40c5a2eb34f9b63d4a27cee4712b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d343ec74-c646-4b15-984a-0e0d3cd6c695%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-08-30 14:17 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: aaade03f602280238adfbdaa8de3c809a60baf49
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9f8a039c-d3be-4643-8a50-71f21c965a8f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-08-30 14:23 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 61b194dbb82b0fd5a8761ab4114510903c5d1032
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7202f17e-aeb1-4f09-8442-8fdda1e5d617%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-08-30 14:37 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31250/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-08-30 15:06 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 4c9a1a3ab1a7a4651538517a57b1631207e3a610
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b7203a0e-22b7-4df5-bc58-1fce460814ae%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-03 16:12 UTC, comcalvi requested changes

2024-09-03 18:17 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31250/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-09-03 18:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b5cb0642c74b8a12ae51f085a320425dfd8ad969
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7a4eee72-749b-486a-8bc5-5d3dcdc48e33%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-03 19:13 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31250/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-09-03 19:42 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0f8e0161547141b84cb12269603897fe9c728601
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=85a43278-b7d2-4e97-9943-32d663cd1972%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-04 15:37 UTC, comcalvi commented on packages/aws-cdk/test/notices.test.ts
> +});
```suggestion
    }
  });
});
```

2024-09-04 15:39 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31250/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-09-04 15:49 UTC, comcalvi approved these changes

2024-09-04 15:50 UTC, aws-cdk-automation commented
:arrow_right: **PR build request submitted to `test-main-pipeline`** :arrow_left:

A maintainer must now check the pipeline and add the `pr-linter/cli-integ-tested` label once the pipeline succeeds.
<!-- thollander/actions-comment-pull-request "request-cli-integ-test" -->

2024-09-04 15:52 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ CLI code has changed. A maintainer must run the code through the testing pipeline (git fetch origin pull/31250/head && git push -f origin FETCH_HEAD:test-main-pipeline), then add the 'pr-linter/cli-integ-tested' label when the pipeline succeeds.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-09-04 21:56 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7fead52b4c73657a002170f44746d8e5639a0fb6
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3cd6d437-356d-4d94-8920-9eb415ac2e3f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-04 21:57 UTC, merged