chore(lambda-event-sources): starting position timestamp for kafka
aws/aws-cdk pull request #31439
Opened 2024-09-13 10:40 UTC by nikovirtala

### Reason for this change

It was impossible to start consuming a Kafka topic from a specific point in time.

### Description of changes

The user may now set `startingPositionTimestamp` to `ManagedKafkaEventSource` and `SelfManagedKafkaEventSource` to start consuming a Kafka topic from a specific point in time. 

[Lambda and CloudFormation have supported the functionality for a while](https://aws.amazon.com/about-aws/whats-new/2023/06/aws-lambda-starting-timestamp-kafka-sources/), and other stream event sources like `KinesisEventSource` already had a CDK implementation for it, so there's nothing new under the sky — just expanding it to cover sources we are using :)

### Description of how you validated changes

The change is tested by adding similar unit tests to other event sources supporting this functionality.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-09-13 11:11 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e2166fbd36682bc1f6bfbde5be00a9d82b7f227f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c0128f35-ba79-49c1-acb6-b59f4c28a1f4%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-16 07:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3f1a47dacdc18989c549b32224248437f5211abc
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d0039791-3b8d-4ef1-b3c9-f5189d638e96%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-16 07:36 UTC, moelasmar commented
could you please add a new GH issue as a Feature request, and link it to this issue.

2024-09-16 07:37 UTC, moelasmar submitted a review, later dismissed
IMO, this is a feature and not a chore, and it needs update in Readme, and new integration test case

2024-10-03 17:43 UTC, sumupitchayan commented
> IMO, this is a feature and not a chore, and it needs update in Readme, and new integration test case

Agreed with @moelasmar, this seems like a `feat` to me - @nikovirtala can you please add an integ test and README documentation on this?

2024-10-03 17:44 UTC, sumupitchayan reviewed
Agreed with @moelasmar, this seems like a feat to me - @nikovirtala can you please add an integ test and README documentation on this?

2024-10-08 00:11 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2024-10-14 01:53 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-10-14 01:53 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-10-14 01:55 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-10-18 12:10 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-10-18 12:39 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e5219836c243b167238cd1830b6c6b74b7c27d52
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f5e77ed9-5ed8-475d-a2a5-14a92a642735%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-10-18 12:40 UTC, nikovirtala commented
> 2. testing Kafka Event Source Mapping requires creating an MSK cluster or such, which is not as trivial as creating a simple resource like DynamoDB Table (I hope there is something I can borrow from the MSK module, if one exist)

Ok, [the MSK module is in alpha state](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-msk-alpha-readme.html), and even that doesn't have an integration test that would create a topic and messages to the topic — which would be required to test this feature 😞 

I doubt that creating all that is too much for me.

2024-10-18 13:05 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-10-18 13:09 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-10-18 13:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 811d9b7b5c298fa846c0b0c73af9e07ea8c0c462
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=32c1ecec-88fc-4884-aea7-29b02fe5cf1d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-10-18 13:22 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-10-18 13:23 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-10-18 13:38 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 81e290b0febd09a08f55755a568b971f879f309d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0e4b1968-efcf-4f1b-8f12-c67dc5afb6e3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-16 11:42 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2024-11-16 12:10 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 19100c2e72ba075e98514859ed66f957bc0c61d2
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=81102cfc-cedf-4209-a804-60bb6fafa989%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-09 12:32 UTC, nikovirtala commented
It seems there are is zero integration tests in this module — so no one can change the given module before these is one?

2025-01-09 13:12 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2025-01-09 13:42 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f621c2280a175f9d6918dbe87c9783718c45b730
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b287be92-dc3c-44d5-a58e-1792710cc1a1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-09 13:58 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

✅ A exemption request has been requested. Please wait for a maintainer's review.

2025-01-09 14:17 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b7032783728e838e1babe34a4a9335434dec72ff
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=32d45e65-c88c-4d99-9383-14ecaff0d409%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-09 15:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 2114f643a558f9deca057ecd7df9e9f4e3f584a2
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=34781511-5ccd-4c36-817e-57cc51d055c6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-09 15:39 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 77978e669bfc326282f6428aa0ef3fbbafb768f9
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d3c331f5-3fdd-4276-a6d0-c8b91289ac5b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-09 23:41 UTC, moelasmar commented on packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts
> +  readonly startingPositionTimestamp?: number;
a minor comment, I know that we already use number as a type for this property in Kinesis, but I was thinking that it is better for customers to use a real time stamp here, and we do calculate the epoch number on behalf of the customers.

I can accept to have this property to keep it aligned with Kinesis, but I prefer to add another property that use Time stamp instead of number .. what do you think?

2025-01-09 23:43 UTC, moelasmar commented
sorry @nikovirtala for not coming back to this PR. I see that you already handled the integ testing point. I left one minor comment.

2025-01-09 23:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 49c090305a5e4e5ca5c23c5e83fbf8c2cf265cf9
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9e22b29b-a481-4bd7-8c35-220846959663%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-10 09:29 UTC, nikovirtala commented on packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts
> +  readonly startingPositionTimestamp?: number;
> a minor comment, I know that we already use number as a type for this property in Kinesis, but I was thinking that it is better for customers to use a real time stamp here, and we do calculate the epoch number on behalf of the customers.
> 
> I can accept to have this property to keep it aligned with Kinesis, but I prefer to add another property that use Time stamp instead of number .. what do you think?

Well, our current internal implementation of this very same functionality is using `Date` but I chose to use the number here to keep the consistency. I will take a look if I can find a nice way to get them both and we can then choose which looks/feels the best. 

*If* we end up to improve the API here, I can then implement those changes also to the Kinesis source (naturally on another pull request).

2025-01-10 09:39 UTC, nikovirtala commented
> sorry @nikovirtala for not coming back to this PR. I see that you already handled the integ testing point. I left one minor comment.

No worries! I was stuck in thinking that the integration test requirement meant something else than it actually does — I had set the bar "a little" too high in my mind 😅

2025-01-10 10:33 UTC, moelasmar commented on packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts
> +  readonly startingPositionTimestamp?: number;
thanks @nikovirtala

2025-01-10 14:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b8aec1b6e53df5c4e4b7f8fdcf3d92d482f7ba24
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c8c8915e-cb8e-41ba-b1d7-54cbce5ae385%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-10 14:49 UTC, nikovirtala commented on packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts
> +  readonly startingPositionTimestamp?: number | Date;
@moelasmar, here is one way to achieve it but is it very idiomatic to do it that way in CDK?

2025-01-10 16:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 06afa323600dba01c10366af74ea03f17ce45628
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9f84e4e2-5456-4bdc-9e13-e771bd8aa7a5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-10 16:49 UTC, moelasmar commented on packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts
> +  readonly startingPositionTimestamp?: number | Date;
in CDK we do not accept the union types in L2 any more. Personally I was thinking on replacing the type to be TimeStamp instead of number, but to be align with kinesis, I think we can add another property, and let customers choose which one to use, and for sure they can only use one of them.

2025-01-12 06:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8577db480bdec55abf995ee8f2f54f924c6a4b2e
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=dc7db670-8238-4cef-aae1-9cc0987db6f6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-23 11:21 UTC, nikovirtala commented on packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts
> +  readonly startingPositionTimestamp?: number | Date;
After digging into how this kind of property type change should happen in CDK, I found out that there is no clearly defined convention for it. There is a long discussion, e.g., on [Enhanced L1s RFC](https://github.com/aws/aws-cdk-rfcs/pull/657) about using the `_v2` pattern, but no consensus on going with it.

So, I suggest that we merge this like this:

> I can accept to have this property to keep it aligned with Kinesis

and worry about the API later once there is a clear convention on how to proceed.

The changes I made to test the union type are now reverted.

2025-01-23 11:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c8245d4cdd0cc964d7f074ed063936455d045d4b
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6d2acb5a-4faf-438f-b5e4-bfccf7ecb91c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-23 14:25 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b287c837125c06737ba3fdd445fd7e2540dc7f88
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0cb14374-846f-421d-91cd-5d2114a4117a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-25 20:19 UTC, samson-keung requested changes
Left a small comment, then I think it will be good to merge!

2025-02-25 20:19 UTC, samson-keung commented on packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts
> +    }
I'd suggest giving warnings instead of throw errors on these validations so that the following use cases become possible:
- when customers use Tokens for `props.startingPosition` and/or `props.startingPosition` (although probably a rare case)
- when customers use escape hatches (e.g. using `addPropertyOverride` method) to set either of the props after initializing the construct

Same comment on the other validations that throws error (line 260 - 268).

2025-03-19 00:17 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. Note that PRs with failing linting check or builds are not reviewed, please ensure your build is passing 

To prevent automatic closure:
- Resume work on the PR
- OR request an exemption by adding a comment containing 'Exemption Request' with justification e.x "Exemption Request: <justification>"
- OR request clarification by adding a comment containing 'Clarification Request' with a question e.x "Clarification Request: <question>"

This PR will automatically close in 14 days if no action is taken.

2025-03-20 23:15 UTC, shikha372 commented on packages/aws-cdk-lib/aws-lambda-event-sources/test/kafka.test.ts
> +    test('AT_TIMESTAMP starting position', () => {
```suggestion
    test('Setting startingPositionTimestamp for kafka event ', () => {
```

2025-03-20 23:17 UTC, shikha372 commented on packages/aws-cdk-lib/aws-lambda-event-sources/test/kafka.test.ts
> +    test('AT_TIMESTAMP starting position', () => {
```suggestion
    test('Setting startingPositionTimestamp for kafka event source ', () => {
```

2025-03-20 23:19 UTC, shikha372 commented on packages/aws-cdk-lib/aws-lambda-event-sources/test/kafka.test.ts
> +    test('startingPositionTimestamp without AT_TIMESTAMP throws error', () => {
```suggestion
    test('setting timestamp without  startingPosition as AT_TIMESTAMP throws error', () => {
```

2025-03-20 23:21 UTC, shikha372 commented on packages/aws-cdk-lib/aws-lambda-event-sources/test/kafka.test.ts
> +    test('startingPositionTimestamp missing throws error', () => {
```suggestion
    test('missing startingPositionTimestamp with startingPosition set to AT_TIMESTAMP throws error', () => {
```

2025-03-20 23:22 UTC, shikha372 commented on packages/aws-cdk-lib/aws-lambda-event-sources/test/kafka.test.ts
> +    test('startingPositionTimestamp without AT_TIMESTAMP throws error', () => {
```suggestion
    test('setting timestamp without setting startingPosition to AT_TIMESTAMP throws error', () => {
```

2025-03-20 23:47 UTC, shikha372 commented
Thank you @nikovirtala for contributing this PR, please let us know if you're still interested continue with this feature implementation, to prevent auto closing this PR.

2025-03-23 12:27 UTC, nikovirtala commented on packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts
> +    }
Warning? Can you show me what is the convention of warning in CDK? — I think I have never dealt with one here.

It is throwing an error because the resulting CloudFormation template won't work if these conditions are not met.

2025-03-23 12:33 UTC, nikovirtala commented
> Thank you @nikovirtala for contributing this PR, please let us know if you're still interested continue with this feature implementation, to prevent auto closure.

I have a lot of interest in getting this feature available but I don't know if I have time to deal with the constantly changing "requirements" from changing reviewers — it should be enough to get things merged if currently used conventions are followed.

2025-03-23 12:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c7a849098295cd0c3c53806cf7fb17b48047e495
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a47e9728-9786-40d6-ac6b-92d3c1b0c8ff%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-03-23 12:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 00293b3d4993fb5e6f24bcc1fe417e80645b5a33
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=807546ba-454e-4b74-80ae-2bc95814157c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-03-23 12:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ef123167120740f5b3d01140df322a7e0606b738
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6d6fff50-8288-4fd1-afbb-2cbca44c0e98%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-03-23 13:00 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e49cac862c8a2333cae470e7931d6d9311228483
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f1e10d8a-d2e7-4056-90dd-32af8fb7bdfd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-03-23 13:00 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 780264095603a55fa23972e6b7ac00a6ab3e7b40
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=85949ac3-5e34-4674-8e40-e6a10607f8ba%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-03-23 13:00 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 284c88c3da0913fc61e3217a333fd102462a7c00
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a9c48528-e409-4629-96d8-a8143a26ad91%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-03-23 13:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ed00a019deedc761ec8beb8171aa8064793e09c9
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4eaa86ed-4b59-4312-95e2-1d9f8dcd0114%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-03-26 22:26 UTC, shikha372 commented on packages/aws-cdk-lib/aws-lambda-event-sources/lib/kafka.ts
> +    }
Hi @nikovirtala , warnings can be added to constructs using [Annotations](https://github.com/aws/aws-cdk/blob/b9cb47c4dbaacd839ddfdc38febdc58260d20c57/packages/aws-cdk-lib/core/lib/annotations.ts#L9)

2025-03-26 23:24 UTC, shikha372 commented
Thank you @nikovirtala for your contribution, all comments are addressed now, will work on getting this merged in.

2025-03-26 23:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f6d3ce14876864a9b13e368ccae2cb8631d1573c
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=feff04aa-e4a0-4c07-b509-c5800939c9b5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-03-26 23:30 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7071e664bf093916a5f62ab07affeb18bf3dfd4f
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a1a6cbdc-1bb7-42fb-becf-ef8fb9dfe936%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-03-26 23:36 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: fc817657272bb416a77a91ccec9b9367cce7cb96
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d7588c25-0c2f-474f-b6ca-c95a7302b21e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-03-27 20:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 13acf8e600b0caa68ff14aea1b488150c0b8fadd
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d4b6a40e-3a19-4b80-880e-93166cdd14ef%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-03-27 22:12 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 49b9810d4d109445e851ede6e54ed5a638d1c7af
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c2ad4665-1807-4f53-9c40-ea144b93bf85%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-03-27 22:27 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 05f60bb039b680714fddbf3a3d41b53e86823142
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6923ee69-ca94-4ed3-92fc-cfbeb63428e0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-03-27 23:02 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 64e22dd59e3225fadfe22095986d5b903ad8ef68
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b00f21f8-47fc-48cf-aa5f-3bab90345709%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-03-27 23:42 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c91bf6ca95bfdc1cdf12706dc8b434780f4a2695
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=32d10fa1-3edf-4d61-990d-c2f52807ae93%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-03-28 00:02 UTC, shikha372 approved these changes

2025-03-28 00:33 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 129d236f9d4ff0cb80fcbc6ddf0460ed4178699d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=872d8167-abfb-4d9c-9089-6459a6b21fe2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-03-28 00:33 UTC, merged