chore(eks): update nodegroup gpu check and add g6e instance class
aws/aws-cdk pull request #31445
Opened 2024-09-13 19:43 UTC by AlexKaracaoglu

### Issue # (if applicable)

Closes #31347.

### Reason for this change

The motivating bug is that you cannot add a combo of g5 and a g6 as instance classes onto the same node group or else the following error will be thrown: `instanceTypes of different architectures is not allowed`.
Further - there was no instance type support for the new g6e instance class.

### Description of changes

* (ec2) Adds support for a g6e `InstanceClass`
  * Announcement: https://aws.amazon.com/about-aws/whats-new/2024/08/amazon-ec2-g6e-instances/
  * g6e: https://aws.amazon.com/ec2/instance-types/g6e/
* (eks) Fixes the `isGpuInstanceType` check
  * G6/G6E instance classes will now be recognized as GPU instance types so those different types can be used together for a multi instance type managed node group

### Description of how you validated changes

Have not since this is a chore to add in a new instance type and add onto the known gpu types. Happy to write some tests to cover the new additions if that is preferred.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-09-13 19:54 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5123e88eb1cf48b1f8908c83f2893cd4a39489bf
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ab0d60ce-3533-4ae3-808a-8b65f42e16a3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-13 19:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b541b427cc49a9952f4596cbcdf976c1e17fe5d6
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b595e905-b10b-4566-b117-b6a6e28684ab%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-13 20:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: dc79508be527bbb9ed8beb532fe78a2e9bc0a68e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f5cdec7c-0ebc-464b-b9b4-a46c589cf949%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-14 18:12 UTC, lpizzinidev approved these changes
Thanks 👍

2024-09-14 18:12 UTC, lpizzinidev commented on tools/@aws-cdk/cdk-build-tools/package.json
Can you please remove this change?

2024-09-16 13:03 UTC, AlexKaracaoglu commented on tools/@aws-cdk/cdk-build-tools/package.json
Removed!

2024-09-16 13:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8e88f82f07867b5c8c9329dfec90eae41b10cf9d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=10696e18-0434-4f5d-b524-9cbc5f0a65c1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-24 17:25 UTC, sumupitchayan reviewed
Thanks for your PR - I think adding an Integ test or modifying and existing one to use this new Instance Type would be nice to confirm that it successfully deploys.

Also, can you add a unit test for the `isGpuInstanceType` function?

2024-10-06 13:21 UTC, pahud commented
Hi @AlexKaracaoglu 

Not sure if you are still on it but you can refer to this commit I made
https://github.com/pahud/aws-cdk/commit/8fd3db823e232e87b010f990f009b8b22aade093

2024-10-11 15:02 UTC, AlexKaracaoglu commented
@pahud @sumupitchayan - Appreciate the follow ups, I'll get some changes in later today

2024-10-11 19:38 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7f82fd51a6e0b447ff7036039de669ccb25a0035
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c959a917-6f76-412e-a79a-54c4beb85eee%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-05 00:14 UTC, paulhcsun requested changes
Hi @AlexKaracaoglu, as mentioned by Sumu, could you use the new instance types in an existing integ test? You can refer to this PR for reference: https://github.com/aws/aws-cdk/pull/27373. I can also help to run the integ test if needed once you add the changes.

2024-11-05 00:16 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-11-05 00:16 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-11-05 00:16 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-11-05 00:18 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-11-05 00:18 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-11-22 14:34 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-11-22 14:49 UTC, AlexKaracaoglu commented
Hey @paulhcsun - appreciate the follow up. I added some changes to the integration tests to support the gpu nodegroup case. Would you be able to assist me with running/getting the snapshots updated now that the changes are in?

2024-11-22 14:53 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f696b9d857feb55155e01f96987655eab9c16a3e
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7cd5cef5-6eec-4be4-80bd-3e8c5ac659ff%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-27 00:12 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2024-12-05 00:12 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2024-12-05 00:14 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-12-12 23:17 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-12-12 23:17 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-12-13 07:29 UTC, paulhcsun commented
Hi @AlexKaracaoglu, apologies for letting this PR drop, I totally missed your comment. I've re-opened the PR and added the `pr-linter/do-not-close` label. 

I was able to run the integ tests successfully but I'm not able to push the changes through your fork because I do not have access rights to the [libertymutual](https://github.com/libertymutual/aws-cdk/tree/nodegroup-gpu-instance-types) fork. Is it possible to temporarily grant me access so that I can push the updated snapshots?

2024-12-20 18:19 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Features must contain a change to a README file.
	❌ Features must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-12-20 18:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ad301b78fd965a878d4e7dcb6707b432f41eb529
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b78abe05-18ca-4916-948a-4f57e3d5faee%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-02 22:10 UTC, paulhcsun commented
Hi @AlexKaracaoglu, I'm still not able to push to the libertymutual fork as mentioned in [my previous comment](https://github.com/aws/aws-cdk/pull/31445#issuecomment-2540775111) and I haven't received a response. Given the importance of your contribution and the need to move forward with the project, we've decided to take the following approach:

1. We've created a new PR, https://github.com/aws/aws-cdk/pull/32715, that incorporates your changes along with the necessary integration test snapshots.
2. In this new PR, we've credited you as the original author and linked to your original PR to ensure your work is properly acknowledged.
3. You've been tagged as a co-author to maintain clear attribution of your contribution.

We believe this approach allows us to integrate your work while maintaining project momentum. 

I will be closing this PR in favor of the other. If you have any questions, concerns, or would like to discuss this further, please don't hesitate to reach out. We truly appreciate your work and hope you'll continue to contribute to our project in the future.

2025-01-02 22:10 UTC, closed without merging