docs: change s3 bucket physical names to use amazon owned s3 buckets
aws/aws-cdk pull request #31561
Opened 2024-09-25 20:38 UTC by evzzk

### Issue # (if applicable)

Closes #<issue number here>.

### Reason for this change

By using Amazon owned s3 bucket physical names, we remove the possibility of documenting customer owned buckets in our examples. 

### Description of changes

Change physical S3 bucket names such as `my-bucket` to Amazon owned ones such as `amzn-s3-demo-bucket`. 

### Description of how you validated changes

### Checklist
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-09-25 21:00 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: cc8f10e6789f5d753940d74ed340918852213e25
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d989cabc-74dd-4c8e-a43c-c397bfa4c286%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-26 08:16 UTC, rix0rrr requested changes
You have checked in new files that are build results, like `.jsii` and `*.js` and `*.d.ts`.

I think you might have had an old checkout of CDK lying around containing 2 packages that have gotten moved, `packages/@aws-cdk/cloud-asembly-schema` and `packages/cdk-assets`.

All those files need to be removed from this PR.

2024-09-26 14:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: cbca0f37b5e3a8ea23096a874e1dc1f1980e6427
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3b7a332f-6de7-45b6-9973-6e691c908991%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-26 16:56 UTC, evzzk commented
Closing. Will resubmit with unwanted files removed from being accidentally added.

2024-09-26 16:56 UTC, closed without merging