feat(core): support adding additional cache key to cdk context values
aws/aws-cdk pull request #31586
Opened 2024-09-27 18:20 UTC by luxaritas

### Issue # (if applicable)

Closes #26982

### Reason for this change

The ContextProvider mechanism and various "lookup" functions of a number of constructs support caching resolved values in the cdk.context.json. The context keys are constructed from the parameters of the lookup, which for lookup functions means whenever a resource with the same parameters is resolved, it is resolved as the same value across the entire app. However when a value may change over time, the user may wish to use the latest value when creating creating a new reference to the construct, effectively tying the cached context value to the scope - this patch enables this.

The primary use case is looking up an AMI parameter for a "stateful" EC2 instance. Currently if you specify cachedInContext, any future images created would use the same cached AMI, and updating the value would require updating all usages of the image across the entire app.

### Description of changes

Adds an `additionalCacheKey` parameter/property to multiple areas of the CDK where lookups can be cached

### Description of how you validated changes

Unit + integration tests

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-09-27 18:22 UTC, luxaritas commented
This PR continues from https://github.com/aws/aws-cdk/pull/28766, which I let go stale stale while waiting for feedback from a maintainer

CC @TheRealAmazonKendra who was having some discussions about this

I still have to make some docs changes based on a couple rounds of previous reviews, but wanted to check CI first

2024-09-27 18:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d35b71f3b91659f8d4d33882d1ad59ec54511ae9
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bba495d0-37f8-45ea-9db4-cfbb80e1c72c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-09-27 19:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: cd2774ec3a674be250c9002bff5b9e65dbfd4730
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=38727ef9-e3a5-40ba-8af8-c8384ca0df04%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-10-11 21:11 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 68061ae3e36faf03b63fda7854783fd0d4e62bac
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b044ca22-a673-4707-b75c-44108d8af119%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-10-21 00:12 UTC, aws-cdk-automation commented
This PR cannot be merged because it has conflicts. Please resolve them. The PR will be considered stale and closed if it remains in an unmergeable state.

2024-10-21 02:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 9217a01d113a26a8b30cd094b50d6548f850076e
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=36d6e8ce-0432-4ad5-b5a7-80bfead90544%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-10-21 14:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 29a5a9575ef082052a2d6f76c4f74c6c72d4d582
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a724410c-62db-4f47-b529-8022f407fe74%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-04-16 08:15 UTC, rix0rrr requested changes
I like it, thanks! 

I've got some small requests for changes but other than that this seems good to go.

2025-04-16 08:15 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ec2/lib/security-group.ts
> +  public static fromLookup(scope: Construct, id: string, securityGroupId: string, additionalCacheKey?: string) {
I'd prefer not to have optional parameters as positionals, because this ultimately leads to `callFunction(3, undefined, undefined, true, undefined, false)` 😉.

If you want to add it here, create an `Options` struct for it. But more pragmatically: it's already available in the `fromLookupAttributes` method, which is good enough. No need to add it here as well then.

2025-04-16 08:15 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ec2/lib/security-group.ts
> +  public static fromLookupById(scope: Construct, id: string, securityGroupId: string, additionalCacheKey?: string) {
Same argument here.

2025-04-16 08:15 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ec2/lib/security-group.ts
> +  public static fromLookupByName(scope: Construct, id: string, securityGroupName: string, vpc: IVpc, additionalCacheKey?: string) {
Same argument hre.

2025-04-16 08:15 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ecs/lib/amis.ts
> +    this.additionalCacheKey = props?.additionalCacheKey;
We should probably add some validation to say that `additionalCacheKey` only makes sense if `cachedInContext==true` ?

2025-04-16 08:15 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ecs/lib/amis.ts
> +    this.additionalCacheKey = props.additionalCacheKey;
We should probably add some validation to say that `additionalCacheKey` only makes sense if `cachedInContext==true` ?

2025-04-16 08:15 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ecs/lib/amis.ts
> +    this.additionalCacheKey = props.additionalCacheKey;
We should probably add some validation to say that `additionalCacheKey` only makes sense if `cachedInContext==true` ?

2025-04-16 08:15 UTC, rix0rrr commented on packages/aws-cdk-lib/aws-ssm/lib/parameter.ts
> +  public static valueFromLookup(scope: Construct, parameterName: string, defaultValue?: string, additionalCacheKey?: string): string {
`defaultValue` is borderline (should probably have been in an options struct already), but I'd really like the `additionalCacheKey` to be part of an options struct.

2025-04-25 16:31 UTC, luxaritas commented
This is on my radar to look at soon

2025-04-26 00:11 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the MERGE CONFLICTS state for 3 weeks, and looks abandoned. Note that PRs with failing linting check or builds are not reviewed, please ensure your build is passing 

To prevent automatic closure:
- Resume work on the PR
- OR request an exemption by adding a comment containing 'Exemption Request' with justification e.x "Exemption Request: <justification>"
- OR request clarification by adding a comment containing 'Clarification Request' with a question e.x "Clarification Request: <question>"

This PR will automatically close in 14 days if no action is taken.

2025-04-27 03:48 UTC, luxaritas commented on packages/aws-cdk-lib/aws-ec2/lib/security-group.ts
> +  public static fromLookup(scope: Construct, id: string, securityGroupId: string, additionalCacheKey?: string) {
`fromLookupAttributes` is private (presumably these methods are to differentiate between mutually exclusive valid sets of options), so this is still needed. I'll swap to an options struct

2025-04-27 04:12 UTC, luxaritas commented on packages/aws-cdk-lib/aws-ssm/lib/parameter.ts
> +  public static valueFromLookup(scope: Construct, parameterName: string, defaultValue?: string, additionalCacheKey?: string): string {
I'm going to assume I shouldn't touch defaultValue since it'd be an API breaking change regardless

2025-04-27 04:13 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7d9042563e1c98b770bca626207d70458d2d047f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e618f985-93a2-40e3-bfba-f266f302bd2c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-04-27 04:25 UTC, luxaritas commented
Something else I've just discovered: `ApplicationListener.fromLookup`, `ApplicationLoadBalancer.fromLookup`, and `NetworkLoadBalancer.fromLookup` all call `SecurityGroup.fromLookupById`. Should we pass through the additionalContextKey from these to the SecurityGroup lookups?

And that said, Im having some second thoughts about this cache customization for lookups that _aren't_ tied to an SSM parameter (eg, looking up a VPC, LB, or SG by ID). At the very least, it shouldn't be _possible_ for an ID lookup to return something different over time, right?

2025-04-29 08:15 UTC, rix0rrr commented
> Though that said, Im having some second thoughts about this cache customization for lookups that aren't tied to an SSM parameter (eg, looking up a VPC, LB, or SG). At the very least, it shouldn't be possible for an ID lookup to return something different over time, right? 

That is true. At least a Vpc *can* get looked up by `isDefaultVpc: true`, or by tags, or by name, so it's not necessarily *only* an `id`. An LB can get looked up by tags, and an SG by name--which *theoretically* could point to a different SG over time.

I think the question is how likely it is that the underlying "looked-up" parameter is going to change, and how likely it is that you'd want all different versions over time being used within one application simultaneously.

The use case for AMIs you identified is a good one... I'm struggling to think of others.

The right solution is probably to implement this only for AMIs, and nothing else (both using the AMI provider and the SSM provider).

2025-05-31 01:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7932bfa3cd07ff8510255fe29da2242e16fa0d9d
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ef4aa673-e35f-4f49-ac3a-186cddb5bf4b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-05-31 01:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3c33f4ed9ca52b167632ce103c74f4ef81a90563
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=39515b49-910d-410c-a846-8c9721ba5b1b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-05-31 02:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: bcd1a5f178c43b6e7b472e30046871b81ffc45ed
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5bff3c74-810c-4cde-af62-5824bcff21a9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-05-31 02:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f45353a64bf097d1b772fbae542668064e5a06a1
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0818f0bb-087f-4dd5-b205-1d036fba9dda%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-06-03 12:12 UTC, rix0rrr approved these changes

2025-06-03 12:12 UTC, rix0rrr commented
Thanks!

2025-06-03 15:09 UTC, luxaritas commented
@rix0rrr Automerge failed because of workflow updates, so manually pulled in main

2025-06-04 14:55 UTC, rix0rrr approved these changes

2025-06-04 15:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 45e0641cbbae19b945ee49b2b43e40a433b09672
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9d2ad209-6a6c-4ed7-876f-b1989ad7a10e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-06-04 15:57 UTC, merged