fix for cognito custom attributes
aws/aws-cdk pull request #32009
Opened 2024-11-04 17:08 UTC by Balaji-JBC

### Issue #26820

Closes #26820 

### Reason for this change

See discussion in mentioned issue.

### Description of changes

custom attributes in userpoolidentityproviderbase is modified to be prepended with custom: so that we don't have to explicitly add custom: which is the current workaround. Part of this solution was observed from @diego-santacruz who created this issue

### Description of how you validated changes

The existing unit and integration tests has been modified to accommodate the change

### Checklist
- [ ] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-11-04 17:25 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: adf483d30c531d974ae6bd4a66428722bdbce3a9
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=10ea4ca4-3243-49ea-abd2-933a4783dfe9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-04 17:26 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: dbf8dbe874b212ba452b414733ae75c14d8e8679
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fa5155a0-1946-4920-a78c-37d2c3fe5933%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-04 18:57 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: cd28ac81570c705e601a593e8c3dc18ee967bfb7
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d5b44054-c099-4b07-9469-fd02aee0e9f0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-04 19:35 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 506aa02d8041bebe2de1cc7eae3b68d8cc5d0489
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2bed0dbc-1cd3-460b-95bb-d41632e21021%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-07 17:46 UTC, Leo10Gama requested changes
Thanks for the contribution! It seems like this change won't be backwards compatible with other versions, since it replaces the attribute value, and thus will be a breaking change. Instead, can we put this new behaviour behind a [feature flag](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/cx-api/FEATURE_FLAGS.md) and set the default to be the current behaviour?

It also looks like the integ tests were updated manually, since normally the entire snapshot folder changes with different updates. Can we also update each of those by running this in the `framework-integ` folder:
```
yarn integ test/aws-cognito/test/integ.<TEST_NAME>.js --update-on-failed
```
If you're having trouble updating them this way, I can also rerun the snapshots on my machine and push the updates here.

2024-11-07 19:53 UTC, Leo10Gama commented
Hi @Balaji-JBC, thanks for the quick response! I like that proposal, only touching custom mappings if they don't already have "custom:" appended, but I want to be sure that customers providing these values are truly broken (i.e. everyone currently providing in values cannot use them). That way, the only customers who need to redeploy their stacks are those whose stacks weren't working to begin with. Are we able to confirm that, even though it shows in the console, these values aren't being read and used correctly? If so, then let's go with that approach.

Doing a deep dive into the issue, it seems like it's not just a matter of appending "custom:" to the beginning of the string, but that the custom attribute itself has to exist in the `UserPool`. Adding that extra verification may be out of scope for this PR, but I think it means we should also update the integration test to include the extra `customAttributes` field for the matching custom `attributeMapping`. I'll refresh the integ test snapshots once that's included.

2024-11-07 21:38 UTC, diego-santacruz commented
Hi,

As I reported in the description of https://github.com/aws/aws-cdk/issues/26820 a workaround is possible with the old broken code, which I am using and maybe other people are using too. The workaround would normally output a broken template with the fix, unless there is a special provision for removing a duplicate `custom:` from the resulting CloudFormation template in the code.

2024-11-09 08:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 30138fbcc87701d28c66ed872edaae8d1bae3b5a
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=05e58a24-957a-42af-a25e-c995574455e0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-10 18:08 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 2ca7906448031720439c895299d1e0aef5271069
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9b478c54-e8eb-43e0-84ad-9acf6fa8086b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-10 18:45 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: add0766f6d1a604dc02fec5244c92da799ed1cb9
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4846374f-eca2-4963-8e22-be8222773af3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-10 19:04 UTC, Balaji-JBC commented
Hello @Leo10Gama , I've included the backward compatibility and updated the test cases. Could you please update the snapshots for the same? Also, let me know if more custom attributes to be added for the test.

> Doing a deep dive into the issue, it seems like it's not just a matter of appending "custom:" to the beginning of the string, but that the custom attribute itself has to exist in the `UserPool`. 

You're right. In the console, you don't get these attributes listed unless it is available in the `UserPool` but in the aws-cdk you can create any attributes and deploy and aws ignores invalid attributes without any error. Shall I create a separate PR with a fix for that as well?

2024-11-12 23:51 UTC, Leo10Gama commented
Hi @Balaji-JBC! I'm going through and updating the integ tests now, however I was only able to update one of them, as the others throw the error:
```
Error: integ.<test> is a new test. Please use the IntegTest construct to configure the test
```
Can you please go through each of the affected tests and update their outputs to use the `IntegTest` class? You should be able to simply provide the test stack under `testCases` similarly to how `integ.user-pool-idp.saml.ts` is.

2024-11-13 00:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c1bf08d451b4b09ff7b00a5e354f2fa57dacffce
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2d9ad54f-b43c-4aee-ad91-fa723bc2cc75%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-12-22 20:40 UTC, Balaji-JBC commented
Hello @Leo10Gama , I've ran the update-on-failed on integ tests and pushed the updated snapshot

2024-12-22 20:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 74626b0fe844768b39b3ea36e7180829274c0bd4
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=08af512e-90bc-4bf9-bbcd-0ddd262c3867%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-12-22 20:54 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 4ad76ff143b870c8becb8d3d65470ad3ab6938a6
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a0b4884f-5083-4914-b1ad-eda5d5dcdc42%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-12-24 04:21 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 1d73b74360a6ad5ec7fa8938a8d473e64e94368c
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ec4a3ce1-dab5-42ec-9fbc-67579a80f7af%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-10 00:31 UTC, gracelu0 requested changes

2025-01-10 00:31 UTC, gracelu0 commented on packages/@aws-cdk-testing/framework-integ/test/aws-cognito/test/integ.user-pool-idp.saml.ts
> +          department: ProviderAttribute.other('department'),
While we've fixed the prefix issue, these integration tests don't properly set up the custom attributes because the `UserPool` does not define them (I verified this by deploying the `integ.user-pool-idp.amazon.ts` test template). 

A couple of asks (once addressed I'm happy to approve):
1. Could we update the `UserPool` in the integration tests to create the corresponding custom attributes?

For example in this test:

```
    const userpool = new UserPool(this, 'pool', {
      removalPolicy: RemovalPolicy.DESTROY,
      customAttributes: {
        department: new StringAttribute({ minLen: 5, maxLen: 40, mutable: false }),
      }
    });
```
2. Could we update the README example [here](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-cognito/README.md?plain=1#L655-L671) as well to create the `uniqueId` custom attribute in the `UserPool`?
3. Could we update the `integ.user-pool-idp-*.ts` tests to use the new `IntegTest` framework? Example:
```
import { IntegTest } from '@aws-cdk/integ-tests-alpha'; //add this to imports

const app = new App();
const stack = new Stack(app, 'integ-user-pool-idp-google');
.
.
.

new IntegTest(app, 'integ-user-pool-identity-provider-google-test', {
  testCases: [stack],
});
```

Thank you! Appreciate your work on this.

2025-02-01 00:11 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2025-02-01 21:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b98507c7a96088a358e20d5df6c6e9c8d0f29704
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a0d63845-2f45-4638-ae05-910331abf99e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-03-05 17:59 UTC, Leo10Gama requested changes
Thanks for updating the snapshots! I want to echo @gracelu0's sentiments here as well. I think we should include those suggested changes:
* Adding the extra `customAttributes` field to the UserPool in the `integ.user-pool-idp.saml.ts` test so that it deploys with the correct field visible in console.
* Updating the `README.md` example in the section related to custom user pool attributes (found [here](https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk-lib/aws-cognito/README.md?plain=1#L752-#L768), since that file has been updated since the last review) to reflect that the UserPool needs to have the `customAttributes` field as well.
* Updating the `integ.user-pool-idp-*.ts` tests to use the new `IntegTest` framework as opposed to their current model. The `saml` test seems to be a good example of how to implement it, if it seems confusing.

In addition, it seems like some merge conflicts have come up since the last review. Could you please address those as well?

Feel free to reach out if you need any additional clarification. Thanks again for your contribution!

2025-03-09 00:10 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the MERGE CONFLICTS state for 3 weeks, and looks abandoned. Note that PRs with failing linting check or builds are not reviewed, please ensure your build is passing 

To prevent automatic closure:
- Resume work on the PR
- OR request an exemption by adding a comment containing 'Exemption Request' with justification e.x "Exemption Request: <justification>"
- OR request clarification by adding a comment containing 'Clarification Request' with a question e.x "Clarification Request: <question>"

This PR will automatically close in 14 days if no action is taken.

2025-03-23 00:12 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2025-03-23 00:12 UTC, closed without merging