fix(cloudwatch-actions): cannot add LambdaActions to alarms with the same id but different addresses
aws/aws-cdk pull request #32057
Opened 2024-11-08 02:27 UTC by tmokmss

### Issue # (if applicable)

Closes #30754.

### Reason for this change

As decribed in the linked issue, the permission ids must be unique per Lambda function, and we cannot use alarm's costruct id to generate a permission id because alarm ids are not necessarily unique. To make sure its uniquenss, we use node address instead. A node address is guaranteed to be unique in a construct tree, so safe to use in permission id.

### Description of changes

Because Lambda's resource policy (permission) is stateless, re-creating it with different logical ID is not a breaking change, as per [the doc](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md#behavior-changes):

> Not all template changes are breaking changes! Consider a user that has created a Stack using the previous version of the library, has updated their version of the CDK library and is now deploying an update. A behavior change is breaking if:
The update cannot be applied at all
The update can be applied but causes service interruption or data loss.

That's why this PR removes the feature flag and just replaced the perimssion id code.

When you deploy an existing stack after this patch, CFn deploys in the following order:

1. start deployment
2. create a permission with new logical ID
3. delete a permission with old logical ID
4. finish deployment

So the permission for an alarm is active at any phase of the deployment.

### Description of how you validated changes

add unit test and run integ test to confrim it deploys without disruption.

### Checklist
- [X] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-11-08 02:29 UTC, aws-cdk-automation requested changes
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-11-08 02:29 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-11-08 02:30 UTC, tmokmss commented on packages/aws-cdk-lib/aws-cloudwatch-actions/test/lambda.test.ts
> +test('can use same lambda for same action multiple time', () => {
Sorry, it accidentally became cryptic diff, but this PR just does the following:
1. adds a new test case for `can use same lambda for multiple alarms with the same id`
2. removes the existing test case for `throws when multiple alarms are created for the same lambda if feature flag is set to false`.

2024-11-08 02:43 UTC, tmokmss commented on packages/aws-cdk-lib/aws-cloudwatch-actions/test/lambda.test.ts
> +test('can use same lambda for same action multiple time', () => {
I moved the added test far away from the removed test to make it more visible.

2024-11-08 02:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: a7c49ca573aad9a497470e0205eef9ff456e1f62
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=44ba9695-a5d3-4cfb-8a03-062c834a998c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-08 03:04 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d92dfc7cba47ac09d16f74c0afab988081f14d5d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=78de774f-f7ca-4e20-bf26-f62249f1bc39%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-08 03:13 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c4c3dbe1cfdd911ec872965a8795c3643e023350
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=cf45c87b-db50-4f19-84c8-a5d110e69f07%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-06 22:20 UTC, GavinZZ requested changes
Putting this PR to state `Request Changes` while I double check with the team that changes like this is allowed. 

Since there's change in logical id, it will result in CloudFormation resource deletion & recreation. 

The only potential concern would be that if the CloudWatch Alarm transitions state while the old permission is deleted but before the new one is created, the Lambda function won’t be invoked because it temporarily lacks permission.

2025-02-10 18:41 UTC, GavinZZ commented
@tmokmss We cannot accept this PR given the current state of change. I brought this up to the team to discuss internally, but we believe that this will be a breaking change for some users. This is because AWS IAM permission change is usually eventually consistent https://docs.aws.amazon.com/IAM/latest/UserGuide/troubleshoot.html, which means that there's potential concern would be that if the CloudWatch Alarm transitions state while the old permission is deleted but before the new one is created, the Lambda function won’t be invoked because it temporarily lacks permission.

2025-02-28 00:10 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the CHANGES REQUESTED state for 3 weeks, and looks abandoned. Note that PRs with failing linting check or builds are not reviewed, please ensure your build is passing 

To prevent automatic closure:
- Resume work on the PR
- OR request an exemption by adding a comment containing 'Exemption Request' with justification e.x "Exemption Request: <justification>"
- OR request clarification by adding a comment containing 'Clarification Request' with a question e.x "Clarification Request: <question>"

This PR will automatically close in 14 days if no action is taken.

2025-03-14 00:11 UTC, aws-cdk-automation commented
This PR has been deemed to be abandoned, and will be automatically closed. Please create a new PR for these changes if you think this decision has been made in error.

2025-03-14 00:11 UTC, closed without merging