refactor(apprunner): consolidate name validations for App Runner Resources and improve error messages
aws/aws-cdk pull request #32062
Opened 2024-11-08 07:39 UTC by mazyu36

### Issue # (if applicable)

N/A

### Reason for this change
Consolidate name validations for App Runner Resources and improve error messages.

### Description of changes
* Split regex-pattern check and length check to be more user-friendly.
  * `autoScalingConfigurationName` in `AutoScalingConfiguration`
  * `observabilityConfigurationName` in `ObservabilityConfigurationName`
  * `vpcIngressConnectionName` in `VpcIngressConnectionName`
* Add name validations.
  * `serviceName` in `ServiceName`. (Ref: [CFn document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-servicename))
  * `vpcConnectorName` in `VpcConnectorName`. (Ref: [CFn document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-vpcconnector.html#cfn-apprunner-vpcconnector-vpcconnectorname))

### Description of how you validated changes
Modify and add unit tests.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-11-08 08:09 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f3b134d79058c13069dfc97d624ed5aa59cd922b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d50846af-1d09-4cf7-a5fb-b346c6d88878%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-13 01:34 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8253ce851cf2e552410fc4014ed435e37fca4e94
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=701031fc-984a-45cb-81dd-384428654a27%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-15 14:10 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: bd7a3c93ba03b4e1bfed4b25176a9965c6f2c452
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5741a7c1-4949-4d83-9bbd-02ab44cc00b7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-15 23:47 UTC, badmintoncryer requested changes
I have made just one comment! Please check it!

2024-11-15 23:47 UTC, badmintoncryer commented on packages/@aws-cdk/aws-apprunner-alpha/lib/vpc-connector.ts
> +      if (!/^[A-Za-z0-9][A-Za-z0-9\-_]*$/.test(props.vpcConnectorName)) {
From [Cfn document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-vpcconnector.html#cfn-apprunner-vpcconnector-vpcconnectorname), it seems that hyphen is not allowed for the VPC Connector name.

```
^[A-Za-z0-9][A-Za-z0-9-\\_]{3,39}$
```

2024-11-16 09:28 UTC, mazyu36 commented on packages/@aws-cdk/aws-apprunner-alpha/lib/vpc-connector.ts
> +      if (!/^[A-Za-z0-9][A-Za-z0-9\-_]*$/.test(props.vpcConnectorName)) {
Thanks.

I think regex pattern in Cfn document is wrong.

I successfully created a VPC Connector with a name containing hyphens.

<img width="731" alt="スクリーンショット 2024-11-16 18 13 54" src="https://github.com/user-attachments/assets/2afec54b-bb0b-4016-ac06-1ffd2d4f5812">

According to the management console, VPC connector names can only contain alphanumeric characters, hyphens, and underscores.
While the regex pattern in the CFn documentation indicates that backslashes are allowed, in practice they are not permitted.

<img width="582" alt="image" src="https://github.com/user-attachments/assets/2f08aa4e-ed81-4a67-82df-6c1067fb5de5">

I would like to provide feedback regarding this documentation to AWS team.

2024-11-16 12:25 UTC, badmintoncryer commented on packages/@aws-cdk/aws-apprunner-alpha/lib/vpc-connector.ts
> +      if (!/^[A-Za-z0-9][A-Za-z0-9\-_]*$/.test(props.vpcConnectorName)) {
Thank you for your information! I understand.

2024-11-19 00:41 UTC, gracelu0 reviewed
LGTM other than 2 typos, will approve once fixed :)

2024-11-19 00:41 UTC, gracelu0 commented on packages/@aws-cdk/aws-apprunner-alpha/test/obserbability-configuration.test.ts
> +])('observabilityConfigurationName length is invalide (name: %s)', (observabilityConfigurationName: string) => {
```suggestion
])('observabilityConfigurationName length is invalid (name: %s)', (observabilityConfigurationName: string) => {
```

2024-11-19 00:41 UTC, gracelu0 commented on packages/@aws-cdk/aws-apprunner-alpha/test/vpc-ingress-connection.test.ts
> +])('vpcIngressConnectionName length is invalide (name: %s)', (vpcIngressConnectionName: string) => {
```suggestion
])('vpcIngressConnectionName length is invalid (name: %s)', (vpcIngressConnectionName: string) => {
```

2024-11-19 01:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8d174102cb3cc87d511820034b96415a80f6b9a4
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4fce7af6-9f4c-4ffc-b864-e451023c108f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-19 01:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: da0b9582b0ce5be9d0b238263624f64b997dd580
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a37420c8-5e9f-473a-8892-5802fcbdb074%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-19 01:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 127d8281f6a436b22411d188bb0d1534d391bb1e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=52061f4a-de84-4d06-b3a3-39e9542c20af%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-19 01:43 UTC, mazyu36 commented
@gracelu0 
Thanks! I've updated.

2024-11-19 01:48 UTC, gracelu0 reviewed
just two more typos sorry I missed them earlier 😅

2024-11-19 01:48 UTC, gracelu0 commented on packages/@aws-cdk/aws-apprunner-alpha/test/service.test.ts
> +])('serviceName length is invalide (name: %s)', (serviceName: string) => {
```suggestion
])('serviceName length is invalid (name: %s)', (serviceName: string) => {
```

2024-11-19 01:48 UTC, gracelu0 commented on packages/@aws-cdk/aws-apprunner-alpha/test/vpc-connector.test.ts
> +])('vpcConnectorName length is invalide (name: %s)', (vpcConnectorName: string) => {
```suggestion
])('vpcConnectorName length is invalid (name: %s)', (vpcConnectorName: string) => {
```

2024-11-19 02:22 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ee8d97c1bf9e9935b6ac6a114d32fa075c11816c
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e34f8e97-132c-4b14-a081-3c99cc7e5007%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-19 03:02 UTC, mazyu36 commented
@gracelu0 
Oops...Sorry, I've fixed again.

2024-11-19 19:00 UTC, gracelu0 approved these changes
Thank you!

2024-11-19 19:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 68341e33995726df2b80f7b340a7fb4c1c51f404
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b17538e7-aa3c-4048-857c-fd24e81f0407%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-19 19:32 UTC, merged