feat(kinesis): support stream consumers
aws/aws-cdk pull request #32087
Opened 2024-11-11 10:43 UTC by humanzz

### Issue # (if applicable)

Closes #32050

### Reason for this change

Support Enhanced fan-out consumers via `AWS::Kinesis::StreamConsumer` and facilitate cross-account stream consumption via

### Description of changes

- introduce `StreamConsumer` construct to model `AWS::Kinesis::StreamConsumer`
  - introduce `addToResourcePolicy` to enable creating/configuring a resource policy for the consumer
  - introduce `grant` and `grantRead` for granting permissions
  - leverage `iam.Grant.addToPrincipalOrResource` in `grant` to be able to use `grant` methods cross environments to update the grantee's iam policy and the consumer's resource policy as needed
- update `ResourcePolicy` to support both `Stream` and `StreamConsumer`
- update `Stream`'s `grant` to leverage `iam.Grant.addToPrincipalOrResource` for cross-environment support

### Description of how you validated changes

unit and integration tests

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-11-11 11:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f04a688d21b2d7e56ad7ffa1275e54b07287cd54
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=10a3df6f-e130-4f3f-8966-7295799f36e6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-11 11:52 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: af07f895c2af98d5f3eca003dc37a7d1d85de314
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c180c725-c662-46cd-bcc8-91464e546ac0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-13 16:10 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 07aaa24911daee3412acb6b6c7ef62205a721f79
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0fe12976-cb40-471d-a3d4-03a01c881627%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-14 15:27 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 46f08eccca99dea0f82f5c5a1792cc5ad1c8b921
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2c56b82b-75a8-47a2-9ba7-158e119137ca%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-17 14:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8f520cdb5a5b63debc02f0384aa19851fb6871bf
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=dd0bc89b-f438-4521-9bae-a4ed4fbc4f29%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-20 17:24 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6878126bb7b1fe8503e041c4c791b4105c2bdac4
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fdb13b2c-5b97-4ff8-b007-76ec4215c696%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-22 11:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 6e2e5714c63c9ce57683d94667dd9f5f53f7a49a
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5f221c65-260e-45ae-bfb3-1d74df7c8ec6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-23 13:34 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3e72f85083706c84be0764bfda7701801c0a1e63
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8bc7fa0c-cc6f-4f94-b531-32c7c32889d5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-25 16:27 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 66e3ab51a7dad67fab3f2072b787aaba0df4ce83
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1674216c-c707-41fa-aa48-808306f58613%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-25 16:45 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5521931260efdc3cf59500858f215547b44f6c57
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8ade615f-1f06-48be-b510-be42eca39603%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-25 17:11 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b49c7721b592456a02839597f3133665086aa22c
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=51d99a6e-64c0-4d04-8a30-569f910aaca8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-25 17:24 UTC, humanzz commented on packages/aws-cdk-lib/aws-lambda-event-sources/lib/kinesis.ts
> -    this.stream.grant(target, 'kinesis:DescribeStream');
This permission is now already part of `grantRead`

2024-11-25 17:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3af8d07a2ab39d90c84e3e955463899fdccc79ca
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ceab9ffa-0c96-4294-a295-09b498466d51%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-12-02 17:38 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f1f7ef6851d76ae924bdf02ada6b92ac42be3e66
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=544babb4-d457-482d-b248-c32d7ebc6acd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-12-18 14:41 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ddca03b7192a979bdda3a53152c5b49b8fc9d350
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=419b988e-5a5d-4e00-89e8-e305b11210b8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-12-28 13:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e96a945d850ac3efcf6ecd5129102a7ca636b876
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bccc3418-4050-479e-9292-a57b728c9580%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-12-28 21:00 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 4a998ccc4cc09c35471d41e502aa218a67d241e0
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0805558e-5667-4579-a58c-2e88c713cbc7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-08 13:29 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 87d17e53fe049ce3c24a561963a03b19c1a5c895
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2cdafc51-2230-46b4-9338-ce74fb14bcd8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-09 21:10 UTC, humanzz commented on packages/aws-cdk-lib/aws-kinesis/lib/stream.ts
>      });
Thanks for this. This is interesting I didn't know about this limitation.

I've checked the link, just to confirm, are u referring to the table of *Kinesis Data Streams actions that can be shared* ?

I'm trying to think about what issues can arise?
1. The list of hardcoded permissions in `stream.ts` (`READ_OPERATIONS`, `WRITE_OPERATIONS`) and `stream-consumers.ts` (`READ_OPERATIONS`) might not match those lists u provided?
1. Anyone using `grant` directly might not know about the limitation, and would just be surprised when cloudformation deployment fail?

Re 1, I think that if so, then it definitely needs addressing
Re 2, depending on how 1 might be addressed, can be automatically solved, or if 1 is not an issue, then it might be ok to leave it on the user maybe to

2025-01-09 21:22 UTC, humanzz commented on packages/aws-cdk-lib/aws-kinesis/lib/stream.ts
>      });
note to self: integ test for grant methods in a cross-account fashion... examples of cross-account tests https://github.com/search?q=repo%3Aaws/aws-cdk%20CDK_INTEG_CROSS_ACCOUNT&type=code

2025-01-09 21:54 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 64b60a25b7312aaa8ccb547e05e041bc210d797f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4a9148cd-3f53-4691-814f-ffa49ed3bfaa%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-15 10:46 UTC, humanzz commented on packages/aws-cdk-lib/aws-kinesis/lib/stream.ts
>      });
Thanks for that. I'll get back to this PR in the next couple of days to try to add integ tests around cross-account, and therefore testing this whole resource policy aspect you rightly raised.

I'm just hoping folks from CDK team start engaging with this PR, as it's been sitting idle for quite sometime now :(

I'll let you know If further assistance is needed, and appreciate the offer :)

2025-01-15 11:18 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 2ee960a49fa8404c60f37bef393292b178dbdef2
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=125fa5b7-9a0e-46ef-b6f8-1658a7ffa95d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-14 19:07 UTC, GavinZZ requested changes
Great work! Thank you for supporting stream consumer in CDK L2. I left some minor comments for clarifications.

2025-02-14 19:07 UTC, GavinZZ commented on packages/aws-cdk-lib/aws-lambda-event-sources/lib/kinesis.ts
> +interface KinesisSource {
Can you provide a docstring for this new interface?

2025-02-14 19:07 UTC, GavinZZ commented on packages/aws-cdk-lib/aws-lambda-event-sources/lib/kinesis.ts
> +abstract class KinesisEventSourceBase extends StreamEventSource {
same for this new abstract class

2025-02-14 19:07 UTC, GavinZZ commented on packages/aws-cdk-lib/aws-lambda-event-sources/lib/kinesis.ts
> -    this.stream.grant(target, 'kinesis:DescribeStream');
Nice catch!

2025-02-17 09:51 UTC, humanzz commented on packages/aws-cdk-lib/aws-lambda-event-sources/lib/kinesis.ts
> +interface KinesisSource {
I can add something, I just didn't initially add, as both `KinesisSource` and `KinesisEventSourceBase` are not public

2025-02-17 09:53 UTC, humanzz commented on packages/aws-cdk-lib/aws-kinesis/lib/stream.ts
> +    return iam.Grant.addToPrincipalOrResource({
Yes... the intention here was to support cross-account use cases. There's a comment above by @byF that suggests this might be problematic given the default permissions, and might require better integ testing

2025-02-17 10:04 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: a9a3ee7566fbde9a3dbe646e97857e3e1cf7d624
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ab2c2bb4-b40c-4bbb-a9c3-f78cde67f3c9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-17 11:37 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 31f9a005a7534deedfac66d0de634ab9d6f82889
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=da93d39b-4336-494e-a2d0-792c7a3f5a68%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-17 12:11 UTC, humanzz commented on packages/aws-cdk-lib/aws-kinesis/lib/stream.ts
>      });
I've finally made it to this. In `integ.stream.ts`, I added

```
const crossAccount = process.env.CDK_INTEG_CROSS_ACCOUNT || '987654321';
const crossAccountPrincipal = new iam.AccountPrincipal(crossAccount);

stream.grantReadWrite(crossAccountPrincipal);
```

just to test things out, and I got a cloudformation error

```
Resource handler returned message: "Policy validation error: Resource policy contains invalid statement at line 1, column 38: The following action names are invalid: "kinesis:ListStreams", "kinesis:SubscribeToShard", "kinesis:DescribeStreamConsumer" (Service: Kinesis, Status Code: 400, Request ID: d8973e32-926a-a5f0-b8ba-21aa8d5ad570, Extended Request ID: ftJnfPUuuIaS816f+I7JsPJYIwHCF7fgwHRtCHmh3ma5d8N/52w21hAllc1riraWt0ABerdF8gHyGGqwQG1cX/RhGXD3zp+T)" (RequestToken: c89f662a-e691-0b80-589e-78bbadc602eb, HandlerErrorCode: InvalidRequest)
```

i.e. `kinesis:DescribeStreamConsumer`, `kinesis:ListStreams`, `kinesis:SubscribeToShard` which are in `stream.ts`'s `READ_OPERATIONS` are problematic. A couple of thoughts
- `kinesis:ListStreams` is a bit odd to be in `READ_OPERATIONS`
- `kinesis:DescribeStreamConsumer` and `kinesis:SubscribeToShared` seem to be required by roles, especially those using KCL https://github.com/aws/aws-cdk/issues/22184

Any thoughts on cleanly handling this @GavinZZ? It seems like, either
1. In stream's grant methods, we need to figure out if it's gonna end up being resource or principal policy that get the actions, and if so, filter out the actions accordingly - but I don't know if there's any exposed utilies for that outside of `grant.ts`
2. Maybe `Grant.addToPrincipalOrResource`, needs some new props, to have some actions marked as principal-exclusive, others as resource-exclusive or something along those lines.

2025-02-17 21:50 UTC, humanzz commented on packages/aws-cdk-lib/aws-kinesis/lib/stream.ts
>      });
@GavinZZ In https://github.com/aws/aws-cdk/pull/32087/commits/c6643d59dd82c3f898b472d6b95cf4ac5ccc6ac9, I managed to filter out incompatible actions from `grantRead` when they're meant to apply for a resource policy.

Moreover, I've added a new cross-account integ test, generating the snapshot using 2 of my aws accounts by setting the relevant environment variables (based on examples i found using https://github.com/search?q=repo%3Aaws/aws-cdk%20CDK_INTEG_CROSS_ACCOUNT&type=code) e.g. `export CDK_INTEG_ACCOUNT=<acc1>; export CDK_INTEG_CROSS_ACCOUNT=<acc2>; export CDK_INTEG_REGION=us-east-1`. However, when unsetting the variables and running `yarn integ test/aws-kinesis/test/integ.cross-account-stream-consumption.js`, the test failed due to account mismatches. I manually updated the snapshot to match.
Something feels wrong about this way of that last manual intervention, but unfortunately I couldn't find any relevant docs at https://github.com/humanzz/aws-cdk/blob/main/CONTRIBUTING.md and https://github.com/humanzz/aws-cdk/blob/main/INTEGRATION_TESTS.md

2025-02-17 22:16 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c6643d59dd82c3f898b472d6b95cf4ac5ccc6ac9
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=329f7344-3b5a-4f3e-a812-34e3111a968e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-18 12:14 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: cbcd96a64c1eb6c1752d25950eee86ba84c3ccd7
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0ad52539-e443-4e0e-8804-33cf6d6c77b2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-18 18:25 UTC, GavinZZ commented on packages/aws-cdk-lib/aws-lambda-event-sources/lib/kinesis.ts
> +interface KinesisSource {
oh I see, it's not exported. That should be fine then.

2025-02-18 18:41 UTC, GavinZZ submitted a review, later dismissed
LGTM, thank you!

2025-02-18 19:01 UTC, GavinZZ commented
@mergifyio requeue

2025-02-18 22:18 UTC, GavinZZ commented
@mergifyio requeue

2025-02-18 22:18 UTC, GavinZZ commented
@mergify update

2025-02-18 22:19 UTC, GavinZZ approved these changes

2025-02-18 22:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d4f491d0425d337b19061f26cc05728b16d0e20f
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d96e2e7a-b07e-42bd-9364-3044b74b8ab2%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-18 23:19 UTC, merged

2025-02-18 23:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 9f0070be32c901ab089acae078cc51a892e5aadd
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=d04776a7-5611-4c16-8ef9-be4ea938769f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->