feat(ecs): support container version consistency
aws/aws-cdk pull request #32225
Opened 2024-11-21 05:30 UTC by isker

Support the new ECS::TaskDefinition ContainerDefinition VersionConsistency property. This is a simple enabled/disabled flag.

Additionally, set a default "disabled" value if the container image is a CDK asset, for the reasons described in the comments.

### Issue # (if applicable)

Closes #32202.

### Reason for this change

Support a new CloudFormation property in the L2 ContainerDefinition construct.

### Description of changes

Add a simple enabled/disabled enum prop to the construct.

More consequentially, default the prop to disabled (instead of unset) if the container image is a CDK asset, for the reasons described in the comments.

### Description of how you validated changes

Unit and integration tests.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-11-21 05:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 63311e2b4fbc53bb90dda1a1f039a1428e91fdcb
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0c69865b-9fd8-4c0e-ac07-e3ef48454a13%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-21 05:55 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: f077a3fc71c234b7eaa2674960c17bdfee437c4c
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1ef5ee52-4b07-4118-bc62-764914267fa8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-22 04:53 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: e4d61ca829525fbe02008ea4f05ad0c6ad4011cc
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=abfcaf3d-7988-4c17-9193-b5010bf132a5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-22 04:58 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 12550579693da3d4327f7637165e72092d82163c
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4991725e-04b6-46ae-a874-ab6a08038f96%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-22 05:32 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 23808f7a211937ec6e33de4cdcde9cdbbdc5f15c
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0c376515-c676-4818-a980-32f0b820bcf9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-25 22:53 UTC, isker commented
@iliapolo I'm not sure why you updated the branch, but it seems that the resulting CodeBuild CI job hanged or something, the GitHub check is stuck in pending.

2025-01-06 04:37 UTC, mazyu36 requested changes
Thank you for the contribution.
Some comments.

2025-01-06 04:37 UTC, mazyu36 commented on packages/aws-cdk-lib/aws-ecs/lib/container-definition.ts
> +  readonly versionConsistency?: VersionConsistency;
How about changing this property to a `boolean` for a clearer interface, like the following?

https://github.com/aws/aws-cdk/blob/719bb2723c6d16361b90a5dd61eef902d06c532a/packages/aws-cdk-lib/aws-ecs/lib/cluster.ts#L1285

https://github.com/aws/aws-cdk/blob/719bb2723c6d16361b90a5dd61eef902d06c532a/packages/aws-cdk-lib/aws-ecs/lib/cluster.ts#L1386

2025-01-06 04:37 UTC, mazyu36 commented on packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/base/integ.task-definition-container-version-consistency.ts
> +app.synth();
nit: this line is not needed.

```suggestion
```

2025-01-06 17:27 UTC, isker commented on packages/aws-cdk-lib/aws-ecs/lib/container-definition.ts
> +  readonly versionConsistency?: VersionConsistency;
I had hoped the [design guidelines](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md) would have something to say about this, but I can't see anything.

2025-01-07 03:42 UTC, mazyu36 commented on packages/aws-cdk-lib/aws-ecs/lib/container-definition.ts
> +  readonly versionConsistency?: VersionConsistency;
Thank you for the reply. I understand.
In my opinion, it's okay to use enum.

I'll approve once the other nit comment is addressed.

2025-01-07 04:28 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b28e0070b2305418ac3b629497dd68708124b9cb
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5b17c0a1-0ca2-4f74-8ea7-2c7499c096a8%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-07 05:03 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: cb2995a514bcee9233446d1139faef81a16f45cd
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=89b01d3b-3c37-4503-b69d-ded2116ce6e1%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-07 06:06 UTC, mazyu36 approved these changes
Thanks!

2025-01-31 02:08 UTC, GavinZZ requested changes
Left one comment to help me understand.

2025-01-31 02:08 UTC, GavinZZ commented on packages/aws-cdk-lib/aws-ecs/lib/container-image.ts
> +        containerDefinition._defaultDisableVersionConsistency?.();
This seems like a weird usage, can you help me understand this syntax.
Also if it's `public` method, we should remove `_`.

2025-01-31 02:28 UTC, isker commented on packages/aws-cdk-lib/aws-ecs/lib/container-image.ts
> +        containerDefinition._defaultDisableVersionConsistency?.();
Thanks for reviewing.

> can you help me understand this syntax.

This is [optional chaining for invoking functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#syntax).  I did it because evil code passes arguments to these functions that are in fact not `ContainerDefinition`s:
https://github.com/aws/aws-cdk/blob/7b5f5a55b0722b8ba9c90ad545216ebb9e8407e4/packages/aws-cdk-lib/aws-batch/lib/ecs-container-definition.ts#L621-L626

So, `_defaultDisableVersionConsistency` can be undefined in spite of what TypeScript indicates.  

> Also if it's public method, we should remove _.

I see many `@internal` `public` methods that have leading underscores. I can remove it if you like, but it does not seem unusal.

https://github.com/search?q=repo%3Aaws%2Faws-cdk%20path%3Apackages%2Faws-cdk-lib%20%40internal&type=code

2025-01-31 21:21 UTC, GavinZZ commented on packages/aws-cdk-lib/aws-ecs/lib/container-image.ts
> +        containerDefinition._defaultDisableVersionConsistency?.();
Thanks for getting back to me. If it's `@internal` method, it's okay to stay `public` for internal constructs usage. However, I see in the unit test files that this method is also exposed to be used in CDK stacks. If we will allow that kind of usage, I think we should remove `_`.

2025-01-31 22:02 UTC, isker commented on packages/aws-cdk-lib/aws-ecs/lib/container-image.ts
> +        containerDefinition._defaultDisableVersionConsistency?.();
> I see in the unit test files that this method is also exposed to be used in CDK stacks.

I'm not sure what you mean by "exposed to be used in CDK stacks."  I'm not intending normal users to call this.  In [these tests](https://github.com/aws/aws-cdk/pull/32225/files#diff-3417482c00e303852c4be6305e74cb7d7667feacd0b818a86c34902f5abe293dR3016-R3067),  I'm just testing the behavior of `_defaultDisableVersionConsistency` on behalf of internal callers like those here in `container-image.ts`.

2025-02-03 03:49 UTC, GavinZZ approved these changes

2025-02-03 19:29 UTC, GavinZZ commented
@mergify update

2025-02-03 19:29 UTC, GavinZZ commented
@mergifyio requeue

2025-02-03 19:31 UTC, GavinZZ approved these changes

2025-02-03 20:06 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 8956bc1576bdc8bf49874283cdcea84214ac8b03
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a158279d-b3e3-4d89-a455-8d7947810198%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-03 21:34 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3a2464b10f960e231e45166d9ac6816cd6aadd0a
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fa95506b-279f-47c7-839e-e9d0fc08f2d7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-03 21:34 UTC, merged