feat(ecs): support availability zone rebalancing
aws/aws-cdk pull request #32263
Opened 2024-11-23 17:29 UTC by isker

### Issue # (if applicable)

Closes #32226

### Reason for this change

New AZ rebalancing feature is not yet supported in L2 constructs.

### Description of changes

Add `availabilityZoneRebalancing` to the props of FargateService and Ec2Service, and validate all the documented constraints on it being `ENABLED`.

### Description of how you validated changes

Unit and integration tests.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-11-23 18:01 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 92d03e2ced414475103b90e2bb3804e677d2d36d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=51d5a62d-4d06-4643-9e80-b80cd23d98bb%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-11-23 18:06 UTC, isker commented
Hi @pahud, I saw you added an `ecs-patterns-v2` label to #32226, which presumably means you want changes to those patterns to use this new feature as well.  I have not implemented that here, at least not yet.

I have not used the patterns myself before, and when I took a look at them, I wasn't sure if I should default this feature to be enabled in services created by those patterns.  What do you think?

2025-01-07 13:26 UTC, badmintoncryer requested changes
Thank you for your contribution! I've made some comments.

2025-01-08 00:11 UTC, aws-cdk-automation commented
<!--STALE PR-->
This PR has been in the MERGE CONFLICTS state for 3 weeks, and looks abandoned. To keep this PR from being closed, please continue work on it. If not, it will automatically be closed in a week.

2025-01-08 03:23 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ea590d680b848995fd5e1b916f4c8fbe7f1c5618
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7a2dd13a-99b7-4547-862e-67bcaaf42450%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-08 04:39 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 52b9a580487b5445dba54240dc1f15410dd97ce2
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8677c364-694a-4994-ae77-54a25b97e189%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-08 13:26 UTC, badmintoncryer commented on packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-service.ts
> +      }
I thought that by defining `availabilityZoneRebalancing` in `BaseServiceOptions`, all validations for `maxHealthyPercent` and those in `attachToClassicLB()` could be described in the `BaseService` class.
What do you think?

2025-01-08 13:48 UTC, isker commented on packages/aws-cdk-lib/aws-ecs/lib/ec2/ec2-service.ts
> +      }
BaseService is also extended by ExternalService, where AvailabilityZoneRebalancing is not a supported feature.

2025-01-08 14:17 UTC, badmintoncryer approved these changes
Thanks! 

`app.synth()` in the integ test code is not necessary. Please remove those lines!

2025-01-08 14:17 UTC, badmintoncryer commented on packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/ec2/integ.availability-zone-rebalancing.ts
> +app.synth();
```suggestion
```

2025-01-08 14:17 UTC, badmintoncryer commented on packages/@aws-cdk-testing/framework-integ/test/aws-ecs/test/fargate/integ.availability-zone-rebalancing.ts
> +app.synth();
```suggestion
```

2025-01-09 05:39 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3a1715c2cefa684e3779715e4299edc0ad672eb6
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2955c649-f577-4681-a1e7-7a6daa0c4005%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-09 06:09 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 4b7ed116eb245b8a3f8945aad916a1648fb6e180
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=efdc6f21-c92a-4609-857a-585a39ee0797%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-04 23:59 UTC, GavinZZ commented
@isker can you fix the conflicts please? I'm happy to give this PR a review this week and try to get this merged.

2025-02-05 02:25 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 46a5184668bd247ce8803fb7d62444f86ccee259
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b410632a-ff34-4b0c-bb46-cd9e56383c5f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-05 02:26 UTC, isker commented
@GavinZZ done.

2025-02-05 18:40 UTC, GavinZZ approved these changes
LGTM, thank you!

2025-02-05 19:31 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: ea688b9a970fb61dd5bf9498a70741c9f9199d7e
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5821e106-7a59-4dd1-ad5b-1232d317295c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-05 19:32 UTC, merged