feat(cognito): passwordless sign-in
aws/aws-cdk pull request #32369
Opened 2024-12-03 06:47 UTC by Tietew

### Issue # (if applicable)

Closes #32265.

### Reason for this change

User Pool has introduced passwordless sign-in including passkey (WebAuthn).
https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow-methods.html#amazon-cognito-user-pools-authentication-flow-methods-passwordless

Related PRs:
- #32367 - passwordless sign-in requires Essentials or higher feature plan.
- #32273 - passwordless sign-in requires user pool clients to allow USER_AUTH auth flow.

### Description of changes

Added following properties:
- `allowedFirstAuthFactors` - specify allowed first authenticate factors: email message one-time password, SMS message one-time password, and passkey
- `passkeyRelyingPartyId` - specify the authentication domain used as passkey relying party ID
- `passkeyVerification` - specify whether the passkey MFA is required or preferred

### Description of how you validated changes

Added unit test and  an integ test.

### Checklist
- [x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md) and [DESIGN GUIDELINES](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md)

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-12-03 06:48 UTC, Tietew commented
This PR is draft until #32367 is merged.

2024-12-03 06:50 UTC, Tietew commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
> +    const allowedFirstAuthFactors = ['PASSWORD'];
When `'PASSWORD'` is missing, CloudFormations fails with following error:
> Resource handler returned message: "Invalid request provided: PASSWORD should be configured as one of the allowed first auth factors."

2024-12-03 07:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 09dba49640b235444761ab5c4c7a45a60e9f234b
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7e5a1b56-3da3-48a8-9c57-442ef124423f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-12-05 02:40 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 0d5449eb3801a6cacf079d95f06c13c60c7b485c
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=667fadb1-3812-46c3-b0d5-d16718ba1e88%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-12-06 04:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 53ffbfb54af8e2bfeb14252742031a423838dfc0
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=bdec77e2-d6d9-425d-b7c6-58e1604cc4e3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-12-07 03:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 5d22a323427e7eeba813120a11afd8e2a9a45acd
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=20ca7638-1827-469e-8ee7-7ac21b7e5001%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-07 05:00 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 985425520f4f09502f6e9f72fbef75de9772a8fe
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=50003754-2742-47b5-90c7-21f5ff1ea448%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-30 03:10 UTC, Tietew commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
> +  readonly passkeyRelyingPartyId?: string;
Ok. I got:
> UserPool (UserPool6BA7E5F2) Properties validation failed for resource UserPool6BA7E5F2 with message: [#/WebAuthnRelyingPartyID: expected maxLength: 63, actual: 65]

2025-01-30 03:20 UTC, Tietew commented on packages/aws-cdk-lib/aws-cognito/test/user-pool.test.ts
> +import { AccountRecovery, Mfa, NumberAttribute, StringAttribute, UserPool, UserPoolIdentityProvider, UserPoolOperation, VerificationEmailStyle, UserPoolEmail, AdvancedSecurityMode, LambdaVersion, Fea
I think it's ok because eslint passes.

2025-01-30 03:23 UTC, Tietew commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
> +    if (!props.allowedFirstAuthFactors) {
I've updated to return undefined explicitly.

2025-01-30 03:23 UTC, Tietew commented
@lpizzinidev Thank you for your comments! I've pushed some modifications.

2025-01-30 03:27 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 51468c74f645a3e1091b8917eb1522bb7f3602b7
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4d30c395-0fc7-46f9-be8f-1c4db4151a3f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-30 04:28 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 3c1778bf202b99c8c9b469fc65ac5c0dbb888260
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=547c51be-8b2e-4f4a-b436-0fc55d22a13e%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-01-31 14:48 UTC, lpizzinidev requested changes

2025-01-31 14:48 UTC, lpizzinidev commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
> +    }
This could introduce subtle bugs in case the number of required auth methods changes for some reason.
Let's check `!Object.keys(allowedFirstAuthFactors).length` at L1417 instead.

2025-02-03 02:09 UTC, Tietew commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
> +    }
Thank you for your suggestion.

But I'll revert this because:
1. Create a stack with a user pool including `SignInPolicy: ['PASSWORD','WEB_AUTHN']`
2. Remove the `SignInPolicy` then update the stack
3. Management console shows the user pool still enables choice-based sign-in with Password and Passkey
4. Set `SignInPolicy: ['PASSWORD']` then update the stack again
5. Management console shows the user pool disables choice-based sign-in.

Therefore, we should provide the way to disable choice-based sign-in explicitly by specifying `allowedFirstAuthFactors: {}`.

2025-02-03 02:10 UTC, Tietew commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
> +    }
Similar issue: #30796

2025-02-03 03:24 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 69e8b8b274248bb6e1ef03654acaeb7788ca0041
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=fe1c9e6f-3507-495d-b5ec-5ea59c7670b9%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-03 03:24 UTC, Tietew commented
@lpizzinidev
I've pushed the revert and an additional test for explicit `allowedFirstAuthFactors: {}`

2025-02-03 11:45 UTC, lpizzinidev commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
> +    }
I see, thanks for checking. 
However, allowing for `allowedFirstAuthFactors: {}` makes for an unclear implementation.
`allowedFirstAuthFactors: { password: true }` with `password` required to `true` could be an option to avoid that, even if that would mean adding a new validation rule.

2025-02-04 02:40 UTC, Tietew commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
> +    }
Agreed. I'll add.

2025-02-04 03:09 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 72501dc34cee7ab802c6c1bd8dbb35ebcca700c9
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1cbf5f1c-dbcb-4541-abaf-0f91769b40bb%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-04 03:52 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 92e1e1100f6d15dfd66d6d8aa435c95a1692e56d
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2e3f12ce-a89c-46cf-b65b-44fd306a5624%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-04 09:02 UTC, lpizzinidev requested changes
My idea was to enforce `password: true` regardless when setting `allowedFirstAuthFactors`. Please let me know what's your thought 👍

2025-02-04 09:02 UTC, lpizzinidev commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
>        throw new ValidationError('To enable choice-based authentication, set `featurePlan` to `FeaturePlan.ESSENTIALS` or `FeaturePlan.PLUS`.', this);
```suggestion
    if (props.featurePlan === FeaturePlan.LITE) {
      throw new ValidationError('To enable choice-based authentication, set `featurePlan` to `FeaturePlan.ESSENTIALS` or `FeaturePlan.PLUS`.', this);
```

2025-02-04 09:17 UTC, Tietew commented
@lpizzinidev Thank you for explanation. I misunderstood.

When Cognito supports to disable password authentication in the future,
the `password` option should default to false...

2025-02-04 09:20 UTC, Tietew commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
>        throw new ValidationError('To enable choice-based authentication, set `featurePlan` to `FeaturePlan.ESSENTIALS` or `FeaturePlan.PLUS`.', this);
`allowedFirstAuthFactors: { password: true }` must allow Lite feature plan.

When the user have a user pool with choice-based authentication enabled and want to downgrade to Lite feature plan, the user must specify `allowedFirstAuthFactors: { password: true }` to disable choice-based authentication explicitly.
see https://github.com/aws/aws-cdk/pull/32369#discussion_r1938673153

2025-02-04 10:38 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b1a07b1e60e8bd6c3bc5b852ec73759bc7d72900
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8c9f83d6-1a41-4fa0-b309-dffe40a868c0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-04 11:38 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 9cf28149df0437b6179330ac5b4419fef71e5b81
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4a798d8f-e544-422c-ac37-1a1de66ffabd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-08 14:58 UTC, lpizzinidev approved these changes
Thanks 👍

2025-02-12 00:25 UTC, samson-keung requested changes
Appreciate the contribution! Thank you.

Left some comments on the design of the construct props.

2025-02-12 00:25 UTC, samson-keung commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
> +      webAuthnUserVerification: props.passkeyUserVerification,
nit: Since the two props above are simply passthrough to the L1, I prefer using the same property names as the L1 so that there is 1 less layer of mental mapping from `passkeyRelyingPartyId` to `webAuthnRelyingPartyId` (related [design guideline](https://github.com/aws/aws-cdk/blob/main/docs/DESIGN_GUIDELINES.md#naming)).

2025-02-12 00:25 UTC, samson-keung commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
> +  readonly allowedFirstAuthFactors?: AuthFactor;
I think it is better to follow the `PasswordPolicy` mentality in the sense that we should define a `SignInPolicy` type. Imagine that if, in the future, there are more fields added to the `SignInPolicy`, having a `SignInPolicy` type will help us group those fields instead of surfacing all of them at the highest level of the `UserPoolProps` type.

2025-02-12 00:25 UTC, samson-keung commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
> +   * @default PasskeyUserVerification.PREFERRED
I believe the CDK default is `undefined` but the CFN default is `preferred`. In that case, I think we should omit the value and add extra information about what happens if this prop is not set. Relevant design guideline and example is [here](https://github.com/aws/aws-cdk/blob/19e603bb6e8b971f85f48fa3f6254aef8e1913d6/docs/DESIGN_GUIDELINES.md?plain=1#L482).

2025-02-12 04:27 UTC, Tietew commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
> +      webAuthnUserVerification: props.passkeyUserVerification,
The reasons why I use the word *Passkey* instead of *WebAuthn* are:
- AWS documents mention Passkey (WebAuthn is referred as "or WebAuthn") - [[1]](https://docs.aws.amazon.com/cognito/latest/developerguide/authentication-flows-selection-sdk.html) [[2]](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow-methods.html#amazon-cognito-user-pools-authentication-flow-methods-passkey)
- Management console uses Passkey with no references to WebAuthn
![image](https://github.com/user-attachments/assets/ef0563b3-0d80-4bca-a914-63812bafeecc)

In the other hand, AWS amplify refers "WebAuthn passkey"
https://docs.amplify.aws/react/build-a-backend/auth/concepts/passwordless/

Do you think which term, Passkey or WebAuthn, is preferred for CDK users?

Other references:
> *[Passkeys](https://passkeys.dev/) are a significant use case for discoverable credentials*
[Web Authentication API - MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API)

> *Passkeys and WebAuthn are distinct but interconnected. Passkeys are essentially digital keys that replace traditional passwords, allowing you to log in using biometrics or a device lock. WebAuthn, on the other hand, is the technical standard that makes passkeys possible.*
[Passkey vs. WebAuthn: What's the Difference?](https://teampassword.com/blog/passkey-vs-webauthn)

2025-02-12 04:33 UTC, Tietew commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
> +  readonly allowedFirstAuthFactors?: AuthFactor;
Is it right that the suggested structure is:
``` ts
new UserPool(this, 'UserPool', {
  passwordPolicy: {
    ...
  },
  signInPolicy: {
    allowedFirstAuthFactors: { passwod: true, emailOtp: true, passkey: true },
    // other sign-in policy props may be added here
  },
});

2025-02-12 04:37 UTC, Tietew commented
@samson-keung Than you for your review. I'm working on your suggestions.
Could you answer some questions I left, please?

2025-02-12 17:58 UTC, samson-keung requested changes

2025-02-12 17:58 UTC, samson-keung commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
> +  readonly allowedFirstAuthFactors?: AuthFactor;
Yes. That is what I am thinking.

2025-02-12 17:58 UTC, samson-keung commented on packages/aws-cdk-lib/aws-cognito/lib/user-pool.ts
> +      webAuthnUserVerification: props.passkeyUserVerification,
Understood. Thank you for the explanation. It makes sense to me. I have also sync-ed with the Cognito team and they also prefer `passkey`.

2025-02-12 18:00 UTC, samson-keung commented
> @samson-keung Than you for your review. I'm working on your suggestions. Could you answer some questions I left, please?

Responded within the threads. Sorry I wasn't able to get to them quicker as I am in the PDT time zone. Updated my profile to reflect that :)

2025-02-13 03:04 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 79e6c9a75a0c994c03b1202468d67572c7bd1b4a
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6c3ad6a8-71fa-4cc8-95ba-cb7ee525d070%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-13 03:43 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c2d1346e2e3a2cb87a5849eeefd787596fa3d7c4
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=8796af53-90e6-42e8-83da-16a37f8f7a5c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-13 03:50 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 31b26cc1f31cbb46f081020cb6927a3df1b1d3e2
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e44a25d1-ede5-4df4-b5be-e63fb056d836%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-13 04:38 UTC, Tietew commented
@samson-keung I pushed updates. Time zone is not an issue. Thank you!

2025-02-13 18:38 UTC, samson-keung approved these changes
LGTM. Thank you for adding this feature!

2025-02-13 19:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: b8b00ef67f2179bcd47481b11f6a300fb71196a0
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=9e22501b-6c97-4bd6-bb14-1ce0b3a6c13c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2025-02-13 19:49 UTC, merged