fix(cloudformation-include): string arrays inside unknown properties …
aws/aws-cdk pull request #32461
Opened 2024-12-10 20:57 UTC by otaviomacedo

We are using `this` to refer to static methods, which fails at runtime. Use the class name instead.

Fixes https://github.com/aws/aws-cdk/issues/32454.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-12-10 20:59 UTC, aws-cdk-automation submitted a review, later dismissed
The pull request linter has failed. See the aws-cdk-automation comment below for failure reasons. If you believe this pull request should receive an exemption, please comment and provide a justification.


A comment requesting an exemption should contain the text `Exemption Request`. Additionally, if clarification is needed add `Clarification Request` to a comment.

2024-12-10 20:59 UTC, aws-cdk-automation commented
The pull request linter fails with the following errors:

	❌ Fixes must contain a change to an integration test file and the resulting snapshot.

<b>PRs must pass status checks before we can provide a meaningful review.</b>

If you would like to request an exemption from the status checks or clarification on feedback, please leave a comment on this PR containing `Exemption Request` and/or `Clarification Request`.

2024-12-10 21:07 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: 7b0f8ecb6f4ead350a57cd16fc7fa0e57358162e
* Result: FAILED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2aee7731-223a-4d5d-a2c6-273216740667%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-12-10 21:41 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: d53044ccd700c322050db7cf70771c13853b5b66
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=f24ec041-bee0-4e2a-81f5-4aa2f86598ed%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-12-11 09:21 UTC, rix0rrr commented on packages/aws-cdk-lib/cloudformation-include/test/test-templates/non-existent-policy-attribute.json
> +        }
Why are you renmaing properties in a file called `non-existent-policy-attribute.json` away from a nonexistent name to an existent name?

2024-12-11 09:21 UTC, rix0rrr requested changes

2024-12-11 09:21 UTC, rix0rrr commented on packages/aws-cdk-lib/cloudformation-include/test/test-templates/non-existent-policy-attribute.json
> +        }
Why are you renaming properties in a file called `non-existent-policy-attribute.json` away from a nonexistent name to an recognized name?

2024-12-11 09:39 UTC, rix0rrr approved these changes

2024-12-11 15:44 UTC, iliapolo commented
@Mergifyio refresh

2024-12-11 16:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: c96608d3a4ab7a196b8bb1f27583c77d7c13290c
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=25135281-0547-4523-8806-b4568bad7520%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-12-11 16:48 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildv2Project1C6BFA3F-wQm2hXv2jqQv
* Commit ID: fd381931562bb64f8cab48dca3fffb5ee00bbc67
* Result: SUCCEEDED
* [Build Logs](https://2cl995f30a.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ab2e2623-bff7-447c-b75c-b41d2022c299%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2024-12-11 16:49 UTC, merged