feat(eks): support ARM64 for self-managed nodegroup
aws/aws-cdk pull request #9875
Opened 2020-08-20 16:14 UTC by pahud

feat(eks): support ARM64 for self-managed nodegroup

Support creating self-managed nodegroups with the latest Amazon Linux  2 EKS-Optimized AMI for ARM64.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-08-20 16:26 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 866531be49bd60103e072e68758baea5770bc303
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6d5a90a3-6f84-465e-9e2c-a220b960f34b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-08-20 17:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: bcd88495f08cc59b8102bf3766b44dee8ae91a07
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=670ab736-0997-4a96-af7c-23954f81a4da%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-08-20 18:28 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: fbec15d0bfb68ca081832ccb19832160cf9cfa2d
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=581f1be6-ee9c-4a34-b68c-cc997bc28115%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-08-21 02:08 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 2c055ac0ebe1164a1f24892fd3d720f1bd05484d
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=41ef1f7e-d45e-44fd-8ddd-671ac3a0defc%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-08-21 04:49 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 70142a957f744fe8ebf5f1fbe4f8add948e86bde
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=03ce3b21-2cc2-46e2-82d3-5f356e10e683%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-08-27 09:04 UTC, eladb reviewed
initial pass

2020-08-27 09:04 UTC, eladb commented on packages/@aws-cdk/aws-eks/README.md
> +    // create a cluster with a default managed nodegroup
Unindent

2020-08-27 09:04 UTC, eladb commented on packages/@aws-cdk/aws-eks/lib/cluster.ts
> +  readonly cpuType?: CpuType;
rename to `cpuArch` or `architecture` or `arch`

2020-08-27 09:04 UTC, eladb commented on packages/@aws-cdk/aws-eks/lib/managed-nodegroup.ts
> +   * Amazon Linux 2(X86_64)
```suggestion
   * Amazon Linux 2 (x86-64)
```

2020-08-27 10:01 UTC, pahud commented
Hi @eladb ,  all addressed in the initial round. :-)

2020-08-27 10:19 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 376e82144918c0bc6d4caafebab04682b48f7930
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a9e701fb-18e9-49b9-bfea-d7902f7e470d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-08-27 10:21 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 6dc7f02251c7ebad7243b6e6e0d026a7042ca480
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=4e786c9d-ccd1-4e2a-b98c-ed0c8de5a144%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-01 12:50 UTC, eladb requested changes

2020-09-01 12:50 UTC, eladb commented on packages/@aws-cdk/aws-eks/README.md
> +Instance types with `ARM64` architecture are supported in both managed nodegroup and self-managed nodegroup. Simply specify the `instanceType` and the latest Amazon Linux 2 AMI for ARM64 will be sele
```suggestion
Instance types with `ARM64` architecture are supported in both managed nodegroup and self-managed capacity. Simply specify an ARM64 `instanceType` (such as `m6g.medium`), and the latest 
Amazon Linux 2 AMI for ARM64 will be automatically selected.
```

2020-09-01 12:50 UTC, eladb commented on packages/@aws-cdk/aws-eks/README.md
> +  defaultCapacityInstance: new ec2.InstanceType('m6g.medium'),
Kind of redundant since you have two examples below already for node groups and capacity:

```suggestion
```

2020-09-01 12:50 UTC, eladb commented on packages/@aws-cdk/aws-eks/README.md
> +// add the 2nd ARM64 managed nodegroup
```suggestion
// add a managed ARM64 nodegroup
```

2020-09-01 12:50 UTC, eladb commented on packages/@aws-cdk/aws-eks/lib/managed-nodegroup.ts
> +export class InstanceInfo {
Please convert these to two free floating functions:

In `managed-nodegroup.ts`:

```ts
function getAmiTypeForInstanceType(instanceType: InstanceType): NodegroupAmiType {
  // ...
}
```

In `cluster.ts`:

```ts
function cpuArchForInstanceType(instanceType: InstanceType) ...
```

2020-09-01 15:50 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 8dc10b0ac3a3cf194d1adf5d8d7422bf901c065a
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=29dc1f39-bca5-4086-b66b-273aef33e528%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-01 15:51 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 2506119f2afddc8e36a4669bf0c382216f1af835
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=28dcca34-c1e1-4880-910f-5ba6a317c276%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-01 15:52 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 957d68e1535e245491355133690174f2d2c36ed3
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1921d4ea-0bbd-483d-9ee6-00f3a0a2e421%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-01 15:53 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: c82539211521c655ed66fc5e2d7ad65563c86b10
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=25d73d47-66ea-45ff-b668-30a63a8afcf6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-01 15:54 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: accb37fb939bdf54157f93841acad03448d6eeed
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=0f231577-7530-465d-ab74-1afcbd52b3ac%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-03 18:02 UTC, eladb commented
There are still a few unresolved issues @pahud

2020-09-03 22:28 UTC, pahud commented
@eladb WIP 💪

2020-09-03 23:04 UTC, pahud commented on packages/@aws-cdk/aws-eks/lib/managed-nodegroup.ts
> +export class InstanceInfo {
Hi @eladb 

Should be resolved. But I am getting the JSII warning now. Please advise. Thanks.

<img width="726" alt="圖片" src="https://user-images.githubusercontent.com/278432/92181884-e4311a00-ee7c-11ea-96ed-b8eb3e183a5c.png">

2020-09-03 23:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 4ce9451874de2aa54f39d153b353c07f8d26881d
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=54d9e241-8efd-41cd-adf2-7f6f822d872b%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-03 23:20 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 3c089827fad54e6457c5b5736808c53d5a8faae1
* Result: FAILED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=12259fb4-7338-4a15-9ced-d1e9bc2bbe0a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-04 06:42 UTC, eladb submitted a review, later dismissed

2020-09-04 06:42 UTC, eladb commented on packages/@aws-cdk/aws-eks/lib/cluster.ts
> +export const GPU_INSTANCETYPES = ['p2', 'p3', 'g2', 'g3', 'g4'];
Move to a source file that is not exported in `index.ts` so these are not part of the public api of the module.

2020-09-04 14:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 5c0d6b80820ed7e9a2f36902998234d98998b58d
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=5d54dec6-24f0-49d9-9df3-187eb550ca5d%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-04 14:45 UTC, pahud commented
Hi @eladb 

All resolved. Please check it out again. thanks.

2020-09-07 09:45 UTC, eladb approved these changes
Approved with a minor comment. 
 Remove the `do-not-merge` label when ready

2020-09-07 09:45 UTC, eladb commented on packages/@aws-cdk/aws-eks/lib/instance-types.ts
> +export const GPU_INSTANCETYPES = ['p2', 'p3', 'g2', 'g3', 'g4'];
Can we change this to a map?

```ts
export INSTANCE_TYPES = {
  gpu: [ ... ],
  ...
};
```

2020-09-07 10:58 UTC, pahud commented on packages/@aws-cdk/aws-eks/lib/instance-types.ts
> +export const GPU_INSTANCETYPES = ['p2', 'p3', 'g2', 'g3', 'g4'];
Hi @eladb 

Just fixed :-)

2020-09-07 11:15 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 45227386eefc26e26bf3c0392389febed3b7ef21
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=224d1ece-e4b5-438b-8068-45a13b345d8c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-07 11:18 UTC, eladb approved these changes

2020-09-07 11:44 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 081e498e97732ade6f8dae603a3fbedeabc794ad
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=b47787f3-a51b-4ccf-8b96-8d92947599dc%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-09-07 11:44 UTC, merged