chore: check format of 'BREAKING CHANGE:' notice
aws/aws-cdk pull request #9928
Opened 2020-08-24 08:12 UTC by rix0rrr

I myself keep on forgetting whether it's spelled 'BREAKING CHANGE:' or
'BREAKING CHANGES:', and maybe whether or not to put a `(topic)` there,
that I prefer a machine checks this for me.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2020-08-24 08:23 UTC, iliapolo reviewed
Maybe put this in a different check? i.e *Body Format* or something?

https://github.com/aws/aws-cdk/blob/master/.github/workflows/pr-linter.yml

2020-08-24 08:24 UTC, iliapolo commented
This is great BTW :)

2020-08-24 08:36 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: d81ca7f2decf96ecb774bfa4524d88143a6d7c7f
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=ac5aeb85-7a86-40a1-aa9c-2135a12d0b85%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-08-24 08:37 UTC, njlynch commented on tools/prlint/index.js
> +            throw new LinterError(`Breaking changes should be indicated by starting a line with \'BREAKING CHANGE: \', variations are not allowed. (found: '${m[0]}')`);
```suggestion
            throw new LinterError(`Breaking changes should be indicated by starting a line with 'BREAKING CHANGE: ', variations are not allowed. (found: '${m[0]}')`);
```

2020-08-24 13:46 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 48e63576fee5438199898aa9a75eca68d482f627
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=2e2cccd4-98fa-426c-b3ee-6ea44e2aa6d5%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-08-24 14:05 UTC, njlynch approved these changes

2020-08-24 14:11 UTC, iliapolo requested changes
If this check stays here, then we should rename the job and and check to a generic `validate` method, since it no longer refers just to mandatory changes.

Another option is to put this in another job, but I can see why this has little value and requires more work.

2020-08-24 14:30 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 34b38e967051a26fe4b2afbfefa3f46202f661d7
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=26c2c0a7-caa3-4244-9375-38476c0728ea%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-08-25 08:36 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: 841e381be0abca87b969c1e6c02fd9291997b87c
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e374310d-fe0c-41b1-881c-ebf30e258420%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-08-25 09:04 UTC, aws-cdk-automation commented
### AWS CodeBuild CI Report

* CodeBuild project: AutoBuildProject6AEA49D1-qxepHUsryhcu
* Commit ID: f3db30154e7f7448f5271afaafc09bf2da94a615
* Result: SUCCEEDED
* [Build Logs](https://6sc75qyfl7.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=814b22d8-c38b-4455-b57f-4d2fad6b0614%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2020-08-25 09:51 UTC, iliapolo approved these changes

2020-08-25 11:15 UTC, merged